### ISSUE TITLE
[HOLD #8503] [Tracking] [Performance] Enable React 18

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#11680]
### Problem
React 18 introduces a lot of new features that improve performance. Some of those, such as "Automatic Batching" come out-of-the-box for free, and others such as Suspense, `startTransition`, and `useSyncExternalStore` are opt-in.

However, we can't use the opt-in features until React 18 is supported on all platforms.

### Solution
Enable React 18 on all platforms. This involves a number of tasks:

- [ ] https://github.com/Expensify/App/issues/8503
- [x] Upgrade react-native-web to the as-yet-unreleased `0.19`, or port over the necessary changes into our fork if we don't want to wait.
    - [x] Deprecate Touchables in favor of Pressable – https://github.com/necolas/react-native-web/issues/2382 this is in-scope for using RNW `0.19`

**Comment by roryabraham** [comment]
Branched this issue off from https://github.com/Expensify/App/issues/8503 for a more correct separation of  concerns.

**Comment by roryabraham** [comment]
No update for now but there's a milestone [here](https://github.com/necolas/react-native-web/milestone/19). Going to make this a monthly while we're waiting.

**Comment by sakluger** [comment]
Noting that @aneequeahmad reported this bug first, so they are eligible for a reporting bonus. @roryabraham feel free to assign me to the issue when it's just about completed so I can create and link an Upwork job.

**Comment by JmillsExpensify** [comment]
@roryabraham Now that we've removed Fabric from WAQ, I'm kind of thinking we should remove React 18 from the initiative as well. Obviously we still need to do this, and related there are performance improvements, but this is still bleeding edge. Do you agree with that?

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
Still on HOLD, but maybe getting closer to coming off HOLD

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
Still on HOLD. We're making faster progress on the Touchables migration so we should be able to remove the HOLD soon

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
I know @WoLewicki and @j-piasecki were interested in this after we turn on the new arch

**Comment by roryabraham** [comment]
Still on HOLD for new arch and https://github.com/Expensify/App/pull/24482

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
Probably the best article I've found on React 18 concurrent features: https://vercel.com/blog/how-react-18-improves-application-performance

**Comment by roryabraham** [comment]
Still on HOLD but we're getting closer and this will be 🔥

**Comment by roryabraham** [comment]
Still on HOLD, but this came up recently [here](https://expensify.slack.com/archives/C04878MDF34/p1705776345530929?thread_ts=1705614086.221599&cid=C04878MDF34)

**Comment by roryabraham** [comment]
This is basically a proxy for the following two issues now:

- https://github.com/Expensify/App/issues/8503
- https://github.com/Expensify/App/issues/33531

So I'm going to close this
