### ISSUE TITLE
Deploy Checklist: New Expensify 2022-10-14

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#11880]
**Release Version:** `1.2.16-1`
**Compare Changes:** https://github.com/Expensify/App/compare/production...staging

**This release contains changes from the following pull requests:**
- [ ] https://github.com/Expensify/App/pull/11718
- [ ] https://github.com/Expensify/App/pull/11782
- [ ] https://github.com/Expensify/App/pull/11841
- [ ] https://github.com/Expensify/App/pull/11857

**Deployer verifications:**
- [ ] I checked the [App Timing Dashboard](https://graphs.expensify.com/grafana/d/yj2EobAGz/app-timing?orgId=1) and verified this release does not cause a noticeable performance regression.
- [ ] I checked [Firebase Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&tag=all) and verified that this release does not introduce any new crashes.

cc @Expensify/applauseleads

**Comment by mvtglobally** [comment]
Regression is completed 

Checking off https://github.com/Expensify/App/pull/11782#issuecomment-1279846718
PR #11857 is failing due to https://github.com/Expensify/App/issues/11892. repro in PROD. There were few blockers with OldDot Concierge. Are we ok to check this off? 
PR https://github.com/Expensify/App/pull/11718 is failing due to https://github.com/Expensify/App/issues/11883. Checking off

**Comment by sketchydroide** [comment]
https://github.com/Expensify/App/issues/11887 also not a deploy blocker.

**Comment by sketchydroide** [comment]
@mvtglobally @kavimuru can we test again please 🙇🏼 

Also I think we can check https://github.com/Expensify/App/pull/11857 off

**Comment by mvtglobally** [comment]
@sketchydroide Are you asking us to run another regression?

**Comment by mvtglobally** [comment]
@sketchydroide 
Both issues doesn't seem to be repro any more 

https://user-images.githubusercontent.com/43995119/196209050-8493710b-22d7-41cb-83c2-33f22e9d931a.mp4

<img width="1359" alt="Screen Shot 2022-10-17 at 10 39 54 AM" src="https://user-images.githubusercontent.com/43995119/196209086-049db719-618c-4256-9929-2783281a386e.png">

**Comment by sketchydroide** [comment]
I think we can also check off https://github.com/Expensify/App/pull/11794

**Comment by sketchydroide** [comment]
https://github.com/Expensify/App/pull/11527 - has been reverted, so we are checking it off

**Comment by sketchydroide** [comment]
https://github.com/Expensify/App/pull/11909 checking it off as it's the revert to https://github.com/Expensify/App/pull/11527 -

**Comment by sketchydroide** [comment]
https://github.com/Expensify/App/issues/11858 is not a bloker, there was some confusion whit it, but it's currently in prod.

**Comment by sketchydroide** [comment]
:shipit:
