### ISSUE TITLE
Deploy Checklist: New Expensify 2022-12-07

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#13431]
**Release Version:** `1.2.37-0`
**Compare Changes:** https://github.com/Expensify/App/compare/production...staging

**This release contains changes from the following pull requests:**
- [x] https://github.com/Expensify/App/pull/10312
- [x] https://github.com/Expensify/App/pull/12031
- [x] https://github.com/Expensify/App/pull/12056
- [x] https://github.com/Expensify/App/pull/12320
- [x] https://github.com/Expensify/App/pull/12759
- [x] https://github.com/Expensify/App/pull/12848
- [x] https://github.com/Expensify/App/pull/12949
- [x] https://github.com/Expensify/App/pull/12954
- [x] https://github.com/Expensify/App/pull/12965
- [x] https://github.com/Expensify/App/pull/12978
- [x] https://github.com/Expensify/App/pull/13045
- [x] https://github.com/Expensify/App/pull/13128
- [x] https://github.com/Expensify/App/pull/13181
- [x] https://github.com/Expensify/App/pull/13189
- [x] https://github.com/Expensify/App/pull/13215
- [x] https://github.com/Expensify/App/pull/13226
- [x] https://github.com/Expensify/App/pull/13230
- [x] https://github.com/Expensify/App/pull/13231
- [x] https://github.com/Expensify/App/pull/13235
- [x] https://github.com/Expensify/App/pull/13246
- [x] https://github.com/Expensify/App/pull/13247
- [x] https://github.com/Expensify/App/pull/13249
- [x] https://github.com/Expensify/App/pull/13265
- [x] https://github.com/Expensify/App/pull/13268
- [x] https://github.com/Expensify/App/pull/13270
- [x] https://github.com/Expensify/App/pull/13272
- [x] https://github.com/Expensify/App/pull/13278
- [x] https://github.com/Expensify/App/pull/13279
- [x] https://github.com/Expensify/App/pull/13284
- [x] https://github.com/Expensify/App/pull/13288
- [x] https://github.com/Expensify/App/pull/13297
- [x] https://github.com/Expensify/App/pull/13298
- [x] https://github.com/Expensify/App/pull/13299
- [x] https://github.com/Expensify/App/pull/13301
- [x] https://github.com/Expensify/App/pull/13302
- [x] https://github.com/Expensify/App/pull/13316
- [x] https://github.com/Expensify/App/pull/13319
- [x] https://github.com/Expensify/App/pull/13321
- [x] https://github.com/Expensify/App/pull/13328
- [x] https://github.com/Expensify/App/pull/13330
- [x] https://github.com/Expensify/App/pull/13331
- [x] https://github.com/Expensify/App/pull/13345
- [x] https://github.com/Expensify/App/pull/13348
- [x] https://github.com/Expensify/App/pull/13351
- [x] https://github.com/Expensify/App/pull/13355
- [x] https://github.com/Expensify/App/pull/13356
- [x] https://github.com/Expensify/App/pull/13357
- [x] https://github.com/Expensify/App/pull/13358
- [x] https://github.com/Expensify/App/pull/13359
- [x] https://github.com/Expensify/App/pull/13360
- [x] https://github.com/Expensify/App/pull/13361
- [x] https://github.com/Expensify/App/pull/13362
- [x] https://github.com/Expensify/App/pull/13363
- [x] https://github.com/Expensify/App/pull/13364
- [x] https://github.com/Expensify/App/pull/13365
- [x] https://github.com/Expensify/App/pull/13370
- [x] https://github.com/Expensify/App/pull/13371
- [x] https://github.com/Expensify/App/pull/13374
- [x] https://github.com/Expensify/App/pull/13383
- [x] https://github.com/Expensify/App/pull/13387
- [x] https://github.com/Expensify/App/pull/13389
- [x] https://github.com/Expensify/App/pull/13393
- [x] https://github.com/Expensify/App/pull/13394
- [x] https://github.com/Expensify/App/pull/13407
- [x] https://github.com/Expensify/App/pull/13412

**Internal QA:**
- [x] https://github.com/Expensify/App/pull/13029 - @mountiny

**Deploy Blockers:**
- [x] https://github.com/Expensify/App/issues/13473
- [x] https://github.com/Expensify/App/issues/13435
- [x] https://github.com/Expensify/App/issues/13466
- [x] https://github.com/Expensify/App/issues/13447

**Deployer verifications:**
- [x] I checked the [App Timing Dashboard](https://graphs.expensify.com/grafana/d/yj2EobAGz/app-timing?orgId=1) and verified this release does not cause a noticeable performance regression.
- [x] I checked [Firebase Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&tag=all) and verified that this release does not introduce any new crashes.

cc @Expensify/applauseleads

**Comment by aldo-expensify** [comment]
I checked off https://github.com/Expensify/App/pull/13247 because I think it needs to be QA'ed in production.

**Comment by francoisl** [comment]
Thanks!


> PR https://github.com/Expensify/App/pull/13328 is failing https://github.com/Expensify/App/issues/13256. Its an older issue but was supposed to be fixed.

This one appears fixed to me, can you please post a screenshot (either here or in the PR)


> PR https://github.com/Expensify/App/pull/13278 is failing https://github.com/Expensify/App/issues/13085

I only checked on desktop, but this one also appears to be fixed to me. Can you provide a recording please?


> PR https://github.com/Expensify/App/pull/12965 is failing https://github.com/Expensify/App/issues/13443. Repro in PROD

I'm going to confirm, but I think these are somewhat separate issues and we can check 12965

---

I'm finishing checking the others and will update this post later.

**Comment by mvtglobally** [comment]
Additional Summary 
@francoisl  Will get screenshots on above in a bit 

PR https://github.com/Expensify/App/pull/12056 is failing https://github.com/Expensify/App/issues/13458. Its not repro in PROD as its a new feature. Pls double check its not a blocker 
PR https://github.com/Expensify/App/pull/12759 is failing https://github.com/Expensify/App/issues/10550.Its very intermittent and probably not related to PR. Checking off 


> PR https://github.com/Expensify/App/pull/12949 is failing https://github.com/Expensify/App/issues/11093. Older KI

This one also looks fine to me, and Android (native & mWeb). Going to ask someone to check iOS

--- PR https://github.com/Expensify/App/pull/12949 ONLY failing on mWeb / Chrome (https://platform.applause.com/services/links/v1/external/b4c75e86778c3bcacfa4784a7f2f6abddc51e94f1e1abf66a3a197acc790dc2b)  

PR #12965 checking off 
PR https://github.com/Expensify/App/pull/13189 is failing https://github.com/Expensify/App/issues/13457. repro in PROD checking off 
PR https://github.com/Expensify/App/pull/13230 is failing https://github.com/Expensify/App/issues/11584. Old KI 
PR  #13246 is failing https://github.com/Expensify/App/issues/13454.Not repro in PROD. As its related to a new feature. Pls double check its not a blocker

**Comment by mountiny** [comment]
Checking https://github.com/Expensify/App/pull/13029#issuecomment-1344087171 off, it works well in staging 🎉

**Comment by francoisl** [comment]
> PR https://github.com/Expensify/App/pull/12056 is failing https://github.com/Expensify/App/issues/13458. Its not repro in PROD as its a new feature. Pls double check its not a blocker

Confirmed [here](https://github.com/Expensify/App/issues/11823#issuecomment-1344632812), not a blocker. Going to check this off.

> PR https://github.com/Expensify/App/pull/12949 ONLY failing on mWeb / Chrome

Looks like the PR is not fully working then. I commented [here](https://github.com/Expensify/App/pull/12949#issuecomment-1344622396) to get some opinion from the participants.

> PR https://github.com/Expensify/App/pull/13246 is failing https://github.com/Expensify/App/issues/13454 repro in PROD. As its related to a new feature. Pls double check its not a blocker

Thanks for the video. It might be specific to desktop on Windows, which is why I couldn't reproduce. Left a [comment](https://github.com/Expensify/App/issues/13085#issuecomment-1344626435) in the issue to see if there's an easy fix

> PR https://github.com/Expensify/App/pull/13246 is failing https://github.com/Expensify/App/issues/13454 repro in PROD. As its related to a new feature. Pls double check its not a blocker

Still looking into this one, will update shortly.

> PR https://github.com/Expensify/App/pull/13328 is failing https://github.com/Expensify/App/issues/13256. Its an older issue but was supposed to be fixed.
> [VIDEO](https://user-images.githubusercontent.com/43995119/206763494-8eccd056-c2d3-4b14-85ab-6493fafdb287.mp4) & [Screenshot](https://user-images.githubusercontent.com/43995119/206763717-6181f216-e5e5-4df2-9618-923ce1a45726.png)

Yes this looks like the correct color, #5AB0FF. Same as on the screenshots in the [reviewer](https://github.com/Expensify/App/pull/13328#issuecomment-1339398330) post. Going to check it off

> PR https://github.com/Expensify/App/pull/13330 is failing https://github.com/Expensify/App/issues/13392 Are we ok to check off?

Yes based on [this conversation](https://expensify.slack.com/archives/C01GTK53T8Q/p1670595564667359?thread_ts=1670512291.721969&cid=C01GTK53T8Q), I'm going to check it off as well

**Comment by francoisl** [comment]
- The blocker https://github.com/Expensify/App/issues/13473 was solved by [reverting](https://github.com/Expensify/App/pull/13482) https://github.com/Expensify/App/pull/12505 (that PR wasn't on staging yet, so we're not CPing it)
-  The other blocker https://github.com/Expensify/App/issues/13466 has a [fix](https://github.com/Expensify/App/pull/13475) going out right now. We'll just need to QA that and then we should be ready to close this.

**Comment by francoisl** [comment]
v1.2.37-2 QA'ed internally and it resolves https://github.com/Expensify/App/issues/13466, we're good to go.

**Comment by francoisl** [comment]
:shipit:
