### ISSUE TITLE
Deploy Checklist: New Expensify 2022-12-09

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#13498]
**Release Version:** `1.2.38-6`
**Compare Changes:** https://github.com/Expensify/App/compare/production...staging

**This release contains changes from the following pull requests:**
- [x] https://github.com/Expensify/App/pull/12505
- [x] https://github.com/Expensify/App/pull/12739
- [x] https://github.com/Expensify/App/pull/12808
- [x] https://github.com/Expensify/App/pull/13214
- [x] https://github.com/Expensify/App/pull/13325
- [x] https://github.com/Expensify/App/pull/13342
- [x] https://github.com/Expensify/App/pull/13375
- [x] https://github.com/Expensify/App/pull/13388
- [x] https://github.com/Expensify/App/pull/13390
- [x] https://github.com/Expensify/App/pull/13396
- [x] https://github.com/Expensify/App/pull/13398
- [x] https://github.com/Expensify/App/pull/13402
- [x] https://github.com/Expensify/App/pull/13404
- [x] https://github.com/Expensify/App/pull/13409
- [x] https://github.com/Expensify/App/pull/13420
- [x] https://github.com/Expensify/App/pull/13425
- [x] https://github.com/Expensify/App/pull/13441
- [x] https://github.com/Expensify/App/pull/13448
- [x] https://github.com/Expensify/App/pull/13475
- [x] https://github.com/Expensify/App/pull/13476
- [x] https://github.com/Expensify/App/pull/13482
- [x] https://github.com/Expensify/App/pull/13519
- [x] https://github.com/Expensify/App/pull/13522
- [x] https://github.com/Expensify/App/pull/13525
- [x] https://github.com/Expensify/App/pull/13530
- [x] https://github.com/Expensify/App/pull/13531
- [x] https://github.com/Expensify/App/pull/13535

**Deploy Blockers:**
- [x] https://github.com/Expensify/App/issues/13488
- [x] https://github.com/Expensify/App/issues/13508
- [x] https://github.com/Expensify/App/issues/13510

**Deployer verifications:**
- [x] I checked the [App Timing Dashboard](https://graphs.expensify.com/grafana/d/yj2EobAGz/app-timing?orgId=1) and verified this release does not cause a noticeable performance regression.
- [x] I checked [Firebase Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&tag=all) and verified that this release does not introduce any new crashes.

cc @Expensify/applauseleads

**Comment by mvtglobally** [comment]
@chiragsalian @francoisl Regression is completed 

Deploy Blockers 
https://github.com/Expensify/App/issues/13508
https://github.com/Expensify/App/issues/13506
https://github.com/Expensify/App/issues/13509
https://github.com/Expensify/App/issues/13510
https://github.com/Expensify/App/issues/13511

PRs 
PR #13396 is failing https://github.com/Expensify/App/issues/13507. Repro in PROD checking off
Last PR pending https://github.com/Expensify/App/pull/12808. We are validating and I will update in a bit

**Comment by mvtglobally** [comment]
@chiragsalian I am seeing new App versions released, but this page checklist is not updated. 
Do you have a list of PRs we are good to retest now?

**Comment by mvtglobally** [comment]
@chiragsalian the following  CPs are PASS. not sure why they are not added to checklist 
https://github.com/Expensify/App/pull/13519
https://github.com/Expensify/App/pull/13531
https://github.com/Expensify/App/pull/13522

**Comment by chiragsalian** [comment]
Awesome thank you, i was just about to post. I'm going through the list now too.

**Comment by mvtglobally** [comment]
Let me know if any other CPs need to be checked

**Comment by chiragsalian** [comment]
Yes can you test https://github.com/Expensify/App/pull/13535

**Comment by chiragsalian** [comment]
Making a list for myself to track,
- [ ] https://github.com/Expensify/App/issues/13508
- [ ] https://github.com/Expensify/App/issues/13506
- [ ] https://github.com/Expensify/App/issues/13509
- [ ] https://github.com/Expensify/App/issues/13510
- [ ] https://github.com/Expensify/App/issues/13511

**Comment by chiragsalian** [comment]
Can you also test https://github.com/Expensify/App/pull/13530

**Comment by mvtglobally** [comment]
@chiragsalian 
https://github.com/Expensify/App/pull/13530 is Pass 
https://github.com/Expensify/App/pull/13535 is seems pass too, but we just want to clarify Desktop stuff https://github.com/Expensify/App/pull/13535#issuecomment-1349620486

**Comment by chiragsalian** [comment]
Checking comment, meanwhile this CP is also ready to be tested - https://github.com/Expensify/App/pull/13525

**Comment by chiragsalian** [comment]
I replied to your https://github.com/Expensify/App/pull/13535#issuecomment-1349620486.

**Comment by chiragsalian** [comment]
Any update on testing https://github.com/Expensify/App/pull/13525, or when can we expect it to be done? Asking cause its the last blocker and then we can do a deploy here.

**Comment by mvtglobally** [comment]
@chiragsalian 
It took some time to get the build. 
Its pass on all platforms, but we have this clarification. It doesnt seem PR related and we are digging through known issues  Avatar image become grey for a moment when switching between pages

https://user-images.githubusercontent.com/43995119/207449865-c63425f4-8aae-4704-b12a-c26e8e8ac983.mp4

**Comment by chiragsalian** [comment]
As [discussed on slack](https://expensify.slack.com/archives/C9YU7BX5M/p1670968843639969?thread_ts=1670967010.959399&cid=C9YU7BX5M) the issue mentioned above is occurring only on andoird. Could you create a follow up GH issue for that @mvtglobally?

**Comment by chiragsalian** [comment]
:shipit:
