### ISSUE TITLE
Deploy Checklist: New Expensify 2022-12-13

### ISSUE THREAD

**Issue by chiragsalian** [Expensify/App#13577]
**Release Version:** `1.2.39-0`
**Compare Changes:** https://github.com/Expensify/App/compare/production...staging

**This release contains changes from the following pull requests:**
- [x] https://github.com/Expensify/App/pull/13323
- [x] https://github.com/Expensify/App/pull/13408
- [x] https://github.com/Expensify/App/pull/13433
- [x] https://github.com/Expensify/App/pull/13470
- [x] https://github.com/Expensify/App/pull/13471
- [x] https://github.com/Expensify/App/pull/13483
- [x] https://github.com/Expensify/App/pull/13499
- [x] https://github.com/Expensify/App/pull/13500
- [x] https://github.com/Expensify/App/pull/13517
- [x] https://github.com/Expensify/App/pull/13552

**Internal QA:**
- [x] https://github.com/Expensify/App/pull/13559 - @MariaHCD @stitesExpensify

**Deployer verifications:**
- [x] I checked the [App Timing Dashboard](https://graphs.expensify.com/grafana/d/yj2EobAGz/app-timing?orgId=1) and verified this release does not cause a noticeable performance regression.
- [x] I checked [Firebase Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&tag=all) and verified that this release does not introduce any new crashes.

cc @Expensify/applauseleads

**Comment by MariaHCD** [comment]
https://github.com/Expensify/App/pull/13559 is tested via the deploy so I think we're good to check it off from this list. cc: @stitesExpensify

**Comment by mvtglobally** [comment]
@chiragsalian 

Regression is almost done. No blockers so far. All PRs checked off.

**Comment by chiragsalian** [comment]
ooh neat.

**Comment by chiragsalian** [comment]
So what's the status on the regression test?

**Comment by mvtglobally** [comment]
@chiragsalian regressio is completed

**Comment by chiragsalian** [comment]
:shipit:
