### ISSUE TITLE
Deploy Checklist: New Expensify 2022-12-14

### ISSUE THREAD

**Issue by chiragsalian** [Expensify/App#13611]
**Release Version:** `1.2.40-0`
**Compare Changes:** https://github.com/Expensify/App/compare/production...staging

**This release contains changes from the following pull requests:**
- [x] https://github.com/Expensify/App/pull/13434
- [x] https://github.com/Expensify/App/pull/13529
- [x] https://github.com/Expensify/App/pull/13573
- [x] https://github.com/Expensify/App/pull/13574
- [x] https://github.com/Expensify/App/pull/13578
- [x] https://github.com/Expensify/App/pull/13581
- [x] https://github.com/Expensify/App/pull/13596
- [x] https://github.com/Expensify/App/pull/13597

**Internal QA:**
- [x] https://github.com/Expensify/App/pull/13399 - @sketchydroide

**Deployer verifications:**
- [x] I checked the [App Timing Dashboard](https://graphs.expensify.com/grafana/d/yj2EobAGz/app-timing?orgId=1) and verified this release does not cause a noticeable performance regression.
- [x] I checked [Firebase Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&tag=all) and verified that this release does not introduce any new crashes.

cc @Expensify/applauseleads

**Comment by mvtglobally** [comment]
@chiragsalian  Regression is done. 

PR https://github.com/Expensify/App/pull/13529 is failing due to https://github.com/Expensify/App/issues/13633 repro in PROD

**Comment by chiragsalian** [comment]
> PR https://github.com/Expensify/App/pull/13529 is failing due to https://github.com/Expensify/App/issues/13633 repro in PROD

**Comment by chiragsalian** [comment]
:shipit:
