### ISSUE TITLE
[HOLD for BZ checklist] [$2000] DEV - Sending a PDF file for the very first time throws a console error “Warning: Failed prop type: The prop `isKeyboardShown` is marked as required in `PDFView`, but its value is `undefined` ”

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13862]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in any account
2. Navigate to any chat
3. Send a PDF file
4. Notice a console warning shows

## Expected Result:
Console warning/error should not shown

## Actual Result:
Console warning/error shows

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.44-0
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1440" alt="Screenshot 2022-12-28 at 10 27 25 AM" src="https://user-images.githubusercontent.com/43996225/209853155-c9897ebb-16ac-4c96-a4d9-1f0da6eb7d41.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672205164459619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016924f68b3e2db67d</li>
        <li>Upwork Job ID: 1608541286453559296</li>
        <li>Last Price Increase: 2023-01-06</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
I'm not able to reproduce, though I notice that in the title it says "very first time" and then in the reproduction steps, that isn't featured. Does that explain the difference?

![Screenshot 2022-12-28 at 13 39 36](https://user-images.githubusercontent.com/1127863/209863886-010d015d-96c7-4f99-a95f-188f99190900.png)

**Comment by JmillsExpensify** [comment]
Oh actually, I just realized that based on the title, this is only happening DEV, is that right? I'm not sure if I'd consider this a bug then, as we're focused on staging and production bugs. Going to float internally to get more thoughts before moving forward.

**Comment by JmillsExpensify** [comment]
Alright, we're good here. While I can't reproduce a DEV issues, I'm going to triage and keep the process moving.

**Comment by jayeshmangwani** [comment]
### Proposal   https://github.com/Expensify/App/blob/9108ef8ae63c836aa6427f42139d7651868913b7/src/components/PDFView/index.js#L168-L170

   we have to add withKeyboardState to PDFView


```diff
+ withKeyboardState
```

**Comment by jayeshmangwani** [comment]
Before adding withKeyboardState 

https://user-images.githubusercontent.com/35371050/210002869-348ea7aa-7a2e-4391-8235-395b4766a184.mov



After adding withKeyboardState 


https://user-images.githubusercontent.com/35371050/210002940-f8105343-4a80-41aa-9f53-c1240533b19c.mov

**Comment by Puneet-here** [comment]
### Proposal
Since we only need `isKeyboardShown` prop in the native file, I think we should define the PropTypes to specific files.

So define all PropTypes from `pdfViewPropTypes` in  [index.js](https://github.com/Expensify/App/blob/9108ef8ae63c836aa6427f42139d7651868913b7/src/components/PDFView/index.js)  and [index.native.js](https://github.com/Expensify/App/blob/9108ef8ae63c836aa6427f42139d7651868913b7/src/components/PDFView/index.native.js) just don't add ` ...keyboardStatePropTypes` and for index.js file and it will fix the issue
https://github.com/Expensify/App/blob/9108ef8ae63c836aa6427f42139d7651868913b7/src/components/PDFView/pdfViewPropTypes.js#L17

**Comment by dhairyasenjaliya** [comment]
**Proposal**

- Here we need to define `defaultProps` by default `isKeyboardShown` to false in `pdfViewPropTypes.js` since this file is not platform specific by default setting false makes more sense as also we need isKeyboardShown on the native platform only setting false by default removes undefined values warning on Web platform as it will never find keyboard events 

```diff
const defaultProps = {
    sourceURL: '',
    style: {},
    onToggleKeyboard: () => {},
+    isKeyboardShown: false,
};

```

https://github.com/Expensify/App/blob/9108ef8ae63c836aa6427f42139d7651868913b7/src/components/PDFView/pdfViewPropTypes.js#L20-L24

**Result with default props**

https://user-images.githubusercontent.com/47522946/210029842-9a6e9078-9689-4503-9368-a1668d4d5a26.mp4

**Result without default props**

https://user-images.githubusercontent.com/47522946/210029895-5bd37df1-17c8-4bd0-8a77-4298a84bca37.mp4

**Comment by hungvu193** [comment]
<b>Proposal</b>
We don't need the keyboard the state in web, in this case we can create 2 proptype  variable for native and web, with web proptype we need to remove the keyboardStatePropTypes.

```diff
diff --git a/src/components/PDFView/index.native.js b/src/components/PDFView/index.native.js
index 1029750b9..08a444f83 100644
--- a/src/components/PDFView/index.native.js
+++ b/src/components/PDFView/index.native.js
@@ -174,7 +174,7 @@ class PDFView extends Component {
     }
 }
 
-PDFView.propTypes = pdfViewPropTypes.propTypes;
+PDFView.propTypes = pdfViewPropTypes.nativePropTypes;
 PDFView.defaultProps = pdfViewPropTypes.defaultProps;
 
 export default compose(
diff --git a/src/components/PDFView/pdfViewPropTypes.js b/src/components/PDFView/pdfViewPropTypes.js
index 5f2c7e381..29334d5db 100644
--- a/src/components/PDFView/pdfViewPropTypes.js
+++ b/src/components/PDFView/pdfViewPropTypes.js
@@ -3,7 +3,7 @@ import stylePropTypes from '../../styles/stylePropTypes';
 import {windowDimensionsPropTypes} from '../withWindowDimensions';
 import {keyboardStatePropTypes} from '../withKeyboardState';
 
-const propTypes = {
+const nativePropTypes = {
     /** URL to full-sized image */
     sourceURL: PropTypes.string,
 
@@ -17,10 +17,23 @@ const propTypes = {
     ...keyboardStatePropTypes,
 };
 
+const propTypes = {
+    /** URL to full-sized image */
+    sourceURL: PropTypes.string,
+
+    /** Additional style props */
+    style: stylePropTypes,
+
+    /** Notify parent that the keyboard has opened or closed */
+    onToggleKeyboard: PropTypes.func,
+
+    ...windowDimensionsPropTypes,
+};
+
 const defaultProps = {
     sourceURL: '',
     style: {},
     onToggleKeyboard: () => {},
 };
 
-export {propTypes, defaultProps};
+export {propTypes, defaultProps, nativePropTypes};

```

**Comment by JmillsExpensify** [comment]
@rushatgabhane Mind taking the first pass on the proposals above? Thank you! 🙌🏼

**Comment by umair-upwork** [comment]
### **Proposal**

**Problem**

This console warning is showing due to `isKeyboardShown` prop in `<PDFView>`. `<PDFView>` expecting prop default value because `isKeyboardShown` is marked as required prop and we are not passing any default value in `<PDFView>`.

### **Solution**

To fix this issue, we just have to pass `isKeyboardShown` prop with default value to `<PDFView>` default props.
```diff
diff --git a/src/components/PDFView/pdfViewPropTypes.js b/src/components/PDFView/pdfViewPropTypes.js
index 5f2c7e381..6991a6da2 100644
--- a/src/components/PDFView/pdfViewPropTypes.js
+++ b/src/components/PDFView/pdfViewPropTypes.js
@@ -21,6 +21,7 @@ const defaultProps = {
     sourceURL: '',
     style: {},
     onToggleKeyboard: () => {},
+    isKeyboardShown: false,
 };
```

### **Result**
https://user-images.githubusercontent.com/79830748/211007786-84108941-1b53-4d8a-a4f4-e5cc12407172.mov

**Comment by jayeshmangwani** [comment]
@rushatgabhane  I have one question here, can you please notify me what's wrong with my [proposal](https://github.com/Expensify/App/issues/13862#issuecomment-1367532843) I took reference from the [ReportActionCompose](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose.js#L745) file as it is used in all platforms and we are passing withKeyboardState for web and desktop too as a file that is common


https://github.com/Expensify/App/blob/f355ee1294cca2f11c1d61bf7e60c3e0f3e3703c/src/pages/home/report/ReportActionCompose.js#L745

**Comment by dhairyasenjaliya** [comment]
@rushatgabhane rather than adding different props for platforms specific files I do think making isKeyboardShown bydefault false makes more sense since we are creating props file to define all props at once for particular component as we do in all components

**Comment by dhairyasenjaliya** [comment]
> That's a fair point. There are multiple ways to solve a problem.
> 
> I just think that it'll be confusing for someone reading the code that a HOC is being consumed, but it's props are just being ignored. Also, the component might update unnecessarily

we can mention in the comment regarding code readability, and also I dont think the component will get an update since the keyboard event will be only triggered on the native platform

**Comment by grgia** [comment]
All yours @Puneet-here!

**Comment by Puneet-here** [comment]
Thanks @grgia @rushatgabhane! PR is ready

**Comment by JmillsExpensify** [comment]
Woo! Thanks for the quick work.

**Comment by JmillsExpensify** [comment]
Well shoot. Did our GH automation fail? I just noticed this PR hit production several hours ago.

**Comment by Puneet-here** [comment]
Regression period is over @JmillsExpensify

**Comment by JmillsExpensify** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@rushatgabhane  / @grgia] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@rushatgabhane  / @grgia] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@rushatgabhane  / @grgia] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@JmillsExpensify] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by JmillsExpensify** [comment]
All contributors invited/hired. 

@rushatgabhane @grgia can you get complete the first several items on the BZ checklist? I'll get on the regression test. Thanks!

**Comment by dhairyasenjaliya** [comment]
hey @JmillsExpensify can you also invite me for reporting the bug

**Comment by JmillsExpensify** [comment]
Nice, yeah let's get that list crossed off!

**Comment by JmillsExpensify** [comment]
@dhairyasenjaliya Thanks sorry for missing that! Invited you to the job. While we work on the checklist items, I'll circle back on the regression test as well.

**Comment by dhairyasenjaliya** [comment]
No issue accepted now thanks @JmillsExpensify

**Comment by JmillsExpensify** [comment]
Great thanks. Offer sent. Payments are as follows:

 - Issue reporter: @dhairyasenjaliya $250
 - Contributor: @Puneet-here $2,000
 - Contributor+: @rushatgabhane $2,000

C/C+ have been paid out, so at this point our todos are:

 - @grgia @rushatgabhane complete first three items on BZ checklist
 - @JmillsExpensify complete regression test
 - @dhairyasenjaliya accept offer

Thanks everyone!

**Comment by Puneet-here** [comment]
@JmillsExpensify, it is also eligible for 50% bonus.

**Comment by JmillsExpensify** [comment]
Well shoot. Sorry about that. Just sent you/Rushat another offer for $1k to make up the difference.

**Comment by Puneet-here** [comment]
Accepted, thanks @JmillsExpensify

**Comment by JmillsExpensify** [comment]
Alright cool. We're back to these next steps

> @grgia @rushatgabhane complete first three items on BZ checklist
> @JmillsExpensify complete regression test
> @dhairyasenjaliya accept offer

**Comment by JmillsExpensify** [comment]
Perfect, thank you! I'm last up, and I'll have to cross that off the list tomorrow.

**Comment by JmillsExpensify** [comment]
Alrighty! I came back to this one and looked into the PR and testing steps. I'm not recommending we create an regression issue given the console error focus/nature of the issue. Closing!
