### ISSUE TITLE
[Main Tracking] - Fabric Bugs 

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#14373]
Problem: SWM has been working on upgrading Fabric in [this branch](https://github.com/Expensify/App/pull/13767) to which Applause did a full regression suite and found several bugs which SWM has been working on, but we're wanting a bit more structure behind tracking the progress. 

Solution: Create this tracking issue listing out the bugs that Applause found to track their progress.

---

Main PR noting the various bugs - [here](https://github.com/Expensify/App/pull/13767)

Fabric Bugs:
- [ ] https://github.com/Expensify/App/issues/14365
- [ ] https://github.com/Expensify/App/issues/14366
- [ ] https://github.com/Expensify/App/issues/14367
- [ ] https://github.com/Expensify/App/issues/14368
- [ ] https://github.com/Expensify/App/issues/14369
- [ ] https://github.com/Expensify/App/issues/14370
- [ ] https://github.com/Expensify/App/issues/14371
- [ ] https://github.com/Expensify/App/issues/14372

Once all are completed successfully, we can review and ensure no further Fabric bugs have been identified. If there have, we will update the list to track those as well, if not, we'll close the issue out.

**Comment by roryabraham** [comment]
@dylanexpensify I wonder if we should actually close this and just fold it into the existing tracking issue https://github.com/Expensify/App/issues/8503

**Comment by dylanexpensify** [comment]
Oh wow, yeah that's a winner winner - doing now
