### ISSUE TITLE
[Tracking] Migrate away from Touchables and create a standardized, accessible button library using Pressables

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#14589]
Design doc link: [here](https://docs.google.com/document/d/1yHHs4IfaMxB2q7eW8Hyt7ew4rNtY6HdduPKdf-Q2ZxE/edit#heading=h.ns12dr1f35rx)

## Proposal: 
Migrate away from Touchables and create a standardized, accessible button library using Pressables

## Problem:

The next release of react-native-web will deprecate Touchable components – the same is likely to happen in a future release of react-native. We use Touchables extensively throughout the app. Meanwhile, we have a clear problem with a lack of accessibility.

## Solution:

Let’s kill two birds with one stone by taking accessibility (and general UI/UX) into account as we do this migration, and create a standardized framework for Pressables across the app. This includes:

- Migrating away from Touchables and standardizing on Pressable, everywhere in the app
- Creating a standardized framework for all of our Pressable components that accounts for:
    - Visual accessibility (i.e: changes in style for hovered and pressed stated)
    - ScreenReader accessibility (i.e: tabindex, focus, etc…)
    - Custom cursor states (i.e: disabled pressables should have the cursor: not-allowed style)
    - Cross-platform compatibility, including iPads with keyboards and touch-screen laptops
    - Haptic feedback (with a framework to standardize various forms of haptic feedback)
    - Intuitive gesture handling (i.e: if you tap on a button, but slide your finger away before lifting your finger, that’s an indication that the user probably meant to “cancel” their tap)
- Ideally creating lint rules to automatically enforce that this framework is followed

## Tasks

- [x] Post **Proposal (full Problem/Solution statement)** in `#expensify-open-source`
- [x] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [x] Paste Proposal in the space above with a link to the Slack thread
- [x] Email `strategy@expensify.com` and paste in the Proposal
- [x] Fill out the **High-level overview of the problem**, **Timeline**, and **Terminology** sections of the Design Doc
- [x] Email `strategy@expensify.com` (continue the same email chain as before) with the link to your Design Doc
- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [x] Fill out the **High-level of proposed solution** section
- [x] Email `stategy@expensify.com` again with links to the doc and pre-design conversation in Slack
- [x] Add the `DesignDocReview` label to get the **High-level of proposed solution** section reviewed
- [x] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.
- [x] Fill out the **Detailed implementation of the solution** and related sections.
- [x] Re-add the `DesignDocReview` label to this issue
- [x] Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase
- [ ] Implement the changes
    - Tracking project: https://github.com/orgs/Expensify/projects/29/views/1
- [ ] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

cc @roryabraham

**Comment by RobertKozik** [comment]
Let me look into it

**Comment by s77rt** [comment]
Will this cover the use of `TouchableWithoutFeedback`
We have this issue here https://github.com/Expensify/App/issues/14301 where we are trying to actually do the opposite, as it's a case where accessibility is something that we don't want and the button should not have any feedback.

**Comment by MelvinBot** [comment]
:wave: Hello Generalist Track Team - you have been assigned to review this **High Level** Design Doc. Please, treat this as a priority. Review [this Stack Overflow](https://stackoverflow.com/c/expensify/questions/5838) for some tips on reviewing a design doc. Once you are done, simply press the `Add "Reviewed Doc" comment` button in the right hand side K2 pannel or follow [these](https://stackoverflow.com/c/expensify/questions/13713) instructions.

---
- `@shmaxey` (Expensifier / Graduate) - https://github.com/Expensify/App/issues/14963
- `@michaelhaxhiu` (Expensifier / Graduate) - https://github.com/Expensify/App/issues/14964
- `@mateocole` (Project Manager) - https://github.com/Expensify/App/issues/14965
- `@zsgreenwald` (Project Manager) - https://github.com/Expensify/App/issues/14966
- `@RobertLadue` (Product Manager) - https://github.com/Expensify/App/issues/14967
- `@stephanieelliott` (Product Manager) - https://github.com/Expensify/App/issues/14968
- `@ryanschaffer` (Generalist) - https://github.com/Expensify/App/issues/14969
- `@KirkBarrett` (Generalist) - https://github.com/Expensify/App/issues/14970
- `@trentpetty` (Accounting Technical Team) - https://github.com/Expensify/App/issues/14971

**Comment by roryabraham** [comment]
High level ready for review. Also started a slack convo [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1675895749367949)

**Comment by trentpetty** [comment]
I have read and reviewed this Design Doc!

**Comment by KirkBarrett** [comment]
I have read and reviewed this Design Doc!

**Comment by mountiny** [comment]
I have read and reviewed this Design Doc!

**Comment by stephanieelliott** [comment]
I have read and reviewed this Design Doc!

**Comment by ryanschaffer** [comment]
ave read and reviewed this Design Doc!

**Comment by ryanschaffer** [comment]
I have read and reviewed this Design Doc!

**Comment by shmaxey** [comment]
I have read and reviewed this Design Doc!

**Comment by michaelhaxhiu** [comment]
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment]
Reviews are progressing, still need two reviews from the product managers tier. Since there have been no major comments so far, @RobertKozik reports that he is making progress with the research for the detailed implementation of the doc.

**Comment by roryabraham** [comment]
Next step is to review the detailed doc and send it out for reviews.

**Comment by RobertLadue** [comment]
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment]
Detailed is ready for review

**Comment by MelvinBot** [comment]
:wave: Hello Generalist Track Team - you have been assigned to review this **Detailed** Design Doc. Please, treat this as a priority. Review [this Stack Overflow](https://stackoverflow.com/c/expensify/questions/5838) for some tips on reviewing a design doc. Once you are done, simply press the `Add "Reviewed Doc" comment` button in the right hand side K2 pannel or follow [these](https://stackoverflow.com/c/expensify/questions/13713) instructions.

---
- `@mateocole` (Expensifier / Graduate) - https://github.com/Expensify/App/issues/16407
- `@shmaxey` (Expensifier / Graduate) - https://github.com/Expensify/App/issues/16408
- `@zsgreenwald` (Project Manager) - https://github.com/Expensify/App/issues/16409
- `@maddylewis` (Project Manager) - https://github.com/Expensify/App/issues/16410
- `@yuwenmemon` (Product Manager / Generalist + Engineer) - https://github.com/Expensify/App/issues/16411
- `@AndrewGable` (Product Manager / Generalist + Engineer) - https://github.com/Expensify/App/issues/16412
- `@johnmlee101` (Product Manager / Generalist + Engineer) - https://github.com/Expensify/App/issues/16413
- `@puneetlath` (Product Manager / Generalist + Engineer) - https://github.com/Expensify/App/issues/16414
- `@stephanieelliott` (Product Manager / Generalist + Non-Engineer) - https://github.com/Expensify/App/issues/16415
- `@KirkBarrett` (Product Manager / Generalist + Non-Engineer) - https://github.com/Expensify/App/issues/16416
- `@ryanschaffer` (Product Manager / Generalist + Non-Engineer) - https://github.com/Expensify/App/issues/16417
- `@twisterdotcom` (Product Manager / Generalist + Non-Engineer) - https://github.com/Expensify/App/issues/16418

**Comment by AndrewGable** [comment]
I have read and reviewed this Design Doc!

**Comment by mountiny** [comment]
I have read and reviewed this Design Doc!

**Comment by mateocole** [comment]
I have read and reviewed this Design Doc!

**Comment by puneetlath** [comment]
I have read and reviewed this Design Doc!

**Comment by stephanieelliott** [comment]
I have read and reviewed this Design Doc!

**Comment by johnmlee101** [comment]
I have read and reviewed this Design Doc!

**Comment by KirkBarrett** [comment]
I have read and reviewed this Design Doc!

**Comment by KirkBarrett** [comment]
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment]
Still waiting for reviews from:

- 1 Expensifier/Graduate
- 1 Product Manager
- 1 engineering product manager or generalist
- 2 non-engineering product managers or generalist

Let's get these reviews in. As of this week this became a blocker to update react-native-web, so it would be great to get started with the implementation here

**Comment by yuwenmemon** [comment]
I have read and reviewed this Design Doc!

**Comment by shmaxey** [comment]
I have read and reviewed this Design Doc!

**Comment by maddylewis** [comment]
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment]
Looks like we've got the reviews we need to move forward into implementation. I know that this was a pretty dense doc, so thanks to everyone who took the time to review!

**Comment by twisterdotcom** [comment]
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment]
Going to track implementation in [this GitHub Project](https://github.com/orgs/Expensify/projects/29/views/1?layout=board)

**Comment by francoisl** [comment]
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment]
[Big PR](https://github.com/Expensify/App/pull/17404) in review

**Comment by JmillsExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment]
We've got the big PR merged and fixed some issues. Now we can start rolling it out everywhere

**Comment by roryabraham** [comment]
Migrations have begun, but I went head and took everything off HOLD. SWM is busy with App.js for the rest of this week, but next week I think I'll do a CTA and ask everyone from their team to just grab one issue at a time so we can start making more rapid progress through this migration, which is blocking some other stuff.

**Comment by roryabraham** [comment]
Making steady progress in the GitHub Project. SWM has a few new engineers (new to us, anyways...) assigned to some of the migration issues

**Comment by roryabraham** [comment]
Migration is ongoing.

**Comment by roryabraham** [comment]
Making rapid progress

**Comment by roryabraham** [comment]
According to https://github.com/orgs/Expensify/projects/29/views/1?layout=board, we have:

- 35 issues done
- 17 done & HOLD for payment
- 18 in progress
- 8 more TODO

**Comment by roryabraham** [comment]
We are very close to being done here, with I think only one remaining Pressable to migrate 🎉 

Then we will merge https://github.com/Expensify/App/pull/20363/files to prevent any re-introduction of the old pressables.

**Comment by roryabraham** [comment]
https://github.com/Expensify/App/pull/20363 is ongoing. All that's left here is that and also the documentation updates.

**Comment by roryabraham** [comment]
Only issue that's not `HOLD for payment` is https://github.com/Expensify/App/issues/17005.

**Comment by roryabraham** [comment]
Asked for a slack update: https://expensify.slack.com/archives/C04878MDF34/p1689641773049579

**Comment by roryabraham** [comment]
Just waiting on the documentation PR here, then we're done

**Comment by roryabraham** [comment]
@robertKozik is busy with C+ work, this isn't urgent but would be really nice to get finished soon. All that's left is documentation

**Comment by roryabraham** [comment]
DM'd @robertKozik to bump on this

**Comment by roryabraham** [comment]
Documentation added, sent project wrap up email, closing this out 🎉
