### ISSUE TITLE
Deploy Checklist: New Expensify 2023-02-02

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#14771]
**Release Version:** `1.2.64-7`
**Compare Changes:** https://github.com/Expensify/App/compare/production...staging

**This release contains changes from the following pull requests:**
- [x] https://github.com/Expensify/App/pull/13216
- [x] https://github.com/Expensify/App/pull/13647
- [x] https://github.com/Expensify/App/pull/14029
- [x] https://github.com/Expensify/App/pull/14426
- [x] https://github.com/Expensify/App/pull/14454
- [x] https://github.com/Expensify/App/pull/14466
- [x] https://github.com/Expensify/App/pull/14502
- [x] https://github.com/Expensify/App/pull/14605
- [x] https://github.com/Expensify/App/pull/14664
- [x] https://github.com/Expensify/App/pull/14704
- [x] https://github.com/Expensify/App/pull/14723
- [x] https://github.com/Expensify/App/pull/14727
- [x] https://github.com/Expensify/App/pull/14728
- [x] https://github.com/Expensify/App/pull/14746
- [x] https://github.com/Expensify/App/pull/14768
- [x] https://github.com/Expensify/App/pull/14770
- [x] https://github.com/Expensify/App/pull/14791
- [x] https://github.com/Expensify/App/pull/14823
- [x] https://github.com/Expensify/App/pull/14826

**Internal QA:**
- [x] https://github.com/Expensify/App/pull/14730 - @Beamanator
- [x] https://github.com/Expensify/App/pull/14653 - @Julesssss
- [x] https://github.com/Expensify/App/pull/14585 - @yuwenmemon
- [x] https://github.com/Expensify/App/pull/13655 - @Beamanator
- [x] https://github.com/Expensify/App/pull/13501 - @grgia

**Deploy Blockers:**
- [x] https://github.com/Expensify/App/issues/14757
- [x] https://github.com/Expensify/App/issues/14781
- [x] https://github.com/Expensify/App/issues/14784
- [x] https://github.com/Expensify/App/issues/14787

**Deployer verifications:**
- [x] I checked the [App Timing Dashboard](https://graphs.expensify.com/grafana/d/yj2EobAGz/app-timing?orgId=1) and verified this release does not cause a noticeable performance regression.
- [x] I checked [Firebase Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&tag=all) and verified that this release does not introduce any new crashes. More detailed instructions on this verification can be found [here](https://stackoverflowteams.com/c/expensify/questions/15095/15096).

cc @Expensify/applauseleads

**Comment by thienlnam** [comment]
Checked off 14454, needs internal prod QA

**Comment by roryabraham** [comment]
I just noticed for the first time that arrow key navigation on:

- search page
- new chat page
- new group page

seems broken. This functionality was added in https://github.com/Expensify/App/pull/7702 and regression tests for these features were added [here](https://github.com/Expensify/Expensify/issues/217359).

**Comment by roryabraham** [comment]
Created https://github.com/Expensify/App/issues/14787

**Comment by Beamanator** [comment]
Just tested https://github.com/Expensify/App/pull/14730 and https://github.com/Expensify/App/pull/13655, results here: https://github.com/Expensify/App/pull/13655#issuecomment-1415558018

The tests looked great mainly, but there were two possible smaller issues that I think can be resolved without being deploy blockers?

**Comment by Julesssss** [comment]
Checked off https://github.com/Expensify/App/pull/14653 ✅

**Comment by roryabraham** [comment]
Checking off https://github.com/Expensify/App/issues/14787

**Comment by mvtglobally** [comment]
@thienlnam Regression is completed 

https://github.com/Expensify/App/pull/13216 is failing https://github.com/Expensify/App/issues/14818 & https://github.com/Expensify/App/issues/14819 repro in PROD
https://github.com/Expensify/App/pull/14029. We are struggling with testing this PR a bit. So far it seems to be failing https://github.com/Expensify/App/issues/14820 and we are seeing this https://github.com/Expensify/App/issues/7270

**Comment by thienlnam** [comment]
Checking off #14730 and #13655 from @Beamanator's comments here https://github.com/Expensify/App/pull/13655#issuecomment-1415558018

**Comment by grgia** [comment]
Checking off #13501

**Comment by thienlnam** [comment]
Checking off #14585 with this comment https://github.com/Expensify/App/pull/14585#issuecomment-1416510158

**Comment by thienlnam** [comment]
:shipit:
