### ISSUE TITLE
[HOLD for payment 2023-08-21] Background Refresh

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#15058]
~~# [DESIGN DOC ➡️](https://docs.google.com/document/d/1VY5WIk0HQGbjjQdCopPmgynusgX9FQpWdiPaHfGQ1bM/edit?usp=sharing)~~ (deprecated)

## Proposal
[WN Post](https://expensify.slack.com/archives/CC7NECV4L/p1680884231927239)

**Strategy**
In order to offer a pleasing user experience, we strive to keep data in NewDot as up to date as possible at any given time. We have implemented solutions for keeping active user’s up to date in real time (namely sending updates in realtime using Pusher). Next we should aim to update inactive users to improve their experience when re-opening the app while offline or on a slow connection.

**Problem**
A growing pain for NewDot is its routinely stale data when first opening the app. Eg:

- Opening the Chats screen and seeing an out of date list
- Opening a chat and not seeing the latest messages

After a moment (or several depending on your connection), the app finishes syncing data that was missed and flickers as it finally displays the latest data. This delay can be particularly frustrating as you may know that you’re missing something new (eg: something from a notification).

**Solution**
iOS and Android grant us some ability to run tasks while the app is in the background so let’s fully utilize it! We can implement background refresh and use it to periodically sync updates we have missed. While this won’t completely eliminate stale data, this should noticeably improve the “freshness” of the app when you open it.

We can dig further on what specifically we should sync, but at a minimum lets use background refresh to sync high level data on chats and messages so that you can catch up with conversations more quickly.

## Tasks

- [x] Post **Proposal (full Problem/Solution statement)** in `#whatsnext`
- [x] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [x] Paste Proposal in the space above with a link to the Slack thread
- [x] Email `strategy@expensify.com` and paste in the Proposal
- [x] Fill out the **High-level overview of the problem**, **Timeline**, and **Terminology** sections of the Design Doc
- [x] Email `strategy@expensify.com` (continue the same email chain as before) with the link to your Design Doc
- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in an appropriate slack channel to discuss any necessary details in public before filling out the **High-level of proposed solution** section. ([pre-design link](https://expensify.slack.com/archives/C056AV5V8UX/p1684788808189649))
- [x] Fill out the **High-level of proposed solution** section
- [x] Email `stategy@expensify.com` again with links to the doc and pre-design conversation in Slack
- [x] Add the `DesignDocReview` label to get the **High-level of proposed solution** section reviewed
- [x] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Host another pre-design meeting in the appropriate slack channel to ask for engineering feedback on the technical solution. (f[ollow-up discussion](https://expensify.slack.com/archives/C04E99DVBTP/p1689002962054419))
- [x] Fill out the **Detailed implementation of the solution** and related sections.
- [x] Re-add the `DesignDocReview` label to this issue
- [ ] Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary
- [ ] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [ ] Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase
- [ ] Implement the changes
- [ ] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

**Comment by MelvinBot** [comment]
This issue has not been updated in over ***15*** days.  eroding to ***Monthly*** issue.

P.S. Is everyone reading this sure this is really a near-term priority? Be brave: if you disagree, go ahead and close it out. If someone disagrees, they'll reopen it, and if they don't: one less thing to do!

**Comment by roryabraham** [comment]
@arosiclair do you want to take this issue over?

**Comment by arosiclair** [comment]
Sure! I'll follow through on this

**Comment by arosiclair** [comment]
[Posted to WN](https://expensify.slack.com/archives/CC7NECV4L/p1680884231927239). Gonna start drafting pre-design questions soon

**Comment by arosiclair** [comment]
I drafted some questions for the pre-design, but am prioritizing Distance Requests design doc atm.

**Comment by arosiclair** [comment]
I'm adding a pre-design section on tracking the success rate of the background refresh with logging.

Today I tested the our background update functionality and found that it wasn't working properly on our current airship version ([react-native-airship](https://github.com/urbanairship/react-native-airship) v15.2.3). I worked with Ryan on this [here](https://expensify.slack.com/archives/C01RJ1RCK8D/p1684357714295549?thread_ts=1680726433.652809&cid=C01RJ1RCK8D) and we've got a new version with some fixes coming in v15.2.6! We'll have to do another upgrade but this should be quick since it's just a patch.

Additionally I'm testing how well we can detect when the app is in the background. We have a visibility function that checks `AppState.currentState === 'active'` on native for this, but we found that to be unreliable in the past. However, currently I'm seeing no issues on my Pixel 4A with Android 13. I'm starting a discussion on this.

**Comment by arosiclair** [comment]
`AppState.currentState === 'active'` testing works in all of the following configs!

- Pixel 4A - Android 13 ✅ 
- Pixel 3 - Android 9 (Emulator) ✅ 
- iPhone 11 - iOS 16 ✅ 

While testing background updates on iOS, I noticed that the full app is being woken and `OpenApp` and `ReconnectApp` are actually already running in the background when we receive push notifications. To ensure we're not doing duplicate work, we should probably check if the app is in the foreground before running OpenApp/ReconnectApp.

**Comment by arosiclair** [comment]
Held the pre-design [here](https://expensify.slack.com/archives/C056AV5V8UX/p1684788808189649). 

One of the bigger takeaways is that we'll want play nicely with [upcoming improvements for ReconnectApp](https://github.com/Expensify/Expensify/issues/282035). Specifically how we'll fetch report actions using `GetChats` detailed by Marc [here](https://expensify.slack.com/archives/C056AV5V8UX/p1684792304186639?thread_ts=1684788858.832619&cid=C056AV5V8UX).

I'll begin drafting a design doc get all of this written down.

**Comment by arosiclair** [comment]
HLD is being drafted. Aiming to put that out this week

**Comment by arosiclair** [comment]
Not quite finished yet but 90% done. Need to add a couple contextual bits and ask about using NVPs for throttling ([discussion](https://expensify.slack.com/archives/C03TQ48KC/p1686586110336299))

**Comment by arosiclair** [comment]
Addressed some pre-review comments. Putting this out tomorrow!

**Comment by arosiclair** [comment]
I'm updating the OP to use the project/design doc template. Rory's original proposal for posterity:

> Slack context: https://expensify.slack.com/archives/C04E99DVBTP/p1675977099688389
> 
> ### Problem
> We want our app to be offline-first. In order to make that experience as good as it can be, we want to make sure that while the phone is connected to the network, we deliver as much up-to-date information to the app as possible. We can refer to this as a “background data trickle”.
> 
> In order to do this on mobile devices even if the app is backgrounded or not running, we have had solutions in place for a while:
> 
> - :apple: on iOS we deliver notifications with the content-available flag. This informs the OS that there’s work to be done in relation to that notification, and it wakes up the app in the background [(docs)](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app).
> - 🤖 on Android, we use [headless JS](https://reactnative.dev/docs/headless-js-android) to process background notifications.
> 
> While this solution sometimes works, it has some _crippling_ limitations.
> 
> - :apple: – on iOS
>     - When a device receives a background notification, the system may hold and delay the delivery of the notification, which can have the following side effects:
>         - When the system receives a new background notification, it discards the older notification and only holds the newest one.
>         - If something force quits or kills the app, the system discards the held notification
>         - Your app has 30 seconds to perform any tasks and call the provided completion handler
>     - The documentation says: "The system treats background notifications as low priority: you can use them to refresh your app’s content, but the system doesn’t guarantee their delivery ... don't try to send more than two or three per hour"
> - :android-bot: – on Android, this is more reliable, but is also prone to OS limitations based on the system conditions (for example, if the device is running low on battery)
> 
> Furthermore, when these methods don't work, it causes a pretty bad UX. For example, it's totally feasible to get "ghost notifications", and this happens to me all the time on iOS:
> 
> - You are online and receive a push notification.
> - The OS throttles you and does not wake up the app in the background, so the data from that notification is not inserted into Onyx.
> - You go offline and open the app
> - You open the app, and the message from the notification is missing, and does not reappear until you come online.
> 
> Note: a similar bug occurs if you are online, but the message appears moments later after the OpenApp API request completes and Onyx is updated.
> 
> ### Solution
> This is just part of the solution proposed in slack, but...
> 
> Start getting more greedy with the background events the host OS gives us. :grabby_hands: This means that when a notification wakes our app in the background, we don't just insert the single reportAction from the notification into Onyx. Instead, we just call `OpenApp` and update all the app's data. As long as this completes within 30 seconds that should work.

**Comment by marcaaron** [comment]
I have read and reviewed this Design Doc!

**Comment by isabelastisser** [comment]
I have read and reviewed this Design Doc!

**Comment by iwiznia** [comment]
I have read and reviewed this Design Doc!

**Comment by nathanmetcalf** [comment]
I have read and reviewed this Design Doc!

**Comment by StefStavri** [comment]
I have read and reviewed this Design Doc!

**Comment by arosiclair** [comment]
Addressed some comments today

**Comment by anmurali** [comment]
I have read and reviewed this Design Doc!

**Comment by jasperhuangg** [comment]
I have read and reviewed this Design Doc!

**Comment by arosiclair** [comment]
Just need another Product Manager signature. Also broke out a discussion on a concern from Ionaton ([link](https://expensify.slack.com/archives/C04E99DVBTP/p1687369300377229))

**Comment by puneetlath** [comment]
I have read and reviewed this Design Doc!

**Comment by pecanoro** [comment]
I have read and reviewed this Design Doc!

**Comment by arosiclair** [comment]
We've gotten all the necessary signatures! Moving forward to the detailed design

**Comment by cead22** [comment]
I have read and reviewed this Design Doc!

**Comment by arosiclair** [comment]
Made good progress on the detailed design today and mostly completed the "Sending refresh notifications section".

**Comment by JmillsExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by arosiclair** [comment]
Made good progress last week but only about 75% of the way there. Some remaining items to address:

- [ ] start a discussion on fetching report actions for top chats
- [ ] add details for logging
- [ ] finish up detailed background section

**Comment by arosiclair** [comment]
Detailed design is complete! I'll open an issue to time our queries for getting and updating the `lastBackgroundRefreshTime` NVP for a large room and start the next round of reviews

**Comment by anmurali** [comment]
I have read and reviewed this Design Doc!

**Comment by Julesssss** [comment]
I have read and reviewed this Design Doc!

**Comment by Gonals** [comment]
I have read and reviewed this Design Doc!

**Comment by StefStavri** [comment]
I have read and reviewed this Design Doc!

**Comment by flodnv** [comment]
I have read and reviewed this Design Doc!

**Comment by conorpendergrast** [comment]
I have read and reviewed this Design Doc!

**Comment by garrettmknight** [comment]
I have read and reviewed this Design Doc!

**Comment by jasperhuangg** [comment]
I have read and reviewed this Design Doc!

**Comment by nathanmetcalf** [comment]
I have read and reviewed this Design Doc!

**Comment by twisterdotcom** [comment]
I have read and reviewed this Design Doc!

**Comment by yuwenmemon** [comment]
I have read and reviewed this Design Doc!

**Comment by francoisl** [comment]
I have read and reviewed this Design Doc!

**Comment by pecanoro** [comment]
I have read and reviewed this Design Doc!

**Comment by arosiclair** [comment]
This gonna get pushed back as I update this to use changes from #vip-reliable-updates. More updates to come

**Comment by johnmlee101** [comment]
I have read and reviewed this Design Doc!

**Comment by arosiclair** [comment]
We held a couple discussions ([1](https://expensify.slack.com/archives/C04E99DVBTP/p1690362342144569), [2](https://expensify.slack.com/archives/C04E99DVBTP/p1690487843904039)) on updating this to use the new reconnect pattern from #vip-reliable-updates and also remove  the use of throttling for refresh notifications. 

Both of these decisions significantly scale down the scope of this project since we are already sending refresh notifications and these notifications already trigger a call to OpenApp/ReconnectApp on iOS. I'll work to verify the same on Android. If it is not the same, we'll just add a call to `App.reconnectApp()` in the push notification handler for when the app is in the background.

Since the scope is now so small, I'll "downgrade" this from a project with a design doc to a normal issue. I should be able to finish this week.

**Comment by Julesssss** [comment]
Sounds good. Do we still plan to complete this as part of the Reliable Updates project?

**Comment by arosiclair** [comment]
Yeah I can get this squared away very soon and then we can finally close out the project. I'll post 2 small PRs to add logs to App and Web-E today. Then testing and updating Android to call reconnectApp should also be pretty easy.

**Comment by arosiclair** [comment]
@garrettmknight this is all set could you just do payment to @Ollyws for his C+ review?

**Comment by garrettmknight** [comment]
@Ollyws sorry for the wait, can you accept the offer and I'll pay?

**Comment by garrettmknight** [comment]
**Summarizing payments for this issue:**

**#urgency bonus?** No
**Contributor+:** @Ollyws $1000

Upwork Job: https://www.upwork.com/ab/applicants/1694731046889934848/job-details

**Comment by garrettmknight** [comment]
All paid, closing.
