### ISSUE TITLE
[HOLD][Tracking] CSP error related issues for newDot

### ISSUE THREAD

**Issue by techievivek** [Expensify/App#15244]
We currently send CSP (content security policy) related headers for newDot using Cloudflare workers, which are only set up for our staging and prod environments. Therefore, testing changes related to CSP on the DEV server is a bit cumbersome. However, we have good news that a [whatsnext](https://expensify.slack.com/archives/CC7NECV4L/p1670264158167419) proposal is in progress, which involves moving the Cloudflare workers code for newDot to the App repo. Until this is done, we kindly request that we keep a pause on working on any issue related to CSP.

If you would like to learn more about CSP, please visit: https://content-security-policy.com/. Additionally, if you're interested in learning more about Cloudflare workers, please visit: https://developers.cloudflare.com/workers/.

For your reference, here are a couple of related issue lists:

- https://github.com/Expensify/App/issues/15042
- https://github.com/Expensify/Expensify/issues/246097
- https://github.com/Expensify/App/issues/24084

Please feel free to add any issues to the list that are related to the CSP error.

Thank you!
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109c13461109f87b5</li>
        <li>Upwork Job ID: 1636794996814442496</li>
        <li>Last Price Increase: 2023-03-17</li>
    </ul>
</details>

**Comment by MelvinBot** [comment]
Triggered auto assignment to @davidcardoza (`Bug`), see https://stackoverflow.com/c/expensify/questions/14418 for more details.

**Comment by MelvinBot** [comment]
### Bug0 Triage Checklist ([Main S/O](https://stackoverflowteams.com/c/expensify/questions/14418))

- [ ] This "bug" occurs on a supported platform (ensure `Platforms` in OP are ✅)
- [ ] This bug is not a duplicate report (check [E/App issues](https://github.com/Expensify/App/issues) and [#expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM))
    - If it is, comment with a link to the original report, close the issue and add any novel details to the original issue instead
- [ ] This bug is reproducible using the reproduction steps in the OP. [S/O](https://stackoverflowteams.com/c/expensify/questions/14418#:~:text=The%20bug%20is%20reproducible)
    - If the reproduction steps are clear and you're unable to reproduce the bug, check with the reporter and QA first, then close the issue.
    - If the reproduction steps aren't clear and you determine the correct steps, please update the OP.
- [ ] This issue is filled out as thoroughly and clearly as possible
    - Pay special attention to the title, results, platforms where the bug occurs, and if the bug happens on staging/production.
- [ ] I have reviewed and subscribed to the linked Slack conversation to ensure Slack/Github stay in sync

**Comment by techievivek** [comment]
Sorry for the ping @davidcardoza, this is just a tracking issue.

**Comment by techievivek** [comment]
Adding this to weekly until we have some movement in the whatsnext proposal.

**Comment by techievivek** [comment]
@justinpersaud Hi, any updates on the [proposal](https://expensify.slack.com/archives/CC7NECV4L/p1670264158167419) to move the newDot Cloudflare worker code to the `App` repo? Will you be working on the project?

**Comment by MelvinBot** [comment]
@techievivek this issue was created 2 weeks ago. Are we close to a solution? Let's make sure we're treating this as a top priority. Don't hesitate to create a thread in #expensify-open-source to align faster in real time. Thanks!

**Comment by techievivek** [comment]
No update on the [whatsnext](https://expensify.slack.com/archives/CC7NECV4L/p1670264158167419) proposal but given this is not a big issue for us it should be just fine to hold this for some time.

**Comment by MelvinBot** [comment]
@techievivek this issue is now 3 weeks old. There is one more week left before this issue <a href='https://stackoverflowteams.com/c/expensify/questions/15233/15234#15234'>breaks WAQ</a>. What needs to happen to get a PR in review this week? Please create a thread in #expensify-open-source to discuss. Thanks!

**Comment by MelvinBot** [comment]
@techievivek Uh oh! This issue is overdue by 2 days. Don't forget to update your issues!

**Comment by techievivek** [comment]
I had a talk with Justin P during minishore in London and we did discuss a few ideas on how we can bring CSP to newDot. I will start looking into it after the ExpensiconX but I will utilize the time during ECX to discuss this with Rory.

**Comment by MelvinBot** [comment]
Job added to Upwork: https://www.upwork.com/jobs/~0109c13461109f87b5

**Comment by MelvinBot** [comment]
Triggered auto assignment to Contributor Plus for review of internal employee PR - @thesahindia (`Internal`)

**Comment by techievivek** [comment]
Sorry @thesahindia for the ping, this is a tracking issue for an issue related to content-security policy error. We do have a proposal in the process that would fix these kinds of issues but we are still in the middle of the discussion.

**Comment by MelvinBot** [comment]
@techievivek Whoops! This issue is 2 days overdue. Let's get this updated quick!

**Comment by techievivek** [comment]
We had some movement in the whatsnext to move the newDot from S3 to our own servers https://expensify.slack.com/archives/CC7NECV4L/p1679342455911239?thread_ts=1678994690.390109&cid=CC7NECV4L, given that we are still not prioritizing working on CSP changes for [now](https://expensify.slack.com/archives/CC7NECV4L/p1679060321387249?thread_ts=1678994690.390109&cid=CC7NECV4L).

**Comment by techievivek** [comment]
Moving this to monthly until we have made some progress on the above whatsnext proposal.

**Comment by techievivek** [comment]
Justin P has started working on the design doc to bring newDot to our own server. We will soon have a way to migrate CSP headers from cloudflare to our own servers.

**Comment by techievivek** [comment]
Still on HOLD for migration newDot from Cloudflare to our own servers.

**Comment by rushatgabhane** [comment]
@techievivek spotted a similar error here - https://github.com/Expensify/App/issues/24084

**Comment by techievivek** [comment]
Still on HOLD.

**Comment by techievivek** [comment]
No progress seems to be coming from the infra team on switching from the AWS to our own server.

**Comment by justinpersaud** [comment]
@techievivek can you refresh my memory on why these specifically depend on the migration? Is there nothing we can do today to solve these?

**Comment by techievivek** [comment]
@justinpersaud 
I believe we encountered some CSP errors, as indicated in this [GH](https://github.com/Expensify/Expensify/issues/246097#issue-1471885757). To address this, we generated a nonce and added it to our CSP rule in this [PR](https://github.com/Expensify/Cloudflare-Workers/pull/43/files). However, when we deployed these changes, they didn't have the desired effect, and there was no way to test them locally. Consequently, we decided to put all CSP-related issues on hold. The plan was to revisit and resolve these issues once we migrate to our own servers, at which point we'll have a more convenient way to test and rectify these problems.

Here is a current CSP issue that we haven't yet resolved.
<img width="1721" alt="Screenshot 2023-10-25 at 6 17 23 PM" src="https://github.com/Expensify/App/assets/35863227/61ef67c8-d602-4e9e-9082-fe1c910b5543">

**Comment by justinpersaud** [comment]
> there was no way to test them locally.

This isn't true anymore. There is a way to test them locally, we just haven't fully put together the instructions on how to do it because there wasn't a use case.

Also, we have a function now to generate a nonce and have a script that uses it and working today.

https://github.com/Expensify/Cloudflare-Workers/blob/main/new.expensify.com/index.js#L9-L17

It's not clear to me that this needs to be held on any migration and can't be solved another way.

**Comment by techievivek** [comment]
> It's not clear to me that this needs to be held on any migration and can't be solved another way.

This doesn't need to be held of any migration if there is an easy way to test changes made to CSP rule on DEV.

> This isn't true anymore. There is a way to test them locally, we just haven't fully put together the instructions on how to do it because there wasn't a use case.

It will be great to have the instruction written on an SO, I can try fixing this once I have a way to test it locally.

> Also, we have a function now to generate a nonce and have a script that uses it and working today.
https://github.com/Expensify/Cloudflare-Workers/blob/main/new.expensify.com/index.js#L9-L17

Wow this is cool `CONTENT_SECURITY_POLICY.replace('nonce-random-value', `nonce-${generateNonce()}`)`. 👌

**Comment by justinpersaud** [comment]
>It will be great to have the instruction written on an SO, I can try fixing this once I have a way to test it locally.

It's a bit more than that. Can you create a GH and assign me with all the requirements you need for your testing? Include details on how you specifically want to test and what you're expecting if possible.

**Comment by techievivek** [comment]
Sorry, couldn't prioritize this I will take a dig into it and have a GH ready for you soon, thanks.

**Comment by techievivek** [comment]
Sorry, couldn't prioritize this since I have been working on 2 EOY projects.

**Comment by techievivek** [comment]
Closing CSP related bugs for now based on this comment https://github.com/Expensify/App/issues/15042#issuecomment-1927017248
