### ISSUE TITLE
[Tracking] Close the gaps on email responses and formatting in app

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#15336]
### Problem
If someone hasn't seen a message in App, we fallback on email, which is great in that this means you don't have to actively be in the app in order to chat with our support team, or even other people. That said, email is kind of an animal of it's own, with different clients approaching formatting differently, we have less control of what's available and what's not, how information is received/sent, and the link. This ends up creating not only an inconsistent experience, but importantly, a frustrating one for our own town and those who they interact with. 

### Solution
Let's group any and all `bug` reports we receive around email formatting, find patterns, and device a holistic solution that closes the gap in how NewDot is experienced whether you're in the app or not. 

### Outstanding Issues
 - https://github.com/Expensify/App/issues/15138
 - https://github.com/Expensify/App/issues/15141
 - https://github.com/Expensify/App/issues/15286
 - https://github.com/Expensify/App/issues/15336

**Comment by JmillsExpensify** [comment]
Assigning myself for now to help get this off the ground.

**Comment by JmillsExpensify** [comment]
@ctkochan22 It's be awesome if you can take this initiative on, including the linked issue. I've also let QA know to be on the lookout for any future reports that are found in this same vein.

**Comment by ctkochan22** [comment]
I'm stoked to take this on

**Comment by ctkochan22** [comment]
Okay, going off some tips from Jason. Lets start a prelim investigation to get a scope on this issue:
- [ ] Let QA know about this tracking GH and to keep an eye peeled on any sort of issues, specifically with formatting, with emailing responses in NewDot
- [ ] Look through currently open issues that may fall within the scope/umbrella of this issue and bring it into the fold.
- [ ] Going to start testing email as well and try to find other issues we can address in this issue

**Comment by trjExpensify** [comment]
Love it. @ctkochan22 is it a huge lift to allow for attachments uploaded in the chat to be added to the emails they receive?

**Comment by ctkochan22** [comment]
> is it a huge lift to allow for attachments uploaded in the chat to be added to the emails they receive?

Let me take a look!

**Comment by ctkochan22** [comment]
Found only one other issue. Will start testing tomorrow, and I'll include trying out attachments.

**Comment by JmillsExpensify** [comment]
If we add attachments, let's also create a separate issue for that one and add it to this issue. Love that idea btw.

**Comment by ctkochan22** [comment]
Next Steps:
- Continue testing the email reply functionality. Try all formatting styles. 
- Create a new issue about allowing for attachments uploaded in the chat to be added to the emails they receive

I think the tracking issue is not super expansive. Needs a bit of collective discussions and maybe a very small design doc. But probably just a large summary in this GH would be enough


Other notes:
- All our email routes through mailgun. If testing locally, there is a SO: https://stackoverflowteams.com/c/expensify/questions/5749/5750#5750

**Comment by JmillsExpensify** [comment]
I'll keep myself assigned for the time being and work on finding someone to help lead this one up!

**Comment by JmillsExpensify** [comment]
Still not focused on this given that we're all at ECX this week.

**Comment by JmillsExpensify** [comment]
Still trying to get on top of other things and get back to this.

**Comment by JmillsExpensify** [comment]
Still not a priority

**Comment by JmillsExpensify** [comment]
Still not a priority

**Comment by JmillsExpensify** [comment]
Not a priority

**Comment by JmillsExpensify** [comment]
Still not a priority

**Comment by JmillsExpensify** [comment]
Not a priority.

**Comment by JmillsExpensify** [comment]
Considering closing this one. Going to get more feedback before doing so.

**Comment by JmillsExpensify** [comment]
Closing this and we stopped getting reports of these issue and this is a hold-over from WAQ.
