### ISSUE TITLE
Add security code hash to magic code SMS for native Android

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#15342]
### Problem

We are going passwordless and we are using magic links and magic codes to sign in users. This feature is now under beta and its being slowly rolled out. We have implemented the SMS code autofill for magic code for all available platforms except Android Native where it requires a backend change https://github.com/Expensify/App/issues/14853

### Why is it important

This is improving UX and sets NewDot on par with other apps using similar security passcodes and consistency across the platforms.

### Solution

As @narefyev91 detailed in [this comment](https://github.com/Expensify/App/issues/14853#issuecomment-1425753015), we will have to add a specific Hash to the SMS message with magic code if it has been triggered from native Android.

There are some details about [the hash here](https://developers.google.com/identity/sms-retriever/verify#computing_your_apps_hash_string). To generate hash you can use this [sh file ](https://github.com/googlearchive/android-credentials/blob/master/sms-verification/bin/sms_retriever_hash_v9.sh) - command to execute `./sms_retriever_hash_v9.sh --package com.expensify.chat --keystore ./android/app/debug.keystore` (for debug keystore `hash = h7MoDsTCzjw`).

In PHP, we will have to check if the request is coming from a native Android device and in such case, we need to update the content of the message to include the hash detailed above.

@narefyev91 will be the best person to ask for help regarding the hash

### Task (Added by @hayata-suenaga)
As this issue needs several PRs and deployment of these PRs needs to be coordinated, I list these PRs here

- App: https://github.com/Expensify/App/pull/15973
- Auth: https://github.com/Expensify/Auth/pull/7637
- Web-E: https://github.com/Expensify/Web-Expensify/pull/36728

The deployment schedule should be App, Auth -> Web-E.
This means that Web-E should be held until App and Auth PRs are deployed to production. App and Auth PRs can be deployed independent of each other.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01078cb4f203d82721</li>
        <li>Upwork Job ID: 1628334514741329920</li>
        <li>Last Price Increase: 2023-02-22</li>
    </ul>
</details>

**Comment by MelvinBot** [comment]
Job added to Upwork: https://www.upwork.com/jobs/~01078cb4f203d82721

**Comment by MelvinBot** [comment]
Triggered auto assignment to @mallenexpensify (`Bug`), see https://stackoverflow.com/c/expensify/questions/14418 for more details.

**Comment by MelvinBot** [comment]
### Bug0 Triage Checklist ([Main S/O](https://stackoverflowteams.com/c/expensify/questions/14418))

- [ ] This "bug" occurs on a supported platform (ensure `Platforms` in OP are ✅)
- [ ] This bug is not a duplicate report (check [E/App issues](https://github.com/Expensify/App/issues) and [#expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM))
    - If it is, comment with a link to the original report, close the issue and add any novel details to the original issue instead
- [ ] This bug is reproducible using the reproduction steps in the OP. [S/O](https://stackoverflowteams.com/c/expensify/questions/14418#:~:text=The%20bug%20is%20reproducible)
    - If the reproduction steps are clear and you're unable to reproduce the bug, check with the reporter and QA first, then close the issue.
    - If the reproduction steps aren't clear and you determine the correct steps, please update the OP.
- [ ] This issue is filled out as thoroughly and clearly as possible
    - Pay special attention to the title, results, platforms where the bug occurs, and if the bug happens on staging/production.
- [ ] I have reviewed and subscribed to the linked Slack conversation to ensure Slack/Github stay in sync

**Comment by MelvinBot** [comment]
Triggered auto assignment to Contributor Plus for review of internal employee PR - @sobitneupane (`Internal`)

**Comment by mountiny** [comment]
Asking internally who wants to pick this up

**Comment by mallenexpensify** [comment]
@mountiny do you have a link to where the convo is happening?

**Comment by mountiny** [comment]
Asked [here](https://expensify.slack.com/archives/C048ZLJ78P5/p1677060400333009?thread_ts=1676936827.200649&cid=C048ZLJ78P5), nobody picked this up yet.

**Comment by MelvinBot** [comment]
@mallenexpensify, @sobitneupane Whoops! This issue is 2 days overdue. Let's get this updated quick!

**Comment by mallenexpensify** [comment]
Dropped 
https://expensify.slack.com/archives/C03TQ48KC/p1677639117983239
and 
https://expensify.slack.com/archives/C048ZLJ78P5/p1677639059384809?thread_ts=1676936827.200649&cid=C048ZLJ78P5

looking for help 🤞

**Comment by hayata-suenaga** [comment]
@mallenexpensify I saw this is a `first pick` issue. I'd like to take this issue

**Comment by hayata-suenaga** [comment]
Asked [a question on slack](https://expensify.slack.com/archives/C048ZLJ78P5/p1677876018341369)

**Comment by hayata-suenaga** [comment]
I'm still working on the PR

**Comment by MelvinBot** [comment]
@mallenexpensify @sobitneupane @hayata-suenaga this issue was created 2 weeks ago. Are we close to a solution? Let's make sure we're treating this as a top priority. Don't hesitate to create a thread in #expensify-open-source to align faster in real time. Thanks!

**Comment by hayata-suenaga** [comment]
putting PR for this now

**Comment by hayata-suenaga** [comment]
seeking help with getting access to production deployment certification (which is needed to compute the hash) in [slack](https://expensify.slack.com/archives/C03TQ48KC/p1678318008542059).

**Comment by roryabraham** [comment]
Self-assigning to help unblock @hayata-suenaga by generating the hash

**Comment by roryabraham** [comment]
Ok @hayata-suenaga, the production hash is `h7MoDsTCzjw`

**Comment by hayata-suenaga** [comment]
@Rory I think the hash you posted `h7MoDsTCzjw` might have created using the debug keystore instead of the production keystore. That is the same hash that @vit posted [here](https://github.com/Expensify/App/issues/15342#issue-1594809058).  It's also the same hash I got when I ran the hash creation script on my local computer.

I'd appreciate it if you could double check it when you have time.

**Comment by roryabraham** [comment]
Hmmm... that is weird. I'm getting the same hash with the debug keystore and the one I downloaded from 1P.

**Comment by roryabraham** [comment]
I have decrypted the production keystore directly using [this line of code](https://github.com/Expensify/App/blob/cf87317ccfb7c61de76c41f576c1d62e7bcf6012/.github/workflows/platformDeploy.yml#L47), then computed the hash again, and got the same result. So it seems like that hash is correct? Weird.

**Comment by AndrewGable** [comment]
@roryabraham and I were able to confirm the production hash is: `xy9/YUBP8xj`

We were not 100% able to confirm this, but we think the dev hash is: `VdYMaWKQlXp`

Please let us know if you need any more help with the hashes 👍

**Comment by hayata-suenaga** [comment]
okay there is two possibilities for the dev hash somehow, `h7MoDsTCzjw` [here](https://github.com/Expensify/App/issues/15342#issuecomment-1462423321) and `VdYMaWKQlXp` [here](https://github.com/Expensify/App/issues/15342#issuecomment-1470000848).

I'll mention both hash on my PR so people can try both when testing.

**Comment by MelvinBot** [comment]
@mallenexpensify, @sobitneupane, @hayata-suenaga Uh oh! This issue is overdue by 2 days. Don't forget to update your issues!

**Comment by hayata-suenaga** [comment]
PRs are under review now

**Comment by MelvinBot** [comment]
@mallenexpensify, @sobitneupane, @hayata-suenaga Uh oh! This issue is overdue by 2 days. Don't forget to update your issues!

**Comment by hayata-suenaga** [comment]
PRs are still under review

**Comment by MelvinBot** [comment]
@mallenexpensify, @sobitneupane, @hayata-suenaga Uh oh! This issue is overdue by 2 days. Don't forget to update your issues!

**Comment by hayata-suenaga** [comment]
Waiting for the PR to be deployed to production to do QA.

**Comment by MelvinBot** [comment]
@mallenexpensify, @sobitneupane, @hayata-suenaga Huh... This is 4 days overdue. Who can take care of this?

**Comment by mountiny** [comment]
Have you been able to test this?

**Comment by hayata-suenaga** [comment]
@mountiny yes I was able to confirm the autofill option appears when I log in from Android.

![image000000](https://user-images.githubusercontent.com/98560306/232821139-37fa7303-ed9a-4418-b13e-bdfc42602939.PNG)

**Comment by mountiny** [comment]
@hayata-suenaga great job! Thanks for sticking with this!

**Comment by mountiny** [comment]
I think we can close this, right, or @sobitneupane are you awaiting any payment in here, I think there was no App pr

**Comment by sobitneupane** [comment]
Good to close. No payment for me.
