### ISSUE TITLE
[Tracking] Fix Composer Component Focus Issues

### ISSUE THREAD

**Issue by bondydaa** [Expensify/App#15992]
## Proposal
There have been a few threads where these discussions happened (Expenisfy internal slack discussion) https://expensify.slack.com/archives/C03U7DCU4/p1673042523102459?thread_ts=1672788778.947399&cid=C03U7DCU4

and here in the external slack https://expensify.slack.com/archives/C01GTK53T8Q/p1671056016060879

I believe the final place we landed was 
> give focus back to the composer input AND allow the software keyboard to be shown at the same time

Ultimately what we want to do is stop trying to continually patch the existing code as we've sort of gotten into a bad spot with it. The goal of this is to start with a blank canvas and come up with a plan on how we want the composer component and the focus/blur interactions to work as if it didn't exist yet. 

Once we have the overall design we desire we can then see how the current code fits with it, if it needs to be rewritten then we'll do that, if we can just tweak the existing code and get it to work then we can do that. 

## Tasks

- [ ] Post **Proposal (full Problem/Solution statement)** in `#expensify-open-source`
- [ ] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [ ] Paste Proposal in the space above with a link to the Slack thread
- [ ] Email `strategy@expensify.com` and paste in the Proposal
- [ ] Fill out the **High-level overview of the problem**, **Timeline**, and **Terminology** sections of the Design Doc
- [ ] Email `strategy@expensify.com` (continue the same email chain as before) with the link to your Design Doc
- [ ] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [ ] Fill out the **High-level of proposed solution** section
- [ ] Email `stategy@expensify.com` again with links to the doc and pre-design conversation in Slack
- [ ] Add the `DesignDocReview` label to get the **High-level of proposed solution** section reviewed
- [ ] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [ ] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [ ] Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.
- [ ] Fill out the **Detailed implementation of the solution** and related sections.
- [ ] Re-add the `DesignDocReview` label to this issue
- [ ] Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary
- [ ] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [ ] Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase
- [ ] Implement the changes
- [ ] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

# Related Issues (Please add any new issues as they are reported) N.B. - closing some until this is picked up.
- https://github.com/Expensify/App/pull/14230
- https://github.com/Expensify/App/issues/16362
- https://github.com/Expensify/App/issues/16844
- https://github.com/Expensify/App/issues/16699
- https://github.com/Expensify/App/issues/16596
- https://github.com/Expensify/App/issues/18001
- https://github.com/Expensify/App/issues/17274
- https://github.com/Expensify/App/issues/18007
- https://github.com/Expensify/App/issues/21401
- https://github.com/Expensify/App/issues/22664
- https://github.com/Expensify/App/issues/23489
- https://github.com/Expensify/App/issues/27182
- https://github.com/Expensify/App/issues/28921
- https://github.com/Expensify/Expensify/issues/329380
- https://github.com/Expensify/App/issues/30689

**Comment by MelvinBot** [comment]
Now this issue is 8 days overdue. Are you sure this should be a Daily? Feel free to change it!

**Comment by MelvinBot** [comment]
12 days overdue. Walking. Toward. The. Light...

**Comment by MelvinBot** [comment]
This issue has not been updated in over ***14*** days.  eroding to ***Weekly*** issue.

**Comment by MelvinBot** [comment]
⚠️ Looks like this issue was linked to a **Deploy Blocker** [here](https://github.com/Expensify/App/issues/17465)

If you are the assigned CME please investigate whether the linked PR caused a regression and leave a comment with the results.

If a regression has occurred and you are the assigned CM follow the instructions [here](https://stackoverflow.com/c/expensify/questions/13647).

If this regression could have been avoided please consider also proposing a recommendation to the PR checklist so that we can avoid it in the future.

**Comment by Natnael-Guchima** [comment]
> ⚠️ Looks like this issue was linked to a **Deploy Blocker** [here](https://github.com/Expensify/App/issues/17465)
> 
> If you are the assigned CME please investigate whether the linked PR caused a regression and leave a comment with the results.
> 
> If a regression has occurred and you are the assigned CM follow the instructions [here](https://stackoverflow.com/c/expensify/questions/13647).
> 
> If this regression could have been avoided please consider also proposing a recommendation to the PR checklist so that we can avoid it in the future.

My bad, I mentioned this issue in the wrong place.

**Comment by MelvinBot** [comment]
This issue has not been updated in over ***15*** days.  eroding to ***Monthly*** issue.

P.S. Is everyone reading this sure this is really a near-term priority? Be brave: if you disagree, go ahead and close it out. If someone disagrees, they'll reopen it, and if they don't: one less thing to do!

**Comment by Natnael-Guchima** [comment]
this might need to be tracked here https://github.com/Expensify/App/issues/18007

**Comment by michaelhaxhiu** [comment]
Is there any indication of when we can prioritize this? Is it held on a specific internal wave @bondydaa? Or it hasn't been slotted on the roadmap yet?

**Comment by bondydaa** [comment]
🤷 i'm not leading this just created the issue, probably needs someone to assign themselves and then it will get prioritized.

**Comment by michaelhaxhiu** [comment]
cc @JmillsExpensify curious for your input. Do you think this is worth slotting into the roadmap or should we just hold longer?

**Comment by michaelhaxhiu** [comment]
Still held

**Comment by abdulrahuman5196** [comment]
@bondydaa I think this https://github.com/Expensify/App/issues/22664 also should be part of this issue

**Comment by abdulrahuman5196** [comment]
@bondydaa And this as well https://github.com/Expensify/App/issues/22676.

Could you kindly confirm if both the above issues should be part of this tracking issue or handled separately.

**Comment by abdulrahuman5196** [comment]
Gentle ping on both the above @bondydaa

**Comment by bondydaa** [comment]
feel free to edit and add them as you see fit, I don't need to be pinged or approve adding issues to this.

**Comment by sakluger** [comment]
Added https://github.com/Expensify/App/issues/22664 to the list of related issues.

**Comment by tjferriss** [comment]
@bondydaa this issue also looks related https://github.com/Expensify/App/issues/22949

**Comment by Beamanator** [comment]
Adding these two, very similar focus issues:
- https://github.com/Expensify/App/issues/27182
- https://github.com/Expensify/App/issues/28921

**Comment by JmillsExpensify** [comment]
Adding this similar issue:

 - https://github.com/Expensify/App/issues/28139

**Comment by abekkala** [comment]
https://github.com/Expensify/App/issues/30178
