### ISSUE TITLE
[HOLD for payment 2023-04-26] [$250] Migrate Expensify.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16107]
### Filenames
- [ ] [src/Expensify.js](https://github.com/Expensify/App/blob/main/src/Expensify.js)
    - **type:** `React.PureComponent`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`,`componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
Just closing the loop on your question @tgolen. I think I answered it in [this Slack thread](https://expensify.slack.com/archives/GNNQZ1MD1/p1680531323975969).

The issues are mostly on HOLD as we are primarily focusing on roadmap progress. Open to ideas on how to do the migration. But it feels lower in priority than some other more urgent things.

**Comment by MelvinBot** [comment]
@jasperhuangg Uh oh! This issue is overdue by 2 days. Don't forget to update your issues!

**Comment by jasperhuangg** [comment]
Still under review, not overdue!

**Comment by MelvinBot** [comment]
@jasperhuangg Huh... This is 4 days overdue. Who can take care of this?

**Comment by MelvinBot** [comment]
@jasperhuangg 6 days overdue. This is scarier than being forced to listen to Vogon poetry!

**Comment by jasperhuangg** [comment]
Been OOO, back today and gonna move the PR forward.

**Comment by MelvinBot** [comment]
`Reviewing` label has been removed, please complete the "BugZero Checklist".

**Comment by MelvinBot** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.3.1-3 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/16664


If no regressions arise, payment will be issued on 2023-04-26. :confetti_ball:

After the hold period is over and BZ checklist items are completed, please complete any of the applicable payments for this issue, and check them off once done.
- [ ] External issue reporter
- [ ] Contributor that fixed the issue
- [ ] Contributor+ that helped on the issue and/or PR

As a reminder, here are the bonuses/penalties that should be applied for any External issue:
- Merged PR within 3 business days of assignment - 50% **bonus**
- Merged PR more than 9 business days after assignment - 50% **penalty**
