### ISSUE TITLE
[$250] Migrate CopyTextToClipboard.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16132]
### Filenames
- [ ] [src/components/CopyTextToClipboard.js](https://github.com/Expensify/App/blob/main/src/components/CopyTextToClipboard.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014eb969b6eb24ef4c</li>
        <li>Upwork Job ID: 1651267789867552768</li>
        <li>Last Price Increase: 2023-04-26</li>
    </ul>
</details>

**Comment by PauloGasparSv** [comment]
Not overdue

**Comment by marcaaron** [comment]
@PauloGasparSv taking this issue off HOLD as per this [Slack post](https://expensify.slack.com/archives/C03TQ48KC/p1680708858739299)

**IMPORTANT:** If anything unexpected pops up during the refactor/review:
- [ ] Take it to [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to get clarification on.
- [ ] Prefix the conversation with `[HOOK REFACTOR]` so that we can find it easily.
- [ ] Link the result of the conversation in this section of the Design Doc titled “[Best Practices Conversations](https://docs.google.com/document/d/1yVqzirMLdLTaoB68IYUJ0vNArj80IaFs9-5CVUFht9o/edit#bookmark=id.lgs1kmu1vo8s)”
- [ ] Add it to the STYLE.md guide in this [open PR](https://github.com/Expensify/App/pull/16882) so we can reference it and apply any teachings in the next phase

**Comment by PauloGasparSv** [comment]
Working on these items first then getting back to this:

- https://github.com/Expensify/Expensify/issues/270487
- https://github.com/Expensify/Expensify/issues/267628
- https://github.com/Expensify/Expensify/issues/272945

**Comment by PauloGasparSv** [comment]
Planning on finishing this by EONW

**Comment by PauloGasparSv** [comment]
> Planning on finishing this by EONW
Was focused on some newsletter issues during the week so I'll try to start working on this tomorrow.

**Comment by MelvinBot** [comment]
Triggered auto assignment to @laurenreidexpensify (`External`), see https://stackoverflow.com/c/expensify/questions/8582 for more details.

**Comment by MelvinBot** [comment]
Triggered auto assignment to Contributor-plus team member for initial proposal review - @parasharrajat (`External`)

**Comment by MelvinBot** [comment]
Current assignee @PauloGasparSv is eligible for the External assigner, not assigning anyone new.

**Comment by PauloGasparSv** [comment]
@laurenreidexpensify @parasharrajat  I added the `External` label by mistake while clicking in the UI here, sorry for that!

Will un-assign you both from here, is there something else I should do (maybe delete the upwork job)?

**Comment by wahaha999** [comment]
## Proposal

I migrated the class component to functional component.

Here is the migrated snippet of the component.

```
import React, { useState, useEffect } from "react";
import { Pressable } from "react-native";
import PropTypes from "prop-types";
import Text from "./Text";
import * as Expensicons from "./Icon/Expensicons";
import Clipboard from "../libs/Clipboard";
import getButtonState from "../libs/getButtonState";
import Icon from "./Icon";
import Tooltip from "./Tooltip";
import styles from "../styles/styles";
import * as StyleUtils from "../styles/StyleUtils";
import variables from "../styles/variables";
import withLocalize, { withLocalizePropTypes } from "./withLocalize";

const propTypes = {
  /** The text to display and copy to the clipboard */
  text: PropTypes.string.isRequired,

  /** Styles to apply to the text */
  // eslint-disable-next-line react/forbid-prop-types
  textStyles: PropTypes.arrayOf(PropTypes.object),

  ...withLocalizePropTypes,
};

const defaultProps = {
  textStyles: [],
};

const CopyTextToClipboard = (props) => {
  const [showCheckmark, setShowCheckmark] = useState(false);
  const [showCheckmarkInterval, setShowCheckmarkInterval] = useState(null);

  useEffect(() => {
    return () => {
      clearInterval(showCheckmarkInterval);
    };
  }, [showCheckmarkInterval]);

  const copyToClipboard = () => {
    Clipboard.setString(props.text);
    setShowCheckmark(true);
    setShowCheckmarkInterval(
      setTimeout(() => {
        setShowCheckmark(false);
      }, 2000)
    );
  };

  return (
    <Text
      onPress={copyToClipboard}
      style={[styles.flexRow, styles.cursorPointer]}
      suppressHighlighting
    >
      <Text style={props.textStyles}>{`${props.text} `}</Text>
      <Tooltip
        text={props.translate(
          `reportActionContextMenu.${
            showCheckmark ? "copied" : "copyToClipboard"
          }`
        )}
      >
        <Pressable onPress={copyToClipboard}>
          {({ hovered, pressed }) => (
            <Icon
              src={showCheckmark ? Expensicons.Checkmark : Expensicons.Copy}
              fill={StyleUtils.getIconFillColor(
                getButtonState(hovered, pressed, showCheckmark)
              )}
              width={variables.iconSizeSmall}
              height={variables.iconSizeSmall}
              inline
            />
          )}
        </Pressable>
      </Tooltip>
    </Text>
  );
};

CopyTextToClipboard.propTypes = propTypes;
CopyTextToClipboard.defaultProps = defaultProps;

export default withLocalize(CopyTextToClipboard);

```

**Comment by PauloGasparSv** [comment]
Forgot to remove the `Help Wanted` label too.

Sorry @wahaha999 I added the `External` label by [mistake here](https://github.com/Expensify/App/issues/16132#issuecomment-1523761638)!

**Comment by wahaha999** [comment]
No problem @PauloGasparSv

**Comment by RamiTrojjet** [comment]
My proposal :
Define the CopyTextToClipboard component as a function component. This involves replacing the class keyword with the const keyword, and defining the component as a function that takes in the props object as an argument.

In the function component, use the useState hook to create a state variable for showCheckmark and a setter function for updating that state. Use the useEffect hook to clear the interval when the component unmounts.

Replace the constructor method in the class component with a regular function that defines the copyToClipboard function using the useState hook to update the showCheckmark state.

Replace the render method in the class component with a return statement in the function component that returns the JSX to be rendered.

Replace any instances of this.props with props, and remove any references to this.state.

Export the CopyTextToClipboard component using the export default statement at the bottom of the file.

**Comment by MelvinBot** [comment]
📣 @RamiTrojjet! 📣

Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork.
Please follow these steps:

1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.

![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)

Format:
```
Contributor details
Your Expensify account email: <REPLACE EMAIL HERE>
Upwork Profile Link: <REPLACE LINK HERE>
```

**Comment by RamiTrojjet** [comment]
Contributor details
Your Expensify account email: ramossetrojjet@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014c1fc870b1b7a216

**Comment by MelvinBot** [comment]
✅ Contributor details stored successfully. Thank you for contributing to Expensify!

**Comment by MelvinBot** [comment]
Triggered auto assignment to Contributor Plus for review of internal employee PR - @mollfpr (`Internal`)

**Comment by PauloGasparSv** [comment]
@RamiTrojjet not receiving proposals [here](https://github.com/Expensify/App/issues/16132#issuecomment-1523761638)! 

I'm going to hide all proposals added here and add the `internal` label so no one else sends one here because I'm not sure what to do.

**Comment by PauloGasparSv** [comment]
Thks so much @RamiTrojjet!

> @PauloGasparSv sure thing, just check with the Upwork automation, cause i was directed here from the Upwork post.

@laurenreidexpensify can you please help me with that?

**Comment by marcaaron** [comment]
What's the latest on this one @PauloGasparSv ? Should we get someone else working on it ?

**Comment by Nikhil-Vats** [comment]
> If you are unable to work on it please remove your assignment and add the External + Help Wanted labels as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119).
> Will do, same as https://github.com/Expensify/App/issues/16132#issuecomment-1574126826

@PauloGasparSv since you mentioned on the other issue that you will do same for this one. Can you add the labels? I will be happy to take this one! Thanks.

**Comment by PauloGasparSv** [comment]
> @PauloGasparSv since you mentioned on the other issue that you will do same for this one. Can you add the labels? I will be happy to take this one! Thanks.

Sure thing, just [checked this message from open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119) indicating we should do that : )

Also assigning you @Nikhil-Vats!

**Comment by nhminhduc** [comment]
Hi i can take this immediately

**Comment by Nikhil-Vats** [comment]
Hi, apologies. I just commented on two issues since they were not external at the time and I was not sure if any of them were going to be external. I agree we should assign this to someone else!

**Comment by chychkoi** [comment]
I'd like to work on this issue

**Comment by Vishrut19** [comment]
I would like to take this issue. Do I need to write a proposal?

**Comment by PauloGasparSv** [comment]
> @PauloGasparSv I think we should assign next volunteer as @Nikhil-Vats was already hired on https://github.com/Expensify/App/issues/16239

Ok, I'm re-assigning this to the next volunteer @nhminhduc and I checked for double-assignments this time!

Btw, [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119) is more info on the `Function Component Migration` issues (if proposals are required, how many to take and so on)

**Comment by nhminhduc** [comment]
@PauloGasparSv Hi, please check if upwork link still work? https://www.upwork.com/jobs/~014eb969b6eb24ef4c said the job no longer available for me. :(

**Comment by PauloGasparSv** [comment]
> @PauloGasparSv Hi, please check if upwork link still work? https://www.upwork.com/jobs/~014eb969b6eb24ef4c said the job no longer available for me. :(

@sophiepintoraetz can you help us with this?

**Comment by MahmudjonToraqulov** [comment]
I'd like to work on this issue

**Comment by nhminhduc** [comment]
PR here https://github.com/Expensify/App/pull/20107

**Comment by sophiepintoraetz** [comment]
Yes, I can! Can you please summarise the payments for me and who needs to be paid, @PauloGasparSv ?

**Comment by PauloGasparSv** [comment]
> Yes, I can! Can you please summarise the payments for me and who needs to be paid, @PauloGasparSv ?

Sure, it's still $250 and @nhminhduc is the one that should be compensated.

Just to be clear, the P.R. wasn't merged yet and we are asking that because the original Upworks Job https://www.upwork.com/freelance-jobs/apply/~014eb969b6eb24ef4c isn't available anymore for @nhminhduc to apply.

**Comment by sophiepintoraetz** [comment]
Job created - @nhminhduc - can you apply for the job here, please?
https://www.upwork.com/jobs/~01a1cc00a111b5b0f6

**Comment by nhminhduc** [comment]
@sophiepintoraetz Thank you. Applied.

**Comment by LovelyDev829** [comment]
Please try this.

import React from 'react';
import PropTypes from 'prop-types';
import * as Expensicons from './Icon/Expensicons';
import PressableWithDelayToggle from './PressableWithDelayToggle';
import Clipboard from '../libs/Clipboard';
import withLocalize, {withLocalizePropTypes} from './withLocalize';

const propTypes = {
    /** The text to display and copy to the clipboard */
    text: PropTypes.string.isRequired,

    /** Styles to apply to the text */
    // eslint-disable-next-line react/forbid-prop-types
    textStyles: PropTypes.arrayOf(PropTypes.object),

    ...withLocalizePropTypes,
};

const defaultProps = {
    textStyles: [],
};

function CopyTextToClipboard(props){

    function copyToClipboard() {
        Clipboard.setString(props.text);
    }
    return (
        <PressableWithDelayToggle
            text={props.text}
            tooltipText={props.translate('reportActionContextMenu.copyToClipboard')}
            tooltipTextChecked={props.translate('reportActionContextMenu.copied')}
            icon={Expensicons.Copy}
            textStyles={props.textStyles}
            onPress={copyToClipboard}
        />
    );
}

CopyTextToClipboard.propTypes = propTypes;
CopyTextToClipboard.defaultProps = defaultProps;

export default withLocalize(CopyTextToClipboard);

**Comment by LovelyDev829** [comment]
ok, thank you

**Comment by LovelyDev829** [comment]
Does it look okay now?

**Comment by sophiepintoraetz** [comment]
@PauloGasparSv - once payment is completed, is there anything else you'll need from me?

**Comment by LovelyDev829** [comment]
Hi, @sophiepintoraetz , could you please explain how to work here?

**Comment by sophiepintoraetz** [comment]
@LovelyDev829 you need to be hired for the job, which you haven't been in this [instance](https://github.com/Expensify/App/issues/16132#issuecomment-1578942891). Have you taken a look at our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)? that will help you to get started.

I see that the PR has merged so have released payment.

**Comment by mollfpr** [comment]
@LovelyDev829 This is already hired a contributor. You can check other open jobs with the label `Help Wanted`, but I suggest you to go through the CONTRIBUTING.md first to start smoothly.

**Comment by PauloGasparSv** [comment]
> @PauloGasparSv - once payment is completed, is there anything else you'll need from me?

I don't think so @sophiepintoraetz and thks for the help!
