### ISSUE TITLE
[HOLD for payment 2023-06-19] [$250] Migrate TermsStep.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16236]
### Filenames
- [ ] [src/pages/EnablePayments/TermsStep.js](https://github.com/Expensify/App/blob/main/src/pages/EnablePayments/TermsStep.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b9f201054b56264</li>
        <li>Upwork Job ID: 1664742132590931968</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
@robertjchen taking this issue off HOLD as per this [Slack post](https://expensify.slack.com/archives/C03TQ48KC/p1680708858739299)

**IMPORTANT:** If anything unexpected pops up during the refactor/review:
- [ ] Take it to [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to get clarification on.
- [ ] Prefix the conversation with `[HOOK REFACTOR]` so that we can find it easily.
- [ ] Link the result of the conversation in this section of the Design Doc titled “[Best Practices Conversations](https://docs.google.com/document/d/1yVqzirMLdLTaoB68IYUJ0vNArj80IaFs9-5CVUFht9o/edit#bookmark=id.lgs1kmu1vo8s)”
- [ ] Add it to the STYLE.md guide in this [open PR](https://github.com/Expensify/App/pull/16882) so we can reference it and apply any teachings in the next phase

**Comment by MelvinBot** [comment]
⚠️ Could not update price automatically because there is no linked Upwork Job ID. The BZ team member will need to update the price manually in Upwork.

**Comment by Nikhil-Vats** [comment]
@marcaaron no one is assigned to this issue. 
Will someone internal be assigned or if this is open for external (since no one is assigned), can I take this up?
Apologies if this is against the guidelines, I asked because no one was assigned which was unusual.

**Comment by chychkoi** [comment]
I'd like to work on this issue

**Comment by multijump** [comment]
I would like to take it

**Comment by MahmudjonToraqulov** [comment]
I would like to take this

**Comment by Santhosh-Sellavel** [comment]
@robertjchen we have volunteers already let's go with the first one

**Comment by petromoldovan** [comment]
### **Proposal**
**Please re-state the problem that we are trying to solve in this issue.**
Refactor the class React component [src/pages/EnablePayments/TermsStep.js](https://github.com/Expensify/App/blob/main/src/pages/EnablePayments/TermsStep.js) into functional component.
<img width="1414" alt="Screenshot 2023-06-03 at 22 18 33" src="https://github.com/Expensify/App/assets/15109844/f05efc71-fc7d-4624-a48b-874450c52d58">

**What is the root cause of that problem?**
Component was initially implemented as class component and must be refactored into functional component.

**What changes do you think we should make in order to solve the problem?**
Refactor component according to the provided guidelines https://react.dev/reference/react/Component#alternatives
Otherwise, major changes are: 
1. getting rid of `constructor` method 
2. replacing state handling with the `useState` hook.

**What alternative solutions did you explore? (Optional)**
N/A

**Comment by petromoldovan** [comment]
Contributor details
Your Expensify account email: petro.moldovan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0151f53b5b6c8fed0a

**Comment by phuchoang23** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Refactor this file [src/pages/EnablePayments/TermsStep.js](https://github.com/Expensify/App/blob/main/src/pages/EnablePayments/TermsStep.js) to a function component

### What is the root cause of that problem?
Cause that file was already written by class component so we have to convert to function component follow the provided guidelines and more things below

**More details:**

- Use useState hook to initial states in `constructor` method
- Should create arrow function for some function that need to bind `this`
- I see we have callback function after state changed so we have to use `useEffect` and `dependence` to handle it when convert from class component to function component

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/0813e2ca1476635a8324cbd9f998424663a33128/src/pages/EnablePayments/TermsStep.js#L32-L42
In `constructor` method:
- Will use useState hook to initial states that are `hasAcceptedDisclosure`, `hasAcceptedPrivacyPolicyAndWalletAgreement` and `error`. 
- Will use arrow function to create functions that are `toggleDisclosure`and `togglePrivacyPolicy` because by default arrow functions bind this to the value in their surrounding scope.

https://github.com/Expensify/App/blob/0813e2ca1476635a8324cbd9f998424663a33128/src/pages/EnablePayments/TermsStep.js#L52-L57
In `toggleDisclosure` function, I see we will call `clearError` function after `hasAcceptedDisclosure` state changed so we will use useEffect with `hasAcceptedDisclosure` dependence because it will listener whenever `hasAcceptedDisclosure` state change, will trigger call `clearError` function. Additional, same with `togglePrivacyPolicy` function.

**Comment by robertjchen** [comment]
Thanks for all the participation and thanks for all the proposals!

Per our guidelines, I think we would want to choose the one with a proposal at the moment, and I think @phuchoang23 's looks the most comprehensive so far. What do you think @Santhosh-Sellavel ? 🙏

**Comment by Santhosh-Sellavel** [comment]
Cool then @robertjchen!

**Comment by chychkoi** [comment]
@robertjchen @Santhosh-Sellavel  was the rule to assign it to someone applied first?
I also have code ready but did not make proposal as Marc mentioned no need to submit proposal for migration tasks.
https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119

**Comment by chychkoi** [comment]
Thanks @robertjchen @Santhosh-Sellavel 
I will try to finish this asap and let you know when PR is ready.

**Comment by chychkoi** [comment]
@robertjchen @Santhosh-Sellavel 
Submitted PR, please check and let me know if any changes are required.

**Comment by chychkoi** [comment]
@Santhosh-Sellavel PR updated please check

**Comment by tjferriss** [comment]
@chychkoi and @Santhosh-Sellavel have both been hired in Upworks. It looks like the PR was deployed to staging this morning.

**Comment by robertjchen** [comment]
Are we waiting on payment for this one before we can close this out?

**Comment by chychkoi** [comment]
@robertjchen I am still waiting for payment

**Comment by robertjchen** [comment]
cc: @tjferriss

**Comment by tjferriss** [comment]
@chychkoi and @Santhosh-Sellavel have both been paid via Upworks.
