### ISSUE TITLE
[HOLD for payment 2023-06-21] [$250] Migrate ReportTypingIndicator.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16269]
### Filenames
- [ ] [src/pages/home/report/ReportTypingIndicator.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportTypingIndicator.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017bb70fdccbb440b5</li>
        <li>Upwork Job ID: 1664734515678191616</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
@danieldoglas taking this issue off HOLD as per this [Slack post](https://expensify.slack.com/archives/C03TQ48KC/p1680708858739299)

**IMPORTANT:** If anything unexpected pops up during the refactor/review:
- [ ] Take it to [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to get clarification on.
- [ ] Prefix the conversation with `[HOOK REFACTOR]` so that we can find it easily.
- [ ] Link the result of the conversation in this section of the Design Doc titled “[Best Practices Conversations](https://docs.google.com/document/d/1yVqzirMLdLTaoB68IYUJ0vNArj80IaFs9-5CVUFht9o/edit#bookmark=id.lgs1kmu1vo8s)”
- [ ] Add it to the STYLE.md guide in this [open PR](https://github.com/Expensify/App/pull/16882) so we can reference it and apply any teachings in the next phase

**Comment by MelvinBot** [comment]
⚠️ Could not update price automatically because there is no linked Upwork Job ID. The BZ team member will need to update the price manually in Upwork.

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by danieldoglas** [comment]
I'll actually unassign this one from me and leave it open for when we reach external people.

**Comment by Nikhil-Vats** [comment]
@danieldoglas since the HOLD is removed and you mentioned you are leaving it open for external. Can you add the external and help wanted label? I am happy to take this up. Thanks.

**Comment by jayeshmangwani** [comment]
I would like to take this

**Comment by chychkoi** [comment]
I'd like to work on this issue

**Comment by Vishrut19** [comment]
I would like to work on it.

**Comment by jaybarnes33** [comment]
Title: Migrate ReportTypingIndicator.js to function component
 
Problem: ReportTypingIndicator.js was written as a class component and hence not in accordance with latest react conventions.

Suggested Solution: Rewrite ReportTypingIndicator.js as a functional component so that we are up to date with latest react conventions and also to be able to use hooks.

**Comment by MahmudjonToraqulov** [comment]
I would like to take this

**Comment by kushu7** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate ReportTypingIndicator.js to function component
### What is the root cause of that problem?
Nothing. we are converting class component into functional component.
### What changes do you think we should make in order to solve the problem?

We can convert this to:
```js
// will keep props as it is.
const ReportTypingIndicator = ({ userTypingStatuses, network, translate, ...rest }) => {
    const [usersTyping, setUsersTyping] = useState([]);

    useEffect(() => {
        const usersTyping = _.filter(_.keys(userTypingStatuses), login => userTypingStatuses[login]);
        setUsersTyping(usersTyping);
    }, [userTypingStatuses]);

    const numUsersTyping = usersTyping.length;

    if (network.isOffline) {
        return null;
    }

    switch (numUsersTyping) {
        case 0:
            return null;

        case 1:
            return (
                <TextWithEllipsis
                    leadingText={PersonalDetails.getDisplayName(usersTyping[0])}
                    trailingText={` ${translate('reportTypingIndicator.isTyping')}`}
                    textStyle={[styles.chatItemComposeSecondaryRowSubText]}
                    wrapperStyle={[styles.chatItemComposeSecondaryRow, styles.flex1]}
                    leadingTextParentStyle={styles.chatItemComposeSecondaryRowOffset}
                />
            );

        default:
            return (
                <Text
                    style={[styles.chatItemComposeSecondaryRowSubText, styles.chatItemComposeSecondaryRowOffset]}
                    numberOfLines={1}
                >
                    {translate('reportTypingIndicator.multipleUsers')}
                    {` ${translate('reportTypingIndicator.areTyping')}`}
                </Text>
            );
    }
};
```
### What alternative solutions did you explore? (Optional)
None

**Comment by achmadk** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
Migrate the `ReportTypingIndicator.js` file which was previously written with React class component to the function component

## What is the root cause of that problem?
According to [this comments](https://github.com/Expensify/App/issues/16615#issue-1644102665)
>  React class components are being deprecated and our code has various complex higher-order components, complex classes with many single-use methods, and render props patterns that are pretty confusing. Additionally, many modern React developers are no longer using these patterns nor are they typically being promoted or taught to new developers which presents a barrier to entry for our codebase. We have a New Expensify, but an Old React.

## What changes should we make to solve the problem?
Refactor into function component but keep in line with [contributor guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md).
1. Redeclare state `usersTyping` inside `ReportTypingIndicator` component which was previously written inside the component's constructor into variable one using `useState`.
2. Add effect with `useEffect` when `userTypingStatuses` props are changed, in order to recalculate `usersTyping` 
3. `ReportTypingIndicator` component should return the element which was previously defined inside `render` method with some adjustments. 

## What alternative solutions did you explore?
Reuse function to get `usersTyping`, because the existing declared function inside the constructor ([line 33](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportTypingIndicator.js#L33)) and `componentDidUpdate` lifecycle ([line 43](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportTypingIndicator.js#L43)) was different. It may be an unexpected error if `usersTyping` value is `undefined` instead of the empty array.

**Comment by achmadk** [comment]
Contributor details
Your Expensify account email: achmad.kurnianto@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f7ee376ef5018bba

**Comment by hayata-suenaga** [comment]
@eVoloshchak I think the first one who posts a comment is picked for migration issues

**Comment by eVoloshchak** [comment]
@hayata-suenaga, agree, for the issues where the investigation isn't needed and the scope of work is clearly defined - whoever posts the comment first is assigned to the issue seems like the logical approach, so let's proceed with @jayeshmangwani's [proposal](https://github.com/Expensify/App/issues/16269#issuecomment-1574294191)

**Comment by achmadk** [comment]
Thanks for the wise consideration, @eVoloshchak @hayata-suenaga. Maybe I can contribute to the Expensify app in another issue.

@jayeshmangwani, please do your best!

**Comment by jayeshmangwani** [comment]
[PR](https://github.com/Expensify/App/pull/20339) is ready for review
cc: @hayata-suenaga @eVoloshchak

**Comment by eVoloshchak** [comment]
Not overdue, this was deployed to staging 2 days ago

**Comment by miljakljajic** [comment]
Just to confirm - will @eVoloshchak and @jayeshmangwani be owed 250 USD each for this issue? I will send out the offers today so we're ready to pay on the 21st.

**Comment by hayata-suenaga** [comment]
@miljakljajic I found a [slack comment by Marc ](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119)on contributor compensation being $250

**Comment by miljakljajic** [comment]
Paid, contracts ended.
