### ISSUE TITLE
Migrate ReportActionItem.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16264]
### Filenames
- [x] [src/pages/home/report/ReportActionItem.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidUpdate`,`shouldComponentUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by jasperhuangg** [comment]
@marcaaron Does this still need to be on HOLD?

**Comment by marcaaron** [comment]
We've already started so I think this can come off HOLD. But maybe we can wait for some more "official" word before continuing with the others.

The official word is just me posting an update somewhere soon saying that we should start looking into them 😄

**Comment by marcaaron** [comment]
@jasperhuangg taking this issue off HOLD as per this [Slack post](https://expensify.slack.com/archives/C03TQ48KC/p1680708858739299)

**IMPORTANT:** If anything unexpected pops up during the refactor/review:
- [ ] Take it to [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to get clarification on.
- [ ] Prefix the conversation with `[HOOK REFACTOR]` so that we can find it easily.
- [ ] Link the result of the conversation in this section of the Design Doc titled “[Best Practices Conversations](https://docs.google.com/document/d/1yVqzirMLdLTaoB68IYUJ0vNArj80IaFs9-5CVUFht9o/edit#bookmark=id.lgs1kmu1vo8s)”
- [ ] Add it to the STYLE.md guide in this [open PR](https://github.com/Expensify/App/pull/16882) so we can reference it and apply any teachings in the next phase

**Comment by jasperhuangg** [comment]
We're still under review here

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by MelvinBot** [comment]
@jasperhuangg Eep! 4 days overdue now. Issues have feelings too...

**Comment by MelvinBot** [comment]
@jasperhuangg Still overdue 6 days?! Let's take care of this!

**Comment by MelvinBot** [comment]
@jasperhuangg Now this issue is 8 days overdue. Are you sure this should be a Daily? Feel free to change it!

**Comment by MelvinBot** [comment]
@jasperhuangg 12 days overdue now... This issue's end is nigh!

**Comment by MelvinBot** [comment]
This issue has not been updated in over ***14*** days. @jasperhuangg eroding to ***Weekly*** issue.
