### ISSUE TITLE
Migrate IOUModal.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16276]
### Filenames
- [ ] [src/pages/iou/IOUModal.js](https://github.com/Expensify/App/blob/main/src/pages/iou/IOUModal.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by thienlnam** [comment]
Talked to Jules 1:1, grabbing this since it's part of manual requests to refactor into MoneyRequestModal
https://docs.google.com/document/d/17jFcMsAotXvsMhXivoF3u7fyzeyXkKpRGXR88Ud0oWY/edit#bookmark=kix.6loq89desjse

**Comment by marcaaron** [comment]
Gonna remove the HOLD on this one since at this point we're mostly done. I would maybe have suggested we focus on this post-Manual Requests, but that's my bad for not making the migration priority more clear.

**Comment by thienlnam** [comment]
This is done! I have this other [issue](https://github.com/Expensify/App/issues/16942) for clean-up, but IOUModal aka MoneyRequestModal is now a functional component

**Comment by MelvinBot** [comment]
`Reviewing` label has been removed, please complete the "BugZero Checklist".

**Comment by MelvinBot** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.2.95-0 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/16679


If no regressions arise, payment will be issued on 2023-04-13. :confetti_ball:

After the hold period is over and BZ checklist items are completed, please complete any of the applicable payments for this issue, and check them off once done.
- [ ] External issue reporter
- [ ] Contributor that fixed the issue
- [ ] Contributor+ that helped on the issue and/or PR

As a reminder, here are the bonuses/penalties that should be applied for any External issue:
- Merged PR within 3 business days of assignment - 50% **bonus**
- Merged PR more than 9 business days after assignment - 50% **penalty**
