### ISSUE TITLE
[$250] Migrate IOUDetailsModal.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16275]
### Filenames
- [ ] [src/pages/iou/IOUDetailsModal.js](https://github.com/Expensify/App/blob/main/src/pages/iou/IOUDetailsModal.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
@Julesssss taking this issue off HOLD as per this [Slack post](https://expensify.slack.com/archives/C03TQ48KC/p1680708858739299)

**IMPORTANT:** If anything unexpected pops up during the refactor/review:
- [ ] Take it to [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to get clarification on.
- [ ] Prefix the conversation with `[HOOK REFACTOR]` so that we can find it easily.
- [ ] Link the result of the conversation in this section of the Design Doc titled “[Best Practices Conversations](https://docs.google.com/document/d/1yVqzirMLdLTaoB68IYUJ0vNArj80IaFs9-5CVUFht9o/edit#bookmark=id.lgs1kmu1vo8s)”
- [ ] Add it to the STYLE.md guide in this [open PR](https://github.com/Expensify/App/pull/16882) so we can reference it and apply any teachings in the next phase

**Comment by Julesssss** [comment]
I might hand this off soon as I'm super busy with Manual Requests. But I would still like the chance to complete one migration.

**Comment by Julesssss** [comment]
Not able to prioritise yet.

**Comment by Julesssss** [comment]
Saving for a quiet day

**Comment by marcaaron** [comment]
Heads up, I'm going around and making all currently assigned issues `Daily`. If you are unable to work on it please remove your assignment and add the `External` + `Help Wanted` labels as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119).

**Comment by priyeshshah11** [comment]
@Julesssss can I volunteer for this?
