### ISSUE TITLE
[$250] Migrate AddSecondaryLoginPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16289]
### Filenames
- [ ] [src/pages/settings/Profile/Contacts/AddSecondaryLoginPage.js](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/AddSecondaryLoginPage.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df6105d7153d75ff</li>
        <li>Upwork Job ID: 1665743162300596224</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
@johnmlee101 taking this issue off HOLD as per this [Slack post](https://expensify.slack.com/archives/C03TQ48KC/p1680708858739299)

**IMPORTANT:** If anything unexpected pops up during the refactor/review:
- [ ] Take it to [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to get clarification on.
- [ ] Prefix the conversation with `[HOOK REFACTOR]` so that we can find it easily.
- [ ] Link the result of the conversation in this section of the Design Doc titled “[Best Practices Conversations](https://docs.google.com/document/d/1yVqzirMLdLTaoB68IYUJ0vNArj80IaFs9-5CVUFht9o/edit#bookmark=id.lgs1kmu1vo8s)”
- [ ] Add it to the STYLE.md guide in this [open PR](https://github.com/Expensify/App/pull/16882) so we can reference it and apply any teachings in the next phase

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by johnmlee101** [comment]
No update. If I can't get to this soon I'll toss back into pool

**Comment by johnmlee101** [comment]
I'll give this another week, if not will do ^

**Comment by marcaaron** [comment]
Heads up, I'm going around and making all currently assigned issues `Daily`. If you are unable to work on it please remove your assignment and add the `External` + `Help Wanted` labels as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119).

**Comment by multijump** [comment]
I can work on this issue

**Comment by Vishrut19** [comment]
I want to work

**Comment by HunainAnis** [comment]
I can work on this!

**Comment by kushu7** [comment]
Ithis page is removed i guess

**Comment by HunainAnis** [comment]
Contributor details
Your Expensify account email: hunainmuhammad@rocketmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0162bd8e4552e7fd43

**Comment by pecanoro** [comment]
I checked and yeah, this page does not exist anymore, so closing!

**Comment by ronak301** [comment]
I can work on this - 
Expensify Email - ronakkothari301@gmail.com
Upwork Profile - https://www.upwork.com/freelancers/~01fc00c5f6854a7ad1
