### ISSUE TITLE
[HOLD for payment 2023-06-30] [$250] Migrate PronounsPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16296]
### Filenames
- [ ] [src/pages/settings/Profile/PronounsPage.js](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/PronounsPage.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010517ed943d1f3420</li>
        <li>Upwork Job ID: 1665691072385675264</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
@mountiny taking this issue off HOLD as per this [Slack post](https://expensify.slack.com/archives/C03TQ48KC/p1680708858739299)

**IMPORTANT:** If anything unexpected pops up during the refactor/review:
- [ ] Take it to [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to get clarification on.
- [ ] Prefix the conversation with `[HOOK REFACTOR]` so that we can find it easily.
- [ ] Link the result of the conversation in this section of the Design Doc titled “[Best Practices Conversations](https://docs.google.com/document/d/1yVqzirMLdLTaoB68IYUJ0vNArj80IaFs9-5CVUFht9o/edit#bookmark=id.lgs1kmu1vo8s)”
- [ ] Add it to the STYLE.md guide in this [open PR](https://github.com/Expensify/App/pull/16882) so we can reference it and apply any teachings in the next phase

**Comment by mountiny** [comment]
Thanks, making this weekly as I am currrently working on Roadmap issue.

**Comment by MelvinBot** [comment]
⚠️ Could not update price automatically because there is no linked Upwork Job ID. The BZ team member will need to update the price manually in Upwork.

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by mountiny** [comment]
havent priritized this with manual requests and app deploy

**Comment by mountiny** [comment]
Shipped th manula requests, now I will work on those and hopefully get time for this one too

**Comment by mountiny** [comment]
low priority

**Comment by marcaaron** [comment]
@mountiny I can grab it from ya if you can't prioritize it. shouldn't take too long.

**Comment by mountiny** [comment]
@marcaaron go ahead, i will be out for the conference half of the next week too so wont get to this most likely.

Are there still some left tho for later? Would love to make some refactoring on my own to make sure i improve my hooks/ functional components skills

**Comment by mountiny** [comment]
I will try to look into this this week

**Comment by mountiny** [comment]
stil would love to do this

**Comment by priyeshshah11** [comment]
@mountiny can I volunteer for this?

**Comment by LukaRusadze** [comment]
Would love to work on this.

**Comment by LukaRusadze** [comment]
Contributor details
Your Expensify account email: rusadzeluka@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f14689d635da27eb

**Comment by mountiny** [comment]
@priyeshshah11 Do you have any other functional component issues assigned to you?

**Comment by Vishrut19** [comment]
I want to work on this issue

**Comment by kushu7** [comment]
Would love to take this.

**Comment by multijump** [comment]
I would like to take this

**Comment by priyeshshah11** [comment]
> @priyeshshah11 Do you have any other functional component issues assigned to you?

@mountiny No I don't

**Comment by mountiny** [comment]
Thanks everyone, be on a look out for other migration issues, assigning @priyeshshah11  as they were the first one to raise hands after the announcement

**Comment by Vishrut19** [comment]
Hey! Idk. How is it even fair when people who are on slack get an update regarding that issue they try to work on it but if there is no place where you get to know that the issue is created then how can someone comment or work for it?

**Comment by Vishrut19** [comment]
> @Vishrut19 Are you not in slack channel? You should definitely be there. Here you have contributing guidelines https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

I am there on the Slack channel. When I commented on this issue at that moment only I saw about this issue on slack as well.

**Comment by agalyan** [comment]
Contributor details
Your Expensify account email: arman.galyan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019cd393456c38df2c

**Comment by MahmudjonToraqulov** [comment]
I would like to work on this issue

**Comment by laurenreidexpensify** [comment]
Offers sent to @priyeshshah11 and @aimane-chnaif on Upwork

**Comment by laurenreidexpensify** [comment]
@lschurr I am OOO til 19 June, adding you in case this gets merged and deployed this week and is eligible for payment before I am back. Thanks

**Comment by LukaRusadze** [comment]
Still up for this if the task frees up

**Comment by Vishrut19** [comment]
I am also available since very long

**Comment by mountiny** [comment]
The issue has `Reviewing` label and there is open PR to solve it here https://github.com/Expensify/App/pull/20178, this is not available to work on.

**Comment by laurenreidexpensify** [comment]
Regressions not relevant here, everyone has been paid in Upwork, closing

**Comment by priyeshshah11** [comment]
Hi @laurenreidexpensify & @mountiny, I asked [this](https://github.com/Expensify/App/issues/20095#issuecomment-1618761460) question in #20095 & had a chat with Christina (the bug-zero member in that issue) & was told to ask that question here. 

So I am just asking that if there are two issues & someone fixes them both within one PR shouldn't they get paid for the one that has the higher compensation if not for both?

**Comment by Christinadobrzyn** [comment]
Oh sorry, maybe I shouldn't have reopened this GH just trying to bring attention to @priyeshshah11 comments ^. I can help with questions about https://github.com/Expensify/App/issues/20095 - @priyeshshah11 was not compensated in that GH because I only paid the reporter on the GH. 

I suggested @priyeshshah11 bring the compensation into this GH since this is where the fix happened.

**Comment by Christinadobrzyn** [comment]
I'll close the issue - sorry I don't think it needs to be open to discuss payment

**Comment by mountiny** [comment]
@priyeshshah11 sorry for this, it would be helpful to write it down here.
- what PR you have written
- which issues did it solve
- how much you got paid? 

That will help us quickly take a loook if we should add more compensation, thanks!

**Comment by priyeshshah11** [comment]
> @priyeshshah11 sorry for this, it would be helpful to write it down here.
> 
> * what PR you have written
> * which issues did it solve
> * how much you got paid?
> 
> That will help us quickly take a loook if we should add more compensation, thanks!

@mountiny yeah sure

- I created this PR https://github.com/Expensify/App/pull/20178
- It solved #16296 & fixed #20095
- I only got paid $250 for #16296

**Comment by mountiny** [comment]
Thanks reopened the other issue

**Comment by mountiny** [comment]
Yes, feel free to comment there
