### ISSUE TITLE
[HOLD for payment 2023-05-04] [$250] Migrate NewContactMethodPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16291]
### Filenames
- [ ] [src/pages/settings/Profile/Contacts/NewContactMethodPage.js](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/NewContactMethodPage.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by MelvinBot** [comment]
⚠️ Could not update price automatically because there is no linked Upwork Job ID. The BZ team member will need to update the price manually in Upwork.

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by bondydaa** [comment]
Sorry I have not gotten started on this like I thought I could, been getting slammed with other chores. Are we opening these up for external contribs now? I can unassign myself if that's the case.

**Comment by bondydaa** [comment]
actually let me give this a go today 🙏

**Comment by marcaaron** [comment]
No worries we haven't opened it up yet. Feel free to take your time.

**Comment by bondydaa** [comment]
oh hmm looks like that component was removed, I think it's now this form? https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/NewContactMethodPage.js

Looks like this was the PR https://github.com/Expensify/App/pull/15330/

**Comment by bondydaa** [comment]
got a PR up https://github.com/Expensify/App/pull/17472

**Comment by MelvinBot** [comment]
@bondydaa Huh... This is 4 days overdue. Who can take care of this?

**Comment by bondydaa** [comment]
oh PR is in review and discussion is happening there.

**Comment by MelvinBot** [comment]
`Reviewing` label has been removed, please complete the "BugZero Checklist".

**Comment by MelvinBot** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.3.6-0 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/17472


If no regressions arise, payment will be issued on 2023-05-04. :confetti_ball:

After the hold period is over and BZ checklist items are completed, please complete any of the applicable payments for this issue, and check them off once done.
- [ ] External issue reporter
- [ ] Contributor that fixed the issue
- [ ] Contributor+ that helped on the issue and/or PR

As a reminder, here are the bonuses/penalties that should be applied for any External issue:
- Merged PR within 3 business days of assignment - 50% **bonus**
- Merged PR more than 9 business days after assignment - 50% **penalty**

**Comment by bondydaa** [comment]
hmm this can be closed since it was internal and done

**Comment by eVoloshchak** [comment]
@bondydaa, I did a review of https://github.com/Expensify/App/pull/17472. If that's eligible for payment, could you please tag someone from the BZ team?

**Comment by bondydaa** [comment]
oh doh yes sorry! didn't mean to forget about you ❤️ .

**Comment by bondydaa** [comment]
@alexpensify can you pay @eVoloshchak as the c+ who reviewed and tested my PR for this ❤️

**Comment by alexpensify** [comment]
To confirm, it's typically 1k for payment for C+ involvement. Does that match your expectorations here @bondydaa?

**Comment by bondydaa** [comment]
Um ya sure, I think whatever is standard here works! 

I think the amount in the title is wrong b/c this got caught up in some weird automation flow.

**Comment by bondydaa** [comment]
Hmm okay sorry after discussing on slack (internal slack https://expensify.slack.com/archives/C01SKUP7QR0/p1683707759784279?thread_ts=1683662490.618769&cid=C01SKUP7QR0) it seems Al and I were wrong, these refactors are only going for $250 and the price in the title was right 😬

**Comment by alexpensify** [comment]
I've started the payment process to @eVoloshchak based on the amount that @bondydaa posted above.

**Comment by alexpensify** [comment]
Closing - the payment process is complete via Upwork.
