### ISSUE TITLE
[HOLD for payment 2023-05-09] [$250] Migrate LegalNamePage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16295]
### Filenames
- [ ] [src/pages/settings/Profile/PersonalDetails/LegalNamePage.js](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/PersonalDetails/LegalNamePage.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
@arosiclair taking this issue off HOLD as per this [Slack post](https://expensify.slack.com/archives/C03TQ48KC/p1680708858739299)

**IMPORTANT:** If anything unexpected pops up during the refactor/review:
- [ ] Take it to [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to get clarification on.
- [ ] Prefix the conversation with `[HOOK REFACTOR]` so that we can find it easily.
- [ ] Link the result of the conversation in this section of the Design Doc titled “[Best Practices Conversations](https://docs.google.com/document/d/1yVqzirMLdLTaoB68IYUJ0vNArj80IaFs9-5CVUFht9o/edit#bookmark=id.lgs1kmu1vo8s)”
- [ ] Add it to the STYLE.md guide in this [open PR](https://github.com/Expensify/App/pull/16882) so we can reference it and apply any teachings in the next phase

**Comment by MelvinBot** [comment]
`Reviewing` label has been removed, please complete the "BugZero Checklist".

**Comment by MelvinBot** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.3.8-8 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/17542


If no regressions arise, payment will be issued on 2023-05-09. :confetti_ball:

After the hold period is over and BZ checklist items are completed, please complete any of the applicable payments for this issue, and check them off once done.
- [ ] External issue reporter
- [ ] Contributor that fixed the issue
- [ ] Contributor+ that helped on the issue and/or PR

As a reminder, here are the bonuses/penalties that should be applied for any External issue:
- Merged PR within 3 business days of assignment - 50% **bonus**
- Merged PR more than 9 business days after assignment - 50% **penalty**

**Comment by arosiclair** [comment]
Hey @tjferriss you mind handling payment for @Santhosh-Sellavel? He did the C+ review

**Comment by tjferriss** [comment]
@Santhosh-Sellavel I just invited you to the Upworks job for payment: https://www.upwork.com/ab/applicants/1657128748660109312/job-details

**Comment by Santhosh-Sellavel** [comment]
Applied thanks @tjferriss!

**Comment by tjferriss** [comment]
Offer extended.

**Comment by Santhosh-Sellavel** [comment]
Thank you, Accepted!

**Comment by tjferriss** [comment]
The payment has been sent.
