### ISSUE TITLE
Migrate WorkspaceInitialPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16304]
### Filenames
- [ ] [src/pages/workspace/WorkspaceInitialPage.js](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceInitialPage.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
@marcaaron taking this issue off HOLD as per this [Slack post](https://expensify.slack.com/archives/C03TQ48KC/p1680708858739299)

**IMPORTANT:** If anything unexpected pops up during the refactor/review:
- [ ] Take it to [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to get clarification on.
- [ ] Prefix the conversation with `[HOOK REFACTOR]` so that we can find it easily.
- [ ] Link the result of the conversation in this section of the Design Doc titled “[Best Practices Conversations](https://docs.google.com/document/d/1yVqzirMLdLTaoB68IYUJ0vNArj80IaFs9-5CVUFht9o/edit#bookmark=id.lgs1kmu1vo8s)”
- [ ] Add it to the STYLE.md guide in this [open PR](https://github.com/Expensify/App/pull/16882) so we can reference it and apply any teachings in the next phase
