### ISSUE TITLE
[HOLD for payment 2023-05-22] [$250] Migrate WorkspaceSettingsPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16309]
### Filenames
- [ ] [src/pages/workspace/WorkspaceSettingsPage.js](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceSettingsPage.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
@dangrous taking this issue off HOLD as per this [Slack post](https://expensify.slack.com/archives/C03TQ48KC/p1680708858739299)

**IMPORTANT:** If anything unexpected pops up during the refactor/review:
- [ ] Take it to [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to get clarification on.
- [ ] Prefix the conversation with `[HOOK REFACTOR]` so that we can find it easily.
- [ ] Link the result of the conversation in this section of the Design Doc titled “[Best Practices Conversations](https://docs.google.com/document/d/1yVqzirMLdLTaoB68IYUJ0vNArj80IaFs9-5CVUFht9o/edit#bookmark=id.lgs1kmu1vo8s)”
- [ ] Add it to the STYLE.md guide in this [open PR](https://github.com/Expensify/App/pull/16882) so we can reference it and apply any teachings in the next phase

**Comment by MelvinBot** [comment]
⚠️ Could not update price automatically because there is no linked Upwork Job ID. The BZ team member will need to update the price manually in Upwork.

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by dangrous** [comment]
Getting to this soon! It's like #3 on my list every day but 1 and 2 keep taking longer than expected. Almost certainly by EOW.

**Comment by dangrous** [comment]
On staging, should be on prod soon

**Comment by dangrous** [comment]
Assigning BugZero to handle payment for @sobitneupane's review!

**Comment by conorpendergrast** [comment]
Contract sent to @sobitneupane for this Upwork job: https://www.upwork.com/jobs/~015a58761a7f15a7ed

Once that's accepted, I'll pay that

**Comment by conorpendergrast** [comment]
It's been accepted, and paid! 

@dangrous looks like we're all done. Anything else?

**Comment by dangrous** [comment]
I think we're good! Closing now - thank you!
