### ISSUE TITLE
[HOLD for payment 2023-04-07] Update Style Guide WRT React Hooks usage

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16325]
## Task

- Our style guide needs to be updated so that we can start using React hooks and deprecate class components. There are a lot of references to class components in general.
- We also need to include the eslint plugin related to React hooks so that it will warn us when they are used incorrectly ("rules of hooks") or with missing dependencies ("exhaustive deps").

**Comment by roryabraham** [comment]
No C+ payment on this one

**Comment by MelvinBot** [comment]
`Reviewing` label has been removed, please complete the "BugZero Checklist".

**Comment by MelvinBot** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.2.92-2 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/16323


If no regressions arise, payment will be issued on 2023-04-07. :confetti_ball:

After the hold period is over and BZ checklist items are completed, please complete any of the applicable payments for this issue, and check them off once done.
- [ ] External issue reporter
- [ ] Contributor that fixed the issue
- [ ] Contributor+ that helped on the issue and/or PR

As a reminder, here are the bonuses/penalties that should be applied for any External issue:
- Merged PR within 3 business days of assignment - 50% **bonus**
- Merged PR more than 9 business days after assignment - 50% **penalty**

**Comment by marcaaron** [comment]
There is no payment needed here.
