### ISSUE TITLE
[No BZ] Add custom status fields

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#16350]
Doc: https://docs.google.com/document/d/1uPS24aoRWE45piaTvr0XvrgV1lK3lSjieG3sD5ZPfQg/edit
Pre-Design: https://expensify.slack.com/archives/C01GTK53T8Q/p1680269725977389

## Proposal
Hackathon idea: Add custom status fields
https://expensify.slack.com/archives/C01GTK53T8Q/p1678998135567649
https://expensify.slack.com/archives/C01GTK53T8Q/p1679278498366469
https://github.com/Expensify/App/pull/16002

## Tasks

- [x] Post **Proposal (full Problem/Solution statement)** in `#expensify-open-source`
- [x] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [x] Paste Proposal in the space above with a link to the Slack thread
- [x] Email `strategy@expensify.com` and paste in the Proposal
- [x] Fill out the **High-level overview of the problem**, **Timeline**, and **Terminology** sections of the Design Doc
- [x] Email `strategy@expensify.com` (continue the same email chain as before) with the link to your Design Doc
- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [x] Fill out the **High-level of proposed solution** section
- [x] Email `stategy@expensify.com` again with links to the doc and pre-design conversation in Slack
- [x] Add the `DesignDocReview` label to get the **High-level of proposed solution** section reviewed
- [x] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.
- [x] Fill out the **Detailed implementation of the solution** and related sections.
- [x] Re-add the `DesignDocReview` label to this issue
- [x] Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary
- [ ] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [ ] Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase
- [ ] Implement the changes
- [ ] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

**Comment by hannojg** [comment]
👋

**Comment by shawnborton** [comment]
or maybe @stitesExpensify do you have any idea?

**Comment by shawnborton** [comment]
Ah that makes sense. Do you mind sharing them all again here for posterity?

**Comment by stitesExpensify** [comment]
Sure!
<img width="374" alt="2023-03-27_10-32-14" src="https://user-images.githubusercontent.com/42391420/228607478-f2bbc566-761a-4bc4-886e-e0c351ee87ae.png">
<img width="371" alt="2023-03-27_10-32-07" src="https://user-images.githubusercontent.com/42391420/228607489-417e3a2a-d414-484c-97d4-4670f44f29d5.png">
<img width="1727" alt="2023-03-27_10-31-32" src="https://user-images.githubusercontent.com/42391420/228607494-c6a938f2-99c5-4628-a85e-1499acf79517.png">
<img width="376" alt="2023-03-27_10-31-56" src="https://user-images.githubusercontent.com/42391420/228607500-c339b51c-0130-497a-aa8b-a5e4e671560b.png">
<img width="1728" alt="2023-03-27_10-31-39" src="https://user-images.githubusercontent.com/42391420/228607506-9cab47f6-47af-414b-9456-2fa08faf9348.png">
![2023-03-22_08-51-14 (1)](https://user-images.githubusercontent.com/42391420/228608093-0c6ed3f7-fde1-42fc-9482-f292348e2db2.gif)

**Comment by shawnborton** [comment]
Posted mockups here: https://expensify.slack.com/archives/C01GTK53T8Q/p1680269764343469

Figma file is here: https://www.figma.com/file/j2KDfzyrmctOOyQeUPCI5c/Custom-Status?node-id=17%3A6208&t=jc10LusHXCd617h1-1

**Comment by hannojg** [comment]
I have started with the design doc: https://docs.google.com/document/d/1uPS24aoRWE45piaTvr0XvrgV1lK3lSjieG3sD5ZPfQg/edit#heading=h.o0yl4fdxt7l

**Comment by stitesExpensify** [comment]
Filled out the data storage, economic considerations, and accounting implications and legal sections of the doc!

**Comment by MelvinBot** [comment]
:wave: Hello Generalist Track Team - you have been assigned to review this **High Level** Design Doc. Please, treat this as a priority. Review [this Stack Overflow](https://stackoverflow.com/c/expensify/questions/5838) for some tips on reviewing a design doc. Once you are done, simply press the `Add "Reviewed Doc" comment` button in the right hand side K2 pannel or follow [these](https://stackoverflow.com/c/expensify/questions/13713) instructions.

---
- `@arielgreen` (Expensifier / Graduate) - https://github.com/Expensify/App/issues/17609
- `@caitlinwhite1` (Expensifier / Graduate) - https://github.com/Expensify/App/issues/17610
- `@zsgreenwald` (Project Manager) - https://github.com/Expensify/App/issues/17611
- `@NickTooker` (Project Manager) - https://github.com/Expensify/App/issues/17612
- `@flaviadefaria` (Product Manager) - https://github.com/Expensify/App/issues/17613
- `@twisterdotcom` (Product Manager) - https://github.com/Expensify/App/issues/17614
- `@quinthar` (Generalist) - https://github.com/Expensify/App/issues/17615
- `@anmurali` (Generalist) - https://github.com/Expensify/App/issues/17616
- `@trentpetty` (Accounting Technical Team) - https://github.com/Expensify/App/issues/17617

**Comment by NickTooker** [comment]
I have read and reviewed this Design Doc!

**Comment by trentpetty** [comment]
I have read and reviewed this Design Doc!

**Comment by Julesssss** [comment]
I have read and reviewed this Design Doc!

**Comment by stitesExpensify** [comment]
HL was released and is in review

**Comment by twisterdotcom** [comment]
I have read and reviewed this Design Doc!

**Comment by iwiznia** [comment]
I have read and reviewed this Design Doc!

**Comment by JmillsExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by arielgreen** [comment]
I have read and reviewed this Design Doc!

**Comment by NikkiWines** [comment]
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment]
I have read and reviewed this Design Doc!

**Comment by laurenreidexpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by anmurali** [comment]
I have read and reviewed this Design Doc!

**Comment by quinthar** [comment]
I have read and reviewed this Design Doc!

**Comment by jliexpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by shawnborton** [comment]
Not overdue

**Comment by caitlinwhite1** [comment]
I have read and reviewed this Design Doc!

**Comment by hannojg** [comment]
I gave the design doc HL a final edit after the latest discussions on slack and feel like we are good to move now forward to the detailed section. 
What do you think @stitesExpensify

**Comment by trjExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by stitesExpensify** [comment]
HL of doc has been reviewed, and we are moving to the detailed section!

**Comment by shawnborton** [comment]
Not overdue

**Comment by stitesExpensify** [comment]
Christoph is going to be taking over for Hanno on this one. 

@chrispader How are we looking on doc progress?

**Comment by hannojg** [comment]
@stitesExpensify Chris and I will both work on it. I have it on my todo for today to finish the detailed section of the document 😊

**Comment by shawnborton** [comment]
What's the latest on this one?

**Comment by stitesExpensify** [comment]
We're finishing up the detailed design. Planning to release the doc today or tomorrow

**Comment by stitesExpensify** [comment]
Unfortunately, I have been auto-assigned a lot of issues/prs to fix and review recently so the doc has taken the back seat. I am going OOO 6/21-6/26 so the review of the doc will happen a week from today instead of today. The good news is that I will be around to answer any comments after releasing the doc for review instead of having them sit. Onwards and upwards!

**Comment by stitesExpensify** [comment]
Hello Hello! SNH and WAQ have delayed me a bit on this, but the detailed portion of the design doc is ready to go! https://docs.google.com/document/d/1uPS24aoRWE45piaTvr0XvrgV1lK3lSjieG3sD5ZPfQg/edit?pli=1#bookmark=id.dm0yu67h9vq8

**Comment by flaviadefaria** [comment]
I have read and reviewed this Design Doc!

**Comment by laurenreidexpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by quinthar** [comment]
I have read and reviewed this Design Doc!

**Comment by caitlinwhite1** [comment]
I have read and reviewed this Design Doc!

**Comment by shawnborton** [comment]
Not overdue, still some outstanding design doc reviews.

**Comment by AndrewGable** [comment]
I have read and reviewed this Design Doc!

**Comment by robertjchen** [comment]
I have read and reviewed this Design Doc!

**Comment by cead22** [comment]
I have read and reviewed this Design Doc!

**Comment by arielgreen** [comment]
I have read and reviewed this Design Doc!

**Comment by joaniew** [comment]
I have read and reviewed this Design Doc!

**Comment by coleaeason** [comment]
I have read and reviewed this Design Doc!

**Comment by stitesExpensify** [comment]
Update:
We have all of the necessary reviews and (almost) all comments have been resolved! 

I have created all necessary github issues, and a project view [here](https://github.com/orgs/Expensify/projects/59/views/1). Feel free to follow along there for progress, and I will be updating here weekly 😄

**Comment by JmillsExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by johnmlee101** [comment]
I have read and reviewed this Design Doc!

**Comment by hannojg** [comment]
@perunt will help with the implementation, can we assign him here as well?

(His priority is still with comment linking, but when being blocked he will help out 😊 )

**Comment by stitesExpensify** [comment]
Progress has started on the front end! We're getting close to the base functionality

**Comment by stitesExpensify** [comment]
First front end PR is merged! The rest of them can be worked on simultaneously so hopefully they will be coming out this week as well. FYI, this project is being hid behind a beta so that we can release it all at once instead of piecemeal. If you want to check it out just add yourself on beta-ify!

**Comment by stitesExpensify** [comment]
We should hold bugs until the end of the implementation. I will post in #expensify-bugs

**Comment by shawnborton** [comment]
Not overdue, I think we're still progressing through this. Anything to add @stitesExpensify ?

**Comment by perunt** [comment]
3 out of 5 PRs were merged. One is currently in review. The last one is also close to being finished. I'm having some struggles with the time picker UX implementation

**Comment by stitesExpensify** [comment]
Still making super solid progress! UX is coming along well thanks to some help from Shawn, and we should be able to release internally next week!

**Comment by JmillsExpensify** [comment]
Curious if this is still on track to release internally soon?

**Comment by stitesExpensify** [comment]
So right now everything is done except for scheduling when your status auto-clears. Taras and I have both been pulled onto more important projects so that feature is currently on pause. 

If we're fine not having auto-clear for now, then I can flip the switch and we can start using status internally today!

**Comment by stitesExpensify** [comment]
We're going to release this internally this week or next, depending on when a final PR gets merged and deployed

**Comment by shawnborton** [comment]
Feature is released, but we're working through some design improvements.

**Comment by shawnborton** [comment]
Where are we at with the follow up improvements to this one?

**Comment by stitesExpensify** [comment]
They're coming along well! They are being rolled into the same PR as auto-clearing https://github.com/Expensify/App/pull/24620

**Comment by stitesExpensify** [comment]
@perunt how are we doing here? :)

**Comment by perunt** [comment]
Sorry for the delay. I was on vacation from 12 to 20 October. I'll hop on this today

**Comment by stitesExpensify** [comment]
We're in the final stretch here!

**Comment by stitesExpensify** [comment]
Final PR is still in review. Additionally, we are considering just opening this up to everyone so that guides can start using status instead of having their status in their name which looks bad in emails

**Comment by stitesExpensify** [comment]
We also just added an additional C+ because the PR is huge and we want to make sure everything is working correctly

**Comment by shawnborton** [comment]
Looks like we're still waiting for @perunt to wrap this one up.

**Comment by perunt** [comment]
we're waiting for a second C+ member review
@allroundexperts

**Comment by shawnborton** [comment]
Getting close to wrapping this up

**Comment by shawnborton** [comment]
Just a couple of clean up items left and we're almost there.

**Comment by shawnborton** [comment]
I think we still have an outstanding clean up issue two, right?

**Comment by shawnborton** [comment]
What's the latest update here? I feel like we're almost done?

**Comment by stitesExpensify** [comment]
Yep almost done. There are 2 issues remaining:
1. We are not sending the `clearAfter` date in UTC which is causing things to clear at the incorrect times
2. The user who set the status is not seeing it cleared even though it did clear for everyone else

Once we've fixed those this project is all done!

**Comment by stitesExpensify** [comment]
Those final follow-up issues are still being worked on

**Comment by shawnborton** [comment]
Is this one good to close now?

**Comment by stitesExpensify** [comment]
Still have follow-ups. Specifically [this one](https://github.com/Expensify/App/issues/33128#issuecomment-1926960950) which should be in review today

**Comment by shawnborton** [comment]
What's the latest here? Are we all good to close this out now?

**Comment by shawnborton** [comment]
@stitesExpensify @thienlnam can we close this out?

**Comment by shawnborton** [comment]
Friendly bump again - can we close this?

**Comment by stitesExpensify** [comment]
We are (still) working through follow up issues. I'm going to move this to a monthly. I am pushing the contributors along the best that I can but as a tracking issue, this is not really useful since most of the functionality is out and works.

**Comment by shawnborton** [comment]
I'm back because Melvin is telling me this one is overdue. Where can I find a list of what remains for this one?

**Comment by stitesExpensify** [comment]
I think that we are actually done here now! I will do a wrap up email for the project, and then close this

**Comment by stitesExpensify** [comment]
I have been super head down on travel and didn't get around to sending the wrap up out. I will do it before the next melvin cycle.
