### ISSUE TITLE
Generate bug reports in the App

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#16365]
## Proposal
Hackathon idea: Generate bug reports via the App

We've decided to move forward with it 
https://expensify.slack.com/archives/C01GTK53T8Q/p1678998180957189

## Tasks
We decided we just need a small pre-design to determine which word triggers and animations this happens on

- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [ ] Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.
- [ ] Implement the changes

**Comment by jasperhuangg** [comment]
High level pre-design is happening [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1679419923909299)!

**Comment by jasperhuangg** [comment]
We've figured out most of what we need in the pre-design, but I'm holding off on moving forward with anything for the time being since I have some other higher priority projects that are happening.

**Comment by jasperhuangg** [comment]
Have other higher priority projects in the works, going to see if anyone is willing to take this off my hands

**Comment by hayata-suenaga** [comment]
Assigning myself. Asked if someone can help me craft the [high level design doc](https://expensify.slack.com/archives/C03TQ48KC/p1680800009090879).

**Comment by hayata-suenaga** [comment]
@stephanieelliott @strepanier03 I'm so sorry

Here is the link to the design doc: https://docs.google.com/document/d/1ljqdFi2FJcJRDASBQZK881frmAllvguiCb6V9Sky3wI/edit?usp=sharing

**Comment by strepanier03** [comment]
Got it, thanks so much @hayata-suenaga!

**Comment by strepanier03** [comment]
I have reviewed this design doc!

**Comment by hayata-suenaga** [comment]
still waiting for reviews

**Comment by srikarparsi** [comment]
I have read and reviewed this Design Doc!

**Comment by ryanschaffer** [comment]
I have read and reviewed this Design Doc!

**Comment by stephanieelliott** [comment]
I have read and reviewed this Design Doc!

**Comment by hayata-suenaga** [comment]
still waiting for design doc reviews.

**Comment by kortneywynn** [comment]
I have read and reviewed this Design Doc! Please ensure that this project is tracked for capitalized software during the development phase (phase 2-4).

**Comment by hayata-suenaga** [comment]
I haven't started the implementation. So this probably goes into June CAP if it qualifies

**Comment by hayata-suenaga** [comment]
I'll prepare to hand off this to contributors

**Comment by hayata-suenaga** [comment]
The guide's team will start reporting bugs: https://expensify.slack.com/archives/C036S0BVAHH/p1687988421861679

will work on this project so that potentially they can also utilize bug report functionality of NewDot

**Comment by hayata-suenaga** [comment]
Changing the priority of this issue to monthly as this is a non-blocker project that doesn't belong to any wave.

**Comment by hayata-suenaga** [comment]
I'll check back on this after Hybrid Web is done

**Comment by hayata-suenaga** [comment]
I gonna start handing off issues next week

**Comment by hayata-suenaga** [comment]
oops I didn't mean to close the issue

**Comment by hayata-suenaga** [comment]
I'll ask in wave 9 if we need this one or not. they might already planning similar feature

**Comment by hayata-suenaga** [comment]
actually asking [in the #product channel](https://expensify.slack.com/archives/C03U7DCU4/p1701284450263319)
