### ISSUE TITLE
Emoji Shower

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#16363]
## Proposal
Hackathon idea that was agreed to move forward with
https://expensify.slack.com/archives/C01GTK53T8Q/p1678998192629149

## Tasks
We decided we just need a small pre-design to determine which word triggers and animations this happens on

- [ ] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [ ] Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.
- [ ] Implement the changes

**Comment by luacmartins** [comment]
I'm gonna demote this to a weekly since I'm working on higher priority items this week.

**Comment by luacmartins** [comment]
I've been prioritizing manual requests. I'll try to get to this soon.

**Comment by luacmartins** [comment]
Coming back from ooo today. I'm prioritizing Manual Requests so probably won't be able to get to this until a couple of weeks from now.

**Comment by luacmartins** [comment]
No updates yet

**Comment by wojtus7** [comment]
Hi 👋 
I'm from SWM and can't wait to work on this one 🤗

**Comment by luacmartins** [comment]
Nice! Assigned you to the issue. The issue description already has some guidelines. Let me know if you have any questions!

**Comment by luacmartins** [comment]
SWM will work on this once @wojtus7 is back from ooo

**Comment by wojtus7** [comment]
Hi! I'm back from ooo and ready to start working on it!
Can you please provide me any links with docs/description of what should it look and behave like? 

Only thing I can see is the slack message https://expensify.slack.com/archives/C01GTK53T8Q/p1678998192629149 and it's only one sentence that it should "Generate a shower of emojis when certain messages are sent" 😎

**Comment by luacmartins** [comment]
Hi @wojtus7! Thanks for checking. The feature we are trying to implement is similar to the [full-screen effect that Apple has available in iMessages](https://support.apple.com/en-us/HT206894), but it's triggered by certain messages like `Happy birthday` or when users get paid.

**Comment by luacmartins** [comment]
We haven't decided which triggers we'll have or which emojis should show up yet, that's part of the pre-design and something you can suggest :)

**Comment by luacmartins** [comment]
Does that answer your question?

**Comment by wojtus7** [comment]
Yup, thank you @luacmartins 

That give me enough info to start working on it for real ❤️

**Comment by wojtus7** [comment]
Hi I created something like this in first iteration:
What do you think? We need to go more into swirl motion, make it longer/shorter, or just try to make improvements to make it just more smooth etc?

(Emojis that are shown are just passed as string prop into component so they are fully customisable and can be text as well)

https://github.com/Expensify/App/assets/42337257/d6d36ced-fc8c-4bff-8990-261a4bdd8c05

**Comment by luacmartins** [comment]
Nice! What is triggering the emoji shower right now?

**Comment by thienlnam** [comment]
> Hi I created something like this in first iteration:
What do you think? We need to go more into swirl motion, make it longer/shorter, or just try to make improvements to make it just more smooth etc?

You can also post in #expensify-open-source to get some opinions here - Not sure if I love the swirl motion but just IMO

**Comment by luacmartins** [comment]
@wojtus7 you can also see what we had for the hackathon [here](https://youtu.be/UrEUJLwhwWM?t=994)

**Comment by wojtus7** [comment]
> Nice! What is triggering the emoji shower right now?

Just a ref function call `play()` 
And just for now I just have interval that play it every 10 seconds

**Comment by luacmartins** [comment]
@wojtus7 I think we should follow @thienlnam's [suggestion](https://github.com/Expensify/App/issues/16363#issuecomment-1551770969) and post this in #expensify-open-source to get more opinions on how this should look like

**Comment by thienlnam** [comment]
@wojtus7 Actually already posted about it here https://expensify.slack.com/archives/C01GTK53T8Q/p1684348678194399

We're currently waiting on input from @shawnborton to see how we should proceed with this - I believe we'd want to use brand elements in this

**Comment by luacmartins** [comment]
Ah nice! I completely missed that post Thanks for the link!

**Comment by shawnborton** [comment]
My vote is to close this one out, I don't think we should proceed with an emoji only approach and we should use branded assets instead. 

It would be nice to put this through the P/S framework to understand exactly what problem it is that we're solving. But my vote is to just pause on this one entirely and move on to other priorities.

**Comment by luacmartins** [comment]
I agree that we have other priorities at the moment. I'm ok with closing this for now and revisiting it in the future if we think this is something worth pursuing.

**Comment by luacmartins** [comment]
Gonna close this one as per the previous two comments! Thanks for making yourself available for this one @wojtus7!
