### ISSUE TITLE
Gyroscope-driven animations of empty chats

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#16366]
## Proposal
Hackathon idea: Gyroscope-driven animations of empty chats

We've decided to move forward with this project
https://expensify.slack.com/archives/C01GTK53T8Q/p1678998169743399

## Tasks
- [ ] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [ ] Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.
- [ ] Implement the changes

**Comment by roryabraham** [comment]
Thanks for creating an issue @thienlnam. Going to make this a weekly though

**Comment by roryabraham** [comment]
No update this week – waiting on some bug fixes in Reanimated.

**Comment by roryabraham** [comment]
Got some feedback from SWM team on this PR, should be able to pick it back up now.

**Comment by roryabraham** [comment]
Tried working on this again today, found that the sensor has a very different orientation on Android v.s: Android Chrome (which provided sensor data out of the box w/o requiring additional permissions)

**Comment by roryabraham** [comment]
Waiting for an update from the Reanimated team in the PR

**Comment by roryabraham** [comment]
No update

**Comment by roryabraham** [comment]
No update since https://github.com/Expensify/App/pull/16004#issuecomment-1560654324 – Gyro sensor orientations are not consistent across native platforms + mobile web browsers.

**Comment by roryabraham** [comment]
Trying to pass this off due to what I think are some bugs / inconsistencies in Reanimated: https://expensify.slack.com/archives/C04878MDF34/p1688081161205169

**Comment by tomekzaw** [comment]
> I think are some bugs / inconsistencies in Reanimated

I can confirm that the behavior of `useAnimatedSensor` hook wasn't consistent across platforms in Reanimated 3.1.0. The root cause of the issue was that Android and iOS use different coordinate systems for sensors. Since then, @mstach60161 submitted the following PRs that unify the measurements:

* https://github.com/software-mansion/react-native-reanimated/pull/4368 (already released in 3.2.0)
* https://github.com/software-mansion/react-native-reanimated/pull/4499 (will be released in 3.4.0)
* https://github.com/software-mansion/react-native-reanimated/pull/4573 (will be released in 3.4.0)

@wojtus7 from SWM would be interested in finishing the PR #16004. The PR would be ready to merge once the app upgrades to Reanimated 3.4.0.

**Comment by roryabraham** [comment]
@wojtus7 Feel free to comment on this so that I can assign it to you 🙂

**Comment by wojtus7** [comment]
Hi @roryabraham I'm happy to take a look at this issue 👀

**Comment by mountiny** [comment]
Assigning @wojtus7 to work on this!

**Comment by wojtus7** [comment]
Hi!

I have working code on my branch where I checked sttuff with latest @nightly version of reanimated, but since we need 3.4.0 version to be officially released (and inside the Expensify App)  to make this work , I don't think creating new draft for it right now that will need to be maintained and anybody who will check it will need to `yarn` and `pod install` potentially broken version of reanimated just to test it, is the best idea?

I think creating PR just as 3.4.0 is released (probably something around <2 weeks) is best approach. WDYT? @roryabraham @mountiny

**Comment by mountiny** [comment]
Yep sounds like a good way forwards!

**Comment by roryabraham** [comment]
Still HOLDing

**Comment by wojtus7** [comment]
Hi!
Reanimated 3.4.0 just dropped and I installed it to test if everything still works.
Do you want me to create PR that bump 3.1.0 -> 3.4.0 after I verify everything's alright? @roryabraham @mountiny

**Comment by mountiny** [comment]
@wojtus7 you need to link the issues correctly in the PR body so correct engineer is assigned

Yeah I think we can get this tested well and merge this

**Comment by roryabraham** [comment]
Reanimation upgrade merged. Thanks for the quick review @mollfpr

**Comment by roryabraham** [comment]
Reanimated version bump was reverted due to a [deploy blocker on staging](https://github.com/Expensify/App/issues/23716). So we'll need to redo that version bump before we can pick up the fun gyroscope stuff again

**Comment by mollfpr** [comment]
I have similar issue while testing on the categories emoji picker, but I'm sure it also appear on the latest `main` 🤔

https://github.com/Expensify/App/pull/23550#issuecomment-1650100975

**Comment by wojtus7** [comment]
Ough :( 
I checked the 3.4.1 but it's broken as well :( 

I guess I will keep and eye on this and try to bump reanimated again as soon as some version fix those issues 🫡

**Comment by wojtus7** [comment]
Hi, I merged new main with 3.4.0 into the PR https://github.com/Expensify/App/pull/23737 and created patch for reanimated to fix the tests, but I don't know how to run it with the `--reset-cache` to apply the patch. 😞

Or it always reset cache and there is still problem but I only resolved it locally?

**Comment by roryabraham** [comment]
We're now awaiting the release of Reanimated 3.5.0. Depending on when that comes, this would also be subject to the feature freeze for all the early-September conferences.

**Comment by mollfpr** [comment]
@roryabraham Could you help adding BZ here and confirm if we need a checklist? Thanks!

**Comment by roryabraham** [comment]
@JmillsExpensify tagging you in for payment. BZ checklist is not needed since this was a new feature, not a bug

**Comment by mollfpr** [comment]
@JmillsExpensify Should this issue price at a 1000? Since this issue was created before the price change.

**Comment by roryabraham** [comment]
@JmillsExpensify bump – this is ready for payment.

**Comment by JmillsExpensify** [comment]
Payment summary: $1,000 payment to @mollfpr for PR review.

**Comment by JmillsExpensify** [comment]
$1,000 payment approved via NewDot based on summary above.
