### ISSUE TITLE
[Tracking] Theme Switching + Light Mode

### ISSUE THREAD

**Issue by grgia** [Expensify/App#16569]
## Proposal

Let's implement theme switching and add support for both light and dark mode.

## Design Doc
https://docs.google.com/document/d/1KwVVu5-DLjmb-2-UwgIw5ElmyKn0ZXs8wUzxcNZjwDc/edit#heading=h.fj65mtzh5fx9

## Pre-designs
[HL Pre-design Link](https://expensify.slack.com/archives/C01GTK53T8Q/p1680169442517089)

## What's Next Post

[Slack Link](https://expensify.slack.com/archives/CC7NECV4L/p1678898651338189)

**Proposal:**
Let’s bring forth both light and dark mode!

**Problem:**
After implementing dark mode, it became clear that a single color mode doesn’t work for all. Some people love dark mode (myself included), while others want to bring back light mode. At the core of any problem, is friction that a person experiences. While this may be a case of user-preference, the truth is- for some people, dark mode causes this friction.

**Solution:**
Sometimes, a user wants what a user wants. So let’s give it to them! Let’s greenlight the theme switching project again and work with an external agency like margelo to make it a reality. This will pave the way for changing themes for certain use cases akin to copiloting/supportalling today! It could also help to ease the final switcheroo when we reunify expensify :tada:

## Tasks

- [x] Post **Proposal (full Problem/Solution statement)** in `#expensify-open-source`
- [x] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [x] Paste Proposal in the space above with a link to the Slack thread
- [x] Email `strategy@expensify.com` and paste in the Proposal
- [x] Fill out the **High-level overview of the problem**, **Timeline**, and **Terminology** sections of the Design Doc
- [x] Email `strategy@expensify.com` (continue the same email chain as before) with the link to your Design Doc
- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [x] Fill out the **High-level of proposed solution** section
- [x] Email `stategy@expensify.com` again with links to the doc and pre-design conversation in Slack
- [x] Add the `DesignDocReview` label to get the **High-level of proposed solution** section reviewed
- [x] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.
- [x] Fill out the **Detailed implementation of the solution** and related sections.
- [x] Re-add the `DesignDocReview` label to this issue
- [x] Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary
- [ ] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [ ] Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase
- [ ] Implement the changes
- [ ] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

## Related Issues
https://github.com/Expensify/App/issues/12260

**Comment by MelvinBot** [comment]
Triggered auto assignment to @joekaufmanexpensify (`NewFeature`), see https://stackoverflowteams.com/c/expensify/questions/14418#:~:text=BugZero%20process%20steps%20for%20feature%20requests for more details.

**Comment by grgia** [comment]
cc @chrispader, I'm working on filling this out but you should see the project proposal email thread

**Comment by chrispader** [comment]
Really looking forward to this! 🚀🥳

**Comment by grgia** [comment]
Pre-design Questions from yesterday:

Questions:

What themes will we have?
- Light, Dark

What will light theme look like?
- (Insert Mockups)
Should we allow the user to sync the theme with system settings?
- Yes
How will the user select their theme? Where will theme settings live?
- Lives in preferences, select through simple list pattern (Insert Mockup)
What will be the default setting? Should we enforce/embrance one of the two themes more? E.g. Initially start the app with dark, because it has way more green 
- Default to dark OR default to system
Should the colors be animated while changing the theme?
- Mainly seen if you have system setting set
Should there be multiple different themes? (Let the user decide between different color pallets)
- Not now
Should we allow custom themes?
-  Probably not, right?
Should we wait for the migration to functional components first?
- i hope not haha
Are illustrations affected by this change? E.g. are there differences in illustrations when switching to another theme?
- Some yes (background of chat, etc)

**Comment by grgia** [comment]
[Figma (WIP)](https://www.figma.com/file/vFv6hI7y1htQhSasrgP0ai/Theme-Switching-%2F-Light-Mode?node-id=1-12802&t=Bw5H86uZ64EGapFR-0#405699366)

**Comment by grgia** [comment]
cc @chrispader 

![image](https://user-images.githubusercontent.com/38015950/228570635-94d2d85b-615d-452b-90ad-ffc5ffef5f25.png)

![image](https://user-images.githubusercontent.com/38015950/228571545-c80a1a47-4c23-4f01-878c-40722e453c4e.png)

**Comment by grgia** [comment]
@shawnborton 
Where do you think we landed on the Landing Page? Should this page be green always? My thoughts here are that the user isn't yet logged in, so we cannot reference their settings. If we decided to make this page different themes, we would default to Auto-Sync with OS. Otherwise, I think I prefer the dark one if we choose one.

![image](https://user-images.githubusercontent.com/38015950/231133655-fa406af6-f32d-42f8-8a21-47574cfce639.png)

**Comment by shawnborton** [comment]
I'm thinking we should just stick with the dark version for the landing page personally, thoughts?

**Comment by grgia** [comment]
My thoughts exactly! Let's do that

**Comment by zanyrenney** [comment]
I have read and reviewed this Design Doc!

**Comment by tgolen** [comment]
I have read and reviewed this Design Doc!

**Comment by aldo-expensify** [comment]
I have read and reviewed this Design Doc!

**Comment by Gonals** [comment]
I have read and reviewed this Design Doc!

**Comment by stitesExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by stephanieelliott** [comment]
I have read and reviewed this Design Doc!

**Comment by Julesssss** [comment]
I have read and reviewed this Design Doc!

**Comment by conorpendergrast** [comment]
I have read and reviewed this Design Doc!

**Comment by puneetlath** [comment]
I have read and reviewed this Design Doc!

**Comment by arielgreen** [comment]
I have read and reviewed this Design Doc!

**Comment by HaleyJacobson** [comment]
I have read and reviewed this Design Doc!

**Comment by anmurali** [comment]
I have read and reviewed this Design Doc!

**Comment by JmillsExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by grgia** [comment]
Will update design doc detailed section with final pieces next working day

**Comment by trjExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by grgia** [comment]
Detailed section is ready!  cc @chrispader

**Comment by tgolen** [comment]
I have read and reviewed this Design Doc!

**Comment by Gonals** [comment]
I have read and reviewed this Design Doc!

**Comment by joekaufmanexpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by johnmlee101** [comment]
I have read and reviewed this Design Doc!

**Comment by stitesExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by joaniew** [comment]
I have read and reviewed this Design Doc!

**Comment by grgia** [comment]
@yuwenmemon @pecanoro @conorpendergrast @quinthar @danielrvidal bump on detailed doc reviews! Detailed section of the doc is fully updated. [Read and review here](https://docs.google.com/document/d/1KwVVu5-DLjmb-2-UwgIw5ElmyKn0ZXs8wUzxcNZjwDc/edit#)!

**Comment by yuwenmemon** [comment]
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment]
I have read and reviewed this Design Doc!

**Comment by puneetlath** [comment]
I have read and reviewed this Design Doc!

**Comment by JmillsExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by grgia** [comment]
@quinthar @danielrvidal @pecanoro @conorpendergrast one last bump on the detailed review -https://docs.google.com/document/d/1KwVVu5-DLjmb-2-UwgIw5ElmyKn0ZXs8wUzxcNZjwDc/edit#heading=h.w8v61l72hksr

**Comment by conorpendergrast** [comment]
I have read and reviewed this Design Doc!

**Comment by quinthar** [comment]
I have read and reviewed this Design Doc!

**Comment by flaviadefaria** [comment]
I have read and reviewed this Design Doc!

**Comment by pecanoro** [comment]
I have read and reviewed this Design Doc!

**Comment by grgia** [comment]
Implementation is in progress, phase 1 is completed, working on organizing for phase 2! Project view here - https://github.com/orgs/Expensify/projects/44

**Comment by chrispader** [comment]
@grgia i'm back from being out sick. Let's sync and continue with this :)

**Comment by grgia** [comment]
Looking into two methods for the migration, aiming to have it in motion before EOW.

**Comment by grgia** [comment]
in progress of beginning migration

**Comment by grgia** [comment]
In final implementation stage

**Comment by grgia** [comment]
Feature dropped! 

What's left:
- Final few theme bugs left to squash
- ESLint PR
- External Resources Updates
- Project Wrap Up

**Comment by roryabraham** [comment]
@grgia is there an issue somewhere for setting up theme switching in some of our android native views?

**Comment by grgia** [comment]
@roryabraham could you explain what you mean by that? We have an issue for native modals, is there a specific view you're looking for?

**Comment by roryabraham** [comment]
Yeah, let me try to clarify a bit. Unfortunately I'm not very experienced at Android native development so I'm going to try my best to explain without trying to get to deep in how it would actually be implemented – I would need to do more research to have a confident opinion on how it should actually be done.

---

Currently we have some Android native styles configured [here](https://github.com/Expensify/App/blob/914fe828aaf772739f02c8a8eff9f12428027b66/android/app/src/main/res/values/styles.xml#L4-L64). As you can see, these styles target various native views, including pickers, spinners, alerts, and the splash screen.

All of the native styles you see there reference static color resources, such as `@color/gray4`, `@color/accent`, `@color/white`, etc... (It does look like there might be a dynamic reference to `?android:colorBackground`?)

The end effect on the user is, for [example](https://github.com/Expensify/App/issues/33136#issuecomment-1858675810), that the picker is always styled for dark mode, regardless of the current app theme in Onyx. The root cause is that we have a custom android App theme, and that theme is always catered to dark mode.

So what I'm suggesting is that we actually need two Android native themes, one for light mode and another for dark mode. Then we need some code to read and set the native theme to match the theme in Onyx, which I guess would be simplest to accomplish with a small native module exposed to JS. I'm not sure if [Appearance.setColorScheme](https://reactnative.dev/docs/appearance#setcolorscheme) would be applicable for this use case or not.

**Comment by Julesssss** [comment]
I think you're pretty much correct @roryabraham. I'm not sure whether `setColorScheme` hooks into the correct native Android function, but if so we can solve this pretty easily by extending with a day/night theme. I also think the native `onConfigurationChange` function is already being called (as the Activity is recreated when changing themes) which saves us a step.

There is some more info on the native Android details [here](https://developer.android.com/develop/ui/views/theming/darktheme#:~:text=Use%20the%20system%20setting%20by,might%20not%20support%20this%20behavior.). But the solution will be to make the custom theme to extend from `Theme.AppCompat.DayNight.XYZ` and then provide an alternate version of the colours. I can help with this, but [here](https://stackoverflow.com/a/54103875/4160784) is a great example. 

Another point is that if we could drop the custom colours and stick with the default Android Modal styles (which I think was discussed), then we just need to extend from the day/night theme and wouldn't need the alternate style for dark/light mode.

**Comment by chrispader** [comment]
I'm gonna start doing some research on this and then create a PR :)

**Comment by situchan** [comment]
> @grgia is there an issue somewhere for setting up theme switching in some of our android native views?

We can use #33235

**Comment by grgia** [comment]
Planning to send a wrap-up for this issue. Most major bugs have been fixed and the remaining are external

**Comment by chrispader** [comment]
> I'm gonna start doing some research on this and then create a PR :)

@grgia @Julesssss @roryabraham i didn't yet get to fully investigate this and solve it, because i'm currently busy with other PRs...

if anyone wants to take this over or has some expertise in it, i am happy to give this task away. I'm going to be OOO after 30/01/2023, so i'll probably not get to finish it by then...

**Comment by grgia** [comment]
The main bugs now are the avatar bug that I had a draft PR up for before EOY and a few minor bugs that have come up and been fixed by contributors.

That said, I still plan to do a wrap up email for this project since it's mostly done! I've been busy with Wave 5/6 so haven't had a chance yet

**Comment by grgia** [comment]
Closing this out!
