### ISSUE TITLE
React Class Component Deprecation

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16615]
**Design Doc:**

https://docs.google.com/document/d/1yVqzirMLdLTaoB68IYUJ0vNArj80IaFs9-5CVUFht9o/edit

## Proposal

**Problem:** React class components are being deprecated and our code has various complex higher order components, complex classes with many single-use methods, and render props patterns that are fairly confusing. Additionally, many modern React developers are no longer using these patterns nor are they typically being promoted or taught to new developers which presents a barrier to entry for our codebase. Basically, we have a New Expensify, but an Old React.

**Solution:** Let’s switch to writing function components by default in Expensify/App and disallow writing any new class components moving forward. We will discuss how this might look and if we want to do this and which hooks we would use, best practices for using them, and how we can migrate our codebase.

## Tasks

- [x] Post **Proposal (full Problem/Solution statement)** in `#expensify-open-source`
- [x] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [x] Paste Proposal in the space above with a link to the Slack thread
- [x] Email `strategy@expensify.com` and paste in the Proposal
- [x] Fill out the **High-level overview of the problem**, **Timeline**, and **Terminology** sections of the Design Doc
- [x] Email `strategy@expensify.com` (continue the same email chain as before) with the link to your Design Doc
- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [x] Fill out the **High-level of proposed solution** section
- [x] Email `stategy@expensify.com` again with links to the doc and pre-design conversation in Slack
- [x] ~Add the `DesignDocReview` label to get the **High-level of proposed solution** section reviewed~
- [ ] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [x] ~Confirm that the doc has the minimum necessary number of reviews before proceeding~
- [x] ~Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.~
- [x] Fill out the **Detailed implementation of the solution** and related sections.
- [x] ~Re-add the `DesignDocReview` label to this issue~
- [x] ~Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary~
- [x] ~Confirm that the doc has the minimum necessary number of reviews before proceeding~
- [X] ~Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase~
- [ ] Implement the changes
- [ ] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

**Comment by MelvinBot** [comment]
Triggered auto assignment to @lschurr (`NewFeature`), see https://stackoverflowteams.com/c/expensify/questions/14418#:~:text=BugZero%20process%20steps%20for%20feature%20requests for more details.

**Comment by marcaaron** [comment]
Sorry this is not a "new feature"

**Comment by Gonals** [comment]
I have read and reviewed this Design Doc!

**Comment by dangrous** [comment]
I have read and reviewed this Design Doc!

**Comment by puneetlath** [comment]
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment]
I have read and reviewed this Design Doc!

**Comment by francoisl** [comment]
I have read and reviewed this Design Doc!

**Comment by marcaaron** [comment]
The latest on this is that we have taken some issues off HOLD and continue to develop our best practices before opening up to external contributors. There has also been some conversation (aided by @puneetlath) to drop the job offer price for these issues to $250 as they are significantly easier than our usual bug fixes. Once we are done with the internal migration we'll make a general announcement in `#expensify-open-source` and open things up to the community to finish up the majority of the work.

**Comment by JmillsExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by marcaaron** [comment]
Took a few more issues off hold recently and made them `Weekly`. I'd estimate we are about 1/3 of the way done with the "internal" part of this implementation and it's moving slow since we deprioritized this project.

As most of the available roadmap issues are assigned out I'm going to start pinging people to get these done (they are not super complex) and we will then offload it to the community to take us to the finish line.

**Comment by JmillsExpensify** [comment]
Pretty cool regardless! Great work.

**Comment by marcaaron** [comment]
Got a bit caught up with App deployer duties this week. Will try to put together an update on this tomorrow and share in `#engineering-chat` so we can figure out the next steps.

**Comment by marcaaron** [comment]
I think everyone is focused on EC3 right now. Once we are on the other side - we'll pick up the pace on this project or pass it to contributors. I'm reluctant to force either right now since I don't want to create a deluge of PRs that need to be reviewed internally and everyone is a bit pressed at the moment.

**Comment by marcaaron** [comment]
Just a heads up, I'm going to be OOO from May 23rd to May 30th. 

I'm going to stay assigned since I think I have the most context on where things are at. But if someone wants to proceed without me or try to figure out how to start passing issues to contributors I am OK with that. I still feel like there are more urgent priorities for us to get to before we tackle these issues.

**Comment by JmillsExpensify** [comment]
Is it worth posting this update in open source as well?

**Comment by marcaaron** [comment]
Considering that we've remained largely silent about this project WRT contributors and only vaguely hinted at possibly needing their help on it eventually - I feel OK with not updating the public channel for now.

**Comment by hayata-suenaga** [comment]
I have read and reviewed this Design Doc!

**Comment by marcaaron** [comment]
It sounds like maybe I need to sync up with @neil-marcellini and @hayata-suenaga on how to best combine efforts with the TypeScript initiative. 

Honestly, the internal response to doing these refactors has been... meh. lol. 

It makes sense as we've all got more visible and higher value tasks to work on. 

Given that we are still "busy", but not nearly as pressed as we were pre-EC3. I think we should offload the entire project at this point to contributors and keep building out our set of "best practices" on the fly. 

Here's my proposal:

1. Merge the best practices we've landed on and FAQ guidance in it's current state (there's one bit about `useMemo()` and `useCallback()` that needs to be updated as per Tim's feedback)
2. Starting next week, anyone who is still assigned an internal issue I'm going to ask them to unassign and apply the External label.
3. We'll offer those issues to contributors at the reduced rate (as previously discussed)
4. Any new conversations that pop up related to best practices we will hash out in realtime. I feel pretty good about that since there really haven't been a _ton_ of controversial discussions so I don't even think this needs much "management" from anyone and we should just pull out all the stops. I am good to take on the role of manager and moderate any conversations and update our docs until we are done.

@puneetlath thoughts on that approach?

**Comment by puneetlath** [comment]
That sounds like a good plan to me!

The only feedback from me is maybe let's open the issues up in waves. Just so we don't have 200 new issues/PRs to manage all at once.

**Comment by neil-marcellini** [comment]
> It sounds like maybe I need to sync up with @neil-marcellini and @hayata-suenaga on how to best combine efforts with the TypeScript initiative.

I believe what we decided on was that we won't migrate a component to Typescript until it's already migrated to a functional component to avoid merge conflicts. I think it's a good idea to make these issues external and get the functional migration moving faster. If a component wasn't migrated by the time we get to it for TS, we're planning to tackle the functional migration for that component too. So ideally it's migrated before we get to it. We're planning to start migrating simple "leaf node" files first so there should be enough time to migrate most components to functional first. cc @hayata-suenaga to confirm.

**Comment by marcaaron** [comment]
Ok thanks for the thoughts everyone. I left an update [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727842949549) in Slack that lays out the rules of engagement for this one and bumped all the internal engineers holding open assigned issues. 

I'm going to check back in on the project at a weekly cadence and do the following:

1. Check to see how many issues are open and unassigned
2. Post in `#expensify-open-source` to update everyone on the progress
3. List any open unassigned issues looking for a contributor to take on

**Comment by marcaaron** [comment]
Making slow and steady progress here so I will keep leaving weekly updates on where stuff is at. 

As far as I can tell, progress has been great and we haven't run into a ton of conversations that needed any serious discussion. There was one thread [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1686574009182619) about function signatures getting inconsistently applied raised and @roryabraham came up with a quick solution to help enforce the best practices 🙇 

**Issues done:** 40
**Issues in progress:** 28
**Issues assigned on hold:** 9
**Issues on HOLD:** 134

I'll take another set of issues off HOLD once we are down to 10-15 in progress.

**Comment by marcaaron** [comment]
Alright spoke with @puneetlath in this thread and looks like we are going to [take some more issues off HOLD](https://expensify.slack.com/archives/C0593T50UHG/p1687799774086809?thread_ts=1684947503.427089&cid=C0593T50UHG). We are still on a "merge freeze" so there is less of a concern about burdening people too much with these reviews.

I will post an update in `#expensify-open-source` today with the next round of issues.

**Comment by marcaaron** [comment]
**Issues done:** 57
**Issues in progress:** 40
**Issues on HOLD**: 112

**Comment by marcaaron** [comment]
**Issues done:** 63
**Issues in progress:** 34
**Issues on HOLD:** 112

I'll wait to see how many we finished by Friday and then take some issues off HOLD on Monday. Merge freeze is over so it feels like we will have some capacity to do some more of these.

**Comment by marcaaron** [comment]
**Issues done:** 75
**Issues in progress:** 28
**Issues on HOLD:** 106

Going to take another 10 issues or so off hold.

**Comment by marcaaron** [comment]
**Issues done:** 94
**Issues in progress:** 24
**Issues on HOLD:** 91

Looks like we are nearly at about the 50% mark for this project 🎉 

Will take another 10 issues off hold tomorrow.

**Comment by marcaaron** [comment]
**Done (or closed):** 113
**In progress:** 22
**On Hold:** 74

Will take some more off HOLD on Monday. Expert contributors have been steadily picking this off as well as precursors to various other projects so this hasn't required too much management on my side.

**Comment by marcaaron** [comment]
**Done:** 135
**In Progress:** 27
**On Hold:** 47

We're down to less than 50 issues on hold 😱 🎉 

Maybe we can pull out the stops here and take them all off HOLD next week. 
Feels like everyone has a pretty good understanding of the best practices at this point.

**Comment by marcaaron** [comment]
There are only 37 issues on HOLD left. They are slowly getting picked off by expert contributors. But I think we should be done here before offshore so gonna put a Monthly on this for now.

**Comment by marcaaron** [comment]
There are only 18 issues left that are still on HOLD. Since there are a lot of projects under tight deadlines during Offshore I am not going to push too hard to get them done so that we can sustain maximum focus on those goals. That said, if any expert contributor groups want to pick them up I am happy to assign them.

**Comment by marcaaron** [comment]
177 issues completed. 
32 issues in progress. 
**0 issues on HOLD** 😮  

_👏 al 👏 most 👏 there_

**Comment by marcaaron** [comment]
19 components left. All in progress. 😮 🪝

**Comment by marcaaron** [comment]
There are 12 open issues. I think we can wrap it up by the EOY. Will go around and bump the remaining issues.

**Comment by marcaaron** [comment]
Last 4 issues are in review. Not sure if we will finish finish by EOW, but since the remaining work is in active review I'm just going to close this tracking issue and consider this DONE. 

Any new components should be functions. Any remaining class components can get refactored as time permits. We did a ton of work here, but should remove this as a distraction for 2024 and move the focus to Wave/VIP issues.

**Comment by roryabraham** [comment]
Thanks for leading the charge here @marcaaron! I think it had a very good impact in modernizing our codebase and making a lot of the components simpler.
