### ISSUE TITLE
[HOLD for payment 2023-04-10] Add new step to App Deploy Checklist

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#16702]
Coming from [this comment](https://expensify.slack.com/archives/C03V9A4TB/p1680111294606869?thread_ts=1680110877.682689&cid=C03V9A4TB), we should add a new step to the deploy checklist to verify that GH actions are working before we attempt to deploy. Taking this step will avoid issues with the deploy process.

**Comment by MelvinBot** [comment]
`Reviewing` label has been removed, please complete the "BugZero Checklist".

**Comment by MelvinBot** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.2.93-4 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/16726


If no regressions arise, payment will be issued on 2023-04-10. :confetti_ball:

After the hold period is over and BZ checklist items are completed, please complete any of the applicable payments for this issue, and check them off once done.
- [ ] External issue reporter
- [ ] Contributor that fixed the issue
- [ ] Contributor+ that helped on the issue and/or PR

As a reminder, here are the bonuses/penalties that should be applied for any External issue:
- Merged PR within 3 business days of assignment - 50% **bonus**
- Merged PR more than 9 business days after assignment - 50% **penalty**

**Comment by luacmartins** [comment]
This is done. Closing.
