### ISSUE TITLE
[HOLD for BugZero Checklist] [$1000] current currency is not highlighted and not marked with :heavy_check_mark:

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#17372]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. click on + button
2. select send money option
3. click on currency

## Expected Result:  
current currency should be highlighted and  marked with :heavy_check_mark: (same as Timezone, Pronouns)

## Actual Result: 
current currency not highlighted

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**  v1.2.99-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/231623389-7bedf533-9774-4bd1-823a-5fae485055e5.mp4

https://user-images.githubusercontent.com/43996225/231623421-38ffc8e2-1663-4bbf-9c4f-f6de43119c70.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1681298924546589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d6db25e1b8518af</li>
        <li>Upwork Job ID: 1649369664727408640</li>
        <li>Last Price Increase: 2023-04-21</li>
    </ul>
</details>

**Comment by MelvinBot** [comment]
Triggered auto assignment to @NicMendonca (`Bug`), see https://stackoverflow.com/c/expensify/questions/14418 for more details.

**Comment by MelvinBot** [comment]
### Bug0 Triage Checklist ([Main S/O](https://stackoverflowteams.com/c/expensify/questions/14418))

- [ ] This "bug" occurs on a supported platform (ensure `Platforms` in OP are ✅)
- [ ] This bug is not a duplicate report (check [E/App issues](https://github.com/Expensify/App/issues) and [#expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM))
    - If it is, comment with a link to the original report, close the issue and add any novel details to the original issue instead
- [ ] This bug is reproducible using the reproduction steps in the OP. [S/O](https://stackoverflowteams.com/c/expensify/questions/14418#:~:text=The%20bug%20is%20reproducible)
    - If the reproduction steps are clear and you're unable to reproduce the bug, check with the reporter and QA first, then close the issue.
    - If the reproduction steps aren't clear and you determine the correct steps, please update the OP.
- [ ] This issue is filled out as thoroughly and clearly as possible
    - Pay special attention to the title, results, platforms where the bug occurs, and if the bug happens on staging/production.
- [ ] I have reviewed and subscribed to the linked Slack conversation to ensure Slack/Github stay in sync

**Comment by NicMendonca** [comment]
Hmm, I think this is a stylistic preference, not a bug. I think it's is very clear which is the current currency:

![image](https://user-images.githubusercontent.com/24947345/232069733-2c0f059c-ca9d-419a-902b-cbf2b3d0f1a7.png)

**Comment by PrashantMangukiya** [comment]
@NicMendonca please click the currency marked with yellow square in your image, it will open Select currency screen. On that screen CA is not highlighted with bold and marked with green check mark. 

So in this issue we are talking about it. You can go to Timezone, Pronouns page to see the exact behaviour what should be expected result for this issue.

Here is quick video I recorded to make it more clear. So this issue should not be closed.

https://user-images.githubusercontent.com/7823358/232077093-8b6883d1-3130-42a3-9699-8eeb0689e0d7.mov

**Comment by gadhiyamanan** [comment]
bump @NicMendonca

**Comment by NicMendonca** [comment]
Hmmm, I still think this is a stylistic preference and not a bug. Timezone and Pronouns are setting you set in your profile, and the currency you use for sending/ requesting money is ad-hoc but seems to be some passion about it here 😊

**Comment by MelvinBot** [comment]
Triggered auto assignment to @iwiznia (`Engineering`), see https://stackoverflow.com/c/expensify/questions/4319 for more details.

**Comment by MelvinBot** [comment]
Job added to Upwork: https://www.upwork.com/jobs/~015d6db25e1b8518af

**Comment by MelvinBot** [comment]
Current assignee @NicMendonca is eligible for the External assigner, not assigning anyone new.

**Comment by MelvinBot** [comment]
Triggered auto assignment to Contributor-plus team member for initial proposal review - @rushatgabhane (`External`)

**Comment by MelvinBot** [comment]
Current assignee @iwiznia is eligible for the External assigner, not assigning anyone new.

**Comment by dukenv0307** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Curret currency is not highlighted and not marked with checkmark icon

### What is the root cause of that problem?
To highlight and mark option that is selected, each option need to has `customIcon`, `boldStyle` property. That's why in `IOUCurrencySelection` current currency is not highlighted and not marked with checkmark icon
https://github.com/Expensify/App/blob/32b1e01de94f770152ab786f68398284564e8d90/src/pages/settings/Profile/TimezoneSelectPage.js#L83-L94

https://github.com/Expensify/App/blob/32b1e01de94f770152ab786f68398284564e8d90/src/pages/iou/IOUCurrencySelection.js#L77-L83
### What changes do you think we should make in order to solve the problem?
get 'iou' props from `ONYX` with key `ONYXKEYS.IOU` to get current currency and add `boldStyle`, `customIcon` property into each option to highlight and mark option that is selected: `customIcon: currencyCode === this.props.iou.selectedCurrencyCode ? greenCheckmark : undefined,`, `boldStyle: currencyCode === this.props.iou.selectedCurrencyCode,`
And we could also add `initiallyFocusedOptionKey` property into `OptionsSelector` to focus option selected whenever go to this page.
### What alternative solutions did you explore? (Optional)
**NA**

### Result

[Screencast from 14-04-2023 16:53:18.webm](https://user-images.githubusercontent.com/129500732/232012409-f3f14d51-d340-46fa-889c-17d6042dee3e.webm)

**Comment by NicMendonca** [comment]
@rushatgabhane any feedback on[ this proposal](https://github.com/Expensify/App/issues/17372#issuecomment-1517756777)?

**Comment by dukenv0307** [comment]
@rushatgabhane Thanks, I updated my [proposal](https://github.com/Expensify/App/issues/17372#issuecomment-1517756777)

**Comment by MelvinBot** [comment]
📣 @dukenv0307 You have been assigned to this job by @iwiznia!
Please apply to this job in Upwork and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻
Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

**Comment by dukenv0307** [comment]
@iwiznia @rushatgabhane The PR is ready to review!

**Comment by MelvinBot** [comment]
@iwiznia, @NicMendonca, @rushatgabhane, @dukenv0307 Uh oh! This issue is overdue by 2 days. Don't forget to update your issues!

**Comment by NicMendonca** [comment]
@rushatgabhane bump on this: https://github.com/Expensify/App/issues/17372#issuecomment-1539338561

**Comment by gadhiyamanan** [comment]
@NicMendonca applied, Thanks!

**Comment by NicMendonca** [comment]
@mananjadhav paid!

**Comment by gadhiyamanan** [comment]
it's @gadhiyamanan not mananjadhav 😅
can you please close the Upwork contact

**Comment by NicMendonca** [comment]
@mananjadhav you did not get paid lol 

@gadhiyamanan I'm sorry!!

**Comment by NicMendonca** [comment]
@rushatgabhane thanks! Paid!

@dukenv0307 just need you to accept the offer - thanks!

**Comment by dukenv0307** [comment]
@NicMendonca accepted, thank you!

**Comment by NicMendonca** [comment]
Everyone has been paid! 

bump @rushatgabhane on [this checklist](https://github.com/Expensify/App/issues/17372#issuecomment-1539338561)

**Comment by NicMendonca** [comment]
Going OOO until June 5th so assigning a buddy to this GH to watch over the checklist. 

Bump @rushatgabhane on the checklist! https://github.com/Expensify/App/issues/17372#issuecomment-1539338561

**Comment by sonialiap** [comment]
@rushatgabhane checklist please :) https://github.com/Expensify/App/issues/17372#issuecomment-1539338561

**Comment by sonialiap** [comment]
Thanks @rushatgabhane !
