### ISSUE TITLE
Deploy Checklist: New Expensify 2023-05-02

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#18322]
**Release Version:** `1.3.9-20`
**Compare Changes:** https://github.com/Expensify/App/compare/production...staging

**This release contains changes from the following pull requests:**
- [x] https://github.com/Expensify/App/pull/15672
- [x] https://github.com/Expensify/App/pull/16076
- [x] https://github.com/Expensify/App/pull/17090
- [x] https://github.com/Expensify/App/pull/17329
- [x] https://github.com/Expensify/App/pull/17447
- [x] https://github.com/Expensify/App/pull/17496
- [x] https://github.com/Expensify/App/pull/17640
- [x] https://github.com/Expensify/App/pull/17704
- [x] https://github.com/Expensify/App/pull/17902
- [x] https://github.com/Expensify/App/pull/17943
- [x] https://github.com/Expensify/App/pull/17953
- [x] https://github.com/Expensify/App/pull/18022
- [x] https://github.com/Expensify/App/pull/18038
- [x] https://github.com/Expensify/App/pull/18059
- [x] https://github.com/Expensify/App/pull/18065
- [x] https://github.com/Expensify/App/pull/18066
- [x] https://github.com/Expensify/App/pull/18085
- [x] https://github.com/Expensify/App/pull/18087
- [x] https://github.com/Expensify/App/pull/18103
- [x] https://github.com/Expensify/App/pull/18126
- [x] https://github.com/Expensify/App/pull/18137
- [x] https://github.com/Expensify/App/pull/18153
- [x] https://github.com/Expensify/App/pull/18155
- [x] https://github.com/Expensify/App/pull/18159
- [x] https://github.com/Expensify/App/pull/18160
- [x] https://github.com/Expensify/App/pull/18173
- [x] https://github.com/Expensify/App/pull/18193
- [x] https://github.com/Expensify/App/pull/18195
- [x] https://github.com/Expensify/App/pull/18227
- [x] https://github.com/Expensify/App/pull/18228
- [x] https://github.com/Expensify/App/pull/18236
- [x] https://github.com/Expensify/App/pull/18242
- [x] https://github.com/Expensify/App/pull/18256
- [x] https://github.com/Expensify/App/pull/18257
- [x] https://github.com/Expensify/App/pull/18261
- [x] https://github.com/Expensify/App/pull/18266
- [x] https://github.com/Expensify/App/pull/18275
- [x] https://github.com/Expensify/App/pull/18276
- [x] https://github.com/Expensify/App/pull/18336
- [x] https://github.com/Expensify/App/pull/18360
- [x] https://github.com/Expensify/App/pull/18361
- [x] https://github.com/Expensify/App/pull/18369
- [x] https://github.com/Expensify/App/pull/18380
- [x] https://github.com/Expensify/App/pull/18395

**Deploy Blockers:**
- [x] https://github.com/Expensify/App/pull/15672
- [x] https://github.com/Expensify/App/issues/18304
- [x] https://github.com/Expensify/App/issues/18314
- [x] https://github.com/Expensify/App/issues/18323
- [x] https://github.com/Expensify/App/issues/18335
- [x] https://github.com/Expensify/App/issues/18341
- [x] https://github.com/Expensify/App/issues/18345
- [x] https://github.com/Expensify/App/issues/18355
- [x] https://github.com/Expensify/App/issues/18356
- [x] https://github.com/Expensify/App/issues/18358
- [x] https://github.com/Expensify/App/issues/18359
- [x] https://github.com/Expensify/App/issues/18376

**Deployer verifications:**
- [x] I checked the [App Timing Dashboard](https://graphs.expensify.com/grafana/d/yj2EobAGz/app-timing?orgId=1) and verified this release does not cause a noticeable performance regression.
- [x] I checked [Firebase Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&tag=all) and verified that this release does not introduce any new crashes. More detailed instructions on this verification can be found [here](https://stackoverflowteams.com/c/expensify/questions/15095/15096).
- [x] I checked [GitHub Status](https://www.githubstatus.com/) and verified there is no reported incident with Actions.

cc @Expensify/applauseleads

**Comment by marcaaron** [comment]
Checking off #18314 because it's on prod

**Comment by marcaaron** [comment]
Checking off https://github.com/Expensify/App/issues/18323 as it's related to the web deploy

**Comment by marcaaron** [comment]
Checking off #18341 as @luacmartins removed the blocker.

**Comment by marcaaron** [comment]
Checking off https://github.com/Expensify/App/issues/18335 as the issue is related to staging web API changes.

**Comment by marcaaron** [comment]
Checked off https://github.com/Expensify/App/issues/18345#issuecomment-1533635331 - it's related to the Pusher issues and web deploy.

**Comment by marcaaron** [comment]
Checking off #18359 as the feature is in active development and we already have some fix planned in https://github.com/Expensify/App/pull/17583/files. Not sure what the rollout plan for that was supposed to be but seems minor so we are not blocking today's deploy on it.

**Comment by marcaaron** [comment]
Checking off https://github.com/Expensify/App/issues/18358 as we reverted the offending PR and retested

**Comment by mvtglobally** [comment]
@marcaaron Still working on the checklist, but here is current issue list 

PR https://github.com/Expensify/App/pull/15672 facing issue https://github.com/Expensify/App/issues/18335
PR https://github.com/Expensify/App/pull/16076 is failing https://github.com/Expensify/App/issues/18330, not repro in PROD but its a new feature 
PR https://github.com/Expensify/App/pull/17090 is failing https://github.com/Expensify/App/issues/18362. repro in prod still checking all env 
PR https://github.com/Expensify/App/pull/17447 is failing https://github.com/Expensify/App/issues/18351, repro in PROD 
PR https://github.com/Expensify/App/pull/17943 is failing https://github.com/Expensify/App/issues/15638 https://github.com/Expensify/App/issues/18344. repro in PROD, checking off 
https://github.com/Expensify/App/pull/18103 is failing https://github.com/Expensify/App/issues/18372, repro in PRoD 
PR https://github.com/Expensify/App/pull/18228 is failing https://github.com/Expensify/App/issues/18343 
PR https://github.com/Expensify/App/pull/18242 is failing

**Comment by marcaaron** [comment]
Most of those don't really seem like blockers to me so I am checking a bunch off.

**Comment by mountiny** [comment]
Checking https://github.com/Expensify/App/pull/17640 off since this failing QA does not seem like a blocker https://github.com/Expensify/App/issues/18349

Checking https://github.com/Expensify/App/pull/18065 off since ti seems like its not failing QA

checking this one https://github.com/Expensify/App/pull/18137 since it also did not fail QA

**Comment by mvtglobally** [comment]
@mountiny Regression is completed 

https://github.com/Expensify/App/pull/18065 had issue https://github.com/Expensify/App/issues/17242 on mWeb, but its repro in PROD.  only Android validation is pending on this on QA side. 
https://github.com/Expensify/App/pull/18380 seem to be failing  

https://user-images.githubusercontent.com/43995119/236222075-fc492423-3a6e-4669-aa05-4c6fc360633b.mp4

**Comment by mountiny** [comment]
Nothing new in the graphs or crashes.

Just waiting for the last CP before kicking the deploy off

**Comment by mountiny** [comment]
Checking https://github.com/Expensify/App/pull/18395 off as it seems to work in staging although the optimistic workspace chats part did not seem to work for me. But i dont think its a blocker as users can use this just fine
