### ISSUE TITLE
[HOLD for payment 2023-06-12] [Tracking Issue]Bug fixes: 2FA

### ISSUE THREAD

**Issue by MonilBhavsar** [Expensify/App#19187]
Here is the list of minor Tracking 2FA bugs to make a quick follow up PR and fix all of them

1. Missing Download translation in Spanish - https://expensify.slack.com/archives/C049HHMV9SM/p1684406965776349
2. `Two-factor` name is inconsistent https://expensify.slack.com/archives/C049HHMV9SM/p1684406403576119
3. Offline Indicator displayed twice https://expensify.slack.com/archives/C049HHMV9SM/p1684408727072029
4. Here is your magic code page appears https://expensify.slack.com/archives/C049HHMV9SM/p1684405641601719
5. Error message persists https://expensify.slack.com/archives/C049HHMV9SM/p1684404156826129
6. View disrupted on small screen devices https://expensify.slack.com/archives/C049HHMV9SM/p1684392775324939

**Comment by stephanieelliott** [comment]
Awesome, thanks for the context @MonilBhavsar!

**Comment by BeeMargarida** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Several smaller issues regarding 2FA.

### What is the root cause of that problem?

1. Missing Download translation in Spanish
2. Two-factor name is inconsistent
   1. Translations were using both `two-factor` and `two factor`
3. Offline Indicator displayed twice
   1. 2FA pages use `ScreenWrapper`, that already includes an offline indicator by default
4. Here is your magic code page appears - when opening the magic link, it does not update correctly after setting the 2FA code
   1. This is because after signing in, the `AuthState` returns to `NOT_STARTED` instead of `JUST_SIGNED_IN`
5. Error message persists
6. View disrupted on small screen devices

### What changes do you think we should make in order to solve the problem?

1. Add translation for `downloadCodes`, since the value being used is hardcoded
2. Change all translation that are 'two factor' to 'two-factor'
3. We need to do 2 things:
   1. Add a prop to `ScreenWrapper` called `shouldShowOfflineIndicator` that has default `true`
   2. Use that prop with value `false` in all pages that use `FullPageOfflineBlockingView`
   3. Modify all usages of `ScreenWrapper` with `FullPageOfflineBlockingView` to include this prop, since the problem will appear there as well. 
4. Change `ValidateLoginPage` to show the `AbracadabraModal` not when the AuthState is `JUST_SIGNED_IN` but `NOT_STARTED` and `isSignedIn === true`.
5. Clear Account messages on mount in `VerifyPage`
6. In the `CodesPage`, use `withWindowDimensions` and apply `paddingHorizontal` as `40` instead of `60` when `isSmallScreenWidth` is true.

### What alternative solutions did you explore? (Optional)

--

**Comment by MonilBhavsar** [comment]
Thanks for the proposal 🙇 

1. We already have translation in `common.download`. Looks like we just need to translate where we display it.
2. Looks good 👍 
3. Oh, since the problem is widespread, I think this needs some discussion and we can handle this in another PR, as it is not solely related to 2FA.
4. Do we only need to remove `!isTfaRequired` and keep `JUST_SIGNED_IN`? Also let's please rename that to `is2FARequired` 😅 
5. Sounds good to me 👍 We can test it out on different devices and see if we still need to adjust the padding.

**Comment by BeeMargarida** [comment]
> Do we only need to remove `!isTfaRequired` and keep `JUST_SIGNED_IN`? 

For the `AbacadabraModal` (after the sign in is complete), we need to remove the `isTfaRequired` and switch `JUST_SIGNED_IN` with `NOT_STARTED` (since this is reset after signing in), basically switch to `this.getAutoAuthState() === CONST.AUTO_AUTH_STATE.NOT_STARTED && isSignedIn && <AbracadabraModal />`

> Also let's please rename that to `is2FARequired` 😅

On it!

**Comment by MonilBhavsar** [comment]
> (since this is reset after signing in)

I see, thanks for clarifying. That makes sense! 🙇

**Comment by stephanieelliott** [comment]
PRs are under review!

**Comment by stephanieelliott** [comment]
Reviews completed, just awaiting merge

**Comment by MonilBhavsar** [comment]
PR is merged!
We need to pay all reporters and @mananjadhav for PR review next week

**Comment by stephanieelliott** [comment]
Created in Upwork: https://www.upwork.com/jobs/~016a53e935d8151e4b

Extended offers to: 
 - C+ for PR review: @mananjadhav 
- Missing Download translation in Spanish - Reporting: @ayazhussain79 
- Two-factor name is inconsistent - Reporting: @Natnael-guchima
- Offline Indicator displayed twice - Reporting: @dhairyasenjaliya 
- Here is your magic code page appears Reporting: @Natnael-guchima
- Error message persists Reporting: @nathan-mulugeta
- View disrupted on small screen devices - Reporting: @ayazhussain79

**Comment by ayazhussain79** [comment]
@stephanieelliott I have identified only this bug : View disrupted on small screen devices

**Comment by mananjadhav** [comment]
@stephanieelliott Unable to access the Upwork job? Do you mind sending an invite?

**Comment by gadhiyamanan** [comment]
@stephanieelliott you accidentally sent me job offer instead of @mananjadhav 😅

**Comment by MonilBhavsar** [comment]
@aman-atg sorry, fixed that

**Comment by MonilBhavsar** [comment]
> Offline Indicator displayed twice - Reporting: @dhairyasenjaliya

@stephanieelliott we didn't fix this issue here as it was out of scope and instead we'll be fixing it [here](https://github.com/Expensify/App/issues/20004) in another issue

**Comment by MonilBhavsar** [comment]
Yes 👍

**Comment by mananjadhav** [comment]
> @stephanieelliott you accidentally sent me job offer instead of @mananjadhav 😅

@stephanieelliott I cannot access the job link. I think because of this. Can you please help?

**Comment by stephanieelliott** [comment]
OKok sorry for the confusion, I _think_ I was able to get this sorted: 

- [x]  **C+ for PR review:** ~`@gadhiyamanan`~ extended offer to @mananjadhav, this has been paid 
- [ ]  **Missing Download translation in Spanish** - Reporting: ~`@ayazhussain79`~ extended offer to @aman-atg
- [x]  **Two-factor name is inconsistent** - Reporting: [@Natnael-Guchima](https://github.com/Natnael-Guchima) this has been paid
- [x]  **Offline Indicator displayed twice** - Reporting: ~`@dhairyasenjaliya`~ not paying on this issue, [handling elsewhere](https://github.com/Expensify/App/issues/19187#issuecomment-1582215967)
- [x]  **Here is your magic code page appears Reporting:** [@Natnael-Guchima](https://github.com/Natnael-Guchima) this has been paid 
 - [x]  **Error message persists Reporting:** [@Nathan-Mulugeta](https://github.com/Nathan-Mulugeta) this has been paid 
 - [ ] **View disrupted on small screen devices** - Reporting: [@ayazhussain79](https://github.com/ayazhussain79) offer extended

Leaving the contracts open just in case I need to swap anything around again 😅, will close by EOD tomorrow once payment is issued for the remaining 2.

**Comment by mananjadhav** [comment]
Tough one @stephanieelliott. Thanks for clearing this one out. Appreciate it!

**Comment by stephanieelliott** [comment]
Hey @aman-atg can you accept the offer in Upwork when you get a chance?

**Comment by stephanieelliott** [comment]
Reapplying the `Bug` label to get another BZ member on this while I am OOO til July 3. Thanks @bfitzexpensify, only thing to do here is issue payment to @aman-atg. The job was extended to them in Upwork, we are just waiting for them to accept is so we can make the payment and close the contract. All others have been paid!

**Comment by bfitzexpensify** [comment]
Paid out and ended the contract for @aman-atg. Sounds like we're all done here, so closing this one out.
