### ISSUE TITLE
[Tracking issue] Secure NewDot Logins - Re-keying personal details & policy member Onyx data

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#19247]
# [Detailed doc section](https://docs.google.com/document/d/1G1rjhsPT1S_9BEw7yFvwUcw8AQih0yBANPPPpiKzYlk/edit#heading=h.rqafo1fdn5g1)

We want to get a small but key chunk of the "Secure NewDot Logins" reviewed and start implementation before some upcoming conferences. As such, we've added a [Re-keying personal details & policy member Onyx data](https://docs.google.com/document/d/1G1rjhsPT1S_9BEw7yFvwUcw8AQih0yBANPPPpiKzYlk/edit#heading=h.rqafo1fdn5g1) section to the design doc.

We created this board to keep track of issues for this project: https://github.com/orgs/Expensify/projects/36/views/1
- Once this section goes through some reviews and we get close to implementation we'll start adding issues.

I'm creating this issue in order to get doc reviews on the "Re-keying personal details & policy member Onyx data" detailed design.

## Implementation issues
- [x] https://github.com/Expensify/App/issues/19532
- [x] https://github.com/Expensify/App/issues/19533
- [ ] App changes: https://github.com/Expensify/App/issues/19007

**Comment by Beamanator** [comment]
Sorry for all the pings & new issues, was just looking for "Detailed" reviewers, finally they're assigned 🙏

**Comment by greg-schroeder** [comment]
I have read and reviewed this Design Doc!

**Comment by isabelastisser** [comment]
I have read and reviewed this Design Doc!

**Comment by joaniew** [comment]
I have read and reviewed this Design Doc!

**Comment by shawnborton** [comment]
I have read and reviewed this Design Doc!

**Comment by puneetlath** [comment]
Making good progress. Auth changes are done. Web changes are close. Once those are done, Callstack will be unblocked from starting to update the client to use the new Onyx object.

**Comment by puneetlath** [comment]
We're very actively implementing this. We've done the Auth and Web changes and are now working on the front-end changes.

**Comment by Beamanator** [comment]
Finally merged the [App changes](https://github.com/Expensify/App/pull/20473) last Thursday! Working on getting all the bug fixes worked out :D

**Comment by Beamanator** [comment]
The re-key is basically done, we're just working on cleaning out a few remaining emails from Onyx - this is bring tracked in the main issue https://github.com/Expensify/Expensify/issues/280523

So closing this one!
