### ISSUE TITLE
[Tracking] Add a Video Player to New Expensify

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#20471]
## Proposal
[Original Proposal](https://expensify.slack.com/archives/C01GTK53T8Q/p1681805745267419)
[WN Internal Proposal](https://expensify.slack.com/archives/CC7NECV4L/p1686174781538369)
[Project](https://github.com/orgs/Expensify/projects/109/views/1)

**Proposal: Add a Video Player to NewDot**

**Problem**
At the moment, when a video is sent as a message, it is treated as a generic file attachment. This means that one has to first download it to their device, and then open it separately, out of the app.
Not only does this provide a subpar user experience, it's also inconsistent with images, which are displayed directly in the chat.

**Solution**
Add the ability for NewDot to play videos in-app, by implementing a video player.

## Design Doc
**https://docs.google.com/document/d/1Fh5Nu3D0-VW7xuV9Qc-OWWZl3-W5azx7Rr1lzNw4UGo/edit**

## Pre-designs

[Pre-design 1](https://expensify.slack.com/archives/C01GTK53T8Q/p1684350579474959)
[Pre-design 2](https://expensify.slack.com/archives/C01GTK53T8Q/p1685982420359039)

## Tasks

- [x] Post **Proposal (full Problem/Solution statement)** in `#expensify-open-source`
- [x] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [x] Paste Proposal in the space above with a link to the Slack thread
- [x] Email `strategy@expensify.com` and paste in the Proposal
- [x] Fill out the **High-level overview of the problem**, **Timeline**, and **Terminology** sections of the Design Doc
- [x] Email `strategy@expensify.com` (continue the same email chain as before) with the link to your Design Doc
- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [x] Fill out the **High-level of proposed solution** section
- [x] Email `stategy@expensify.com` again with links to the doc and pre-design conversation in Slack
- [x] Add the `DesignDocReview` label to get the **High-level of proposed solution** section reviewed
- [x] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.
- [x] Fill out the **Detailed implementation of the solution** and related sections.
- [x] Re-add the `DesignDocReview` label to this issue
- [x] Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase
- [ ] Implement the changes
- [ ] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

**Comment by francoisl** [comment]
@jczekalski FYI. GH won't let me co-assign you for some reason, feel free to co-assign yourself to this issue.

**Comment by jczekalski** [comment]
@francoisl I can't assign myself. Perhaps you'll be able to co-assign me once I've commented in the issue?

**Comment by francoisl** [comment]
EOW update: Jan has been partially OOO this week, and I didn't have much time to update the doc. Hoping to resume working on this next week! 💪

**Comment by puneetlath** [comment]
Would this video player also work for audio files (e.g. mp3)?

**Comment by francoisl** [comment]
@puneetlath this was brought up during the second pre-design ([here](https://expensify.slack.com/archives/C01GTK53T8Q/p1686084132638919?thread_ts=1685982420.359039&cid=C01GTK53T8Q)), and Jan recommended we focus on video for now, since supporting audio files would possibly require different libs.

**Comment by jczekalski** [comment]
Hey @francoisl, I've already filled out some sections of the design doc, though it's still WIP and I'm working on a copy. Should I copy everything to the actual design doc?

**Comment by francoisl** [comment]
Good to hear, thanks! For now it's fine, you can keep it in your WIP copy. One question though - did you figure out if we'll need to make backend changes to generate and store thumbnails – or if we'll be able to make the thumbnails directly from the client?

**Comment by francoisl** [comment]
Waiting on the mockups, in the meantime I remade a new design doc with the new template, and will continue filling it out.

**Comment by jczekalski** [comment]
Hey @francoisl, I recently started working on a different project at Software Mansion and this issue was transferred to a different developer. I'll ask him to comment in the issue, so you can assign him.

**Comment by Skalakid** [comment]
Hey @francoisl, recently I've taken this task from Jan and started working on it. For now, I was creating my own POC where I was testing available packages and investigating challenges connected to them. Also, I continued writing Jan's design doc copy. I think we are having most of the information about the video player so I moved everything to the main file so you can take a look :D

**Comment by francoisl** [comment]
The doc is making good progress thanks to Michał. There's one open question regarding thumbnails that we [took to Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1691590187942739), other than that the doc is almost ready for review.

**Comment by dannymcclain** [comment]
It's not overdue Melvin. I posted an update to [this issue](https://github.com/Expensify/Expensify/issues/301131) without realizing not everyone had access to it.

Here's where we settled for the video player UI. ⏯️
![image](https://github.com/Expensify/App/assets/7516624/1241784b-bc0c-459a-8e1f-9eaf55e87a21)

You can find these screens (and all the little pieces for the player UI) in the [NewDot / Video Player Figma file](https://www.figma.com/file/ucwSmgVnBPRbe6srOG5KxG/Video-Player?type=design&node-id=1-68&mode=design&t=nEm308dd2Oazw0Qk-11).

For the "more" 3-dot menu, we want to use our standard context menu styling.
<img width="1130" alt="image" src="https://github.com/Expensify/App/assets/7516624/bd0fca0b-ea2b-4523-a638-15f22235ce78">

**Comment by francoisl** [comment]
High-level design doc sent out for review, going to apply the `DesignDocReview` label to get some reviewers assigned.

https://docs.google.com/document/d/1Fh5Nu3D0-VW7xuV9Qc-OWWZl3-W5azx7Rr1lzNw4UGo/edit

**Comment by puneetlath** [comment]
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment]
I have read and reviewed this Design Doc!

**Comment by tylerkaraszewski** [comment]
I have read and reviewed this Design Doc!

**Comment by Julesssss** [comment]
I have read and reviewed this Design Doc!

**Comment by techievivek** [comment]
I have read and reviewed this Design Doc!

**Comment by nkuoch** [comment]
I have read and reviewed this Design Doc!

**Comment by sakluger** [comment]
I have read and reviewed this Design Doc!

**Comment by danielrvidal** [comment]
I have read and reviewed this Design Doc!

**Comment by JmillsExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by heyjennahay** [comment]
I have read and reviewed this Design Doc!

**Comment by ryanschaffer** [comment]
I have read and reviewed this Design Doc!

**Comment by francoisl** [comment]
Front-end part of the detailed section is mostly done, going to work on the backend.

**Comment by francoisl** [comment]
Detailed section of the doc is ready for review, going to reapply the DesignDoc label to get reviewers assigned.

**Comment by puneetlath** [comment]
I have read and reviewed this Design Doc!

**Comment by tylerkaraszewski** [comment]
I have read and reviewed this Design Doc!

**Comment by joelbettner** [comment]
I have read and reviewed this Design Doc!

**Comment by joelbettner** [comment]
I have read and reviewed this Design Doc!

**Comment by quinthar** [comment]
I have read and reviewed this Design Doc!

**Comment by danielrvidal** [comment]
I have read and reviewed this Design Doc!

**Comment by nkuoch** [comment]
I have read and reviewed this Design Doc!

**Comment by laurenreidexpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by iwiznia** [comment]
I have read and reviewed this Design Doc!

**Comment by francoisl** [comment]
The project board is up with the issues, update here in Slack: https://expensify.slack.com/archives/C05NTGSDSF2/p1702093797797469

**Comment by kowczarz** [comment]
Since the Video Player feature is a blocker for other tasks and most of the code was written before introduction of TS restrictions, we decided to add new JS files to the main. As soon as we will merge the feature, we need to migrate following files to TS:
- src/components/Attachments/AttachmentView/AttachmentViewVideo/index.js
- src/components/HTMLEngineProvider/HTMLRenderers/VideoRenderer.js
- src/components/VideoPlayer/BaseVideoPlayer.js
- src/components/VideoPlayer/IconButton.js
- src/components/VideoPlayer/VideoPlayerControls/ProgressBar/index.js
- src/components/VideoPlayer/VideoPlayerControls/VolumeButton/index.js
- src/components/VideoPlayer/VideoPlayerControls/index.js
- src/components/VideoPlayer/index.js
- src/components/VideoPlayer/index.native.js
- src/components/VideoPlayer/propTypes.js
- src/components/VideoPlayer/utils.ts
- src/components/VideoPlayerContexts/PlaybackContext.js
- src/components/VideoPlayerContexts/VideoPopoverMenuContext.js
- src/components/VideoPlayerContexts/VolumeContext.js
- src/components/VideoPlayerPreview/VideoPlayerThumbnail.js
- src/components/VideoPlayerPreview/index.js
- src/components/VideoPopoverMenu/index.js
- src/hooks/useThumbnailDimensions.ts
- src/libs/API/parameters/UpdateWelcomeMessageParams.ts
- src/pages/ReportWelcomeMessagePage.tsx
- src/pages/ShareCodePage.js
- src/pages/home/report/ReportDetailsShareCodePage.js
- src/pages/settings/Report/NotificationPreferencePage.js
- src/pages/settings/Report/WriteCapabilityPage.js

**Comment by francoisl** [comment]
The video player is on staging now!

Centralizing issues and follow-up tasks in [this issue](https://github.com/Expensify/App/issues/36625).
