### ISSUE TITLE
[Tracking issue] Onyx re-key effort

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20806]
## Open bugs since merging `main`:
- [x] https://github.com/Expensify/App/issues/20800
- [x] https://github.com/Expensify/App/issues/20801
- [ ] https://github.com/Expensify/App/issues/20802
- [ ] https://github.com/Expensify/App/issues/20803
- [ ] https://github.com/Expensify/App/issues/20804
- [x] https://github.com/Expensify/App/issues/20807
- [ ] https://github.com/Expensify/App/issues/20809
- [x] https://github.com/Expensify/App/issues/20811
- [ ] https://github.com/Expensify/App/issues/20812
- [ ] https://github.com/Expensify/App/issues/20813
- [x] https://github.com/Expensify/App/issues/20816
- [x] https://github.com/Expensify/App/issues/20820
- [ ] https://github.com/Expensify/App/issues/20822
- [ ] https://github.com/Expensify/App/issues/20830

Unrelated to this migration
- [ ] https://github.com/Expensify/App/issues/20839

**Comment by Beamanator** [comment]
NVm going with a project

**Comment by Beamanator** [comment]
Reopening b/c projects are private unless org admin makes them public :D

**Comment by Beamanator** [comment]
bugs are getting worked out, most fixes are on staging or prod by now

**Comment by Beamanator** [comment]
Only two incomplete issues so far, not blocking SNH:
- https://github.com/Expensify/App/issues/20830
- https://github.com/Expensify/App/issues/20812

**Comment by Beamanator** [comment]
I don't think this issue is needed anymore, bugs are being handled separately as needed
