### ISSUE TITLE
Move the high-traffic account setup process to C+ team

### ISSUE THREAD

**Issue by conorpendergrast** [Expensify/App#21386]
[As discussed via Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1686774661508419)

### Problem:

We require that all PRs be tested using high-traffic accounts, to more closely reflect how our customers user Expensify and prevent issues with code negatively impacting larger customers.
The [current process](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) asks our Contributors to post to [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to request being set up (which involves adding user accounts to two policies).
However, the results in requests being missed for a long time ([eg](https://expensify.slack.com/archives/C01GTK53T8Q/p1686190525794769), [eg](https://expensify.slack.com/archives/C01GTK53T8Q/p1686197504410539), [eg](https://expensify.slack.com/archives/C01GTK53T8Q/p1686142658815079), and delays or skips PRs being correctly tested.

### Solution

Let’s update [the process](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) to have the contributor post into the PR that they’re fixing, and asking the assigned C+ team member to set them up. That will distribute this step across the whole C+ team (not just siloed on Expensifiers who are paying attention to the Slack channel). An onboarding step for new C+ members will be to add them as policy admins for the two high-traffic policies (and we’ll add all existing C+ members as a policy admins too, through their preferred high traffic Expensify accounts).

The specific change we’ll make is to change the process to read as below
All internal engineers, contributors, and C+ members are required to test with a “high traffic” account against the staging or production web servers. Ask in your PR for the assigned Contributor+ team member to turn your account into a High Traffic account. These accounts more closely mirror the accounts used in production by real people.
You can say:
Hey C+ team member, can you please make [xxxxx+xxxx@xxxx.com](mailto:xxxxx+xxxx@xxxx.com) into a High Traffic account following [this process](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts)? Thanks!
The process for the C+ to set up an account as a high-traffic account is:
1. Sign in to Old Expensify with your existing high-traffic account
2. Go to **Settings** > **Policies** > **Group**
3. For both the Crowded Policy (Do Not Delete) and the Big Chat (Do Not Delete) workspaces, go to **People** > **Invite** and add the test accounts

## Todo

- [x] Ask all of C+ for their high-traffic account emails
- [x] Update [the doc](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) https://github.com/Expensify/App/pull/21388
- [x] Create the PR to update the documentation to use [this google form instead](https://docs.google.com/forms/d/e/1FAIpQLScpiS0Mo-HA5xHPsvDow79yTsMBgF0wjuqc0K37lTK5fheB8Q/viewform) https://github.com/Expensify/App/pull/21388
- [x] Create a form to allow removing a user from the policies?
- [x] Remove all policy admins
- [x] Announce confirmation of the change
- [x] Update [this StackOverflow post](https://stackoverflowteams.com/c/expensify/questions/14504) to outline the new process and the Zaps involved

**Comment by conorpendergrast** [comment]
@Expensify/contributor-plus Hey! Can you reply here with your high-traffic account email addresses please? Those are the accounts that I'll add to the high-traffic setups as admins, so I recommend having a dedicated account for those if you don't already. Thanks!

**Comment by narefyev91** [comment]
hey! nikolay.arefyeu@callstack.com

**Comment by mananjadhav** [comment]
Two emails:

- manan.jadhav@gmail.com
- manan.jadhav+wkowner@gmail.com

**Comment by sobitneupane** [comment]
> Hey! Can you reply here with your high-traffic account email addresses please?

Following is not a high-traffic account. Can you please convert it into high-traffic account as well.

dev.sobitneupane+ht@gmail.com

**Comment by s77rt** [comment]
admin+hightraffic@abdelhafidh.com

I think this is hightraffic already, can you please double check? Weirdly I don't seem to get the magic code, would be glad to check that too

**Comment by conorpendergrast** [comment]
Ok, I've added these as policy admins for both policies: 

allroundexperts@gmail.com,miroslav.stevanovic317+ht@gmail.com,miroslav.stevanovic317+hightraffic@gmail.com,nikolay.arefyeu@callstack.com,dev.sobitneupane+ht@gmail.com,manan.jadhav+wkowner@gmail.com,manan.jadhav@gmail.com,aiman.chnaif@gmail.com,aiman.chnaif+hightraffic@gmail.com,thesahindia@gmail.com,fedidev+ht@gmail.com,admin+hightraffic@abdelhafidh.com

If anyone who added a "real" account regrets that, then you are all admins and can add a new account as a Policy Admin (using the steps in the OP), then that account can remove the "real account"

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/21386#issuecomment-1604095879

Same here

**Comment by conorpendergrast** [comment]
Yep - it won't be accessible in New Expensify, just in Old Expensify. Workspaces are not designed for multiple admins in New Expensify (yet)

**Comment by sobitneupane** [comment]
> For both the Crowded Policy (Do Not Delete) and the Big Chat (Do Not Delete) workspaces, go to People > Invite and add the test accounts

I cannot figure out how to perform this step. As soon as I press one of the above policy in OldDot, I am redirected to newDot.

**Comment by mollfpr** [comment]
@conorpendergrast luthfi.ufi14@gmail.com please, thank you!

**Comment by eVoloshchak** [comment]
Could you convert it into a high-traffic account too, please?
copyreading+ht@gmail.com

**Comment by conorpendergrast** [comment]
@sobitneupane Thanks for giving the instructions a test! Can you try these links? 

- https://www.expensify.com/policy?param={%22policyID%22:%221A94466582348771%22}#people
- https://www.expensify.com/policy?param={%22policyID%22:%2282E68EBFA8B4A771%22}#people

**Comment by abdulrahuman5196** [comment]
@conorpendergrast 
Could you kindly convert the below accounts into high-traffic account and make it admin?

abdulrahuman5196+ht@gmail.com
abdulrahuman5196+ht1@gmail.com

**Comment by sobitneupane** [comment]
> @sobitneupane Thanks for giving the instructions a test! Can you try these links?

No luck. Redirected to https://www.expensify.com/admin_policies

**Comment by Santhosh-Sellavel** [comment]
@conorpendergrast 
santhoshsellavel+hightraffic@gmail.com

**Comment by conorpendergrast** [comment]
@sobitneupane Ok, DAMMIT this change might need to be held until we "fix" multi-admin support in New Expensify. I was able to do this via our supportal tool, and I'll re-test with a "real" account.

**Comment by conorpendergrast** [comment]
Alright, so @twisterdotcom has created [this magic form](https://docs.google.com/forms/d/e/1FAIpQLScpiS0Mo-HA5xHPsvDow79yTsMBgF0wjuqc0K37lTK5fheB8Q/viewform) which will allow people to self-service this. That means that I can roll this back and remove everyone as policy admins, and update the instructions to point everyone to that form. Thank you Ted!

**Comment by Santhosh-Sellavel** [comment]
@conorpendergrast What should one do if the remove their account from high traffic?

**Comment by conorpendergrast** [comment]
I think we can probably do the same form for that too. In the meantime, what email address do you want removed?

**Comment by Santhosh-Sellavel** [comment]
santhoshsellavel@gmail.com

**Comment by conorpendergrast** [comment]
@Santhosh-Sellavel Done!

**Comment by conorpendergrast** [comment]
ok, thanks to the genius of @twisterdotcom, and the magic of google forms, zapier and our API, I present to you the following forms: 

1. [Make an account high-traffic](https://docs.google.com/forms/d/e/1FAIpQLScpiS0Mo-HA5xHPsvDow79yTsMBgF0wjuqc0K37lTK5fheB8Q/viewform)
2. [Remove a high-traffic account](https://docs.google.com/forms/d/e/1FAIpQLSd9_FDav83pnhhtu1KGAKIpf2yttQ_0Bvq1b9nuFM1-wbL11Q/viewform)

I've put in a PR to update documentation so that anyone (contributor, C+ or employee) can add and remove high-traffic accounts using those forms.

Next, I'll set everyone as not policy admins (just normal users) to clean that up too
