### ISSUE TITLE
[HOLD for payment 2023-08-14] [HOLD for payment 2023-08-08] [HOLD for payment 2023-08-03] [$1000] Polish admins-only policy room feature

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#21456]
## Background
We recently added a configurable setting to all default and user-created policy rooms, available to admins only, that allows admins to define who can post in that room: All members or Admins only. This enables admins to "control the conversation" in rooms that have large membership, or for whatever other reason should be lower-noise.

While the bulk of the work is complete, there's some remaining polish to be done on the FE.

## Tasks
- [ ] Add the "Who can post" setting to the ["New Room" form](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceNewRoomPage.js)
* The default form value should be `all`
* Send the `writeCapability` value when calling the `AddWorkspaceRoom` endpoint
* Ensure the value is included in the optimisticData (to support offline creation)
* Note: BE PRs supporting the `writeCapability` value in the `AddWorkspaceRoom` endpoint aren't live yet, but don't need to block work here
- [ ] Filter out admin-only rooms for members in the "Share somewhere" selector of the "Assign task" action (accessible via the FAB menu) - so that members cannot share a task to the room
- [ ] Reduce the padding between the last message and the bottom of the page when the composer isn't present (e.g. for the "member" view in an admin-only room)
- [ ] Update the room description to be `Use ${roomName} to hear about important announcements related to ${workspaceName}` for admin-only rooms
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ddadecb1f0a54b9</li>
        <li>Upwork Job ID: 1675048364496478208</li>
        <li>Last Price Increase: 2023-07-01</li>
    </ul>
</details>

**Comment by amyevans** [comment]
Internal issue for reference: https://github.com/Expensify/Expensify/issues/282865

I shared [in Slack](https://expensify.slack.com/archives/C03UK30EA1Z/p1687553033000009) to see if a Callstack team member has capacity for this.

**Comment by jliexpensify** [comment]
LMK if you need any Upworks stuff sorted!

**Comment by rezkiy37** [comment]
Hi, I'm Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by rezkiy37** [comment]
@amyevans Hi!
Is it possible to add my Expensify accounts to the white list of **Create Policy Room**?

<img width="675" alt="Screenshot 2023-06-26 at 17 07 42" src="https://github.com/Expensify/App/assets/57314631/bd6ea8bb-2709-4f76-b793-8edb41b1fe94">

**Comment by amyevans** [comment]
Done

**Comment by amyevans** [comment]
> `Collaboration among ${workspaceName} admins starts here! 🎉 Use ${roomName} to chat about topics such as workspace configurations and more.`

This is the copy for the `#admins` room, and the `#admins` room is something different - it is one of 2 rooms created by default when you create a new workspace aka policy (`#announce` being the other default room). The purpose of the `#admins` room is for collaboration between admins. Users who are members of the policy (but not admins of the policy) are not in the `#admins` room.

Then we have this feature we're working on here, which is any room that is restricted to only admins posting (but plenty of non-admins are in the room). Check out the screen recordings/code in https://github.com/Expensify/App/pull/19094 for more context. So we'll want to insert a new condition here-ish:
https://github.com/Expensify/App/blob/5c6b751601c8bf71d9cc42dd12c2f63c0c160a35/src/libs/ReportUtils.js#L571

that checks if it's a room where only admins can post and then spits out `Use ${roomName} to hear about important announcements related to ${workspaceName}`.

Does that make sense?

**Comment by rezkiy37** [comment]
@amyevans Thank you for your [answer](https://github.com/Expensify/App/issues/21456#issuecomment-1609763072).
Just to clarify: 
1. The `#admins` room is the `policyAdmins` chat type.
2. `isAdminRoom` verifies it of `getRoomWelcomeMessage`.
https://github.com/Expensify/App/blob/5c6b751601c8bf71d9cc42dd12c2f63c0c160a35/src/libs/ReportUtils.js#L574-L576
3. `phrase1` should be `Use `. Because `${roomName}` should be presseble to navigate.
https://github.com/Expensify/App/blob/5c6b751601c8bf71d9cc42dd12c2f63c0c160a35/src/components/ReportWelcomeText.js#L83-L94
4. `phrase2` should be ` to hear about important announcements related to ${workspaceName}`.

Correct me if I am wrong 🙂

**Comment by amyevans** [comment]
> 1. The `#admins` room is the `policyAdmins` chat type.

Yep! (But again, that isn't the room we're talking about in this feature at all.)

> 2. `isAdminRoom` verifies it of `getRoomWelcomeMessage`.
https://github.com/Expensify/App/blob/5c6b751601c8bf71d9cc42dd12c2f63c0c160a35/src/libs/ReportUtils.js#L574-L576

This doesn't directly answer your question, but more to point of what to do here, we'll want to create a new helper function:
```js
function isAdminsOnlyPostingRoom(report) {
    const capability = lodashGet(report, 'writeCapability', CONST.REPORT.WRITE_CAPABILITIES.ALL) || CONST.REPORT.WRITE_CAPABILITIES.ALL;
    return capability === CONST.REPORT.WRITE_CAPABILITIES.ADMINS;
}
```

and use that function in a _new_ condition in this logic:
```js
} else if (isAdminsOnlyPostingRoom(report)) {
...
}
```

> 3. `phrase1` should be `Use `. Because `${roomName}` should be presseble to navigate.
https://github.com/Expensify/App/blob/5c6b751601c8bf71d9cc42dd12c2f63c0c160a35/src/components/ReportWelcomeText.js#L83-L94
> 4. `phrase2` should be ` to hear about important announcements related to ${workspaceName}`.

Good point about _why_ we separate out the phrases. That looks correct, thanks!

**Comment by rezkiy37** [comment]
@amyevans Got it. Thank you!

**Comment by rezkiy37** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
This is a feature issue. It has 4 tasks. Anyway, it resolves some user problems too:

1. Provides new functionality - "**Who can post**" setting during creating a new room. 
2. Restricts to share "**Assign task**" in admin-only rooms if a current user is not admin itself.
3. Reduces the spacing between the last message and the bottom of the page when **Composer** isn't present.
4. Updates message the welcome message for admin-only rooms.

### What is the root cause of that problem?
1. Add the "**Who can post**" setting to the ["**New Room**"](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceNewRoomPage.js) form.
    - The default form value should be **all**.
    - Send the `writeCapability` value when calling the **AddWorkspaceRoom** endpoint.
    - Ensure the value is included in the `optimisticData` (to support offline creation).
    - **Note**: BE PRs supporting the `writeCapability` value in the **AddWorkspaceRoom** endpoint aren't live yet, but don't need to block work here.
2. Filter out admin-only rooms for members in the "**Share somewhere**" selector of the "**Assign task**" action (accessible via the **FAB** menu) - so that members cannot share a task to the room.
3. Reduce the padding between the last message and the bottom of the page when **Composer** isn't present _(e.g. for the "member" view in an admin-only room)._
4. Update the room description to be `Use ${roomName} to hear about important announcements related to ${workspaceName}` for admin-only rooms.

### What changes do you think we should make in order to solve the problem?
1. Add the “**Who can post**” setting to the “**New Room**” form.
  a. **[WorkspaceNewRoomPage](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceNewRoomPage.js)** component.
    1. Add `writeCapabilityOptions` of **render** method. The array is mapped of all write capabilities. The map returns the array of objects: **value** (_capability itself_) and **label** (_reuse already existed strings_).
    ```javascript
    const writeCapabilityOptions = _.map(CONST.REPORT.WRITE_CAPABILITIES, (value) => ({
        value,
        label: this.props.translate(`writeCapabilityPage.writeCapability.${value}`),
    }));
    ``` 
    2. Add one more **Picker** after **RoomNameInput**, because I consider to follow the same order of pickers as in **ReportSettingsPage**. It should reuse already existed title (_Who can post_). The default value should be - `CONST.REPORT.WRITE_CAPABILITIES.ALL` (_all_). It takes `items` (_values_) from `writeCapabilityOptions`.
    3. Change bottom spacing of workspaces **Picker Wrapper (_View_)** from `mb5` to `mb2` to keep consistency between them.
    4. Apply destructuring assignment of values of **submit** method. Because, the method always uses chains to get each value.
    5. Take and pass `writeCapability` to **Report.addPolicyReport(…, writeCapability)** in the **submit** method.
2. Filter out admin-only rooms for members in the “**Share somewhere**” selector of the “**Assign task**” action (_accessible via the **FAB** menu_) - so that members cannot share a task to the room.
  a. [**shouldReportBeInOptionList**](https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/libs/ReportUtils.js#L1936) function of **ReportUtils.js**.
    1. Takes one more argument - `isShareDestination` (the default value - `false`). Since, this function is being used across other places and other list of reports, I should apply changes only for the “**Share somewhere**” selector.
    2. Add one more condition before the final return. When `isShareDestination` is `true` and `writeCapability` equals admin-only, the app should verify that a current user can post to a report. Find `linkedWorkspace` by `policy.id` and `report.policyID`. Then, check a role of the current user for this workspace. The role should be equal admin to allow the user to share to this report, otherwise this report is out of the list.
    ```javascript
    if (isShareDestination && report.writeCapability === CONST.REPORT.WRITE_CAPABILITIES.ADMINS) {
        const linkedWorkspace = _.find(policies, (policy) => policy && policy.id === report.policyID);
        const shouldAllowShare = lodashGet(linkedWorkspace, 'role', '') === CONST.POLICY.ROLE.ADMIN;

        return shouldAllowShare;
    }
     ``` 

   b. [**getOptions**](https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/libs/OptionsListUtils.js#L581) function of **OptionsListUtils.js**.
    1. Takes one more value of `options` object. It is `isShareDestination` (the default value - `false`). Since, this function is being used across other places and other list of reports, I should apply changes only for the “**Share somewhere**” selector.
    2. Passes the value to **ReportUtils.shouldReportBeInOptionList(…, isShareDestination)**.
    
   c. [**getShareDestinationOptions**](https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/libs/OptionsListUtils.js#L947) function of **OptionsListUtils.js**.
    1. Passes `isShareDestination` to **getOptions(..., {..., isShareDestination: true})**.
    
3. Reduce the padding between the last message and the bottom of the page when **Composer** isn’t present _(e.g. for the “member” view in an admin-only room)_.
  a. Add `pb0` (_paddingBottom: 0_) to [spacing.js](https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/styles/utilities/spacing.js). 
  b. Apply `styles.pb0` to **View** with `styles.p5` of [**ReportActionItemCreated**](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItemCreated.js), when no other messages and **Composer** is hidden.
    1. To understand that there is no messages yet, I would use `lastMessageText` of `report` and compare with an empty string.
    2. To understand that **Composer** is hidden, I would apply the same conditions as inside [**ReportFooter**](https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/pages/home/report/ReportFooter.js#L62-L73).
    ```javascript
    const errors = lodashGet(props.report, 'errorFields.addWorkspaceRoom') || lodashGet(props.report, 'errorFields.createChat');
    const isArchivedRoom = ReportUtils.isArchivedRoom(props.report);
    const hideComposer = ReportUtils.shouldHideComposer(props.report, errors);
    const shouldOmitBottomSpace = props.report.lastMessageText === '' && (isArchivedRoom || hideComposer);
    ```
    ```javascript
    <View
        accessibilityLabel={props.translate('accessibilityHints.chatWelcomeMessage')}
        // Apply the condition here
        style={[styles.p5, shouldOmitBottomSpace && styles.pb0, StyleUtils.getReportWelcomeTopMarginStyle(props.isSmallScreenWidth)]}
    >
    ```

4. Update the room description to be `Use ${roomName} to hear about important announcements related to ${workspaceName}` for admin-only rooms.
  a. [**reportActionsView**](https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/languages/en.js#L283) of **en.js**.
    1. Add `beginningOfChatHistoryAdminOnlyPostingRoomPartOne` - _"Use "_.
    2. Add `beginningOfChatHistoryAdminOnlyPostingRoomPartTwo` like a method to pass `workspaceName` - _" to hear about important announcements related to ${workspaceName}"_.
  b. [**ReportUtils.js**](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js)
    1. Create a function - **isAdminsOnlyPostingRoom**. It takes report and gets writeCapability or use default value - all. It compares `writeCapability` with admins to verify that only admins can post here.
    ```javascript
    function isAdminsOnlyPostingRoom(report) {
        const writeCapability = lodashGet(report, 'writeCapability', CONST.REPORT.WRITE_CAPABILITIES.ALL);
    
        return writeCapability === CONST.REPORT.WRITE_CAPABILITIES.ADMINS;
    }
    ```
    2. Add one more **else if** to [**getRoomWelcomeMessage**](https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/libs/ReportUtils.js#L570). It should use the new **isAdminsOnlyPostingRoom** function. When it returns `true`, it sets the first string (`beginningOfChatHistoryAdminOnlyPostingRoomPartOne`) to `phrase1` and the second string (`beginningOfChatHistoryAdminOnlyPostingRoomPartTwo`) to `phrase2`.

### What alternative solutions did you explore?
3. Reduce the padding between the last message and the bottom of the page when **Composer** isn’t present _(e.g. for the “member” view in an admin-only room)_.
  a. Remove [wrapper](https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/pages/home/report/ReportFooter.js#L70) of **OfflineIndicator** of **ReportFooter**. Remove [**styles.offlineIndicatorRow**](https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/styles/styles.js#L806), because no wrapper anymore. The wrapper has a static height and is being rendered always on large screens. No sense to keep this empty wrapper when users are online.

**Comment by rezkiy37** [comment]
### The 1st task example:

https://github.com/Expensify/App/assets/57314631/d71abc12-d781-452a-93f5-cc4ef045cdbf

<img width="890" alt="1 1" src="https://github.com/Expensify/App/assets/57314631/f6f32200-dc31-48b0-9f7d-8d3534b82cf6">

<img width="890" alt="1 2" src="https://github.com/Expensify/App/assets/57314631/655f0520-9ed4-4b7d-90b0-7388a24181f3">

**Comment by rezkiy37** [comment]
### The 2nd task example:
https://github.com/Expensify/App/assets/57314631/23833ab3-8e67-417c-bd0d-642f7a5e5c4f

**Comment by rezkiy37** [comment]
### The 3rd task example:
<img width="970" alt="3" src="https://github.com/Expensify/App/assets/57314631/956cd6c8-1537-42ab-b05e-b760aa97fe53">
<img width="970" alt="3 1" src="https://github.com/Expensify/App/assets/57314631/4c75f3bb-0649-46ec-b9ce-280d27cc8548">

**Comment by rezkiy37** [comment]
### The 4th task example:
<img width="1362" alt="4" src="https://github.com/Expensify/App/assets/57314631/e44e07e7-bab0-44c5-9886-f8b534dfac02">

**Comment by amyevans** [comment]
Thanks for writing that out as a detailed proposal! I haven't had the opportunity to review it yet and will eventually want a C+ to help with the PR review, so going to pull 1 in now for proposal review as well.

**Comment by mananjadhav** [comment]
Thanks for the detailed proposal @rezkiy37. Took sometime to go through all the points. Your [proposal](https://github.com/Expensify/App/issues/21456#issuecomment-1612772642) looks good. 

cc - @amyevans 

🎀 👀 🎀 C+ reviewed.

**Comment by rezkiy37** [comment]
@amyevans Hi!
Could you please provide me translations for `Use ${roomName} to hear about important announcements related to ${workspaceName}` in Spanish.

**Comment by amyevans** [comment]
`Utiliza ${roomName} para enterarte de anuncios importantes relacionados con ${workspaceName}.`

**Comment by amyevans** [comment]
Heads up I'm OOO Mon/Tue next week! Feel free to open a PR and have @mananjadhav review it though, and I will get back to this Wed.

**Comment by jliexpensify** [comment]
Invite sent to @mananjadhav

**Comment by shawnborton** [comment]
Not overdue, still working through this

**Comment by rezkiy37** [comment]
#21950 is ready for review 🙂

**Comment by mananjadhav** [comment]
PR review is done, left with 2 comments.

**Comment by Pujan92** [comment]
Seems causing a regression https://github.com/Expensify/App/issues/23638

**Comment by rezkiy37** [comment]
Hi, @amyevans, @shawnborton and @mananjadhav!
Unfortunately, 2 regressions have occurred after the the merging: https://github.com/Expensify/App/issues/23638 and https://github.com/Expensify/App/issues/23646. I am going to fix the both of them.

**Comment by mananjadhav** [comment]
Yes @rezkiy37. Thanks for that. I'll be available over the weekend too to fix these regressions.

**Comment by amyevans** [comment]
@rezkiy37 thanks, I assigned us all to both! I'm around to review the PRs as well.

**Comment by rezkiy37** [comment]
@amyevans, @mananjadhav, I've opened a PR for review - https://github.com/Expensify/App/pull/23815.

**Comment by Pujan92** [comment]
@rezkiy37 I think this issue https://github.com/Expensify/App/issues/23818 might be a regression from this PR

**Comment by rezkiy37** [comment]
Hi, @amyevans and @mananjadhav!
Unfortunately, 1 regressions have occurred after the the merging: https://github.com/Expensify/App/issues/23818. I am going to fix it asap.

**Comment by rezkiy37** [comment]
@amyevans, @mananjadhav, I've opened a PR for review - https://github.com/Expensify/App/pull/23919.

**Comment by jliexpensify** [comment]
@amyevans can you check this Payment summary?

- Contributor: @rezkiy37 $500 (due to regression) - Callstack, to invoice serparately
- C+: @mananjadhav $500  (due to regression) - New.Dot payment

No Upworks job created

**Comment by mananjadhav** [comment]
@jliexpensify The payout for me will be 125$, as there are two regressions.

**Comment by mananjadhav** [comment]
There won't be any offending PR because this was more of a feature request. About regressions steps, @amyevans Can you confirm if these are added during the feature design?

**Comment by amyevans** [comment]
> About regressions steps, @amyevans Can you confirm if these are added during the feature design?

Good reminder, I haven't put in the request for new regression tests yet but I will Monday!

**Comment by jliexpensify** [comment]
[Payment summary here](https://github.com/Expensify/App/issues/21456#issuecomment-1659467256) (to save me scrolling up)

**Comment by amyevans** [comment]
Regression tests GH created: https://github.com/Expensify/Expensify/issues/308182

I think we're set to proceed with payment today!

**Comment by jliexpensify** [comment]
Cool, so there isn't anything to pay in Upworks - @mananjadhav is getting paid in New.Dot and @rezkiy37 is invoicing us.

@amyevans are you happy to close this one, if everything is done?

**Comment by amyevans** [comment]
Sure, I wasn't sure if we had to keep it open until the payment was made in NewDot. Closing now!
