### ISSUE TITLE
Create the default map view with ExpensiMap

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22703]
Please follow the [plan in the design doc](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.fbpvqcxfpb9s).

### TODO List

- [x] Explore Mapbox's web and react native API
- [x] Read the project doc again to check what API is needed in `App`
- [x] Figure out how to merge two platforms' API

**Comment by luacmartins** [comment]
Still on hold

**Comment by luacmartins** [comment]
On hold

**Comment by luacmartins** [comment]
Still on hold

**Comment by luacmartins** [comment]
Still on hold

**Comment by luacmartins** [comment]
On hold

**Comment by luacmartins** [comment]
@hayata-suenaga reached out and is interested in working on this issue. So I'll pass it over to him.

**Comment by hayata-suenaga** [comment]
I texted with @luacmartins and expressed my interest in taking over this issue. Assigning myself

**Comment by hayata-suenaga** [comment]
A small todo list in OP ⬆️

**Comment by neil-marcellini** [comment]
Cool thanks for picking it up! I would suggest following the plan in the doc exactly as it's written and let us know if you run into any problems along the way. It should all work smoothly and you won't have to spend quite as much time reading up on the libraries, etc.

**Comment by hayata-suenaga** [comment]
ah I meant more like "reading documentation linked in the design doc"

you already did good research so I agree this won't take time (more like following the design doc)

**Comment by hayata-suenaga** [comment]
I keep working on this today

**Comment by hayata-suenaga** [comment]
working on it

**Comment by hayata-suenaga** [comment]
this will be closed when [this PR](https://github.com/Expensify/App/pull/24306) is merged and deployed

**Comment by hayata-suenaga** [comment]
I believe we can close this issue now 🤔
