### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] Fix styling of Google Sign In button on Safari

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#25864]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps
* Open the main page on desktop Safari, with Apple and Google sign in links

## Expected Result:
Describe what you think should've happened
* Google button should appear in full, and stay static once loaded

## Actual Result:
Describe what actually happened
* The G part of the button looks fine, but right after it loads the white background shifts one pixel right and is cut off by that amount.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Yes

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** https://expensify.slack.com/archives/C01GTK53T8Q/p1692805800476329?thread_ts=1692802374.824749&cid=C01GTK53T8Q

https://github.com/Expensify/App/assets/5487802/178f0126-d890-47c0-949c-5cd91376f14c

**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1692805800476329?thread_ts=1692802374.824749&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131c050705af6ac9f</li>
        <li>Upwork Job ID: 1695197552733020160</li>
        <li>Last Price Increase: 2023-08-25</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 26508718</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Google sign in button cuts from right in safari

### What is the root cause of that problem?
Seems after adding overflow hidden started the problem. When parent width and overflow hidden gets given it seems to create the problem for safari.
https://stackoverflow.com/questions/75306089/safari-when-using-border-radius-and-overflow-hidden-to-parent-and-the-child-th

### What changes do you think we should make in order to solve the problem?
We can use `styles.willChangeTransform(will-change: transform)` for the layout glitch for the safari as suggested in the comment and I think we are already using the same at other places.

OR

We can increase the width of the container and apply some padding so it cut part can be visible on the padding area.

<img width="1166" alt="Screenshot 2023-08-24 at 23 56 15" src="https://github.com/Expensify/App/assets/14358475/d0bcb183-4a25-47f7-afbb-2331ebfef785">

**Comment by greg-schroeder** [comment]
Setting this to $250 as a minor adjustment

**Comment by burczu** [comment]
not overdue - reviewing / waiting for other proposals

**Comment by burczu** [comment]
@Pujan92 Could you please be more specific in your proposal on how you want to use the `styles.willChangeTransform` styles? Thanks

**Comment by Pujan92** [comment]
@burczu updated the proposal.

**Comment by jopaleti** [comment]
Hello there, can I be assigned to solve this bug?
I will provide solution to it.

**Comment by burczu** [comment]
@jopaleti Please read the [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and just post your proposal here using the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md).

**Comment by burczu** [comment]
I've reviewed the @Pujan92's [proposal](https://github.com/Expensify/App/issues/25864#issuecomment-1692207997) and I think we can go with it - it fixes the issue.

🎀 👀 🎀 C+ reviewed

**Comment by arosiclair** [comment]
There's two proposed solutions there. Which one do we think is best? @burczu @Pujan92. 

Can you explain how `will-change: transform` fixes the issue? Is there actually a `transform` being applied to that container?

**Comment by burczu** [comment]
@arosiclair I was referring to the first solution from @Pujan92's proposal

**Comment by greg-schroeder** [comment]
Thoughts on the above @arosiclair?

**Comment by greg-schroeder** [comment]
Bump @arosiclair <3

**Comment by arosiclair** [comment]
@Pujan92 please add comments explaining why `will-change: transform` is needed

**Comment by burczu** [comment]
Just to inform: I'll be OOO on Thursday and Friday (7-8 September).

**Comment by Pujan92** [comment]
@burczu [PR](https://github.com/Expensify/App/pull/26874) is ready for review!

**Comment by greg-schroeder** [comment]
Sorry for the delay, I've been out with an illness. Processing this today.

**Comment by greg-schroeder** [comment]
@burczu does not require payment (Contractor)
@Pujan92 requires payment [offer](https://www.upwork.com/nx/wm/offer/26508718) (Contributor)

**Comment by greg-schroeder** [comment]
Paid. @burczu can you take care of the [checklist](https://github.com/Expensify/App/issues/25864#issuecomment-1719178727)?

**Comment by Pujan92** [comment]
@greg-schroeder is this eligible for urgency bonus as @burczu wasn't available for 2 days based on this [comment](https://github.com/Expensify/App/issues/25864#issuecomment-1708324739)?

**Comment by burczu** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: It's not a regression - it was just hard to be noticed during initial testing, I guess.
* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: n/a
* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: n/a
* [x]  [@burczu] Determine if we should create a regression test for this bug.
* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@greg-schroeder] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:
