### ISSUE TITLE
[SITU - WAITING ON CHECKLIST] [$500] [Distance] - The requester avatar and name are not shown for a while after request is created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26722]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26580
## Action Performed:
1. Go to staging.new.expensify.com
2. Open a workspace chat
3. Send a Distance IOU to the workspace chat

## Expected Result:
The requester avatar and name are shown as soon as the request is created

## Actual Result:
The requester avatar and name are not shown for a while

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/84ffd207-4a25-42c0-9f21-7e6f114f7f3e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0130c70f29cf0ac46d</li>
        <li>Upwork Job ID: 1701423694582550528</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26698696</li>
<li>StevenKKC | Contributor | 26698698</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
@hayata-suenaga and @situchan , from the comment above:

> Issue found when executing PR https://github.com/Expensify/App/pull/26580

**Comment by StevenKKC** [comment]
## Proposal

### Please state again the problem we are trying to solve in this issue.
Distance - The requester avatar and name are not shown for a while after request is created.

### What is the cause of this issue?
The root cause is that we does not pass correct `payeeAccountID` and `payeeEmail` to `IOU.getMoneyRequestInformation`.
https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/actions/IOU.js#L512-L524
Because we pass `payeeAccountID` and `payeeEmail` with `null`, `iouReport`'s `managerID` is set to `null`, and then `reportPreviewAction`'s `actorAccountID` is set to `0`.
https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/ReportUtils.js#L1935
https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/ReportUtils.js#L2207
So the avatar and name are not shown until `OpenReport` returns correct report data.
### What changes do you think we should make to solve the problem?
We should set correct `payeeAccountID` and `payeeEmail` in `IOU.createDistanceRequest`
```js
const { ... } = getMoneyRequestInformation(
        ...
        userAccountID,
        currentUserEmail,
        ...
    );
```
### What alternative solutions have you investigated? (Optional)
None.

**Comment by hayata-suenaga** [comment]
@StevenKKC where is `getMoneyRequestInformation` invoked?

**Comment by StevenKKC** [comment]
@hayata-suenaga `getMoneyRequestInformation` is invoked in `IOU.createDistanceRequest`.
https://github.com/Expensify/App/blob/cbda2b03824d9b125ec6ab19e87ff533bea1b22f/src/libs/actions/IOU.js#L511-L524

**Comment by jliexpensify** [comment]
Not overdue, but @hayata-suenaga did you want to review the above?

**Comment by hayata-suenaga** [comment]
I completely missed this thank you for pinging me 🙇 

I somehow thought this one has already been fixed but it's still happening on production.

https://github.com/Expensify/App/assets/98560306/f1a9c9c9-bb5a-41a2-b26f-c5d95e8faca7

**Comment by hayata-suenaga** [comment]
I gonna make this issue external

**Comment by tgolen** [comment]
@situchan I think this is waiting for you to evaluate the proposal? It looks like a good proposal to me.

**Comment by situchan** [comment]
@StevenKKC can you please share demo video after applying your solution?

**Comment by StevenKKC** [comment]
@situchan This is a demo video.

[demo.webm](https://github.com/Expensify/App/assets/131836113/bc0598e2-72ea-41bf-8b2d-a6730f7938f7)

**Comment by situchan** [comment]
@StevenKKC thanks. [Proposal](https://github.com/Expensify/App/issues/26722#issuecomment-1706046278) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by StevenKKC** [comment]
@situchan PR https://github.com/Expensify/App/pull/27581 is ready for review.

**Comment by jliexpensify** [comment]
@hayata-suenaga just confirming: was this an actual regression (the comment in the body states it's related to https://github.com/Expensify/App/issues/26567)? If so, then @StevenKKC should be paid the urgency bonus ($750) and @situchan shouldn't be handled payment in this issue as it's a regression, is this correct?

**Comment by situchan** [comment]
This is not regression from https://github.com/Expensify/App/issues/26567 but already existed before.
QA team just caught this bug while testing distance request flow on that PR.

**Comment by jliexpensify** [comment]
Thanks, got it! So then (assuming there are no regressions from this PR) - this should be the payment summary:

- Contributor: @StevenKKC $500 + $250
- C+: @situchan $500 + $250

[Upwork job](https://www.upwork.com/jobs/~0130c70f29cf0ac46d)

**Comment by tgolen** [comment]
@jliexpensify Looks like this issue is waiting for you.

**Comment by jliexpensify** [comment]
Thanks for the bump Tim! Yep, was OOO and a whole bunch of issues hot the payment date. Sorthing this out now.

**Comment by jliexpensify** [comment]
@situchan - can you complete the checklist please?

**Comment by jliexpensify** [comment]
Paid and job closed. @situchan just waiting on you to complete the checklist, cheers!

**Comment by tgolen** [comment]
bump @situchan to complete the checklist

**Comment by StevenKKC** [comment]
@jliexpensify I am afraid to let you know that My Upwork account is suspended permanently so I couldn't withdraw money. I would be really appreciate it if you refund money and send to my friend's account.

**Comment by jliexpensify** [comment]
@StevenKKC I'm sorry, but we cannot pay out your funds to another account, as this is a break of Upworks T+C's and could cause Expensify to be suspended. Can you share some additional context/details on what's happening with your situation, and I'll bring this up with our team? Feel free to DM me if you like.

**Comment by jliexpensify** [comment]
@StevenKKC our team has reached out to Upworks specifically regarding this issue and unfortunately, there is nothing that can be done from our side - we have to pay into your Upworks account. The advice we have been given is to ask you to continue working with Upworks to get your account restored. Thanks for your understanding!

@situchan can you also complete the checklist please?

**Comment by StevenKKC** [comment]
Yes, thank you for your consideration. I received the terrible news from Upwork support that my account has been permanently disabled. In this case what should I do?

**Comment by jliexpensify** [comment]
@StevenKKC this is something you'll need to talk to Upworks about. As mentioned before, we're not able to pay via another means, sorry about that!

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/25707
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/25707/files#r1349870552
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This was caught by Applause team so I don't think we need more regression test.

**Comment by jliexpensify** [comment]
@StevenKKC an update from our team: I'm going to close this issue for now. Once you've resolved things with Upworks, please tag me and I will re-open and pay you.
