### ISSUE TITLE
[WAITING ON CHECKLIST] [$500] Web - Emoji suggestions is not displayed between "~~" & "__"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27602]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Type `**` then `:jo` in between `**`
3. Observe emoji suggestions is displayed
4. Type `__` or `~~` then `:jo` in between `__` or `~~`
5. Observe emoji suggestions is not displayed

## Expected Result:
Emoji suggestions should be displayed.

## Actual Result:
Emoji suggestions is not displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b549fb94-b777-4a91-82a8-5dde6785c126

https://github.com/Expensify/App/assets/93399543/8283f0fb-2073-4f20-a360-965fe3ad3715

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694829781444709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167ad7e94902ca806</li>
        <li>Upwork Job ID: 1703139355938205696</li>
        <li>Last Price Increase: 2023-09-16</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @Krishna2323
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694829781444709

### Proposal

### Please re-state the problem that we are trying to solve in this issue.

Emoji suggestions is not displayed between "~~" & "__"

### What is the root cause of that problem?

The function `isEmojiCode` splits the string based on the regex `SPECIAL_CHAR_OR_EMOJI`. This regex is designed to split the string on various special characters and emojis, but it didn't include the characters _ and ~.

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/home/report/ReportActionCompose/SuggestionEmoji.js#L176

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/CONST.ts#L1223-L1225

### What changes do you think we should make in order to solve the problem?

By modifying the SPECIAL_CHAR_OR_EMOJI regex to include ~ and _, the function correctly splits the string, and the check for the emoji code works as expected.

*_Updated Regex:_*
/[\n\s,/?"{}[\]()&^%\\;`_~$=#<>!*\p{Extended_Pictographic}\u200d\u{1f1e6}-\u{1f1ff}\u{1f3fb}-\u{1f3ff}\u{e0020}-\u{e007f}\u20E3\uFE0F]|[#*0-9]\uFE0F?\u20E3/gu

We can add "~_" anywhere in between []

### Result:

**Comment by jliexpensify** [comment]
Yep, so if it's just `__` and `~~` that exhibit this behaviour, that seems odd and inconsistent! So we should probably fix it - I was just pointing out that you need to add a space to generate the emoji picker.

**Comment by burczu** [comment]
I've checked [the proposal](https://github.com/Expensify/App/issues/27602#issuecomment-1722306822) from @Krishna2323 (posted by @kbecciv) and it fixes the issue so I think we can proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by jliexpensify** [comment]
Bump @madmax330 for Contributor approval

**Comment by jliexpensify** [comment]
Hi @Krishna2323 - can you apply for the job here? https://www.upwork.com/jobs/~0167ad7e94902ca806 

Thanks!

**Comment by jliexpensify** [comment]
No need, I'll do a payment summary before payment for your final review, and will combine the 2 payments into 1.

**Comment by jliexpensify** [comment]
Oh, weird! I'll look into it now.

**Comment by jliexpensify** [comment]
Payment Summary:

PR was merged in 4 days, so no bonuses

- Reporter / Contributor: @Krishna2323 $50 + $500
- C+: @burczu $500 (I think you invoice us?)

[Upworks job](https://www.upwork.com/jobs/~0167ad7e94902ca806)

The PR hasn't been deployed yet so we don't have a payment date.

**Comment by jliexpensify** [comment]
Cool, easy fix - thanks for pointing it out

**Comment by burczu** [comment]
> Payment Summary:
> 
> PR was merged in 2 business days
> 
> * Reporter / Contributor: @Krishna2323 $50 + $500 + $250
> * C+: @burczu $500 + $250 (I think you invoice us?)
> 
> [Upworks job](https://www.upwork.com/jobs/~0167ad7e94902ca806)
> 
> The PR hasn't been deployed yet so we don't have a payment date.

@jliexpensify I'm not eligible for payment because I'm contractor from Callstack.

**Comment by jliexpensify** [comment]
Oh, got it - thanks! I'll remove you (I thought you Invoiced us though?)

**Comment by jliexpensify** [comment]
[Payment summary](https://github.com/Expensify/App/issues/27602#issuecomment-1738351058) 

@burczu - bump to complete the checklist!

**Comment by jliexpensify** [comment]
Paid and job closed! @burczu please complete the checklist!

**Comment by jliexpensify** [comment]
Bump @burczu please complete the checklist!

**Comment by jliexpensify** [comment]
Bump @burczu to complete the checklist please!

**Comment by burczu** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: No regression - it was done this way from the very beginning.
* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: n/a
* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: n/a
* [x]  [@burczu] Determine if we should create a regression test for this bug.
* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@jliexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by jliexpensify** [comment]
Ok, no regression test needed? Closing!
