### ISSUE TITLE
[HOLD for C+ payment and bugzero checklist] [$500] Workspace - App crashes on member's side when deleting a workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28336]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open two new accounts
2. Create a workspace on account A
3. Invite account B as a member on account A's workspace
4. Go to announce room on account B
5. Send a message
6. Hover over the last sent message and click on reply in thread
7. Send a message inside the thread
8. Go to account A and click on the workspace settings and delete the workspace
9. Observe account B

## Expected Result:
App should not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.74-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/2cc0ffd5-e39f-4045-81f4-2c553fce9ada

https://github.com/Expensify/App/assets/115492554/87fead10-e971-427c-8737-be1f4063342e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695397800777089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0198d8205c8f8f5131</li>
        <li>Upwork Job ID: 1707090926479659008</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 26964208</li>
<li>Nathan-Mulugeta | Reporter | 26964210</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
App crashes on other User B side when a User A deletes a workspace.
### What is the root cause of that problem?
When User A deletes the workspace, the report of rooms of the workspace are removed so in this here
https://github.com/Expensify/App/blob/b57f6d2a38ca736435bacce833c06ede55c987c6/src/libs/ReportUtils.js#L854-L855
`parentReport` is undefined so this here
https://github.com/Expensify/App/blob/b57f6d2a38ca736435bacce833c06ede55c987c6/src/libs/ReportUtils.js#L658-L660
fails because `report` is undefined.
### What changes do you think we should make in order to solve the problem?
Add a check for report in the above function
```js
return report && report.participantAccountIDs && report.participantAccountIDs.length === 1;
```

### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment]
@allroundexperts Updated the [proposal](https://github.com/Expensify/App/issues/28336#issuecomment-1737838664) with video.

**Comment by c3024** [comment]
PR ready for review @allroundexperts

**Comment by kadiealexander** [comment]
Payouts due:

- [x] Issue Reporter: $50 @Nathan-Mulugeta
- [x] Contributor: $500 + $250 bonus @c3024
- [ ] Contributor+: $500 + $250 bonus @allroundexperts

Eligible for 50% #urgency bonus? Yes

Upwork job is [here]().

**Comment by kadiealexander** [comment]
@allroundexperts please don't forget the checklist!

**Comment by JmillsExpensify** [comment]
$750 payment approved for @allroundexperts based on summary above.

**Comment by kadiealexander** [comment]
https://github.com/Expensify/Expensify/issues/330534
