### ISSUE TITLE
[HOLD for payment 2023-11-09] [HOLD for payment 2023-10-27] [TRACKING] HelpDot tidying + updates

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#28497]
### General Updates
- [ ] The `# headings` should be bigger IMO - can we update `#` headers so that they show bigger / like more obvious headings? - https://github.com/Expensify/App/issues/29481
<img width="872" alt="image" src="https://github.com/Expensify/App/assets/38016013/1204be97-a39a-4985-b2cb-ba5355ef4907">

### Category-specific Updates
- [ ] Create hub `Expensify Partner Program` (design team request for icon [here](https://github.com/Expensify/Expensify/issues/321344))
- [ ] Move `Expensify Card` hub and nest it under `Bank Accounts & Credit Cards`
- [ ] Update `Exports` to `Insights & Custom Reporting`
- [ ] Update `Policy & Domain Settings` to `Workspace & Domain Settings`

### Subcategory-specific Updates
- [ ] Delete the `Business Bank Accounts AUD file (the resource was incorrectly published under a newly created file (Add a Business Bank Account AUD) 
- [ ] Update file name of Add-a-Business-Bank-Account-(AUD).md to Business-Bank-Account-AUD.md
- [ ] Update file of [Deposit-Accounts-AUS.md](https://github.com/Expensify/App/blob/main/docs/articles/expensify-classic/bank-accounts-and-credit-cards/deposit-accounts/Deposit-Accounts-AUS.md) to Deposit-Accounts-AUD
- [ ] Delete the Your Expensify Account Manager file (that resource is merged into a general "support" article)
- [ ] Update `Personal Credit Cards` to `Personal Cards`

### Articles to write (non-technical)
- [x] How employees get the Expensify Card
- [x] How employees use the Expensify Card
- [ ] Report Details (under Expense and Report Features)

### Minor fixes to published resources (Maddy can submit a PR for these)
- [x] Change list in SS to bulleted list

### Bugs / Fixes
- [x] Tables in articles have a cluttered styling
- [x] Redirect old article links to new articles links
- [ ] Typing the name of an article in the search bar isn't pulling up the resource (example - [Scheduled Submit](https://help.expensify.com/articles/expensify-classic/policy-and-domain-settings/reports/Scheduled-Submit#gsc.tab=0))
<img width="1467" alt="image" src="https://github.com/Expensify/App/assets/38016013/a4a9f321-8d26-411d-8576-6c147867c584">

### Ideas for Improving Visual Design
- [x] Separate `Overview` `How to` `Deep Dive` `FAQ` sections by adding an alternating background or border to each header section. Something minor like a slightly different background color that alternates from header section to header section - https://github.com/Expensify/App/issues/29481
<img width="1385" alt="image" src="https://github.com/Expensify/App/assets/38016013/6657931b-f7c6-47a7-a9c6-1b4bc640e3d6">

**Comment by Talha345** [comment]
@maddylewis @rushatgabhane Hi, I found some bugs in the HD on production. Since you guys are still working on it, can I already report the bugs as well as the solutions?

I have fixed quite some issues on HD in the past, so if you need additional manpower, i would be happy to help!

**Comment by Talha345** [comment]
> there is a know bug about back button after deeplinking.
> 
> @Talha345 other than that yes please, could you please let us know the bugs

@rushatgabhane Sure, should i report here or in slack?

**Comment by Talha345** [comment]
@rushatgabhane Sure. Hope I will be compensated for valid bugs.

Steps to Reproduce:

1. Go to https://help.expensify.com/articles/new-expensify/getting-started/chat/Expensify-Chat-For-Conference-Attendees#gsc.tab=0
2. Click on any of the 3 links under Getting Started section.
3. Invalid redirect happens and 404 page is shown.

Video:


https://github.com/Expensify/App/assets/36226639/8e7dfc22-50ec-4c87-bb34-aa5b981bc805

**Comment by dubielzyk-expensify** [comment]
Uploading `svg` of new Category Hub icon for Partner Program
![simple-illustration__partner](https://github.com/Expensify/App/assets/145416827/ef7b87c4-2f29-4172-9d17-9d5ec51d1e6c)

**Comment by maddylewis** [comment]
still working / ongoing tracking issue

**Comment by maddylewis** [comment]
### Payments
- [ ] @rushatgabhane - C+ ($500)
- [ ] @Talha345 - reporting bonuses (3x = $150)

**Comment by maddylewis** [comment]
this is live - closing!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @rushatgabhane based on [this comment](https://github.com/Expensify/App/issues/28497#issuecomment-1782942345).
