### ISSUE TITLE
[Awaiting Checklist] [$500] Cursor freeze on paste emoji in edit message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29128]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696835638613239

## Action Performed:
1. Open the app
2. Open any report
3. Send any message
4. React to any other message with any emoji and right click on reaction
5. Copy emoji text
6. Edit message sent in step 3
7. Paste the emoji text few times and observe that cursor position freezes
## Expected Result:
App should not freeze cursor position on paste of emoji
## Actual Result:
App freezes cursor position on paste of emoji in edit message
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/e86751f7-dc81-4ef7-8f3b-3efb627b2d53

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/12097459-c3f0-4858-bfd5-395fbdc1df25

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/7bb06f25-1d7c-4f2a-8a4c-3e5ada4a10de

https://github.com/Expensify/App/assets/38435837/f339d30c-9336-4ba2-85c6-eaff93d294f0

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/d21f0e7f-6b96-4db3-824c-eb9e6f6b2272

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0157837cc3b2f27ed2</li>
        <li>Upwork Job ID: 1711488681499811840</li>
        <li>Last Price Increase: 2023-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27159501</li>
<li>Krishna2323 | Contributor | 27159503</li>
<li>dhanashree-sawant | Reporter | 27159505</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by jjcoffee** [comment]
@Krishna2323 Thanks for your proposal! The text is a bit dense, so I'd appreciate a bit more of a clear & concise RCA. I also would prefer if you broke down what changes you are making and where. Could you update your proposal with these changes?

**Comment by jjcoffee** [comment]
Thanks! @Krishna2323's [proposal](https://github.com/Expensify/App/issues/29128#issuecomment-1753948069) LGTM.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by twisterdotcom** [comment]
Bump on the checklist @jjcoffee.

**Comment by twisterdotcom** [comment]
Sorted.
