### ISSUE TITLE
[Awaiting checklist completion] [$500] No space after emoji or cursor displayed before emoji on android chrome and ios native

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29405]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1696939352410509

## Action Performed:
1. Open the app
2. Open any report
3. Type emoji text in following way ': joy:'
4. Remove space before text to convert it to emoji
5. Observe in android chrome, there is no space after emoji and in IOS native, cursor is displayed before emoji
## Expected Result: 
App should add space after emoji on converting emoji text to emoji
## Actual Result: 
App does not display space after emoji on android chrome and displays cursor before emoji on IOS native on converting emoji text to emoji when typed in specific way

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/0b170745-1c57-4f87-9137-8162f9377e07

https://github.com/Expensify/App/assets/38435837/b70fd233-5f13-4605-9aca-481c92d14f59

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/58964f7a-c660-45cc-bec1-faa86d34434d

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164d5ee2c19ee0a5a</li>
        <li>Upwork Job ID: 1712265898986901504</li>
        <li>Last Price Increase: 2023-10-26</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27494949</li>
<li>dhanashree-sawant | Reporter | 27494950</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by roksanaz** [comment]
I investigated this issue and I couldn't reproduce it on Android (the space appeared after the emoji on mobile website on Chrome). 
As for iOS, I tested other chat apps to search if this is the issue with Expensify app only or rather with iOS, e.g. Slack, and if you type ': joy:' and remove the space between the colon and "j" afterwards, the emoji isn't even converted (it remains as ':joy:'). Should this issue be treated as a bug or not then?

**Comment by twisterdotcom** [comment]
It does work on the iOS app and on web, just not the Android app.

And for Slack, they do render it after you remove the space:

https://github.com/Expensify/App/assets/9133401/7fa0af72-1c4b-4798-9a71-e82dea7a2ad9

**Comment by roksanaz** [comment]
@twisterdotcom About iOS: in Expensify the emoji appears immediately after you remove the space (meaning your cursor is after the first colon symbol), while on Slack you need to manually set the cursor after the second colon symbol. That is why the cursor is in the correct position on Slack and on Expensify it's not.

**Comment by roksanaz** [comment]
I am Roksana from Callstack - expert contributor group. I’d like to work on this job.

**Comment by roksanaz** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In the native iOS application if the user types the emoji manually, but they unintentionally put a space after the first colon mark (e.g. “: joy:”) and then remove the space, the emoji is converted successfully, but the cursor goes before the emoji instead of after the emoji. 
 
### What is the root cause of that problem?

There is a method for setting the cursor position programatically:

https://github.com/Expensify/App/blob/e968637a35b19dfbd7ad7f437b68fda57fc16d63/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L230-L235

But `selection` parameter  (which indicates the cursor position) is not passed for native iOS platform, because setting `selection` used to be unstable for iOS in previous versions of React Native (https://github.com/facebook/react-native/issues/29063).


### What changes do you think we should make in order to solve the problem?

`selection` parameter is not unstable in the version of React Native that is used in the app if implemented correctly (https://github.com/facebook/react-native/issues/29063#issuecomment-1607632702). The implementation used for Expensify is similar to the one quoted. Therefore I suggest to stop omitting this parameter for iOS. We should pass the same `props` as for Android and web, without omitting the `selection` prop that is happening here:


https://github.com/Expensify/App/blob/eee46dc3e9fffd2fb737dadbd70975f752787a42/src/components/Composer/index.ios.js#L112-L113

**Comment by twisterdotcom** [comment]
Now I think we can right @aimane-chnaif?

**Comment by twisterdotcom** [comment]
I think we can get this going and approve it for an internal 👍 right @akinwale?

**Comment by twisterdotcom** [comment]
@youssef-lr let's get @roksanaz assigned!

**Comment by roksanaz** [comment]
Hello, I just want to let you know that from now on @artus9033 will take over this issue, so I would be grateful if you could assign this to him :)

**Comment by twisterdotcom** [comment]
@artus9033 could you comment on this issue so I can assign you please?

**Comment by artus9033** [comment]
Sure, thank you

**Comment by twisterdotcom** [comment]
Ah, missed your comment! Sorry @artus9033. You're assigned now. Thanks!

**Comment by artus9033** [comment]
> @artus9033 how's it going?

Still working on fix update due to the unfavorable behaviour of RN's TextInput on iOS, which fires a series of `onSelectionChange` events after inserting an emoji that causes problems. I am close to the perfect solution and will submit new commits soon.

**Comment by artus9033** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the native iOS application if the user types the emoji manually, but they unintentionally put a space after the first colon mark (e.g. “: joy:”) and then remove the space, the emoji is converted successfully, but the cursor goes before the emoji instead of after the emoji.

This is an updated approach with regards to https://github.com/Expensify/App/pull/30835#issuecomment-1848892309

### What is the root cause of that problem?
There is a way to set the cursor position programatically through a prop passed to `TextInput`, but the `selection` parameter (which indicates the cursor position) is not passed for native iOS platform, because setting selection used to be unstable for iOS in previous versions of React Native (https://github.com/facebook/react-native/issues/29063) and causes problems.

The previous proposal involved a momentary behaviour of the cursor jumping to `{0, 0}`, since it was delaying setting the cursor position to the pre-calculated one. I attempted to overcome this caret behaviour, however on iOS native the original passing of the selection on iOS caused `onSelectionChange` to be fired sequentially when replacing emoji markers, resulting in unfavorable behaviour of the cursor "jumping around" for a brief moment before being positioned properly by the fix.

### What changes do you think we should make in order to solve the problem?

A solution would be to set a flag to sync cursor position inside `onChangeText` on iOS specifically by setting it via `TextInput` ref after all interactions finish, to the position pre-calculated in `onSelectionChange`.

**Comment by mountiny** [comment]
@kavimuru Based on the comment [here](https://github.com/Expensify/App/issues/33727#issuecomment-1872147161) this issue was not resolve on ios native @roksanaz @aimane-chnaif 

Could you provide more details on this one/ verify this is still not fixed in staging?

**Comment by kavimuru** [comment]
@mountiny @aimane-chnaif this is the video https://platform.applause.com/services/links/v1/external/18b2ae2543684c6e0f912e822e9e4efa99d2c6e98489a2e6f806358a726a6dce

**Comment by twisterdotcom** [comment]
Wow, this is an old one! Okay. Payment Summary:

- @artus9033 is from Callstack, no individual payment required.
- @aimane-chnaif paid $500 [here](https://www.upwork.com/nx/wm/offer/27494949) (Reviewer)
- @dhanashree-sawant paid $50 [here](https://www.upwork.com/nx/wm/offer/27494950) (Reporter)

Awaiting checklist completion by @aimane-chnaif.
