### ISSUE TITLE
[C+ checklist requires completion] [$500] Distance Expense - No red dot in chat (LHN) or expense preview when invalid waypoints are used

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29954]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
Offline mode:

1. Launch the app.
2. Navigate to Global Create > Request Money.
3. Select the ''Distance'' option.
4. Disable the internet connection.
5. Enter an invalid start location.
6. Enter an invalid finish location.
7. Tap on ''Next''.
8. Choose a workspace from the list.

Online mode:

9. Enable the internet connection
10. Go to workspace chat, verify the distance expense preview
11. Go to LHN and verify the workspace chat

## Expected Result:
A red dot appears in workspace chat (LHN) and on the expense preview after creating an expense with invalid waypoints.

## Actual Result:
A red dot doesn't appear in workspace chat (LHN) or on the expense preview after creating an expense with invalid waypoints.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/115492554/78dea660-9a60-44f9-9864-24af3cfdc268

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>

<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db8a056567f7d682</li>
        <li>Upwork Job ID: 1714950822453010432</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by brunovjk** [comment]
@dukenv0307 I believe there are other problems related to [waypoint validation](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22+waypoints), do you think we can change your solution to cover more scenarios? I don't know if there are other PRs

**Comment by greg-schroeder** [comment]
Awaiting proposal review

**Comment by burczu** [comment]
@dukenv0307 What do you think about [this comment](https://github.com/Expensify/App/issues/29954#issuecomment-1770683865)?

P.S. I've checked your proposal and indeed it does fix the issue.

**Comment by burczu** [comment]
@dukenv0307 I think the question asked by @brunovjk is if this issue can potentially fix other issues listed by them.

**Comment by burczu** [comment]
Hmmm, it works for me: https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22+waypoints

**Comment by burczu** [comment]
I think this is the question to you to tell us if you think something on the list may be related :)

**Comment by burczu** [comment]
Yeah, I've just checked the list too and I agree.

So, I think we [the proposal](https://github.com/Expensify/App/issues/29954#issuecomment-1770554910) from @dukenv0307 is what we can proceed with.

🎀 👀 🎀 C+ reviewed

**Comment by pecanoro** [comment]
Sounds good! Assigning @dukenv0307, sorry for the small delay!

**Comment by greg-schroeder** [comment]
Processing

**Comment by greg-schroeder** [comment]
Offer sent to @dukenv0307

**Comment by greg-schroeder** [comment]
All that's left is checklist by @burczu

**Comment by greg-schroeder** [comment]
bump @burczu

**Comment by burczu** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR:

**https://github.com/Expensify/App/pull/18423**

* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

**https://github.com/Expensify/App/pull/18423#discussion_r1392497395**

* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

**Didn't find any**

* [x]  [@burczu] Determine if we should create a regression test for this bug.

**As this issue occurs only while the App in offline mode, I tend to believe this is not very common case and we don't necessary need regression test for this.**

* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@greg-schroeder] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by greg-schroeder** [comment]
Thanks @burczu!
