### ISSUE TITLE
[Awaiting Checklist Completion] [$500]  Inconsistency bug: emoji suggestion does not reopen on revisit (works fine for mentions)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30188]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698048662555869

## Action Performed:
1. Open the app
2. Open any report
3. Type in :tea to trigger emoji suggestions
4. Visit another tab or minimize the window
5. Revisit the app tab and observe that focus is present but emoji suggestion is not displayed
6. Similarly try it for mentions and observe that mentions are displayed properly on revisit

## Expected Result:
App should display emoji suggestions on tab revisit as we do for mention suggestions

## Actual Result:
 App should display emoji suggestions on tab revisit as we do for mention suggestions

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/acfda114-c3fd-4fed-b138-b525052842bd

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/2c97133e-c3f6-44a4-8fe0-22e3484f3510

https://github.com/Expensify/App/assets/93399543/ed6f7ff5-d1e0-4624-8961-14de4d6534cc

https://github.com/Expensify/App/assets/93399543/6d940faa-3130-4448-b198-a187acb08791

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/158f965d-1b95-4797-b9b0-45885462f965

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b89a38dcc5e639b</li>
        <li>Upwork Job ID: 1716492845942243328</li>
        <li>Last Price Increase: 2023-11-06</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Contributor | 27643100</li>
<li>dhanashree-sawant | Reporter | 27643101</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsistency bug: emoji suggestion does not reopen on revisit (works fine for mentions)

### What is the root cause of that problem?

The root cause of this issue is that `SuggestionEmoji` doesn't have `useEffect` to re-calculate emoji suggestions when `isComposerFocused` is true while `SuggestionMention` has [useEffect](https://github.com/Expensify/App/blob/f42a195b78b524e57b72a8c801583b63498a16bc/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L236) to re-calculate mention suggestions when `isComposerFocused` is changed, see [calculateMentionSuggestion](https://github.com/Expensify/App/blob/f42a195b78b524e57b72a8c801583b63498a16bc/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L183) which is depended on `isComposerFocused`.

### What changes do you think we should make in order to solve the problem?

To let emoji suggestion also show up when revisiting tab, we can add `isComposerFocused` by destructuring assignment after this line

https://github.com/Expensify/App/blob/3f32b7dabbc9ee19e6e859d6460f7652f4824c4d/src/pages/home/report/ReportActionCompose/SuggestionEmoji.js#L61

and add an `useEffect` after this line

https://github.com/Expensify/App/blob/3f32b7dabbc9ee19e6e859d6460f7652f4824c4d/src/pages/home/report/ReportActionCompose/SuggestionEmoji.js#L181

```js
    useEffect(() => {
        if (isComposerFocused) {
            calculateEmojiSuggestion(selection.end);
        }
    }, [selection, calculateEmojiSuggestion, isComposerFocused]);
```

Then we can show emoji suggestions after revisting tab.

<details>
  <summary>Click to see demo video</summary>

  https://github.com/Expensify/App/assets/117511920/f591a10c-dc13-4b1b-afa6-4462de6cb78b
</details>

### What alternative solutions did you explore? (Optional)

N/A

**Comment by twisterdotcom** [comment]
One proposal here for ya @allroundexperts.

**Comment by s-alves10** [comment]
@allroundexperts 

`calculateEmojiSuggestion` won't be called when composer focused state is changed if we add `isComposerFocused` to its dependency. In mentions, `calculateMentionSuggestion` was added to the dependency list of useEffect and so the function is called when `calculateMentionSuggestion` is changed 

And if we add extra dependency to the useEffect(`selection` and `calculateEmojiSuggestion`), redundant call of `calculateEmojiSuggestion` would be made. We should add only `isComposerFocused`

**Comment by eh2077** [comment]
@allroundexperts  Thanks for reviewing proposals. That's a good point. I'll dig deeper and post an update soon.

**Comment by twisterdotcom** [comment]
Still waiting on proposals

**Comment by eh2077** [comment]
> @eh2077 @s-alves10 Would you mind explaining why we can't add `isComposerFocused` as a dependency to the `calculateEmojiSuggestion` callback instead of the new useEffect which you are creating? Wouldn't that be inline with what we're doing with mentions?

@allroundexperts First, we need to have an `useEffect` in `SuggestionEmoji` to reflect the state change of `isComposerFocused`. Second, about having consistent implementation between them, I checked change records of `SuggestionMention`
1. We added [useEffect](https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L232-L241) in `SuggestionMention` to handle typing `@` showing up mention menu issue on iOS native platform, see [PR](https://github.com/Expensify/App/pull/27327/files#diff-ae24962beaa90b3398bced3342a26ed2162d6a89c99b257bd1428e745f711503)
2. Later we fixed a regression caused by the `useEffected` by checking `isComposerFocused` in method `calculateEmojiSuggestion` to skip calculating mentions and adding method `calculateEmojiSuggestion` to the dependency list of `useEffect`, see [PR](https://github.com/Expensify/App/pull/29951/files#diff-ae24962beaa90b3398bced3342a26ed2162d6a89c99b257bd1428e745f711503). 
   But I think just checking `isComposerFocused` to skip calling method `calculateMentionSuggestion` in the `useEffect` can achieve the same effect, which is suggested in my proposal.

**Comment by twisterdotcom** [comment]
Bump @allroundexperts for a review of @eh2077's comment.

**Comment by twisterdotcom** [comment]
@allroundexperts let me know if you can't get to this and I'll reassign a new C+ next week if not.

**Comment by twisterdotcom** [comment]
No, we _just_ assigned @eh2077 Melv!

**Comment by eh2077** [comment]
@allroundexperts The PR https://github.com/Expensify/App/pull/31289 is ready for review, thanks.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @allroundexperts should request $500 via Expensify (C+)
- @eh2077 paid $500 [here](https://www.upwork.com/nx/wm/offer/27643100) (Contributor)
- @dhanashree-sawant paid $50 [here](https://www.upwork.com/nx/wm/offer/27643101) (Reporter)

Waiting now on @allroundexperts to complete the checklist.

**Comment by allroundexperts** [comment]
## Checklist

1. I was not able to pinpoint an exact PR which caused this bug. This seems like an edge case which existed since we introduced emoji suggestions.
2. N/A
3. A slack discussion isn't needed here. I don't think that any checklist item would have avoided this.
4. A regression test is not necessary here in my opinion since this is minor and does not really have a large impact on the user experience. If the internal engineer disagrees however, the test steps in the OP look clear enough to me.

**Comment by cristipaval** [comment]
I agree with you at 4, @allroundexperts! Regression steps for this edge case might be an overkill.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on comment above.
