### ISSUE TITLE
[WAITING ON CHECKLIST][$500] Web/Safari - LHN - Created Split Bill Group chat in offline displays in bottom in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30472]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Disable internet connection
3. Click on FAB
4. Click on Request Money
5. Enter amount and click Next button
6. Select two or more attendees with non-existing account and Click next
7. On final confirmation page click Split button
8. Scroll down the LHN and find the created group chat position

## Expected Result:
Created Split Bill group chat should be displayed on top in LHN

## Actual Result:
Created split bill group chat displayed in bottom in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/5cf04c09-f0fd-420f-9551-a627cd958436

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162c5869781746626</li>
        <li>Upwork Job ID: 1717692476337967104</li>
        <li>Last Price Increase: 2023-11-02</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Contributor | 27506525</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Just having a read of this issue - is this because it's a Split expense that's been created offline? i.e. For things created offline, they just stay in limbo. Any thoughts @parasharrajat ?

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When a money request is split with participants with whom there is no open IOU Report, the LHN displays the IOU Reports with such participants towards the end of the LHN. 

### What is the root cause of that problem?

When a split money request is created, the optimistic data of the IOU Report is set [here](https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/libs/actions/IOU.js#L172C1-L180C11). However, since this would be a new report `lastVisibleActionCreated` will not be set. Since LHN sorts the reports based on `lastVisibleActionCreated` as shown [here](https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/libs/SidebarUtils.ts#L209C1-L220C6), the newly created IOU Reports will be displayed towards the end of LHN. This is the root cause.

### What changes do you think we should make in order to solve the problem?

To set `lastVisibleActionCreated` for newly created IOU Reports, we can set it to the report action like this [here](https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/libs/actions/IOU.js#L178)

```
                ...(isNewIOUReport ? {pendingFields: {createChat: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD}, lastVisibleActionCreated: iouAction.created} : {}),

```
### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment]
Dupe of #30467

**Comment by rojiphil** [comment]
> In other words, Are task reports, money requests reports, new chat all show at the bottom while created offline?

@parasharrajat 
New chat report works well in offline but task report and iou report shows up at the bottom.
Chat report works well as as we are setting `lastVisibleActionCreated` [here](https://github.com/Expensify/App/blob/345a3a1dc6456e3c8059bb6f8b59b87157262537/src/libs/ReportUtils.js#L2843). 
Meanwhile, we do not set the `lastVisibleActionCreated` for `buildOptimisticTaskReport` [here](https://github.com/Expensify/App/blob/345a3a1dc6456e3c8059bb6f8b59b87157262537/src/libs/ReportUtils.js#L3059C1-L3074C2) and for `buildOptimisticIOUReport` [here](https://github.com/Expensify/App/blob/345a3a1dc6456e3c8059bb6f8b59b87157262537/src/libs/ReportUtils.js#L2339C1-L2364C2). We will also have to do this for `buildOptimisticExpenseReport` [here](https://github.com/Expensify/App/blob/345a3a1dc6456e3c8059bb6f8b59b87157262537/src/libs/ReportUtils.js#L2377C1-L2403C2). 
I think a more generic approach like this may be a better thing to do. 
What do you think? 
If so, I can update the proposal accordingly.

**Comment by rojiphil** [comment]
@parasharrajat 

Gentle bump on your thoughts [here](https://github.com/Expensify/App/issues/30472#issuecomment-1784872492)

**Comment by jliexpensify** [comment]
Not overdue, waiting on @parasharrajat

**Comment by jliexpensify** [comment]
Not overdue, PR is being worked on

**Comment by jliexpensify** [comment]
Hmm doesn't look like Melvin updated the payment date, but it's been 7 days since deployment.

I'll whip up a summary and pay everyone.

**Comment by jliexpensify** [comment]
Payment Summary:

- Contributor: @rojiphil $500 - have hired you
- C+: @parasharrajat $500 (request on New.Dot)

[Upworks job here](https://www.upwork.com/jobs/~014a629a298301ac58)

**Comment by jliexpensify** [comment]
@rojiphil if you didn't get an invite from me, can you apply for the job? Upworks error-ed out when I hired you. Thanks!

**Comment by jliexpensify** [comment]
@parasharrajat anything from the checklist required?

**Comment by rojiphil** [comment]
> @rojiphil if you didn't get an invite from me, can you apply for the job? Upworks error-ed out when I hired you. Thanks!

Thanks @jliexpensify. I got the invite. I also accepted and submitted the work.

**Comment by jliexpensify** [comment]
Paid and job closed, just waiting on the checklist @parasharrajat

**Comment by jliexpensify** [comment]
Awesome, closing!

For JMills: [Payment Summary](https://github.com/Expensify/App/issues/30472#issuecomment-1857076508)

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
