### ISSUE TITLE
[WAITING ON CHECKLIST][HOLD for payment 2023-11-21] [$500] Attachment - File name is placed on the left of the preview page if add docx and mp4.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31103]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account.
3. Open 1:1 conversation, click on the + button in the compose box.
4. Click on add attachment.
5. Upload docx or mp4.

## Expected Result:
The file name is placed on the center of the preview page, if you add docx and mp4 attachments.

## Actual Result:
The file name is placed on the left, not in the center of the preview page, if you add docx and mp4 attachments.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/b5a87617-7ced-41d0-a403-4a707bbacdee

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a07e3cb1d6ca87c5</li>
        <li>Upwork Job ID: 1722549601357987840</li>
        <li>Last Price Increase: 2023-11-09</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Not reproduced in production 

![image](https://github.com/Expensify/App/assets/115492554/955046b3-b84a-4ba9-b225-80e911469a38) 

![image (8)](https://github.com/Expensify/App/assets/115492554/70d88fdf-d130-43b0-b6ee-22becad3e1bd)

**Comment by zhongweizhou522** [comment]
Anybody can help  me to join slack channel?

**Comment by zoosphar** [comment]
Hello,
I figured out why the issue is occurring and also did a temporary fix, PFB the screenshot of the same
<img width="1440" alt="Screenshot 2023-11-09 at 3 58 41 PM" src="https://github.com/Expensify/App/assets/29529379/68cc96e0-b6fd-4ba5-baf9-db90ea8a87f5">

This could be a basic conditional and styling error, where the code is not covering all the cases which includes mp4 and docx files.

**Comment by zhongweizhou522** [comment]
I already submitted my contributor details.

**Comment by Beamanator** [comment]
@zhongweizhou522 please send another email to contributors@expensify.com, please don't post in GH issues for slack access 🙏

**Comment by Beamanator** [comment]
@zoosphar it doesn't look like you submitted a proposal, you just took a screenshot of your fix working? You'll need to submit a full proposal if you want to have the opportunity to work on this job

**Comment by Beamanator** [comment]
@ZhenjaHorbach the proposal you linked doesn't explain anything about why it would also fix this issue, can you please explain?

**Comment by Beamanator** [comment]
CPing [fix PR](https://github.com/Expensify/App/pull/31130)

**Comment by puneetlath** [comment]
Confirmed it's fixed!

**Comment by jliexpensify** [comment]
I'm assuming this is the correct Payment Summary?

- C+: @Santhosh-Sellavel $500 (New.Dot request)

**Comment by jliexpensify** [comment]
Oh weird, 2 payment dates! Bump @Santhosh-Sellavel to complete the checklist please.

**Comment by jliexpensify** [comment]
[Payment Summary here](https://github.com/Expensify/App/issues/31103#issuecomment-1804838034)

**Comment by zoosphar** [comment]
> @zoosphar it doesn't look like you submitted a proposal, you just took a screenshot of your fix working? You'll need to submit a full proposal if you want to have the opportunity to work on this job

Hey @Beamanator 
I did submit a proposal on Upwork for the same and didn't get any reply on Upwork. Can you tell me if I missed anything to take care of in future?

Here is the proposal I submitted
<img width="530" alt="Screenshot 2023-11-21 at 2 23 16 PM" src="https://github.com/Expensify/App/assets/29529379/3c9f60f5-f672-4d4e-bdaf-c367ea78edce">

**Comment by jliexpensify** [comment]
@zoosphar as stated in our Contributing.MD, all proposals must use the template and be posted in the GitHub issue, not Upworks.

**Comment by jliexpensify** [comment]
Bump @Santhosh-Sellavel to complete the checklist. Thanks!

**Comment by Santhosh-Sellavel** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30995
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30995#issuecomment-1803962382
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. I guess N/A as it's caught by Applause should be part of basic cases
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A 
> * [ ]  [@jliexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by jliexpensify** [comment]
Great, thanks Santhosh - closing.

[Reference for New.Dot payments](https://github.com/Expensify/App/issues/31103#issuecomment-1804838034)

**Comment by JmillsExpensify** [comment]
$500 payment approved for @Santhosh-Sellavel based on [this comment](https://github.com/Expensify/App/issues/31103#issuecomment-1804838034).
