### ISSUE TITLE
[HOLD for payment 2023-12-08] [Theme Switching Migration] Master File Tracking

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31677]
Instructions - https://github.com/Expensify/App/pull/27346

Coming from https://expensify.slack.com/archives/C03UK30EA1Z/p1700644906437179?thread_ts=1700563711.542099&cid=C03UK30EA1Z

We need to migrate the following files to use our styles/theme hooks.

- [ ] src/libs/Navigation/AppNavigator/getRootNavigatorScreenOptions.js
- [ ] src/components/AddressForm.js
- [ ] src/components/Attachments/AttachmentView/AttachmentViewPdf/index.android.js
- [ ] src/components/AvatarWithImagePicker.js
- [ ] src/components/Composer/index.ios.js
- [ ] src/components/Composer/index.android.js
- [ ] src/components/EmojiPicker/EmojiPickerMenu/index.js
- [ ] src/components/Icon/BankIcons.ts
- [ ] src/components/MenuItem.js
- [ ] src/components/ScreenWrapper/index.js
- [ ] src/libs/ComposerUtils/updateNumberOfLines/index.native.ts
- [ ] src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.js
- [ ] src/libs/Navigation/AppNavigator/RHPScreenOptions.js
- [ ] src/libs/Navigation/AppNavigator/getRootNavigatorScreenOptions.js
- [ ] src/pages/ReferralDetailsPage.js
- [ ] src/pages/ReimbursementAccount/RequestorStep.js
- [ ] src/pages/settings/Wallet/Card/BaseGetPhysicalCard.js
- [ ] src/pages/settings/Wallet/Card/GetPhysicalCardConfirm.js
- [ ] src/pages/settings/Wallet/Card/GetPhysicalCardName.js
- [ ] src/pages/settings/Wallet/Card/GetPhysicalCardPhone.js
- [x] ~~src/styles/addOutlineWidth/index.ts~~

PropTypes
- [ ] src/components/OptionsList/optionsListPropTypes.js
- [ ] src/components/OptionsSelector/optionsSelectorPropTypes.js

Styles
- [ ] src/pages/signin/SignInPageLayout/signInPageStyles/index.native.js
- [ ] src/pages/signin/SignInPageLayout/signInPageStyles/index.js
- [ ] src/styles/containerComposeStyles/index.native.ts
- [ ] src/styles/containerComposeStyles/index.ts
- [ ] src/styles/getContextMenuItemStyles/index.native.ts
- [ ] src/styles/getContextMenuItemStyles/index.ts
- [ ] src/styles/optionRowStyles/index.ts
- [ ] src/styles/optionRowStyles/index.native.ts

**Comment by grgia** [comment]
cc @roryabraham Let me know if you're interested in helping to review these when they're done!

**Comment by grgia** [comment]
cc @chrispader as well

**Comment by koko57** [comment]
Could you please assign me to this tracking issue?

**Comment by koko57** [comment]
@grgia it turns out we don't need to migrate src/styles/addOutlineWidth/index.ts - it's used in styles/styles.ts

**Comment by grgia** [comment]
@koko57 are you able to update the issue description? If so, feel free to update as needed! I used a strikethrough for that one

**Comment by koko57** [comment]
@grgia no, unfortunately I cannot update it 😞

**Comment by chrispader** [comment]
@grgia should i work on some of this or are these issues/batches already assigned to someone?

**Comment by koko57** [comment]
@grgia here's the summary what we've managed to do so far
open PRs:
https://github.com/Expensify/App/pull/31774
https://github.com/Expensify/App/pull/31728
https://github.com/Expensify/App/pull/31723
https://github.com/Expensify/App/pull/31827
https://github.com/Expensify/App/pull/31691 (need to address one comment)

drafts:
https://github.com/Expensify/App/pull/31815

**Comment by grgia** [comment]
@chrispader, we've got PRs up for these; but if you'd like to help review, that would be great!

**Comment by koko57** [comment]
@grgia looks like only [this one](https://github.com/Expensify/App/pull/31723) is missing something, the rest are ok

**Comment by koko57** [comment]
Tuesday update:

All the PRs are opened for review 🙂 🎉  
I see that some of them are already approved 🙂

**Comment by chrispader** [comment]
Should we make sure that all of these batches also include changes to `propTypes`? I noticed some of the components' `propTypes` haven't been updated, but we might ignore this since we're migrating TypeScript anway?

Wdyt? @grgia

**Comment by grgia** [comment]
@chrispader good point. I think we should include the proptypes for class components until they are officially migrated. 

cc @koko57 thoughts on this?

**Comment by chrispader** [comment]
All the PRs looks good to me! 👍

**Comment by grgia** [comment]
@koko57 @chrispader 

It looks like we need to replace default theme import for these files

- [ ] https://github.com/Expensify/App/blob/9c095833c924e564b6488a693c7eddd87e32f0b1/src/components/Icon/index.tsx#L5
- [ ] https://github.com/Expensify/App/blob/3b02565ea9df14b93ca3c1f2ce3de2ef4c8f4c1d/src/styles/getTooltipStyles.ts
- [ ] https://github.com/Expensify/App/blob/68233f4b7b7e2fae3f8031c0e3727e5f7c63ae94/src/components/MapView/MapView.web.tsx#L13
- [ ] https://github.com/Expensify/App/blob/1080ca04fb28754b8f115a996943b37259bfa9d7/src/components/ShowMoreButton/index.js#L11
- [ ] https://github.com/Expensify/App/blob/86767e1eda45e738c0335cbcaa1e3060d1ece82a/src/pages/home/report/ReportActionItem.js#L50
- [ ] https://github.com/Expensify/App/blob/1d44d68e0d66ac69a032d119f2ca70ccf48e60f9/src/pages/home/report/ReportActionItemSingle.js#L24
- [ ] https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/stories/Composer.stories.js#L10
- [ ] https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/styles/getModalStyles.ts#L6
- [ ] https://github.com/Expensify/App/blob/05a58d8ecbbea76e1b21a9f989d72e0bc278906f/src/styles/getReportActionContextMenuStyles.ts#L3
- [ ] https://github.com/Expensify/App/blob/3b02565ea9df14b93ca3c1f2ce3de2ef4c8f4c1d/src/styles/getTooltipStyles.ts#L6
- [ ] https://github.com/Expensify/App/blob/1b22f59fd874fcc4297ee8f4350ae34d02f74aeb/src/styles/styles.ts#L23
- [ ] https://github.com/Expensify/App/blob/8537b739f520d3eba39958575d176b12f149b12a/src/styles/StyleUtils.ts#L12

**Comment by chrispader** [comment]
> Then I can take care of the rest of the files, but please clarify how should I change import like this: [App/src/styles/StyleUtils.ts](https://github.com/Expensify/App/blob/8537b739f520d3eba39958575d176b12f149b12a/src/styles/StyleUtils.ts#L12)

We need to pass `theme` from the component with `useTheme` to any of the functions that currently depend on `themeColors`

**Comment by koko57** [comment]
@chrispader @grgia - for this file I think it should stay as it is [App/src/styles/styles.ts](https://github.com/Expensify/App/blob/1b22f59fd874fcc4297ee8f4350ae34d02f74aeb/src/styles/styles.ts#L23)

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by koko57** [comment]
@chrispader @grgia https://github.com/Expensify/App/pull/32247 ready for review

**Comment by chrispader** [comment]
> @chrispader @grgia - for this file I think it should stay as it is [App/src/styles/styles.ts](https://github.com/Expensify/App/blob/1b22f59fd874fcc4297ee8f4350ae34d02f74aeb/src/styles/styles.ts#L23)

Yes right. We're removing this import and `defaultStyles` as soon as all components are migrated.

**Comment by grgia** [comment]
@koko57 
I created two issues for these
https://github.com/Expensify/App/issues/32254
https://github.com/Expensify/App/issues/32255

**Comment by rezkiy37** [comment]
@grgia, I've opened a PR for review - https://github.com/Expensify/App/pull/32250.

**Comment by koko57** [comment]
@grgia thanks! we're almost done, but I will link the PRs for this issue. The last PR is nearly there

**Comment by koko57** [comment]
@grgia the last one I'm opening in a few minutes - there will be 2 PR for the Util issue

**Comment by grgia** [comment]
Closing as complete 🎊
