### ISSUE TITLE
[WAITING ON CHECKLIST] [$500] Bank account - App crashes when tapping on Fix the errors in Connect BA page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31795]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to Settings > Workspaces > any workspace.
3. Click Bank account.
4. Click Connect manually.
5. Enter both bank account numbers.
6. Without checking the ToS checkbox, tap Continue.
7. Tap Fix the errors.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari - console error
- [x] MacOS: Desktop 

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/08d29610-5cf5-421e-8f26-b54f7f1086c7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127dd2a89d454700f</li>
        <li>Upwork Job ID: 1727796833108000768</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@mkhutornyi RCA seems correct, but I think we should rename the prop passed down to ref, since that's what we've been doing for TS migrations. Are you available to work on a fix PR within the next hour?

**Comment by luacmartins** [comment]
Fix CPed, removing blocker label

**Comment by jliexpensify** [comment]
Not overdue but bump for @burczu to complete the checklist

**Comment by jliexpensify** [comment]
Payment Summary:

- Contributor: @mkhutornyi $500 - I can't find you on Upworks, can you apply for the job?
- C+: @burczu (invoiced payment) - Please complete checklist!

[Upworks job](https://www.upwork.com/jobs/~0127dd2a89d454700f)
