### ISSUE TITLE
[Awaiting checklist completion] [Wave 6: Workspace Chats] Expense - 'Marked as reimbursed' message in expense report is not wrapped

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32286]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.6.2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32157
## Action Performed:
Precondition:
- User is an employee of a Collect workspace
1. Log in to ND as the employee
2. Go to the workspace chat > + > Request money
3. Create a manual request
4. As admin, pay the request
5. As employee, tap on the expense preview to open the paid expense report

## Expected Result:
The reimbursement message at the top is wrapped

## Actual Result:
The reimbursement message at the top is not wrapped

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/2384c468-c2a9-42f2-b467-25cdc22120db

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ff3867dd75517b9</li>
        <li>Upwork Job ID: 1734928173565202432</li>
        <li>Last Price Increase: 2023-12-13</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Not a blocker, this is a feature behind beta and normal customers cant see this now.

Callstack can help us with this

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by mountiny** [comment]
Thanks!

**Comment by mountiny** [comment]
I will bump QA to retest

**Comment by rezkiy37** [comment]
@lanitochka17, just tried to reproduce on 2 different emulators:

<img width="1003" alt="Screenshot 2023-12-07 at 12 10 25" src="https://github.com/Expensify/App/assets/57314631/ec06c199-2c98-41f6-beb2-ac9c01f34380">


Also tried on a real device:

![image](https://github.com/Expensify/App/assets/57314631/e4761bd1-d663-4807-af55-3dff08960cb6)

So, the app looks good. Are you able to test on another device? 

cc @mountiny

**Comment by lanitochka17** [comment]
@rezkiy37 After testing on the SG A50/Chrome phone, the problem was not reproduced

![viber_image_2023-12-07_09-23-53-404](https://github.com/Expensify/App/assets/78819774/ae08ec31-fee9-4f12-91c4-3a2ac0377363)

**Comment by rezkiy37** [comment]
Vit found a difference that causes a bug. It happens with a really long email. So, the bug is relevant. Sorry for additional attention 😅

<img width="553" alt="Screenshot 2023-12-07 at 18 28 07" src="https://github.com/Expensify/App/assets/57314631/6b51f9e7-7e69-4df5-a84a-5b6d7cdc12cb">

**Comment by rezkiy37** [comment]
Working on a fix.

**Comment by rezkiy37** [comment]
Still working on a fix.

**Comment by rezkiy37** [comment]
Preparing a proposal.

**Comment by rezkiy37** [comment]
Currently, the proposal is being reviewed internally.

**Comment by rezkiy37** [comment]
Great! 
So, I am preparing a PR.

**Comment by mountiny** [comment]
Thanks!

**Comment by rezkiy37** [comment]
During internal [PR](https://github.com/Expensify/App/pull/32910) review, I got a suggestion to use [EmailUtils.prefixMailSeparatorsWithBreakOpportunities()](https://github.com/Expensify/App/blob/main/src/libs/EmailUtils.ts#L22) with a combination of `word-break: 'break-word'`. 

This actually makes sense, because already there was an [issue](https://github.com/Expensify/App/issues/30985) to fix when emails were split in an inconsistent manner between platforms.

cc @Ollyws

**Comment by rezkiy37** [comment]
Uploading Example.mp4…

**Comment by mountiny** [comment]
this sounds good

**Comment by rezkiy37** [comment]
Guys, I am having a vacation till the 4th January. So, I will be OOO within this period.

**Comment by mountiny** [comment]
$500 to @Ollyws for their PR review and testing

**Comment by bfitzexpensify** [comment]
Offer sent @Ollyws

**Comment by bfitzexpensify** [comment]
Bump on the BZ checklist - thanks @Ollyws

**Comment by bfitzexpensify** [comment]
I'm going to be mostly ooo until Jan 29, assigning a second BZ team member to keep an eye on this.

- final step here is the completion of the BZ checklist by @Ollyws
