### ISSUE TITLE
[$500] Task – There is no additional subtask with assignee under the main task in a group chat.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32840]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account.
3. Navigate to group conversation.
4. As user A Create a task.
5. Navigate to the task conversation.
6. Click + and create a subtask.
7. Assign it to yourself.
8. Navigate back to group conversation.

## Expected Result:
There is parent task with reply and one more line with subtask assigned to yourself in a group chat

## Actual Result:
There is no additional subtask with assignee under the main task in a group chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/93444eac-3e19-41b2-8ae3-640c4aa7e8b5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7a662cde150692b</li>
        <li>Upwork Job ID: 1734352525285384192</li>
        <li>Last Price Increase: 2024-01-08</li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
The referral program link is not working  https://help.expensify.com/articles/new-expensify/billing-and-plan-types/Referral-Program

**Comment by AndrewGable** [comment]
This doesn't need to block deploy

**Comment by mallenexpensify** [comment]
Is the Expected behaviour that 
<img width="362" alt="image" src="https://github.com/Expensify/App/assets/22508304/dc331412-aa45-4cf3-8d60-da61647afae5">
is supposed to look like
<img width="492" alt="image" src="https://github.com/Expensify/App/assets/22508304/f0095e57-d51b-411d-83c0-4c1183908a78">

where it shows the task is assigned to a user? 

I'm new to Subtasks.

**Comment by keisyrzk** [comment]
@kbecciv 
The "issue" is indeed replicable but the expected result is not clear. Could you please share how exactly should the expected result look like?

**Comment by AndrewGable** [comment]
I'm not sure what the expected UI is @mallenexpensify - We probably should bring to Slack to confirm.

**Comment by mallenexpensify** [comment]
> There is parent task with reply and one more line with subtask assigned to yourself in a group chat

@kbecciv can you provide more details on this? Bonus if you have any screenshots or markups. 

Checking on [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1703034740368559), to see if #vip-vsb is the best room and also for anyone familiar with subtasks

**Comment by mallenexpensify** [comment]
@kbecciv 👀 above plz

**Comment by kbecciv** [comment]
@mallenexpensify The issue found when executing TR [here] https://expensify.testrail.io/index.php?/tests/view/4055828. Requested for re-test

**Comment by kbecciv** [comment]
Issue is Reproducible on build 1.7.18.2

https://github.com/Expensify/App/assets/93399543/cf6226bb-eb7e-41d0-8c7d-761b025c07a4

**Comment by mallenexpensify** [comment]
> There is parent task with reply and one more line with subtask assigned to yourself in a group chat

I'm struggling with the expected behaviour because I don't know where that came from.  I don't see it specifically mentioned in the TestRail case. 
<img width="611" alt="image" src="https://github.com/Expensify/App/assets/22508304/62623c74-d7b8-47c0-a0c8-08062758a4c0">

Also unsure how _big_ of a conversation we should have about managing visibility of subtasks.  I imagine they'll be useful for project management and power users so we should _get it right_ outta the gates.

**Comment by mallenexpensify** [comment]
Checking in #design to see if anyone worked on this, bumped to weekly
https://expensify.slack.com/archives/C03TME82F/p1704411384548909

**Comment by mallenexpensify** [comment]
@kbecciv can you point to _anywhere_ that states or shows how we're supposed to manage subtasks?  I'm leaning towards closing this but I'm curious about subtasks (now that I got assigned to this)

**Comment by kbecciv** [comment]
@mallenexpensify We are currently have 2 TCs related to subtask https://expensify.testrail.io/index.php?/cases/view/2654659 and https://expensify.testrail.io/index.php?/cases/view/2777983
@thienlnam Is subtask 'Task 2' meant to be placed under the main task 'Task 1'? for this TC https://expensify.testrail.io/index.php?/cases/view/2777983
Thank you in advance!


https://github.com/Expensify/App/assets/93399543/050add12-b2b6-48f9-b4f3-bfd793156cb8

**Comment by thienlnam** [comment]
These appear to be showing up correctly - subtasks are just tasks inside tasks. I believe we can close this. I'm not exactly sure what is missing

**Comment by mallenexpensify** [comment]
Closing, I can understand why we'd want to do anything differently with subtasks, and I've been testing them quite a bit lately. 

Task
<img width="639" alt="image" src="https://github.com/Expensify/App/assets/22508304/1838a248-1045-4662-90e7-ee0182af9aea">

Subtask inside above task
<img width="517" alt="image" src="https://github.com/Expensify/App/assets/22508304/c55d3722-5ad8-4660-ba83-761ee94e088f">
