### ISSUE TITLE
[WAITING ON CHECKLIST][$500] IOU-Order of display of date and distance is different in distance confirmation & details page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33751]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a Workspace chat
3. Tap plus icon ---- Request money ---- Distance
4. Enter start and finish waypoints
5. Tap next
6. Note in distance request confirmation page, first date and then distance section is displayed.
7. Tap distance
8. Tap on distance request created to open distance request details page
9. Note in distance request details page, first distance and then date section is displayed.

## Expected Result:
The order of display of date and distance must be same in distance confirmation & details page.

## Actual Result:
The order of display of date and distance is different in distance confirmation & details page.

In distance request confirmation page, first date and then distance section is displayed. In distance request details page, first distance and then date section is displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/48cdc5e9-5e2b-4df2-a1d0-eb7ceddf1762

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b42dbccdf1e5222</li>
        <li>Upwork Job ID: 1740699117183172608</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28091364</li>
<li>dukenv0307 | Contributor | 28091366</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU-Order of display of date and distance is different in distance confirmation & details page

### What is the root cause of that problem?
in confirmation date comes before distance 
https://github.com/Expensify/App/blob/7d1b0f8b99616c48aedb975dd73fc3086c9f20e3/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L649-L673
while it is oposite for request view
https://github.com/Expensify/App/blob/7d1b0f8b99616c48aedb975dd73fc3086c9f20e3/src/components/ReportActionItem/MoneyRequestView.js#L228-L263
### What changes do you think we should make in order to solve the problem?

We should choose one oreder and make it consistent for both
### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment]
Can repro on v1.4.20-2. Going to let Dylan know in the #wave5 channel

**Comment by jliexpensify** [comment]
@fedirjh - please review proposals!

**Comment by deetergp** [comment]
I agree, let's go with @dukenv0307's proposal 👍

**Comment by jliexpensify** [comment]
@fedirjh bump to complete the checklist please!

**Comment by jliexpensify** [comment]
Payment Summary

- Contributor: @dukenv0307 $500
- C+: @fedirjh $500

[Upwork job](https://www.upwork.com/jobs/~014b42dbccdf1e5222)

**Comment by jliexpensify** [comment]
Paid and posting removed. Waiting on checklist from @fedirjh
