### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] Status - The colon between hours and minutes is misaligned

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34136]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Profile > Status
2. Click Clear after > Custom > Time

## Expected Result:
The time is displayed properly

## Actual Result:
The colon between hours and minutes in Status is misaligned

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6336680_1704805259230!Screenshot_20240109-174344_New_Expensify](https://github.com/Expensify/App/assets/78819774/8c5eb8a4-9053-4b5a-b94b-0b8360199ade)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f22c871c339d732d</li>
        <li>Upwork Job ID: 1744875536384045056</li>
        <li>Last Price Increase: 2024-01-10</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 28092023</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by roryabraham** [comment]
Not sure why this is unassigned, I guess I'll grab it

**Comment by roryabraham** [comment]
It was missing the `Engineering` label

**Comment by roryabraham** [comment]
Thanks for the proposal @mkhutornyi, when do you think you'll be able to have a PR ready?

**Comment by thienlnam** [comment]
<img width="283" alt="Screenshot 2024-01-10 at 1 50 03 PM" src="https://github.com/Expensify/App/assets/30609178/dc7532a6-7631-485d-b877-0f198fd02442">
Verified this is fixed on staging

**Comment by paultsimura** [comment]
This caused a regression: https://github.com/Expensify/App/issues/34385

**Comment by greg-schroeder** [comment]
Amended offers sent to @mkhutornyi and @shubham1206agra

Can you please complete the checklist above @shubham1206agra? Thanks!

**Comment by shubham1206agra** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/33221
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/33221/files#r1471135719
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No as this was deploy blocker.
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@greg-schroeder] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by greg-schroeder** [comment]
@roryabraham @thienlnam can you confirm this for me? https://github.com/Expensify/App/issues/34136#issuecomment-1916768960

Should this be a reduced payment or not?

**Comment by roryabraham** [comment]
@greg-schroeder – confirmed, this should not be a reduced payment. The regression was introduced by https://github.com/Expensify/App/pull/33221/files#diff-a96e6554e48aa6637ea884224e6943a1dabc067fabd173015072164bac3e96a6 and neither @shubham1206agra nor @mkhutornyi were involved.

**Comment by greg-schroeder** [comment]
Okay got it, thanks @roryabraham! It was just hard for me to tell and I wanted to be sure. I'll adjust the payments accordingly

**Comment by greg-schroeder** [comment]
@shubham1206agra paid you $500 (gave you a $250 bonus on the original offer)

@mkhutornyi amended your offer to $500, so please accept and I'll pay you ASAP

**Comment by greg-schroeder** [comment]
@mkhutornyi I withdrew it and tried again - can you look?
