### ISSUE TITLE
[HOLD for payment 2024-03-13] [MEDIUM] Follow-ups to the LHN previews

### ISSUE THREAD

**Issue by koko57** [Expensify/App#34411]
Coming from: https://github.com/Expensify/App/issues/30042

Tracking issue listing all of the issues that should be addressed in the follow-ups:
- [x] https://github.com/Expensify/App/issues/33760 name is displayed twice for IOU previews in Search Page 
- [ ] unify the logic for getting alternateText for [getOptions](https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/libs/OptionsListUtils.js#L1063) and `getOptionData` (mentioned [in this PR](https://github.com/Expensify/App/pull/33966#discussion_r1444808394))
- [ ] name of the user sending a message in multiple users' chat is not displayed
- [x] Drop usage of the `originalMessage` to get request amount and currency and use the linked transaction instead, coming from [here](https://github.com/Expensify/App/issues/30042#issuecomment-1903886902) 
- [x] Do not show the name of the user who modified the request https://github.com/Expensify/App/issues/35515
- [ ] Do not show description for multiple request chat ([reference](https://expensify.slack.com/archives/C01GTK53T8Q/p1708610187601779))

Ideas for other improvements:
- move getting lastActor / actor display name to a separate function, try to move it out the functions called in getLastMessageTextForReport (create message text and get actor name separately then combine it)
- getReportPreviewMessage - pass an object with params instead of comma separated params 

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by koko57** [comment]
cc @mountiny

**Comment by koko57** [comment]
working on this one - I've extracted the logic into a separate function, but it's still WIP

**Comment by mountiny** [comment]
Thanks!

**Comment by koko57** [comment]
@mountiny the function I extracted still had some problems. I thought that it would be maybe better to divide this refactor into smaller steps. First one - I created a function for getting lastActorName. I also moved the logic for creating alternate text  for archived room to `getLastMessageTextForReport` - I think we should move as much logic for alternateText as possible there. 

Let me know what you think about it and if I can open this PR for the review

**Comment by koko57** [comment]
@mountiny just to make sure it's an expected behaviour (found it on staging, after applying the changes it's still the same):
on the Search Page for archived rooms (workspace chats) we're displaying the reason for the member (pink underline), but a "Workspace" for the admin (blue unedrline). On LHN we're displaying the reason both for the member and the admin. Is that correct?
<img width="376" alt="Screenshot 2024-01-23 at 15 01 12" src="https://github.com/Expensify/App/assets/28020445/cf98d812-b505-4049-946c-b46a0b44e9fa">

**Comment by mountiny** [comment]
Hmm I would say this should be same for user and the admin

**Comment by trjExpensify** [comment]
In search results, the workspace chat should be: 

**Admin/other participants**

>**Tom Rhys Jones**
>Duraflame, Inc. 

**Member**
>**Duraflame, Inc.** 
>Workspace

**Comment by trjExpensify** [comment]
@mountiny Nikki reported this [here](https://expensify.slack.com/archives/C049HHMV9SM/p1705534327388279), but there hasn't been an issue created for it yet.

**Comment by trjExpensify** [comment]
I don't think this is about the archiveReason specifically, that probably just happens to be the last thing in the chat being previewed which is incorrect.

**Comment by koko57** [comment]
@trjExpensify I can fix it here 🙂

**Comment by trjExpensify** [comment]
Okay, excellent. I've linked that thread here so we don't create a dupe issue.

**Comment by mountiny** [comment]
@koko57 Just wanted to point out this issue which was raised by Pavlo [here](https://github.com/Expensify/App/issues/30042#issuecomment-1903886902), lets focus on that one next in this case so we can remove the usage of the `originalMessage.amount` and `.currency`

**Comment by koko57** [comment]
ok! thanks for updating the list in the description!

**Comment by koko57** [comment]
Let's keep this issue open, there is still some work to be done 🙂

**Comment by mountiny** [comment]
@koko57 Can we please prioritize removing the usage of the originalMessage.amount/currency now? thank you!

**Comment by koko57** [comment]
@mountiny yes, of course! Not sure if I will be able to finish it this week, I'm ooo tomorrow, but I'll continue on Monday

**Comment by mountiny** [comment]
Merged, thank you! Also added this to the tracking https://github.com/Expensify/App/issues/35515

**Comment by koko57** [comment]
@mountiny yes, of course!

**Comment by koko57** [comment]
@mountiny I've found out that the problem with the user name showing for the edit system messages is because when we go offline and it's our first action we do for a particular request the `report.lastActorAccountID` is '0'. Because of that, we cannot hide the user name as the id is not the same as currentUserID. This problem occurs for all types of requests and changing anything offline for the first time. When online the report is updated and that's why we instantly see the proper message without the last actor's name (when the last actor is the current user).

So either we should update lastActorAccountID for the report optimistically or in the SidebarUtils we could fallback to reportAction.actorAccountID like this:

<img width="987" alt="Screenshot 2024-02-07 at 16 56 47" src="https://github.com/Expensify/App/assets/28020445/0d164bf7-b5e6-4175-bec2-dfd4eafc8f67">

[checked, it works, checking now for possible regressions]

but I wonder if there would be any case that we actually don't want to do that? 🤔

**Comment by mountiny** [comment]
@koko57 oh yeah that makes complete sense, I think the reports should optimistically update the `lastActorAccountID`

**Comment by koko57** [comment]
@mountiny nice, thanks! I'm testing these changes and on my way to submit the PR

**Comment by koko57** [comment]
@mountiny PR opened: https://github.com/Expensify/App/pull/36219

**Comment by koko57** [comment]
@mountiny just wanted to make sure before I make another PR - we want to display message's author name in group chats, don't we? 
Like this:
<img width="368" alt="Screenshot 2024-02-12 at 14 14 23" src="https://github.com/Expensify/App/assets/28020445/e47ed23e-5111-4b79-8508-3981ce5b65ed">

**Comment by mountiny** [comment]
@koko57 I assume that if its not you who sent the last message then yes

**Comment by koko57** [comment]
@mountiny thanks! so I'll be submitting a new PR shortly

**Comment by koko57** [comment]
I've checked it once again - now on staging on the search page we DO display lastActor name for the group chat, but we don't do it for the LHN. So by this fix we'll get rid of the inconsistency. 

Opened a draft PR: https://github.com/Expensify/App/pull/36591 but I need to cover one more case that I've spotted during retesting

**Comment by mountiny** [comment]
Thanks!

**Comment by koko57** [comment]
PR opened: https://github.com/Expensify/App/pull/36591

**Comment by koko57** [comment]
@mountiny on the [problem with description]([reference](https://expensify.slack.com/archives/C01GTK53T8Q/p1708610187601779)) - I can't reproduce it anymore, I guess it was fixed somewhere else.

So if it's fixed, when we merge https://github.com/Expensify/App/pull/36591 the last thing that is left here is: _unify the logic for getting alternateText for [getOptions](https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/libs/OptionsListUtils.js#L1063) and getOptionData (mentioned https://github.com/Expensify/App/pull/33966#discussion_r1444808394)_

As it's more a DX improvement (and actually a hard one to work on) can we deprioritize it? All the UX-related bugs are fixed.

**Comment by mountiny** [comment]
@koko57 Merged

I agree we can deprioritize the DX improvement. maybe we could separate it in its own issue and get someone else to look into this since you are focused on higher priority tasks

**Comment by mountiny** [comment]
Agata is ooo this week, not sure if there is anything left to do here. Going to wait for her to confirm

**Comment by mananjadhav** [comment]
@mountiny Can you assign me this issue for the C+ review?

**Comment by mountiny** [comment]
waiting for Agata to come back from ooo

**Comment by mountiny** [comment]
Created a new issue https://github.com/Expensify/App/issues/38220

@mananjadhav Can you please help me with the payment summary here?

**Comment by mananjadhav** [comment]
> @mananjadhav Can you please help me with the payment summary here?

@mountiny This got posted by the bot, is there anything else needed from me here? I can see multiple PRs previously here, and each of them has C+ assigned.

**Comment by mananjadhav** [comment]
quick bump here @mountiny. Meanwhile I am requesting my payout on the NewDot. Would be great if you can confirm the summary.

**Comment by mountiny** [comment]
@mananjadhav could you actually help me list out the PRs?

**Comment by mananjadhav** [comment]
@mountiny I can see 4 PRs overall linked with this issue:

@eVoloshchak reviewed the following, not sure if these are paid out. But both of them are merged more than a month ago:
- https://github.com/Expensify/App/pull/34872
- https://github.com/Expensify/App/pull/36219

@situchan reviewed https://github.com/Expensify/App/pull/35818, for which they're already paid.

I (@mananjadhav) reviewed https://github.com/Expensify/App/pull/36591

**Comment by mountiny** [comment]
I believe @eVoloshchak was not paid out but the two PRs were one original and second a regression fix. So I would say the payout would be $500 to @eVoloshchak 

For @mananjadhav I assume classic $500 then.

Sounds good?

**Comment by mananjadhav** [comment]
Sounds good. @mountiny

**Comment by JmillsExpensify** [comment]
$500 approved for @mananjadhav based on summary.

**Comment by adelekennedy** [comment]
@eVoloshchak based on the above I sent you a contract on Upwork

**Comment by eVoloshchak** [comment]
@adelekennedy, thanks! No need for Upwork though, I've just requested the payment via NewDot

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on summary.
