### ISSUE TITLE
Master Tracking - HelpDot Resource Organizaiton 

### ISSUE THREAD

**Issue by caitlinwhite1** [Expensify/App#34515]
**Phase 1** 

- [x] **Parse and categorize the remaining OldDot resources to be added to HelpDot**([GH]([Parse and categorize the remaining OldDot resources to be added to HelpDo](https://github.com/Expensify/Expensify/issues/357171)) - @abekkala @slafortune 
       1. Go through [this sheet](https://docs.google.com/spreadsheets/d/1k2NbDgE4OipW78fOFw2gVOjBdQDVrHIwASlWKrXGGsU/edit#gid=0), and mark which resources should or shouldn't be migrated by marking them in column A
       2. Plug the resources that should be migrated from [this sheet](https://docs.google.com/spreadsheets/d/1k2NbDgE4OipW78fOFw2gVOjBdQDVrHIwASlWKrXGGsU/edit#gid=1090529378) in column H of [this spreadsheet](https://docs.google.com/spreadsheets/d/1kX3YFro8VjdEssTAXECFpjjqPGA_FruDz0JZHj6oDXY/edit#gid=172916836) and mark them done in column B [here](https://docs.google.com/spreadsheets/d/1k2NbDgE4OipW78fOFw2gVOjBdQDVrHIwASlWKrXGGsU/edit#gid=1090529378).
       
- [ ] **Collect all existing and drafted NewDot resources and index them** - @aimeebarigian @caitlinwhite1 
       1. Check for assigned wave channels [here](https://docs.google.com/spreadsheets/d/1ogCtInLMKDUfD-Iczv5VtLLabKO2HtQj6TcIYaFBR-E/edit?pli=1#gid=1398185886)
       2. For each of your assigned waves, use available resources to identify HelpDot resrouces that are already written. The best 
       places for this are the dedicated slack channel and GH project board. 
       For example Wave 9 project board be found [here](https://github.com/orgs/Expensify/projects/96/views/1). Look through the 
      GH's within the project board to try and find any HelpDot resrouces mentioned. Check recent/daily updates for projects 
       mentioned and again any HelpDot resources mentioned. 
       4. Take all collected resources from your assigned wave and post to the dedicated slack channel. Tag the wave curator(this 
       should be listed in the channel details). Provide the list of HelpDot resrouces you were able to track down and ask them to list 
       any that aren't mentioned. 
       5. Once the list is for that channel is confirmed in slack, add them to the Master Tab of this spreadsheeet. 
        
**Phase 2** 

- [x]  **Passign the V2 articles off to Ren** - @abekkala @slafortune 
Post [this spreadsheet](https://docs.google.com/spreadsheets/d/1kX3YFro8VjdEssTAXECFpjjqPGA_FruDz0JZHj6oDXY/edit#gid=172916836) to slack in #expensifyhelp. Tag Ren and Maddy letting them know that column H of the V2 Category Structure tab is complete. From here Ren will take over and go through each article to spruce it up, and add the article to the appropriate Category of the Expensify Classic on HelpDot. You can close this [GH](https://github.com/orgs/Expensify/projects/105?pane=issue&itemId=49025985). 

- [ ] **Make note of which NewDot features are in the pipeline and confirm under which category those resources should be published** - @aimeebarigian @caitlinwhite1 
          1. Check for assigned wave channels [here](https://docs.google.com/spreadsheets/d/1ogCtInLMKDUfD-Iczv5VtLLabKO2HtQj6TcIYaFBR-E/edit?pli=1#gid=1398185886)
          2. build out project board for upcoming resources - discuss this new process in slack and post updates in relative channel
   

- [x] **Work with Ren on Expensify Classic Categories + Subcategories - @slafortune @abekkala** 
          1. Fill in column G [here](https://docs.google.com/spreadsheets/d/1kX3YFro8VjdEssTAXECFpjjqPGA_FruDz0JZHj6oDXY/edit#gid=172916836) with all relative HelpDot articles for the category listed 
          2. Compare columns B,C, and D[here](https://docs.google.com/spreadsheets/d/1kX3YFro8VjdEssTAXECFpjjqPGA_FruDz0JZHj6oDXY/edit#gid=172916836)  to [Ren's Expensify Classic Category doc](https://docs.google.com/document/d/1b4YUO1LfBVJFF7BlD77MyVb8PH30zN0LvzEXIaQ9uPQ/edit#heading=h.xpihf025rp0c) and make sure what he has listed on the right side match/make sense
           3. If anything is missing from when Ren has mapped out, raise in #expensifyhelp

**Comment by caitlinwhite1** [comment]
@abekkala @slafortune added your latest tasks for working with Ren under phase 2. Feel free to update if needed!

**Comment by caitlinwhite1** [comment]
@aimeebarigian We can start breaking down our steps for the new project board as part of phase 2 as well. I'll have a play around with the different categories we might need for that board today.

**Comment by maddylewis** [comment]
i feel like this is mostly done, so im going to close!
