### ISSUE TITLE
[Tracking] [Wave Collect] [Quick Action] NewDot: Quick Action Button

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#34802]
[Design Doc](https://docs.google.com/document/d/1Fa-sKBcROi1fjpZnHMUZ3J6Q96yXCEfU-ex14e_wdns/edit#heading=h.mnjguil21u0a)

## Proposal
[WN](https://expensify.slack.com/archives/CC7NECV4L/p1705502921746179)
**Strategy:** We’re migrating customers to our new superapp where an abundance of choice and feature discovery is at the forefront to encourage them to “land and expand” across a growing number of use cases. That said, it’s crucial that we maintain the streamlined usability our existing customers know and love. Getting the balance right is important for both the success of reunification, and the long term usability of our superapp.

**Problem:** We’ve over indexed Global Create to optimise for feature discovery, at the expense of our core use cases. Put plainly, it takes more steps to scan a receipt in NewDot than it does on the OldApp. This is important to address now as migration plans are in progress, to avoid the “first look” of our new app being one that adds more time and effort to perform an action taken a thousand times before, increasing the likelihood to return to Classic. Needless to say, this is already coming up with our employees as early adopters.

**Solution:** Add a quick action button to the bottom of global create. The button will record the last action you took (i.e Request Money > Scan) and the destination for it (i.e To: Duraflame, Inc.). When used for submitting receipts to a workspace like this example, we’ll also stop showing the confirmation page to enter additional expense details unless the workspace has required categories or tags for coding, a la “fire and forget” in OldApp.

## Tasks

- [x] Post **Proposal (full Problem/Solution statement)** in `#whatsnext`
- [x] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [x] Paste Proposal in the space above with a link to the Slack thread
- [x] Email `strategy@expensify.com` and paste in the Proposal
- [x] Fill out the **High-level overview of the problem**, **Timeline**, and **Terminology** sections of the Design Doc
- [x] Email `strategy@expensify.com` (continue the same email chain as before) with the link to your Design Doc
- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [x] Fill out the **High-level of proposed solution** section
- [x] Email `stategy@expensify.com` again with links to the doc and pre-design conversation in Slack
- [x] Add the `DesignDocReview` label to get the **High-level of proposed solution** section reviewed
- [x] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.
- [x] Fill out the **Detailed implementation of the solution** and related sections.
- [x] Re-add the `DesignDocReview` label to this issue
- [x] Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase
- [x] Implement the changes
- [x] Add regression tests so that QA can test your feature with every deploy ([instructions](https://stackoverflowteams.com/c/expensify/questions/363)) ([GH](https://github.com/Expensify/Expensify/issues/392634))
- [x] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

## Implementation Issues
- [x] https://github.com/Expensify/Expensify/issues/377599
- [x] https://github.com/Expensify/Expensify/issues/377602
- [x] https://github.com/Expensify/App/issues/38048
- [x] https://github.com/Expensify/App/issues/38050
- [x] https://github.com/Expensify/App/issues/38051
- [ ] https://github.com/Expensify/App/issues/38054
- [x] https://github.com/Expensify/Expensify/issues/377606
- [x] https://github.com/Expensify/Expensify/issues/386006
- [ ] https://github.com/Expensify/Expensify/issues/385309
- [x] https://github.com/Expensify/Expensify/issues/386320
- [x] https://github.com/Expensify/Expensify/issues/378892
- [x] https://github.com/Expensify/App/issues/40282

**Comment by trjExpensify** [comment]
Pre-design [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1706198053588819). Threads are dying down, plan to get the HL doc together by the start of next week.

**Comment by trjExpensify** [comment]
>plan to get the HL doc together by the start of next week.

Alrighty, ideal nav ended up being ready to launch last week, so it knocked my timeline out by a couple of days. But the HL is now out for review.

**Comment by mountiny** [comment]
I have read and reviewed this Design Doc!

**Comment by jliexpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by Gonals** [comment]
I have read and reviewed this Design Doc!

**Comment by Julesssss** [comment]
I have read and reviewed this Design Doc!

**Comment by dylanexpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by davidcardoza** [comment]
I have read and reviewed this Design Doc!

**Comment by trjExpensify** [comment]
Updated to #wave6, as we switch these features over from wave5 to wave6.

**Comment by LLPeckham** [comment]
I have read and reviewed this Design Doc!

**Comment by slafortune** [comment]
I have read and reviewed this Design Doc!

**Comment by cead22** [comment]
I have read and reviewed this Design Doc!

**Comment by JmillsExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by heyjennahay** [comment]
I have read and reviewed this Design Doc!

**Comment by ryanschaffer** [comment]
I have read and reviewed this Design Doc!

**Comment by isabelastisser** [comment]
I have read and reviewed this Design Doc!

**Comment by trjExpensify** [comment]
We have sufficient reviews, and @Gonals has made a start on the detailed!

**Comment by puneetlath** [comment]
I have read and reviewed this Design Doc!

**Comment by johncschuster** [comment]
I have read and reviewed this Design Doc!

**Comment by cead22** [comment]
I have read and reviewed this Design Doc!

**Comment by slafortune** [comment]
I have read and reviewed this Design Doc!

**Comment by ryanschaffer** [comment]
I have read and reviewed this Design Doc!

**Comment by nkuoch** [comment]
I have read and reviewed this Design Doc!

**Comment by garrettmknight** [comment]
I have read and reviewed this Design Doc!

**Comment by Gonals** [comment]
Issues created:

- [ ] https://github.com/Expensify/Expensify/issues/377599
- [ ] https://github.com/Expensify/Expensify/issues/377602
- [ ] https://github.com/Expensify/App/issues/38048
- [ ] https://github.com/Expensify/App/issues/38050
- [ ] https://github.com/Expensify/App/issues/38051
- [ ] https://github.com/Expensify/App/issues/38054
- [ ] https://github.com/Expensify/Expensify/issues/377606

**Comment by marcochavezf** [comment]
I have read and reviewed this Design Doc!

**Comment by techievivek** [comment]
I have read and reviewed this Design Doc!

**Comment by trjExpensify** [comment]
Wahoo! Let's get it! Few questions for yah here: https://expensify.slack.com/archives/C036QM0SLJK/p1710290076770649?thread_ts=1710203466.272029&cid=C036QM0SLJK

**Comment by Gonals** [comment]
- Auth PR in review
- PHP PR in review (although unrelated tests are failing, but we don't need it to move on with App stuff)
- Starting with App PRs tomorrow

**Comment by trjExpensify** [comment]
Update here: https://expensify.slack.com/archives/C036QM0SLJK/p1710800428559829

**Comment by trjExpensify** [comment]
Still cracking through the issues. https://github.com/Expensify/App/issues/38050 is the focus right now.

**Comment by quinthar** [comment]
I have read and reviewed this Design Doc!

**Comment by mountiny** [comment]
I have read and reviewed this Design Doc!

**Comment by Gonals** [comment]
Working on Skipping confirmation! It is being a bit more cumbersome than expected!

**Comment by Gonals** [comment]
Skipping confirmation finally in review! https://github.com/Expensify/App/pull/39413

I'll start adding tracking stuff soon

**Comment by trjExpensify** [comment]
Latest update [here](https://expensify.slack.com/archives/C036QM0SLJK/p1712620108231099).

**Comment by trjExpensify** [comment]
Latest [here](https://expensify.slack.com/archives/C036QM0SLJK/p1713194565060919).

**Comment by Gonals** [comment]
Current PR situation:

Issues created:

- [x] https://github.com/Expensify/Expensify/issues/377599 
- [x] https://github.com/Expensify/Expensify/issues/377602
- [x] https://github.com/Expensify/App/issues/38048
- [x] https://github.com/Expensify/App/issues/38050
- [ ] https://github.com/Expensify/App/issues/38051
- [ ] https://github.com/Expensify/App/issues/38054
- [ ] https://github.com/Expensify/Expensify/issues/377606
- [x] https://github.com/Expensify/Expensify/issues/386006
- [ ] https://github.com/Expensify/Expensify/issues/385309
- [ ] https://github.com/Expensify/Expensify/issues/386320
- [ ] https://github.com/Expensify/Expensify/issues/378892

**Comment by trjExpensify** [comment]
Latest [here](https://expensify.slack.com/archives/C036QM0SLJK/p1713799275136129).

**Comment by trjExpensify** [comment]
Latest [here](https://expensify.slack.com/archives/C036QM0SLJK/p1713799275136129). We're launch ready!

**Comment by trjExpensify** [comment]
Latest here. TL;DR - just the [educational tooltip polish PR](https://expensify.slack.com/archives/C036QM0SLJK/p1714400587768059) to go.

**Comment by trjExpensify** [comment]
- Educational tooltip PR still in review
- Regression tests have been handed over to Applause

**Comment by trjExpensify** [comment]
QA are adding regression tests and we have the educational tooltip polish PR deep in review!

**Comment by trjExpensify** [comment]
Regression tests have been added, checking in on the tooltip.

**Comment by trjExpensify** [comment]
Tooltip PR super close, that's it to close this out.

**Comment by trjExpensify** [comment]
No change, merge freeze now.

**Comment by trjExpensify** [comment]
Bumped @tienifr today on the final feedback.

**Comment by trjExpensify** [comment]
Checked-in on the tooltip.

**Comment by trjExpensify** [comment]
Conflicts to resolve, bumped on those and resolution of this final bug in the tooltip PR.

**Comment by trjExpensify** [comment]
[Latest](https://github.com/Expensify/App/pull/40066#issuecomment-2158454949).

**Comment by trjExpensify** [comment]
[Latest](https://github.com/Expensify/App/pull/40066#issuecomment-2165055464).

**Comment by trjExpensify** [comment]
[Latest](https://github.com/Expensify/App/pull/40066#pullrequestreview-2125880717). Over to Rocio and Alberto and we can finally get that merged. 🙏

**Comment by trjExpensify** [comment]
PR has been merged! @Gonals, all set to send the wrap-up for the project and close this out. :)

**Comment by trjExpensify** [comment]
Wrap-up sent. Couple of days to go on the regression period for the tooltip polish, and then we'll close this.

**Comment by trjExpensify** [comment]
Regression period over, closing!
