### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] Workspace - Unable to select members after adding them to the workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34828]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1,Navigate to Settings > Profile > Contact Method > New Contact Method > Add Email
2, change the new email as the default contact
3, Copy the main email and remove it
4, Go to Settings > Workspace > Members > click on Invite> then paste the main email or search for the email used to create the account
5, Add the email, click on the checkbox, and observe that it remains unselected

## Expected Result:
After changing the default email and removing the main contact email (used to create the Expensify account), adding the main contact address to the workspace as a member should either be selected or not allowed

## Actual Result:
After changing the default email and removing the main contact email, attempting to select the main contact address as a member in the workspace by clicking on the checkbox is not work

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/75ded569-c226-4f1d-b8e1-64c6c54eea5d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01285e5476dd516a43</li>
        <li>Upwork Job ID: 1748410004851982336</li>
        <li>Last Price Increase: 2024-01-26</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave 8. 
CC @zanyrenney

**Comment by greg-schroeder** [comment]
Awaiting proposal review @0xmiroslav

**Comment by greg-schroeder** [comment]
@sobitneupane said he's working partially this week, let's try to get this one reviewed ASAP once you're back though!

**Comment by DylanDylann** [comment]
I can take over this issue as C+ contributor if @sobitneupane didn't start on it

**Comment by greg-schroeder** [comment]
Thanks Sobit!

**Comment by sobitneupane** [comment]
Thanks for the proposal @tienifr.

Are we using `policy.owner` else where? If so, we should update `policy.owner` optimistically. Additionally, after refreshing or signing in again, does the policy.owner received from the API reflect the updated information, or does it still show the old data?

**Comment by sobitneupane** [comment]
Thanks for the update @tienifr 

[Proposal](https://github.com/Expensify/App/issues/34828#issuecomment-1901729736) from @tienifr looks good to me.

🎀 👀 🎀 C+ reviewed.

**Comment by greg-schroeder** [comment]
@youssef-lr can you please confirm the C assignment as soon as you're able? Thanks!

https://github.com/Expensify/App/issues/34828#issuecomment-1921328469

**Comment by youssef-lr** [comment]
on it tomorrow @greg-schroeder!

**Comment by greg-schroeder** [comment]
Bump @youssef-lr

**Comment by youssef-lr** [comment]
While fixing does work, it will be fixing a symptom as this should be fixed in the backend. We should be sending an updated `owner` once the main email is removed. This will ensure wherever other parts of the code using `policy.owner` will also work.

>By the way, when creating the workspace, we need to set the ownerAccountID optimistically (currently we don't)

I'm not sure this is possible, the `accountID` is an ID generated from the backend, if we generate it in the frontend it will just be replaced once we get a response from the backend. It's not similar to reportIDs or reportActionIDs that are random IDs. The accountID is sequential.

**Comment by greg-schroeder** [comment]
discussion ongoing, not overdue

**Comment by greg-schroeder** [comment]
Thoughts about the above @youssef-lr?

**Comment by youssef-lr** [comment]
Sounds good @tienifr, let's go with using the `ownerAccountID` as well as updating the policy owner optimistically.

**Comment by greg-schroeder** [comment]
done

**Comment by youssef-lr** [comment]
@tienifr I think $500 is still a fair price given that the original change was straightforward.

**Comment by greg-schroeder** [comment]
Processing

**Comment by greg-schroeder** [comment]
@sobitneupane $500 (manual request)
@tienifr $500 (paid)

Next up is the checklist!

**Comment by greg-schroeder** [comment]
@sobitneupane quick bump on the checklist so we can close this out!

**Comment by youssef-lr** [comment]
Waiting on @sobitneupane

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

I guess it was missed while refactoring to use accountID.

> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

N/A
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

N/A 
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Navigate to Settings > Profile > Contact Method > New Contact Method > Add Email
2. Change the new email as the default contact
3. Copy the main email and remove it
4. Go to Settings > Workspace > Members > click on Invite> then paste the main email or search for the email used to create the account
5. Add the email, click on the checkbox, and verify that it's selected

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment]
Requested payment in newDot.

Payment Summary: https://github.com/Expensify/App/issues/34828#issuecomment-1995674640

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on summary.

**Comment by greg-schroeder** [comment]
Filed test, closing
