### ISSUE TITLE
[PAID, WAITING ON SITU FOR CHECKLIST] [$500] Account - Account is not simultaneously signed out on secondary device when closing account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36632]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Sign in to main device and secondary device with the same account
2. Close account on main device
3. Navigate to secondary device

## Expected Result:
* Account should be signed out on the secondary device simultaneously
* There should be 'Account closed successfully' message under email input field
* There shouldn't be console log error

## Actual Result:
* Account is not signed out before user interacts with the account
* There is no 'Account closed successfully' message under email input field
* There is console log error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9397c990-6ec4-4c25-8b51-5201392bdee7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011fa63892ed79f932</li>
        <li>Upwork Job ID: 1758227147283243008</li>
        <li>Last Price Increase: 2024-02-22</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>wildan-m | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by brandonhenry** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When an account is closed on one device, the account does not simultaneously sign out on a secondary device. Additionally, there is no "Account closed successfully" message displayed under the email input field on the secondary device, and there is an error logged in the console.

### What is the root cause of that problem?
The root cause appears to be a lack of real-time session management across multiple devices. The current system does not seem to notify or force logout on all active sessions once an account is closed. This might be due to the session tokens not being invalidated across the system or the secondary device not polling for session validity in real-time.

### What changes do you think we should make in order to solve the problem?

- Implement a push notification system that informs all active sessions when an account is closed, prompting immediate sign out.
- Invalidate the session tokens at the server level once an account closure action is initiated, preventing further API calls from a closed account.
- Ensure that the secondary device listens for account status changes and responds accordingly by signing the user out and displaying the appropriate account closure message.
- Address the console log error by ensuring proper error handling and messaging across the application.

### What alternative solutions did you explore? (Optional)
An alternative approach could involve periodically checking the validity of the session token against the server, but this could introduce unnecessary network requests and latency. Maybe do so but with a max retry count.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

When an account closed, it will return this onyx update:
```
    {
        "onyxMethod": "clear"
    },
```

It doesn't have key property

This code call includes without null check

https://github.com/Expensify/App/blob/20af9e52db6031dea6d0086a6692682eb15e422a/src/libs/actions/User.ts#L491


### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/20af9e52db6031dea6d0086a6692682eb15e422a/src/libs/actions/User.ts#L491

```
    const reportActionsOnly = pushJSON.filter((update) => update.key?.includes('reportActions_'));
```

### What alternative solutions did you explore? (Optional)

**Comment by wildan-m** [comment]
Proposal [Updated](https://github.com/Expensify/App/issues/36632#issuecomment-1949642667)

Add alternative solutions

**Comment by situchan** [comment]
Thanks for the proposals everyone.
@brandonhenry the root cause is not correct
@wildan-m you considered only 1 issue in RCA while 3 issues total
@suneox your proposal is almost close but I'm not sure it's the right place to trigger signout manually.

**Comment by wildan-m** [comment]
@situchan [my proposal updated](https://github.com/Expensify/App/issues/36632#issuecomment-1949642667) with result video. I feel the result cover all of three cases.

**Comment by situchan** [comment]
@wildan-m the root cause is still not updated

**Comment by wildan-m** [comment]
@situchan My [Proposal updated](https://github.com/Expensify/App/issues/36632#issuecomment-1949642667).

It provides further clarification on the underlying issue, enhanced resolution, and the rationale behind avoiding calling `signOut` on the secondary device.

**Comment by jliexpensify** [comment]
Waiting on @situchan to re-review

**Comment by situchan** [comment]
reviewing updated proposal today

**Comment by situchan** [comment]
@wildan-m's [proposal](https://github.com/Expensify/App/issues/36632#issuecomment-1949642667) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by chiragsalian** [comment]
Proposal LGTM, feel free to create the PR @wildan-m.

**Comment by wildan-m** [comment]
@situchan @chiragsalian thanks for the assignment.

I have questions. When we close high traffic account, do we need to request HT account activation again when we log back in? Will previous chats be deleted?

**Comment by wildan-m** [comment]
@situchan @chiragsalian [the PR](https://github.com/Expensify/App/pull/37481) is ready.

**Comment by chiragsalian** [comment]
> When we close high traffic account, do we need to request HT account activation again when we log back in?

**Comment by chiragsalian** [comment]
> When we close high traffic account, do we need to request HT account activation again when we log back in?

I'm not 100% sure but I'm pretty sure you would have to request it again once you reopen the account. But why are you testing with the HT account. Won't it be easier to test this issue with non HT accounts.

**Comment by situchan** [comment]
Maybe they wanna check this off

- [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).

I think it's fine as this bug is not related to HT account

**Comment by wildan-m** [comment]
@chiragsalian thank you for the confirmation. I have used my HT account for testing, could you assist me in re-assigning it to the HT account?

wildevemail+1@gmail.com

**Comment by wildan-m** [comment]
@chiragsalian, please ignore my earlier request. [This form](https://docs.google.com/forms/d/e/1FAIpQLScpiS0Mo-HA5xHPsvDow79yTsMBgF0wjuqc0K37lTK5fheB8Q/viewform) is automated to assign tasks promptly.

**Comment by wildan-m** [comment]
@jliexpensify @chiragsalian @situchan seems no regression here?

**Comment by jliexpensify** [comment]
Hi @wildan-m correct, I'll be paying now (no need to tag us!) 

Bump @situchan to complete the checklist.

**Comment by jliexpensify** [comment]
Payment Summary

- C: @wildan-m $500
- C+: @situchan $500

[Upwork job](https://www.upwork.com/jobs/~011fa63892ed79f932)

**Comment by jliexpensify** [comment]
Paid and job closed, waiting on checklist form Situ.

**Comment by situchan** [comment]
Offending PR with comment: https://github.com/Expensify/App/pull/31055/files#r1525621084
As this was caught by QA team, we can skip regression test.
