### ISSUE TITLE
[BZ checklist] [$500] [Held requests] IOS - Hold Request - Keyboard is up but the field is not focused with error message showing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36948]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Create a manual request from any user
3. Navigate to request details page
4. Tap 3-dot menu > Hold request
5. Close the menu
6. Tap 3-dot menu > Hold request

## Expected Result:
The "Reason" field will be focused

## Actual Result:
Keyboard is up but the field is not focused with error message showing up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/166e2bb8-8844-4071-8358-3b4d96e79eff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014db792b47c7bf65e</li>
        <li>Upwork Job ID: 1760046429209067520</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by situchan** [comment]
This is polish than bug. Not deploy blocker

**Comment by neil-marcellini** [comment]
I agree that it's not a blocker because this is a new feature that isn't on production yet, and it's a very minor issue. I will make it external and get a C+ started reviewing proposals.

**Comment by situchan** [comment]
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/36948#issuecomment-1955100173) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by situchan** [comment]
@Krishna2323 in this issue, let's fix other similar pages with the same root cause.
i.e. I found WorkspaceProfileDescriptionPage

**Comment by ikevin127** [comment]
I agree that @Krishna2323's solution goes by the [docs](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#how-do-i-auto-focus-a-textinput-using-usefocuseffect), but in this case the TextInput [`shouldDelayFocus`](https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/components/TextInput/BaseTextInput/index.native.tsx#L85-L99) logic doesn't work as expected because of the navigation transition delay and I think fixing that as suggested by my proposal [here](https://github.com/Expensify/App/issues/37279#issuecomment-1966632703) is a more holistic approach instead of using the  `useAutoFocusInput` hook in every component where the issue occurs.

What do you guys think ?

cc @neil-marcellini @situchan @Krishna2323

**Comment by robertjchen** [comment]
Are we all set to move forward here, or is additional discussion required? 🙏

**Comment by robertjchen** [comment]
@neil-marcellini @situchan What do you think of the suggestion? 🙏 https://github.com/Expensify/App/issues/36948#issuecomment-1967047452

**Comment by neil-marcellini** [comment]
👀 taking a look now

**Comment by neil-marcellini** [comment]
> @Krishna2323's [proposal](https://github.com/Expensify/App/issues/36948#issuecomment-1955100173) looks good to me. 🎀 👀 🎀 C+ reviewed

I agree with @situchan. The proposal works and seems much more simple.

**Comment by bfitzexpensify** [comment]
@Krishna2323 please let us know when you'll be able to raise a PR - thanks!

**Comment by trjExpensify** [comment]
@Krishna2323 do we have an ETA to come out of draft with that PR? Thanks!

**Comment by situchan** [comment]
> @situchan, `WorkspaceProfileDescriptionPage` autofocus works fine, should we change it? We are using `autoFocus` prop in multiple places, do we want to change it in all places?

It's ideal to fix all occurrences but too many. It's definitely increased scope.
@neil-marcellini what do you think? Should we fix only reported pages or all throughout the app?

**Comment by robertjchen** [comment]
In the interest of time, let's just move forward with just the reported pages for now 🙏

**Comment by trjExpensify** [comment]
Automation didn't run. Needs payment on 3rd April.

**Comment by trjExpensify** [comment]
Offers sent!

**Comment by trjExpensify** [comment]
Cool! Payment summary as follows: 

- $500 to @Krishna2323 for the fix - paid
- $500 to @situchan for the C+ review - offer sent

**Comment by bfitzexpensify** [comment]
Payment to @situchan done. 

@situchan, adding a manual BZ checklist here - please complete! Thanks

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@situchan] The PR that introduced the bug has been identified. Link to the PR:
 [@situchan] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
 [@situchan] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
 [@situchan] Determine if we should create a regression test for this bug.
 [@situchan] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
 [@bfitzexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by bfitzexpensify** [comment]
Bump on the BZ checklist @situchan - thank you

**Comment by bfitzexpensify** [comment]
Bumping again @situchan - thank you!

**Comment by bfitzexpensify** [comment]
Still OOO, will bump when back.

**Comment by bfitzexpensify** [comment]
I'm going to close this one out myself. 

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x]  The PR that introduced the bug has been identified. Link to the PR: polish, not a bug - https://github.com/Expensify/App/issues/36948#issuecomment-1955162300
- [x]  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x]  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  Determine if we should create a regression test for this bug. No need, minor bug
- [x]  If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
- [x]  Link the GH issue for creating/updating the regression test once above steps have been agreed upon: N/A
