### ISSUE TITLE
[Checklist and NewDot C+ payment][$500] Distance - Distance request briefly shows local currency instead of workspace currency after creating it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37643]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Default workspace currency is different from local currency
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Request money > Distance
4. Create a distance request

## Expected Result:
The amount in distance request preview in the main chat will show default workspace currency

## Actual Result:
The amount in distance request preview in the main chat briefly shows local currency

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/20458bc8-834d-47ab-b012-28386673e607

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a112a7314639b9b</li>
        <li>Upwork Job ID: 1765247495001948160</li>
        <li>Last Price Increase: 2024-03-06</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When creating a distance request, the user's local currency code is shown in the preview instead of the workspace currency.

### What is the root cause of that problem?
When creating a distance request, we already calculate the distance amount and include the workspace currency here.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L349-L350

The currency is taken from the workspace mileage rate.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L251

However, there are 2 places where the currency is overwritten with the local currency.

First, when we arrive at the distance confirmation page, the manual (amount) tab is unmounted. This will trigger this `useEffect` clean up which sets the transaction currency with the original currency. The original currency is the user local currency.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/pages/iou/request/step/IOURequestStepAmount.js#L106-L113

Second, when the confirmation page is mounted, we check if the transaction contains an `originalCurrency` attribute, if yes, the transaction currency is set to `originalCurrency`.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/pages/iou/request/step/IOURequestStepConfirmation.js#L111-L118

They assume that when the user arrives, the `originalCurrency` is already removed from the transaction because we clear it when pressing the Next button, but **only** from the **manual** page/tab.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/pages/iou/request/step/IOURequestStepAmount.js#L136
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/libs/actions/IOU.ts#L294-L296

### What changes do you think we should make in order to solve the problem?

I see that this `originalCurrency` logic is only being used for manual case because both scan and distance don't have an amount input, so it makes sense to check whether the request is manual or not before doing the cleanup. Also, we need to clear the `originalCurrency` when pressing the Next button in distance tab.

```js
> IOURequestStepConfirmation
useEffect(() => {
    if (!transaction || !transaction.originalCurrency || requestType !== CONST.IOU.REQUEST_TYPE.MANUAL) {
        return;
    }
    // If user somehow lands on this page without the currency reset, then reset it here.
    IOU.setMoneyRequestCurrency_temporaryForRefactor(transactionID, transaction.originalCurrency, true);
}, []);

> IOURequestStepAmount
useEffect(() => (iouRequestTypeRef.current = iouRequestType), [iouRequestType]);

useEffect(() => {
    return () => {
        if (isSaveButtonPressed.current || iouRequestTypeRef.current !== CONST.IOU.REQUEST_TYPE.MANUAL) {
            return;
        }
        IOU.setMoneyRequestCurrency_temporaryForRefactor(transactionID, originalCurrency.current, true);
    };
}, []);

> IOURequestStepDistance
const navigateToNextStep = () =>
    IOU.setMoneyRequestOriginalCurrency_temporaryForRefactor(transactionID, null);
```

### What alternative solutions did you explore? (Optional)
The `originalCurrency` is basically being used to reset the transaction currency when the user cancels editing the amount, I don't see it being useful for the start page. So, we can ignore the `originalCurrency` effect when we are not editing amount.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/pages/iou/request/step/IOURequestStepAmount.js#L99-L113

Currently, we check for `backTo` params to check whether it's an amount edit page or not, so I'm gonna use that too for now.

```
useEffect(() => {
    if (!backTo) return;
    ...restOfTheCode
}, [])
```

Then, we don't need the changes on other pages anymore.

**Comment by kadiealexander** [comment]
Not overdue!

**Comment by kadiealexander** [comment]
@sobitneupane please review the proposal from @bernhardoj.

**Comment by sobitneupane** [comment]
Thanks for the [proposal](https://github.com/Expensify/App/issues/37643#issuecomment-1974732849) @bernhardoj.

We can go with your alternative proposal. Let's define a variable `isEditing` and we can use it in https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/pages/iou/request/step/IOURequestStepAmount.js#L166

The code was introduced by https://github.com/Expensify/App/pull/34075 to solve https://github.com/Expensify/App/issues/33608 issue.

🎀 👀 🎀 C+ reviewed

**Comment by roryabraham** [comment]
neither proposal is very clear to me tbh

**Comment by roryabraham** [comment]
Ok, I think think is pretty confusing because there are so many places where data is being modified in `useEffect` callbacks. I also think checking for the presence of a `backTo` param to see if we're manually editing a field feels like a really convoluted approach that's very tightly coupled to our UI flows.

**Comment by roryabraham** [comment]
> However, there are 2 places where the currency is overwritten with the local currency.

Can someone explain to me what would happen if we were to just remove these effects completely?

- https://github.com/Expensify/App/blob/b051dc40de616cabf8c0bb46312526d74963ca31/src/pages/iou/request/step/IOURequestStepAmount.js#L99-L113
- https://github.com/Expensify/App/blob/005580dca9cc82c4a5ba720af337513e553e2d9f/src/pages/iou/request/step/IOURequestStepConfirmation.js#L111-L118

**Comment by bernhardoj** [comment]
@roryabraham 

The first one is to revert the currency to the "draft" (original) currency.

https://github.com/Expensify/App/assets/50919443/e86feb59-bb7f-4eff-9374-6f6c25205776

If we remove it, then the currency will be updated even without pressing the Save button (on the edit page).

I believe the second one is to mimic the behavior of the previous version of the money request page. Currently, when we select a currency from the currency selection page, it will immediately be saved to the transaction draft.

If the user directly accesses the confirmation page (by changing the URL), the second `useEffect` will revert the currency to the "draft" (original) currency.

1. Open the money request page
2. Change the currency from A to B (originalCurrency is A, currency is B)
3. Change the URL to the confirmation page
4. The second `useEffect` will kick in and the currency shown will be currency A (originalCurrency)

Previously, the currency would only be saved when we pressed the Next button, so if the user directly accessed the page, the user would see the first currency.
1. Open the money request page
2. Change the currency from A to B (currency is A)
3. Change the URL to the confirmation page
4. The currency shown will be currency A (currency)

If we remove it, then we will see the updated currency on confirmation page.

https://github.com/Expensify/App/assets/50919443/1d5898f1-4c42-473b-87fc-facda1e8a333

**Comment by bernhardoj** [comment]
> I also think checking for the presence of a backTo param to see if we're manually editing a field feels like a really convoluted approach that's very tightly coupled to our UI flows.

Currently, the edit amount and the start amount page use the same component, IOURequestStepAmount. What if we create a new one for edit, IOURequestStepEditAmount, which just uses IOURequestStepAmount and passes `isEditing` props to it?

**Comment by roryabraham** [comment]
Thanks for taking the time to explain @bernhardoj

> The first one is to revert the currency to the "draft" (original) currency

Where is it getting saved? I think this should only happen when you click the save button. Rather than what we have now, which is:

- it's "immediately" saved
- if we leave without clicking the save button, we revert it back
"

which is much more confusing than just saving it when you click the save button.

This feels like the root cause of our issues in both cases. What do you think?

**Comment by bernhardoj** [comment]
@roryabraham 

> Where is it getting saved? 

When we pick a currency.
https://github.com/Expensify/App/blob/37a2dbb9dd5e89d61210feb0eb1de3a80cb6ca6d/src/pages/iou/request/step/IOURequestStepCurrency.js#L80-L84

Actually, my comment about the second `useEffect` is a bit misleading. In the previous version, if we were at the start page, selecting a currency will immediately save it to the transaction draft. 

However, if we were editing the currency, we just go back to the edit amount page with the currency added to the params. Pressing the save button will save the currency from the params.

<img width="609" alt="image" src="https://github.com/Expensify/App/assets/50919443/81764b7b-35e1-4985-a78e-036af61a54f2">

> I think this should only happen when you click the save button

I also prefer this one (using the params approach). What about we revert https://github.com/Expensify/App/pull/34075 and fix the issue that the PR is trying to solve? The issue is very simple to fix, we just need to pass the selected currency to the params and use it when it's available in currency selection page,

```
const currency = currencyFromParams || currencyFromTransaction;
```

just like we did before in the amount page.
<img width="604" alt="image" src="https://github.com/Expensify/App/assets/50919443/8e6cc6c2-837b-42f1-b269-09e87de33f50">

**Comment by kadiealexander** [comment]
Not overdue, @roryabraham any thoughts on the above?

**Comment by sobitneupane** [comment]
@roryabraham [Those](https://github.com/Expensify/App/issues/37643#issuecomment-1992691184) useEffects were introduced by [this PR](https://github.com/Expensify/App/pull/34075) to resolve https://github.com/Expensify/App/issues/33608

One way would be to revert the changes made by https://github.com/Expensify/App/pull/34075 and solve https://github.com/Expensify/App/issues/33608 issue with a different approach.

**Comment by roryabraham** [comment]
I like the idea of reverting https://github.com/Expensify/App/pull/34075, and the two `useEffects` I linked above, and solving this and the old issue https://github.com/Expensify/App/issues/33608 with a different approach, such as using route params as suggested in @bernhardoj's last comment.

However, so far we don't have a proposal on this issue outlining such an approach clearly.

**Comment by bernhardoj** [comment]
I have updated my [proposal](https://github.com/Expensify/App/issues/37643#issuecomment-1974732849) to include the revert and fix the old issue as the main solution and moved the previous main solution as the 2nd alternative.

**Comment by sobitneupane** [comment]
> To solve it, we can allow the currency picker page to accept the currency from params and transaction object, similar to what we do in [the old amount page](https://github.com/Expensify/App/pull/34075/files#diff-e1e89aa3b5e5f657041e6428082dc1d13c8b6471df5d867796993f3c06c99740L59-L71).

@bernhardoj Can you please add more explanation about the solution of the [issue](https://github.com/Expensify/App/issues/33608). Please also add details on where will you make changes.

I like the idea you are proposing. If we are okay with passing currency through param, your proposal should do the job.

Challenges that we might face with the solution are:
- Direct revert of the PR doesn't look likely as it was two months old PR. We should be careful of the changes that are made after that PR.
- How will we handle the case where invalid currency is used as currency param in direct link?

**Comment by bernhardoj** [comment]
> Direct revert of the PR doesn't look likely as it was two months old PR

Yes, we need to manually do it.

> How will we handle the case where invalid currency is used as currency param in direct link?

We can check whether the currency is valid or not, just like we did on this old money request page
https://github.com/Expensify/App/blob/1f3e31fae69a168dd4f76a91faf257c33e334364/src/pages/iou/steps/NewRequestAmountPage.js#L70

> Can you please add more explanation about the solution of the https://github.com/Expensify/App/issues/33608. Please also add details on where will you make changes.

Added the component name and the code to handle invalid currency

**Comment by sobitneupane** [comment]
Thanks for the update @bernhardoj 

@roryabraham I think we can go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/37643#issuecomment-1974732849)

**Comment by roryabraham** [comment]
Thanks for iterating on this a bit, feeling better about where we landed

**Comment by bernhardoj** [comment]
PR is ready

cc: @sobitneupane

**Comment by roryabraham** [comment]
PR was merged yesterday

**Comment by s77rt** [comment]
This one is a false alert https://github.com/Expensify/App/issues/37643#issuecomment-2067787598 sorry for that

**Comment by roryabraham** [comment]
@kadiealexander the [PR](https://github.com/Expensify/App/pull/38892) was deployed to production on 2024-04-22, so the next step is to pay this out on Monday 2024-04-29

**Comment by kadiealexander** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@sobitneupane] Determine if we should create a regression test for this bug.
- [ ] [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment]
### Payment Summary
- Contributor: @bernhardoj due $500 via [Upwork](https://www.upwork.com/nx/wm/workroom/36766845/overview?nav_dir=pop)
- Reviewer: @sobitneupane owed $500 via NewDot

#### BugZero Checklist (@kadiealexander)
- [x] I have verified the correct assignees and roles are listed above and updated the neccesary manual offers
- [x] I have verified that there are no duplicate or incorrect contracts on Upwork for this job (https://www.upwork.com/ab/applicants//hired)
- [x] I have paid out the Upwork contracts or cancelled the ones that are incorrect
- [x] I have verified the payment summary above is correct

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/34075
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/34075#issuecomment-2097917879
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.
Yes

> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

Prerequisite: Have a workspace with a currency set to different currency than your local currency

1. Open the workspace chat
2. Create a new distance request
3. Verify the distance request preview shows the workspace currency

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment]
Requested payment in newDot.

**Comment by kadiealexander** [comment]
Regression test: https://github.com/Expensify/Expensify/issues/394860

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane
