### ISSUE TITLE
[Awaiting checklist and C+ payment][$500] Android - Sign-in page flickers after using autofill

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38347]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
precondition: user has saved credentials on the device
1. Open the app
2. Tap the email address field
3. Select any saved credentials

## Expected Result:
The credentials are pasted in the field with no flickering

## Actual Result:
The page flickers after pasting the credentials

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/07d43ce3-93b7-4b8b-813c-9e3524f288d9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c54bb0a7e9ff28d4</li>
        <li>Upwork Job ID: 1768503077693136896</li>
        <li>Last Price Increase: 2024-03-22</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp 
CC @quinthar

**Comment by lanitochka17** [comment]
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
Production:


https://github.com/Expensify/App/assets/78819774/c79abb06-dcda-4b15-9315-48aca33e4f38

**Comment by omarnagy91** [comment]
### Proposal for Addressing Sign-in Page Flickering Issue

#### Problem Statement

We have encountered a flickering issue on the Android sign-in page when users utilize the autofill functionality to input their credentials. This behavior leads to a suboptimal user experience, as the page's elements rapidly re-render in quick succession, creating a visible flickering effect.

#### Root Cause Analysis

After a thorough investigation, the root cause of the flickering issue appears to be tied to two main factors within our  `BaseLoginForm`  component:

1.  **Rapid State Updates on Input Change**: The component's state is updated every time there's a change in the input field. Autofill triggers these updates almost instantaneously for each piece of autofilled information, leading to multiple state updates and consequent re-renders in a very short time frame.
    
    Relevant code snippet:
    
    ```    
    const onTextInput = useCallback(
        (text: string) => {
            setLogin(text);
            if (firstBlurred.current) {
                validate(text);
            }
            ...
        },
        [account, closeAccount, input, setLogin, validate],
    );
    ```
    
2.  **Immediate Validation on Input Change and Blur**: Our current logic executes validation on every input change after the first blur event. This validation, especially following an autofill action, triggers additional state updates and potentially more re-renders, exacerbating the flickering effect.
    
    Relevant code snippet:
    
```    
    if (firstBlurred.current) {
        validate(text);
    }
```

These factors combined result in a visible flickering effect due to the rapid and successive updates and re-renders of the component's state.

#### Proposed Changes

To mitigate the flickering issue and enhance the user experience on the sign-in page, the following changes are proposed:

1.  **Debounce Input Change Handler**: Implement a debounce mechanism for the input change handler. This will ensure that state updates (and subsequent validation) are not triggered by every single character change but rather after the user has stopped typing for a predefined interval. This approach will significantly reduce the number of state updates and re-renders, especially during autofill.
    
    Proposed code change:
    
    ```
    
    // Utilize lodash's debounce or a similar utility function
    const debouncedOnTextInput = useCallback(debounce((text) => {
        setLogin(text);
        if (firstBlurred.current) {
            validate(text);
        }
    }, 300), [setLogin, validate]); // 300ms debounce interval
    ```
2.  **Optimize Validation Logic**: Review and optimize the validation logic to ensure it is as efficient as possible. Consider delaying validation until a user action indicates that autofill has completed (e.g., user taps the submit button), rather than validating immediately after input changes.
    
    Proposed adjustment:
    
    ```
    // Adjust validation trigger to occur on form submission rather than immediate input change
    const onFormSubmit = () => {
        if (validate(login)) {
            // Proceed with form submission logic
        }
    };
    ```

    

#### Conclusion

By implementing the proposed changes, we aim to eliminate the flickering issue on the Android sign-in page, thereby improving the overall user experience. These adjustments will help ensure that the component handles autofill and user inputs more gracefully, with fewer unnecessary re-renders and a smoother visual experience

**Comment by allroundexperts** [comment]
@omarnagy91 Thanks for your proposal. Can you also share a video of these changes in action?

**Comment by kadiealexander** [comment]
Not overdue. @omarnagy91 bump!

**Comment by ikevin127** [comment]
Not able to reproduce!

I tried both on a real android device (OnePlus 7T) and emulator, both locally (dev) with latest main and also used adhoc build of recent main (18h ago) from [here](https://github.com/Expensify/App/pull/38710#issuecomment-2011979371). No dice reproducing this 🤔

**Comment by kadiealexander** [comment]
Requested a retest!

**Comment by ikevin127** [comment]
@kadiealexander Can you please ask for the tester to include steps for precondition:

> user has saved credentials on the device

And also mention what device they used and whether it was a real device or emulator.

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Sign-in page flickers when using Android 14's GBoard keyboard autofill functionality.

### What is the root cause of that problem?

> [!important]
> I was not able to reproduce this by following the OP steps but instead I was able to precisely replicate the behaviour:
>
> **Precondition**: User has saved credentials on the device.
> 1. Open the app.
> 2. Tap the email address field.
> 3. Long press on the autofill "Key".
> <img width="343" alt="Screenshot 2024-03-25 at 21 55 26" src="https://github.com/Expensify/App/assets/56457735/268dc8a4-5c55-4766-ba5f-483f8787930e">

<details>
<summary>Video (replicated behaviour)</summary>

https://github.com/Expensify/App/assets/56457735/a9684103-3a93-4355-b988-96234658558e

</details>

The reason why this flicker can be observed currently and wasn't before is because of a recent performance related issue (https://github.com/Expensify/App/issues/36645) and PR https://github.com/Expensify/App/pull/38093 introduced by me.

**What happens exactly ?**
1. In the OP video and also my own replica (reproduced with different steps), what happens is that for a split second app (state) goes into background then back to foreground, all this happens as a result of interacting with the GBoard autofill functionality (external from our app).

To illustrate this, in the following video I'm reproducing the behaviour in a slow manner by actually opening the GBoard autofill popover which causes the app (state) to go to background and return back to foreground when closing:

<details>
<summary>Video (illustrating 1.)</summary>

https://github.com/Expensify/App/assets/56457735/b83bee92-8b5a-4f05-a291-ad436a016fec

</details>

2. Because of this app state transition and the logic introduced recently by my PR, when app (state) is going into background we unmount the Lottie animation and instead show the empty view here:

https://github.com/Expensify/App/blob/fe0699c29437cc0e1c1829f8a895bfee80de0553/src/components/Lottie/index.tsx#L27-L29

What actually happens during the flicker is that the `SignInHeroImage` Lottie animation is unmounted because `appState.isBackground` is true which shifts the sign in page layout down for a split second, this can be observed in the OP video if played frame by frame:

<details>
<summary>OP video flicker (frame-by-frame)</summary>

https://github.com/Expensify/App/assets/56457735/b3b93017-5cf7-4732-9712-9b808da87efe

</details>

While the app state / Lottie animation unmount functionality introduced by me is the reason why this can be observed, the actual root cause of the issue is that within the Lottie component, we're not passing all the styles to the empty `View` which is being rendered when the Lottie animation is unmounted -> this causes the sign in page layout to move down when app goes into background briefly, which creates the flicker effect in our issue.

This happens on the sign in page because within the `SignInHeroImage` component, the Lottie animation has additional size related styles:

https://github.com/Expensify/App/blob/fe0699c29437cc0e1c1829f8a895bfee80de0553/src/pages/signin/SignInPageLayout/SignInHeroImage.tsx#L42

which are not passed to the Lottie component's empty `View` which is rendered when app goes into the background briefly.

### What changes do you think we should make in order to solve the problem?

Within the Lottie component, pass all the styles from the Lottie animation to the empty `View` component here:

https://github.com/Expensify/App/blob/fe0699c29437cc0e1c1829f8a895bfee80de0553/src/components/Lottie/index.tsx#L28

not only the `aspectRatioStyle` but all the animation `props.style` too, like so:

```diff
-    <View style={aspectRatioStyle} />
+   <View style={[aspectRatioStyle, props.style]} />
```

By doing this we make sure to pass all the Lottie animation styles coming from the upstream components -> to the empty `View` so that when we're unmounting the animation and displaying the `View`, this has exactly the same size as the animation itself ensuring there won't be any layout shifting and therefore no flicker.

### Videos (before / after)

<details>
<summary>Android: Native</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/e0e84754-1080-48a4-8eec-aebea6feb5d8"> | <video src="https://github.com/Expensify/App/assets/56457735/777ec4b7-5ea8-4eb2-a052-25a51d04c720"> |

</details>

**Comment by kadiealexander** [comment]
@allroundexperts any thoughts on the proposal above?

**Comment by allroundexperts** [comment]
Thanks for the in depth explanation @ikevin127. Your [proposal](https://github.com/Expensify/App/issues/38347#issuecomment-2018879193) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by ikevin127** [comment]
PR https://github.com/Expensify/App/pull/39374 ready for review! 🚀

**Comment by ikevin127** [comment]
⚠️ Automation failed here -> this should be on **Hold for payment [2024-04-28]** according to 3 days ago's production deploy from https://github.com/Expensify/App/pull/39374#issuecomment-2069770445.

cc @kadiealexander

**Comment by ikevin127** [comment]
@kadiealexander Bump, payment overdue based on https://github.com/Expensify/App/issues/38347#issuecomment-2076260307.

Please let me know if there's anything required from my side to complete payment here. Thank you!

**Comment by kadiealexander** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@allroundexperts] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@allroundexperts] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@allroundexperts] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@allroundexperts] Determine if we should create a regression test for this bug.
- [ ] [@allroundexperts] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment]
### Payment Summary
[Upwork Job]()
- Contributor: @ikevin127 paid $500 via [Upwork](https://www.upwork.com/nx/wm/workroom/36849861/overview)
- Reviewer: @allroundexperts owed $500 via NewDot

#### BugZero Checklist (@kadiealexander)
- [x] I have verified the correct assignees and roles are listed above and updated the neccesary manual offers
- [x] I have verified that there are no duplicate or incorrect contracts on Upwork for this job (https://www.upwork.com/ab/applicants//hired)
- [x] I have paid out the Upwork contracts or cancelled the ones that are incorrect
- [x] I have verified the payment summary above is correct

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/38093
2. Kevin is already aware of this as he fixed it. As such,  a comment is not needed.
3. N/A
4. A regression test would be helpful. Test steps given in OP look good.

**Comment by kadiealexander** [comment]
https://github.com/Expensify/Expensify/issues/395764

Payment summary [here](https://github.com/Expensify/App/issues/38347#issuecomment-2084261559).

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
