### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] IOU - Approve button appears while approvals is disabled

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39171]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR :** https://github.com/Expensify/App/pull/38253
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisites:
Have a collect WS and make chat enabled on ND
Have 2 accounts (one admin, one employee)
Having `Make or track payments enabled
Toggle on delay submissions on ND (Logged in as the admin)
Toggle off Add approvals
On OD Make reimbursement direct with a VBBA

1. [Employee] Request money from the workspace chat and submit it
2. [Admin] Click on the IOU preview and observe the header

## Expected Result:
"Pay with expensify" button should show up since this is the case where Delay submissions is enabled and approvals is disabled

## Actual Result:
"Approve" button appears on the header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4c0144dc-f6e3-4455-9c33-2db66596918b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014fc34bb4b2bfbb10</li>
        <li>Upwork Job ID: 1773511332097155072</li>
        <li>Last Price Increase: 2024-03-29</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103218707</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by izarutskaya** [comment]
@greg-schroeder I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The approve button is still displayed even though the add approvals option is disabled.

### What is the root cause of that problem?
We already have a condition here to not show the approve button if the approval is disabled (`isOnSubmitAndClosePolicy`).
https://github.com/Expensify/App/blob/4fbd2184458a9cbfee0380b571fc95bff042c0af/src/libs/actions/IOU.ts#L4509-L4513

However, the auto-reporting frequency needs to be instant (`isOnInstantSubmitPolicy`) to not show the approval button. In our case, the frequency is set to WEEKLY, so the condition is never met.

### What changes do you think we should make in order to solve the problem?

Change the condition to accept either `isOnInstantSubmitPolicy` or `isOnSubmitAndClosePolicy`.
```
if (isOnInstantSubmitPolicy || isOnSubmitAndClosePolicy) {
```

Or we can remove `isOnInstantSubmitPolicy`

**Comment by DylanDylann** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/39171#issuecomment-2025274202) looks good to me 

🎀 👀 🎀 C+ reviewed

**Comment by stitesExpensify** [comment]
@bernhardoj do you know why we initially implemented it to only be disabled when `isOnInstantSubmitPolicy`? That seems like it was done intentionally, and I just want to make sure we aren't going to break something

**Comment by bernhardoj** [comment]
It was first implemented in https://github.com/Expensify/App/pull/35470, but looks like in this PR https://github.com/Expensify/App/pull/38253 (where the QA found the issue), the test step expect the approve button to not show.

cc: @luacmartins @lakchote

**Comment by luacmartins** [comment]
We should not show the approve button if approvals are disabled

**Comment by DylanDylann** [comment]
@luacmartins As mentioned [here](https://github.com/Expensify/App/pull/35470#issue-2110069753)

> Approver shouldn't be able to "Approve" an expense report IFF the report's policy is a Collect Policy, on "Instant Submit" reporting frequency, with "Submit & Close" approval mode. 

Do we want to display the Approve button if users are in approval mode and not in "Instant Submit" reporting frequency 

cc @Beamanator

**Comment by Beamanator** [comment]
> > Approver shouldn't be able to "Approve" an expense report IFF the report's policy is a Collect Policy, on "Instant Submit" reporting frequency, with "Submit & Close" approval mode.

Agreed (I wrote that lol)

> Do we want to display the Approve button if users are in approval mode and not in "Instant Submit" reporting frequency

To be clear, you're asking "if users are in approval mode **Submit & Close**", right? I believe in that case we wouldn't want to show the "Approve" button either

**Comment by bernhardoj** [comment]
> Because "Submit & Close" basically means: After a submitter submits a report, what next? We close the report, we don't wait for the admin to Approve it

That makes sense, but currently, the condition expects the instant submit is on too to hide the approve button.
https://github.com/Expensify/App/blob/ebc8de8229fa700e5a7d08f4589db934a79d4f1d/src/libs/actions/IOU.ts#L4599-L4601

I think it makes sense if we remove the instant submit condition because whether it's an instant or manual submit, the report will be closed immediately, right?

**Comment by Beamanator** [comment]
I tentatively think that definitely makes sense 😅 👍

**Comment by greg-schroeder** [comment]
Discussion continues here - @stitesExpensify @Beamanator we cool with @bernhardoj's approach to solve this one?

**Comment by Beamanator** [comment]
I say let's move forward with always disabling / hiding the Approve button for Submit & Close approval mode, carlos agreed earlier too 👍

**Comment by rojiphil** [comment]
> I say let's move forward with always disabling/hiding the Approve button for Submit & Close approval mode

Oh! If this is where we are heading to, then there is already a PR [here](https://github.com/Expensify/App/pull/39071) for this. Not sure of the specifics of this issue but would the PR solve the issue here?

**Comment by Beamanator** [comment]
Ooh good catch! @greg-schroeder do you mind checking if this bug still exists? Maybe that linked PR ^ already fixed this!

**Comment by greg-schroeder** [comment]
Okay that was just deployed to prod

**Comment by stitesExpensify** [comment]
Waiting for a re-test

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment]
Aha, looks like it's no longer a thing! Closing accordingly per the above. Please reopen if you disagree and explain your reasoning!

**Comment by lanitochka17** [comment]
Issue  is still reproducible on the latest build 9.0.9-2

https://github.com/user-attachments/assets/c1731e4c-7d7c-43df-888a-8acd3cc99890

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - Approve button appears while approvals is disabled

### What is the root cause of that problem?

In [`canApproveIOU`](https://github.com/Expensify/App/blob/f3a8f736208166286e6f7da3562f1503d5ef2a3d/src/libs/actions/IOU.ts#L6369-L6399) function we are not checking if the policy `isSubmitAndClose`

### What changes do you think we should make in order to solve the problem?
Add `!PolicyUtils.isSubmitAndClose(policy)` to canApproveIOU result.

```
    const result = isCurrentUserManager && !isOpenExpenseReport && !isApproved && !iouSettled && !isArchivedReport && !PolicyUtils.isSubmitAndClose(policy);
```

### What alternative solutions did you explore? (Optional)

**Comment by greg-schroeder** [comment]
Back into proposal review

**Comment by DylanDylann** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/39171#issuecomment-2025274202) looks good to me

🎀 👀 🎀 C+ reviewed


Note that: The [mentioned PR](https://github.com/Expensify/App/issues/39171#issuecomment-2042523080) is another case and It doesn't fix this bug

**Comment by bernhardoj** [comment]
PR is ready

cc: @DylanDylann

**Comment by greg-schroeder** [comment]
PR is being reviewed

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @bernhardoj - $500 - You can make a manual request
C+: @DylanDylann - $500 - Paying through Upwork

**Comment by greg-schroeder** [comment]
Please complete the checklist @DylanDylann when you're able!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$500 approved for @bernhardoj

**Comment by DylanDylann** [comment]
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/35470
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: The author explained [here](https://github.com/Expensify/App/issues/39171#issuecomment-2034311204)
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal

Prerequisite: Admin has a collect workspace and turns off the approval and sets the Delayed submission to MANUAL (or other than INSTANT)

1. As an employee, add a money request and submit it to the workspace expense chat
2. As the admin, open the workspace chat (refresh or reopen the app if needed to get the latest data)
3. Verify the pay button shows instead of the approve button on the report preview

Do we agree 👍 or 👎

**Comment by greg-schroeder** [comment]
Filed regression test, closing
