### ISSUE TITLE
[Awaiting checklist completion] [$250] Settings - Switch to Expensify Classic - Blank RHP when refreshing page with /confirm?backTo=settings URL

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39184]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to Profile
3. Click Switch to Expensify Classic
4. Proceed to the final page
5. Click Switch to Expensify Clasic
6. Return to ND tab
7. Refresh the page https://staging.new.expensify.com/settings/exit-survey/confirm?backTo=settings

## Expected Result:
The content in "Before you go" RHP is preserved after refreshing the page

## Actual Result:
"Before you go" RHP becomes blank after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f162d7b2-ea33-498d-8452-34b1f7c234fa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0198a70a7181e3f02c</li>
        <li>Upwork Job ID: 1773364847520067584</li>
        <li>Last Price Increase: 2024-03-28</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by twisterdotcom** [comment]
Doesn't look like this was reported by an end user or employee right?
>Issue reported by: Applause - Internal Team

Nor was it part of a test:
>If this was caught during regression testing, add the test name, ID and link from TestRail: N/A

Agree though, given this is the URL we keep you on, it's odd to refresh and have that empty LHN:

https://github.com/Expensify/App/assets/9133401/8f4b3ede-ef3e-4053-af7f-b87b4dd85392

Given it's dismissed by clicking anywhere else on the page, I'll make this weekly and $250 in VSB and FUTURE

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Before you go" RHP becomes blank after refreshing the page

### What is the root cause of that problem?
After we switch to old dot, [this selector](https://github.com/Expensify/App/blob/1ef7d38241a8d1d6b3b257e19abbc3d4ffff7e71/src/pages/settings/ExitSurvey/ExitSurveyConfirmPage.tsx#L109) return value becomes undefined, which makes the page not render.

### What changes do you think we should make in order to solve the problem?

[this selector](https://github.com/Expensify/App/blob/1ef7d38241a8d1d6b3b257e19abbc3d4ffff7e71/src/pages/settings/ExitSurvey/ExitSurveyConfirmPage.tsx#L109) return value is undefined, return `null` or empty string.

### What alternative solutions did you explore? (Optional)
NA

**Comment by robertjchen** [comment]
Agreed with the proposal and review, thank you! 👍

**Comment by nkdengineer** [comment]
@dukenv0307 The PR is [here](https://github.com/Expensify/App/pull/39232)

**Comment by twisterdotcom** [comment]
Payment Summary:

- @dukenv0307 paid $250 [here](https://www.upwork.com/nx/wm/workroom/36842437/overview) (Reviewer)
- @nkdengineer paid $250 [here](https://www.upwork.com/nx/wm/offer/101871642) (Contributor)

**Comment by twisterdotcom** [comment]
@dukenv0307 let me know when you've done the checklist so we can close.

**Comment by nkdengineer** [comment]
> @nkdengineer paid $250 [here](https://www.upwork.com/nx/wm/offer/101871642) (Contributor)

@twisterdotcom Thanks! I accepted the offer.

**Comment by robertjchen** [comment]
Thanks!!
