### ISSUE TITLE
[HOLD] [Report Fields] [Tracking] Remove Report Fields from Collect 

### ISSUE THREAD

**Issue by caitlinwhite1** [Expensify/App#39440]
Coming from [Collect Plan V2](https://docs.google.com/document/d/1IJXnUCr65bG2DEQ6qRS-aum1ZEQuLkNgxpbkoZWFDGY/edit), we're now considering report fields an advanced feature only available on Control. This means we need to update the current logic so that report fields only appear on Control reports.

**Relative Docs:**
- [Report Fields](https://docs.google.com/document/d/1LXGXwWsei-Zx2wJMaYBmVe_M8NH7AHJZ5bIqwSec4uo/edit)
- [Collect Plan V2](https://docs.google.com/document/d/1IJXnUCr65bG2DEQ6qRS-aum1ZEQuLkNgxpbkoZWFDGY/edit)

**To Do's:** 
- [x] prevent report fields from returning on collect workspaces when we upgrade users from collect to control for New Expensify - [PR](https://github.com/Expensify/Auth/pull/10414) 
- [ ] Upgrade current OldDot users of report field users to control - PR(yet to be created)
- [ ] Prevent all Collect users  from adding report fields in OldDot - PR(yet to be created)
- [ ] Remove Beta - [GH](https://github.com/orgs/Expensify/projects/130/views/1?pane=issue&itemId=56122158)
- [ ] Add Report Fields to downgard modal - Add relative GH when this gets created as part of Collect Plan V2
- [ ] confirm pricing page is updated accordingly

**Additional Notes:**
- When the upgrade from collect to control happens for report field users, there is no special consideration we need to have for historical data as this is already supported in backend logic.

**Comment by caitlinwhite1** [comment]
cc @thienlnam Including you here for relative PR's!

**Comment by JmillsExpensify** [comment]
@thienlnam based on the list above, it looks like we're in a holding pattern until we upgrade Collect users to Control, agreed? If so, we'll probably want to put a HOLD on this issue until that initiative gets kicked off this summer.

**Comment by caitlinwhite1** [comment]
still on HOLD

**Comment by caitlinwhite1** [comment]
updating to monthly for the time being

**Comment by caitlinwhite1** [comment]
will look into taking this off hold this week as we're now working on summer release initiatives

**Comment by caitlinwhite1** [comment]
no changes here

**Comment by caitlinwhite1** [comment]
latest priority is here: https://github.com/Expensify/App/issues/44340#issuecomment-2284546322
