### ISSUE TITLE
[Ready for C+ checklist and payment][$250] Split - Group chat does not show bill creator name in LHN preview after refreshing the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39647]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money > Manual
3. Create a split bill with two users
4. Once landed in group chat, note that group chat in LHN shows the bill creator name in the preview
5. Refresh the page

## Expected Result:
The group chat will continue to show the bill creator name in LHN preview after refreshing the page

## Actual Result:
The group chat does not show the bill creator name in LHN preview after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f9407c5a-6c4d-4aee-808a-ce4639cb42c2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126a3e7c5e2856078</li>
        <li>Upwork Job ID: 1777107502133911552</li>
        <li>Last Price Increase: 2024-04-28</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The LHN subtitle shows the sender name when creating the split bill, but then it disappears.

### What is the root cause of that problem?
When we refresh/wait for a moment, we will get the correct response from the BE and the sender name disappears is already correct because we don't want to show the sender name if it's coming from ourself.
https://github.com/Expensify/App/blob/2995f2c79751d5096919eb98a26e0bd7b8533658/src/libs/OptionsListUtils.ts#L529-L533

The logic to show the sender name is, by taking the report `lastActorAccountID` and getting the user data from the ID.
https://github.com/Expensify/App/blob/2995f2c79751d5096919eb98a26e0bd7b8533658/src/libs/SidebarUtils.ts#L297

However, when we create a split bill, the `lastActorAccountID` is 0, so the user detail is empty.
https://github.com/Expensify/App/blob/2995f2c79751d5096919eb98a26e0bd7b8533658/src/libs/ReportUtils.ts#L3781

If it's empty, we will get it from the last report action person data which contains the user display name.
https://github.com/Expensify/App/blob/2995f2c79751d5096919eb98a26e0bd7b8533658/src/libs/SidebarUtils.ts#L299-L307

Because 0 is not the same as the current user ID, the current user display name is shown as the sender.

### What changes do you think we should make in order to solve the problem?

Set the `lastActorAccountID` optimistically when creating a split bill (and revert it when fails). We did this when adding a message/task too.

We might need to do this for other money request too.

### What alternative solutions did you explore? (Optional)
Don't show the display name when the `lastActorAccountID` is 0.

**Comment by eh2077** [comment]
Reviewing proposals

**Comment by aldo-expensify** [comment]
I have some doubts about the "Expected results" being correct here. If we say that the frontend is right, and the split creator name shouldn't appear in the report's last message in the LHN from the perspective of the creator, this means that the last message of the report is different for each participant, and I think we may want to avoid that.

@marcaaron can I get your eyes here since I think you know about groups. 🙏

**Comment by marcaaron** [comment]
I agree 1000%.

With Group Chats, we did not really change much about how this works on the frontend side of things though - just replaced the Group DM with a Group Chat so I'm not sure where we went wrong or if this was just always awkward.

Could probably take this to #vip-split room and loop in whoever is working on Splits now. cc @arielgreen @dubielzyk-expensify and @youssef-lr? Can we see about rolling this in as a polish item for this project?

**Comment by dubielzyk-expensify** [comment]
Seems like a minor bug. I agree that it'd be nice to fix it though, but fine with this as a polish item

**Comment by eh2077** [comment]
@kadiealexander Based on the discussions above, can you help to update the `Expected results` section of this issue?

**Comment by eh2077** [comment]
> @kadiealexander Based on the discussions above, can you help to update the `Expected results` section of this issue?

@kadiealexander Friendly bump!

**Comment by eh2077** [comment]
Or @bernhardoj would you like to update your proposal according to @aldo-expensify 's https://github.com/Expensify/App/issues/39647#issuecomment-2057456493 ?

**Comment by bernhardoj** [comment]
Updated!

**Comment by eh2077** [comment]
@bernhardoj Thanks for the update! 

Based on the above discussions, yes, it makes more sense to `Don't show the display name when the lastActorAccountID is 0`.

So, @bernhardoj 's [alternative solution](https://github.com/Expensify/App/issues/39647#issuecomment-2039767594) looks good.

@aldo-expensify All yours.

🎀👀🎀 C+ reviewed

**Comment by eh2077** [comment]
@aldo-expensify Should we assign @bernhardoj  to move this issue forward?

**Comment by aldo-expensify** [comment]
It is not clear to me from the conversation which option we want, so I asked here https://expensify.slack.com/archives/C05RECHFBEW/p1713833726038629 to confirm

**Comment by aldo-expensify** [comment]
Sorry @eh2077 @bernhardoj for the back and forward. The conclusion from the slack conversation is:

The bill creator name should appear in the last message, and the front end should take care of that. The backend will send the last message with the bill creator in it.


I think this code is related to that: 

https://github.com/Expensify/App/blob/42d4ed7b72dc979df430a2a7eac4ba30a3eac790/src/libs/OptionsListUtils.ts#L711-L713

I think this was what @bernhardoj  original solution was trying to achieve, correct?

**Comment by eh2077** [comment]
@aldo-expensify Thanks for driving clarity. 

@bernhardoj Can you take some time to update proposal based on the expected result^ ?

**Comment by aldo-expensify** [comment]
I just noticed a mistake in the expected results I typed above. The backend WON'T send the bill creator as part of the last message:

<img width="838" alt="image" src="https://github.com/Expensify/App/assets/87341702/916ba658-4d62-4a77-9179-4d5319ba91ee">

**Comment by bernhardoj** [comment]
My proposal has both behaviors, showing or not showing the sender name if it's the current user. If I understand correctly from @aldo-expensify comment, we always want to show the sender's name, so it should be the 2nd alternative.

<img width="899" alt="image" src="https://github.com/Expensify/App/assets/50919443/fdddba3b-0199-4025-b3f6-5e9d278a851f">

**Comment by eh2077** [comment]
@bernhardoj Thanks for the update. Yeah, the 2nd alternative makes sense to me.

@aldo-expensify All yours.

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @eh2077

**Comment by eh2077** [comment]
The fix has hit production https://github.com/Expensify/App/pull/41483#issuecomment-2101804136

**Comment by kadiealexander** [comment]
Sorry guys, this one slipped through the cracks! 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@eh2077](https://github.com/eh2077)] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@eh2077] Determine if we should create a regression test for this bug.
- [ ] [@eh2077] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:


Payouts due:

- [ ] Contributor: $250 @bernhardoj 
- [ ] Contributor+: $250 @eh2077

Upwork job is [here](https://www.upwork.com/jobs/~0126a3e7c5e2856078).

**Comment by eh2077** [comment]
### BugZero Checklis

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _I can't find the specific PR caused this issue. I think this case is not handled when we added the feature._
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. _This bug was reported by QA team and it's an edge case, so I think we don't need a regression test for it._
