### ISSUE TITLE
[C+ Checklist Needs Completion] CRITICAL: [Actionable Whispers] [$250] Categorize it - No workspace found appears briefly after clearing search field

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40520]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, this is a new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Track expense.
3. Create a track manual expense.
4. Select Categorize it from the whisper.
5. Enter an invalid string in the search field.
6. Clear the search field.
## Expected Result:
In step 5: The error message should appear when entering the invalid string
In step 6: Workspace list will show up immediately after clearing the search field. 

## Actual Result:
In step 5: Nothing showing to indicate for no results found
In step 6: Workspace list empty state (No workspace found) appears briefly after clearing the search field.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/2f307cde-8d2a-4cec-bd5a-93e9bbca756f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b97ed1aa9534847a</li>
        <li>Upwork Job ID: 1781102371560218624</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
@marcaaron FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by thienlnam** [comment]
Will take this one since it's related to track

**Comment by thienlnam** [comment]
Doesn't look like it needs to be a blocker

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Track expense- Categorize it - No workspace found appears briefly after clearing search field

### What is the root cause of that problem?
We show the not found page even when the search term is empty:
https://github.com/Expensify/App/blob/985591f48a7fc34fdd2eb68172bc3748112cf20d/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L381

This results in current behavior.

### What changes do you think we should make in order to solve the problem?
We should remove the `searchTerm.trim() === ''` condition from here: 


https://github.com/Expensify/App/blob/985591f48a7fc34fdd2eb68172bc3748112cf20d/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L381

**Comment by neonbhai** [comment]
Proposal [updated](https://github.com/Expensify/App/issues/40520#issuecomment-2065484949)

**Comment by c3024** [comment]
RCA and fix suggested by @gijoe0295 [here](https://github.com/Expensify/App/issues/40520#issuecomment-2065503305) look good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There are 2 issues:
1. When we search for invalid workspace, the No result found isn't shown
2. When we clear the search term, the empty workspace view is shown

### What is the root cause of that problem?
1. To show the no result found message, we check the length of both `newChatOptions.personalDetails` and `newChatOptions.recentReports`.
https://github.com/Expensify/App/blob/9b2c5187e2203d83bba50bfa66936691788cbd18/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L247-L250

For categorize and share track expense, we don't include personal detail in the list. 
https://github.com/Expensify/App/blob/9b2c5187e2203d83bba50bfa66936691788cbd18/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L147-L153

However, the `newChatOptions` always include personal detail in it.
https://github.com/Expensify/App/blob/9b2c5187e2203d83bba50bfa66936691788cbd18/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L166

So, if we search for an invalid workspace name but still valid for personal detail result, the no result found won't be shown.

2. When we remove the search term while the list is empty, the `searchTerm` state is updated immediately, but the list is recalculated based on `debouncedSearchTerm`, which is debounced.
https://github.com/Expensify/App/blob/9b2c5187e2203d83bba50bfa66936691788cbd18/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L380-L383

So the condition above becomes true for a while. In this condition, we check for the section data to check whether the list is empty or not.

### What changes do you think we should make in order to solve the problem?

1. There are 2 options. First, we use `isAllSectionsEmpty` variable too to show the no result found message.

Second, add `includePersonalDetails` to `getFilteredOptions` param and the value will be false when the action is either `CATEGORIZE` or `SHARE`. Then, we don't need this action check anymore because the personal detail will be empty.
https://github.com/Expensify/App/blob/9b2c5187e2203d83bba50bfa66936691788cbd18/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L147-L153 
```
includePersonalDetails: ![CONST.IOU.ACTION.CATEGORIZE, CONST.IOU.ACTION.SHARE].includes(action)
```
This is better so we don't need to calculate personal detail list when we don't want it.

2. Replace `searchTerm` with `debouncedSearchTerm` in the logic to render the empty workspace view.
https://github.com/Expensify/App/blob/9b2c5187e2203d83bba50bfa66936691788cbd18/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L380-L383

**Comment by bernhardoj** [comment]
@c3024 can you review my proposal since the other proposals don't address the no result found bug?

**Comment by c3024** [comment]
@bernhardoj 

Oh, I searched for a random string and there were no matches in personal details as well for that string so the message "No results found" was shown correctly so I assumed it was fixed somewhere. But if the string matches some personal detail but no workspace then there will be no results and also no message displayed like you pointed out.

This needs to be fixed as well. I prefer your first option of using `isAllSectionsEmpty` for header message.

cc: @thienlnam

**Comment by bernhardoj** [comment]
PR is ready

cc: @c3024

**Comment by quinthar** [comment]
Wow great!

**Comment by greg-schroeder** [comment]
@c3024 All that's left is the [checklist](https://github.com/Expensify/App/issues/40520#issuecomment-2077220637) and we can close this out!

**Comment by c3024** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #32692 
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/bernhardoj/Expensify/commit/9c79b100f83160136187e4dc6cc3b1562d3f09f0#r141745523
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion started because no specific steps can be included in the checklist for early detection of the bug.
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Open your self DM chat
2. Track a new expense. Wait until the concierge message shows up
3. Choose `Categorize it`
4. Search for a text that matches with no workspace name but does with a user display name/login
5. Verify the `No result found` header message is shown with no results

👍  or 👎

**Comment by greg-schroeder** [comment]
Thanks @c3024 - filing regression test
