### ISSUE TITLE
[WAITING ON CHECKLIST] [$250] Multiple requests to `SearchForReport` when searching for a user

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40608]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713544197266279

## Action Performed:
1.  Click the search icon from the LHN
2. Open network tab
3. Type something in the search bar
## Expected Result:
Shouldn't be numerous requests to `SearchForReport` 
## Actual Result:
Numerous requests to `SearchForReport` is sent

For proposals - see this [comment](https://github.com/Expensify/App/issues/40608#issuecomment-2069525820):

>We should either add or change the code so that it debounces the calls in a "sane" manner, probably the same as we did for the userIsTyping events

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/2e415c87-5457-4702-b731-68e5dcbda6e5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8c8aa1341923a49</li>
        <li>Upwork Job ID: 1782550098085855232</li>
        <li>Last Price Increase: 2024-04-29</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by iwiznia** [comment]
This was omitted from the issue description:
> We should either add or change the code so that it debounces the calls in a "sane" manner, probably the same as we did for the userIsTyping events

Please take it into consideration for the proposals.

**Comment by jliexpensify** [comment]
Whoop sorry, missed this one yesterday - I can repro.

**Comment by jliexpensify** [comment]
@ahmedGaber93 bump as we have 2 proposals

**Comment by ahmedGaber93** [comment]
Reviewing today.

**Comment by ahmedGaber93** [comment]
@ShridharGoel @tienifr Thanks for the proposal.

The both proposals suggest increasing debounce time, and @tienifr [proposal](https://github.com/Expensify/App/issues/40608#issuecomment-2071327754) point 2 suggest UX changes that allow the user to submit the input to start search immediately.

I think increasing debounce time to 1000ms like [isUserTyping](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L193) will reduce API calls, but also the live search result will be more late, but I think we can accept that for more API performance, and we're already displaying the saved data in onyx storage without needing to wait to API response.

The UX changes by @tienifr [proposal](https://github.com/Expensify/App/issues/40608#issuecomment-2071327754) point 2 is not the best for `search immediately purpose`, it should be for `full result purpose` and in most cases submit action will not affect on the result.

@iwiznia There is another behavior appear after increasing the time, the result for the saved data in onyx storage will also debounce because [filtering data](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/ChatFinderPage/index.tsx#L112) depend on  `debouncedSearchValue` change. Should we also solve this? 



https://github.com/Expensify/App/assets/41129870/d04fdb37-4a57-4bc5-8750-10d73d4d3952

**Comment by iwiznia** [comment]
> I think increasing debounce time to 1000ms like [isUserTyping](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L193) will reduce API calls, but also the live search result will be more late,

I don't think that's true, that's what leading is for: https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L196


> the result for the saved data in onyx storage will also debounce because [filtering data](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/ChatFinderPage/index.tsx#L112) depend on debouncedSearchValue change.

Don't get why this is bad, what are the consequences of it?

**Comment by ahmedGaber93** [comment]
> Don't get why this is bad, what are the consequences of it?

@iwiznia Filtering the data every 1000ms seem bad UX, for example, if we have 4 items `a1, a2, b1, b2`.
- when user opens the search page, he will see the 4 items by default.
- if user type `a` in the search, he will still see the 4 items `a1, a2, b1, b2` for 1000ms util filtering data run, and then he will see the filtered result `a1, a2` which seem slow response as the 4 items already displayed for the user but filtering wait 1000ms to run.

I don't think this is worth, so I asked you.

**Comment by ahmedGaber93** [comment]
> I don't think that's true, that's what leading is for: 

@iwiznia I guess your response is for this part `but also the live search result will be more late`, if that as I understand from the debounce [docs](https://lodash.com/docs/4.17.15#debounce) and testing it, `leading` will affect only on the first debounce call (leading edge).

If user start typing and type first letter `a`, the search API will run immediately without waiting (leading edge), but after that typing any search value will wait the delay time then call search API.

So I think the live search result from API will be more late than current.

**Comment by iwiznia** [comment]
Yeah,1s might not be the best value to use as it feels quite high.

**Comment by ahmedGaber93** [comment]
@iwiznia I think the only available improvement right now is increasing the debounce time, can we move forward with this improvement? Or this not enough?

If we can move forward, I think 500ms may be good.

**Comment by iwiznia** [comment]
Sounds good. Still not sure if 1s is the best number... doing some live tests will probably help out to know.

**Comment by ahmedGaber93** [comment]
> @ahmedGaber93 I believe we can avoid this by having a separate debounce time for API call (1s) and keeping the current debounce time for filtering as is (300ms, so it's interactive right after the user types). We don't have to make them the same value.

@tienifr yes, I think you need to follow that if we decide to use long debounce time for API  >= 1s.

**Comment by jliexpensify** [comment]
Hi @ahmedGaber93 how are we going with this? Do we have a proposal in mind?

**Comment by ahmedGaber93** [comment]
@jliexpensify I am closing to choose it, based on @iwiznia replay for this https://github.com/Expensify/App/issues/40608#issuecomment-2079816960

If we decide to use a short delay time, we will go with the first [proposal](https://github.com/Expensify/App/issues/40608#issuecomment-2068140199).
And If we decide to use a long delay time, we will go with the second [proposal](https://github.com/Expensify/App/issues/40608#issuecomment-2071327754) which add extra fix for long time side effects here https://github.com/Expensify/App/issues/40608#issuecomment-2079730460.

cc @iwiznia

**Comment by ahmedGaber93** [comment]
> @ahmedGaber93 Also, even if we go with a short delay, I think it's still important that the live filtering is not affected, via the https://github.com/Expensify/App/issues/40608#issuecomment-2079730460 I mentioned earlier. Having live filtering taking more than 300ms doesn't feel smooth to the user.

Hmm. Let me test again if short values like 500ms seem bad for live filtering.

**Comment by ahmedGaber93** [comment]
Although 500ms is not bad for filtering saved data in onyx, but 300ms seem better, and I think the best is 0 by using `searchValue` for `filteredOptions`, and `debouncedSearchValue` for `searchInServer`.

**Comment by ahmedGaber93** [comment]
@tienifr Can you update your proposal with the extra fix https://github.com/Expensify/App/issues/40608#issuecomment-2079730460 and here https://github.com/Expensify/App/issues/40608#issuecomment-2091351302?

**Comment by ahmedGaber93** [comment]
@tienifr 0  is the best for UX,  but it may not be the best for performance, Let's discuss about this in the PR.

**Comment by ahmedGaber93** [comment]
@tienifr's [proposal](https://github.com/Expensify/App/issues/40608#issuecomment-2071327754) by increasing the debounce timing for `searchInServer` and keep filtering data debounce timing without change LGTM.

I think we can move forward with @tienifr's proposal and debounce timing that we will discuss with @iwiznia about the best value for it.

🎀 👀 🎀 C+ reviewed

**Comment by jliexpensify** [comment]
Not overdue

**Comment by jliexpensify** [comment]
Payment Summary

- C: @tienifr $250
- C+: @ahmedGaber93 $250

[Upwork job](https://www.upwork.com/jobs/~01c8c8aa1341923a49)

Just waiting on the checklist!

**Comment by jliexpensify** [comment]
Bump @ahmedGaber93 for the checklist!

**Comment by jliexpensify** [comment]
Payments made and job closed.

**Comment by ahmedGaber93** [comment]
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: N/A
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug.
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

This issue is for improving performance and reduce API calls, So I think there is no offending PR, and need for regression test.
