### ISSUE TITLE
[HOLD for payment 2024-05-09] [Tracking] Ren's progress on draft review / publishing status

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#40810]
## Expensify Classic
- [ ] Travel - https://github.com/Expensify/App/issues/40478
- [ ] Expensify Card Reconciliation
     - Slack thread - [HERE](https://expensify.slack.com/archives/C02QSAC6BJ8/p1713889923207739?thread_ts=1712251668.429679&cid=C02QSAC6BJ8)
     - Draft - [HERE](https://docs.google.com/document/d/1m-51Iijp0L1RDgfLLdcIAyC1BFBvr-AKkjpZiate2u4/edit#heading=h.yocly5owtf99)

### Getting Started
- [ ] Collect Migration (Joe) - https://github.com/Expensify/App/issues/40808
### Chat
- [ ] https://github.com/Expensify/App/pull/40877 (Leave a chat room)
- [ ] https://github.com/Expensify/App/pull/40883 (Send & format chat messages)
- [ ] https://github.com/Expensify/App/pull/40886 (Start a conversation thread)
- [ ] https://github.com/Expensify/App/pull/40888 (Reorder chat inbox)
- [ ] https://github.com/Expensify/App/pull/40892 (Create a new chat)
- [ ] https://github.com/Expensify/App/pull/40899 (Edit or delete messages)
- [ ] https://github.com/Expensify/App/pull/40900 (Flag chat messages)
- [ ] https://github.com/Expensify/App/pull/40901 (Expensify Chat rooms for admin)
- [ ] https://github.com/Expensify/App/pull/40906 (Invite members to a chat group or room)
### Expenses & Payments
- [ ] Drafts and Tags (Xtina) - https://github.com/Expensify/App/issues/40331
- [ ] Invoicing (Xtina) - https://github.com/Expensify/App/pull/40916 (Send an invoice)
### Travel
- [ ] Travel (Ben) - https://github.com/Expensify/App/issues/40478
### Integrations 
- [ ] QBO (Zany) - https://github.com/Expensify/App/issues/40920
- [ ] Xero (LS) - https://github.com/Expensify/App/issues/41118
### Settings
