### ISSUE TITLE
[CHECKLIST] [$250] Expense - Merchant name of the deleted expense in OD report is still shown in ND report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40980]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4506647
**Issue reported by:** Applause - Internal Team
*

## Action Performed:
Employee - OldDot
1. Navigate to one of the empty reports
2. Add an expense to the report

Employee - NewDot
1. As the employee in NewDot - Navigate to the workspace chat
2. Verify the report that had the expense added shows the new amount
3. Click on the report with the newly added expense
4. Verify the expense is displayed in the report conversation

Employee - OldDot
1. Navigate to the report with the expense
2. Delete the expense from the report

Employee - NewDot
1. As the employee in NewDot - Navigate to the workspace chat
2. Verify the report that had the expense removed displays $0.00
3. Verify if the name of Merchant still displayed below the $0.00

## Expected Result:
Only $0.00 is shown in the report

## Actual Result:
Merchant name of the deleted expense is shown below the $0.00

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cc58bc8c-8610-40e7-bc45-f31a960fcfb0

![Bug6460737_1713988639176!merchantname_shown](https://github.com/Expensify/App/assets/78819774/2927fb08-6a3e-415e-b499-257b9c3948ed)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a644000e2f4f8e02</li>
        <li>Upwork Job ID: 1783553598312005632</li>
        <li>Last Price Increase: 2024-05-09</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by garrettmknight** [comment]
Repro'd opening it up.

**Comment by garrettmknight** [comment]
Since this is a pretty niche bug and low priority I don't expect this to get fixed intentionally, quickly, but we could very well fix it elsewhere with our backwards compatibility work so I'm setting it for a retest weekly.

**Comment by fitd-tech** [comment]
**Please re-state the problem that we are trying to solve in this issue.**
We don't want to display a Merchant name when the total owed is $0.00.

**What is the root cause of that problem?**
I can't find a good indicator of whether the expense has been deleted, because the `iouReport` doesn't seem to show updated information (the total amount is always `0`, for instance). Instead, we're getting the total amount from the action message string.

**What changes do you think we should make in order to solve the problem?**
For the sake of this particular Issue, we can set `shouldShowSubtitle` to false when `getDisplayAmount` returns`'$0.00'` and `numberOfRequests` equals 1. 

The video attached to the Issue shows some other issues. You must click on the report preview in order for the report to update and reflect the new $0.00 amount. The user would still have to perform this step in order for the merchant name to be removed. I would assume that this is a known issue, but I can attempt to resolve it here if you'd like.

**What alternative solutions did you explore? (Optional)**
We could also only set `formattedMerchant` if the above condition is true, instead of removing the subtitle altogether. I could also look into getting the updated `iouReport` so we explicitly know if the IOU total is $0.00.

**Comment by garrettmknight** [comment]
@akinwale mind giving this proposal a review when you get a chance?

**Comment by akinwale** [comment]
Still looking for proposals here.

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Merchant name of the deleted expense in OD report is still shown in ND report below the $0.00.

### What is the root cause of that problem?

When the OD expense is deleted from the report, in ND nothing changes in the transaction object.
`merchant` remains the initially assigned merchant and `modifiedMerchant` remains empty string `""`.

Because of this, the [`TransactionUtils.getMerchant()`](https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/libs/TransactionUtils.ts#L352-L357) function always returns the `merchant`, even when the expense is removed from the OD report since the `modifiedMerchant` doesn't actually change in this case.

**One might wonder, how come the display amount changes if the transaction object does not change ?**

It turns out that we're checking for the display amount using the `getDisplayAmount` function [here](https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/components/ReportActionItem/ReportPreview.tsx#L158-L183), which extracts the display amount from `action.message?.[0]?.text` which **does** change when the expense is removed from OD report.

### What changes do you think we should make in order to solve the problem?

Create a new function named `isDisplayAmountZero` which will return a boolean determining if the `displayAmount` string value is `0` (works for any currency, eg. $0.00 or ₫0):
```ts
    function isDisplayAmountZero(displayAmount: string) {
        if (!displayAmount || displayAmount === "") {
            return false;
        }

        const numericPart = displayAmount.replace(/[^\d.-]/g, '');
        const amount = parseFloat(numericPart);
        return !isNaN(amount) && amount === 0;
    }
```

With this new function we add the following check to the end of the [`shouldShowSubtitle`](https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/components/ReportActionItem/ReportPreview.tsx#L226) variable like so: 
```ts
const shouldShowSubtitle = !isScanning && (shouldShowSingleRequestMerchantOrDescription || numberOfRequests > 1) && !isDisplayAmountZero(getDisplayAmount());
```

By doing this, if the expense display amount is `0` -> we won't show the report review subtitle (merchant or description) anymore, basically aligning the `getDisplayAmount` functionality with the subtitle (merchant or description) functionality. 

This means that when the expense is removed from the OD report and the display amount changes to $0.00 in ND report preview, the subtitle (merchant or description) will be hidden as long as the display amount equals `0`.

### Screenshots (before / after)

<details>
<summary>MacOS: Chrome</summary>

| Before | After |
| ------------- | ------------- |
| <img width="699" alt="Screenshot 2024-05-08 at 15 36 47" src="https://github.com/Expensify/App/assets/56457735/0e934cac-fceb-4e6e-ae26-7a0c6c97a2ac"> | <img width="699" alt="Screenshot 2024-05-08 at 15 36 12" src="https://github.com/Expensify/App/assets/56457735/cb4825c6-69e5-41ef-a3eb-ca8681cdf9ef"> |

</details>

**Comment by garrettmknight** [comment]
@akinwale is this new proposal viable? Please review when you get a chance.

**Comment by akinwale** [comment]
@ikevin127's [proposal](https://github.com/Expensify/App/issues/40980#issuecomment-2101621957) makes sense here. We can move forward with the solution.

🎀👀🎀 C+ reviewed.

**Comment by deetergp** [comment]
Agreed. @ikevin127's [proposal](https://github.com/Expensify/App/issues/40980#issuecomment-2101621957) looks good 👍

**Comment by ikevin127** [comment]
PR https://github.com/Expensify/App/pull/42015 ready for review! 🚀

**Comment by mvtglobally** [comment]
Issue is reproducible during KI retests.

https://github.com/Expensify/App/assets/43995119/25558486-7749-4482-afd3-e2504d7226cc

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: ❌ 

Since this is a cross-app edge case (OD to ND), there was no offending PR that introduced this since we're not testing front-end ND pull requests on OD in order to catch this kind of edge cases.
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: ❌ 
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: ❌ 

Since we're migrating the platform from OD to ND, I don't think we should start a discussion or update the PR review checklist to extend testing of ND features to OD.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

Employee - OldDot

1. Navigate to one of the empty reports.
2. Add an expense with **merchant** to the report.

Employee - NewDot

1. As the employee in NewDot - navigate to the workspace chat.
2. Verify the report preview is matching the OD expense's **amount** and **merchant**.

Employee - OldDot

1. Navigate to the report with the expense.
2. Delete the expense from the report.

Employee - NewDot

1. As the employee in NewDot - navigate to the workspace chat.
2. Verify that the report which had the expense removed displays $0.00 amount now.
3. Verify that the merchant is not shown anymore underneath the amount. ⬇️ 
**Note:** If the change did not propagate yet, navigate to another LNH report then return back to the workspace chat in order for the report data to re-fetch.

Do we agree 👍 or 👎.

**Comment by deetergp** [comment]
Just a couple days out from the hold expiring 👍

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @ikevin127 $250 paid via Upwork
- Reviewer: @akinwale  $250 paid via Upwork

**Comment by garrettmknight** [comment]
@akinwale can you finish the checklist when you get a chance?

**Comment by akinwale** [comment]
@garrettmknight Looks like @ikevin127 already completed it: https://github.com/Expensify/App/issues/40980#issuecomment-2140903567

@ikevin127 The bot tends to get confused when it's also a C+ acting as a contributor so it tags both. The C+ who did the review is responsible for completing the checklist.

**Comment by garrettmknight** [comment]
Ah, gotcha, thanks!
