### ISSUE TITLE
[Awaiting checklist] [$250] [Held requests] 'Hold expense` option does not show in the preview overflow menu

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41440]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714532350260749

## Action Performed:

1. Create one or two expenses on a Collect policy
2. Navigate to Workspace Chat > Report
3. Hover over an expense
4. Click the three dots in the comment action menu

## Expected Result:
Hold is an option in the comment action overflow menu
## Actual Result:
Hold is not available
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-04-30 at 20 59 21@2x](https://github.com/Expensify/App/assets/38435837/c43647cd-6a98-4200-bbe1-e094b34a8e65)

![Snip - (7) New Expensify (2)](https://github.com/Expensify/App/assets/38435837/cc1e3170-6bb3-455c-98de-c82b372819cb)
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124de9c5bfd8809b9</li>
        <li>Upwork Job ID: 1786382301159866368</li>
        <li>Last Price Increase: 2024-05-03</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by hungvu193** [comment]
@Krishna2323's [proposal here](https://github.com/Expensify/App/issues/41440#issuecomment-2089191798) is straightforward 💪. LGTM!
🎀 👀 🎀  C+ reviewed

**Comment by hungvu193** [comment]
bump @flodnv for final review.

**Comment by trjExpensify** [comment]
@robertjchen @marcochavezf perhaps one of you can do the secondary proposal review?

**Comment by robertjchen** [comment]
Reviewed and agreed with @Krishna2323 's proposal 👍

**Comment by hungvu193** [comment]
Still working on the PR

**Comment by hungvu193** [comment]
Same

**Comment by robertjchen** [comment]
One more tiny lint issue on the PR and we can merge 👍

**Comment by robertjchen** [comment]
merged and now on staging

**Comment by twisterdotcom** [comment]
Payment Summary:

- @hungvu193 paid $250 [here](https://www.upwork.com/nx/wm/workroom/37210826/overview) (Reviewer)
- @Krishna2323 paid $250 [here](https://www.upwork.com/nx/wm/workroom/37214010/overview) (Contributor)

**Comment by hungvu193** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: No offending PR, this is a new feature rather than a bug.
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug: No

This is more of feature request than a bug, I don't think we should create a regression test IMO.
(https://expensify.slack.com/archives/C049HHMV9SM/p1714836774366969).
