### ISSUE TITLE
Task – Task details page doesn’t scroll down when create a subtask

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41904]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4547877
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to any chat and create a task with a long description
4. Open task details and scroll to the top
5. Click on + and create a subtask assigned to any user

## Expected Result:
Page scrolling down when create a subtask

## Actual Result:
Page doesn’t scroll down when create a subtask

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1399b391-e9dc-454c-bbae-877f3533606f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment]
This seems like a duplicate 
https://github.com/Expensify/App/issues/41567
