### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18]  Composer doesn't load in #Exfy-roadmap after google sign in

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41955]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-6
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715268315433579

## Action Performed:
1. Go to https://new.expensify.com/r/868417741568295 in an incognito window
2. Click sign in
3. Sign in with google

## Expected Result:
After signing in the composer/text input for the chat should appear
## Actual Result:
The composer/text input doesn't appear until refreshing, and after waiting quite a while
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/93c8de05-e82d-4e07-997b-9275fea30a23

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d29743e8ff2b58e</li>
        <li>Upwork Job ID: 1788679025374908416</li>
        <li>Last Price Increase: 2024-05-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by neil-marcellini** [comment]
I've already started doing some investigation on this one, so assigning myself.

**Comment by m-natarajan** [comment]
[Exfy-roadmap.log](https://github.com/Expensify/App/files/15267745/Exfy-roadmap.log)

**Comment by neil-marcellini** [comment]
I'm planning to jump in and continue investigations very soon

**Comment by neil-marcellini** [comment]
Ok, so I'm still able to reproduce the issue. As I said in Slack last time, the report doesn't have "write" in the permissions list, so that's why the user can't comment. The OpenReport call after signing in doesn't return the full report data in the response.

Here's [logs for that request](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%228846540518187ab8-SJC%22%20AND%20timestamp%3A%5B2024-05-15T00%3A00%20TO%202024-05-16T23%3A59%5D). I'll trace through the code along with the logs to see what the flow is.

I'm pretty sure the only report data in the response is coming from [this block](https://github.com/Expensify/Web-Expensify/blob/7e3baf8c7bcc3bcd2b55b21108f4cc443833eb81/lib/ReportAPI.php#L6040-L6053), every other area creating report Onyx updates must not be getting hit.


Shoot actually, all of that is wrong 🤦‍♂️. Now I see that the permissions are in fact returned properly in the OpenReport response for that room after signing in. So the root cause must be somewhere else. Back to the drawing board.

```
permissions:  ["read", "write", "share"]
```

**Comment by neil-marcellini** [comment]
I've been focused on finishing up a project and haven't had time to investigate since last time. I'll keep it daily though and try to take a look for an hour or so tomorrow.

**Comment by neil-marcellini** [comment]
Alright I've been taking another look, and it looks like there something strange going on where the first call to OpenReport, before the user signs in, returns `permissions: ["read"]`. Then after signing in with google there's another OpenReport call which successfully returns `permissions:  ["read", "write", "share"]`, as I said last time. However, the ReportFooter component doesn't have the updated report permissions key, so it hides the composer.

![image](https://github.com/Expensify/App/assets/26260477/b91e3ea8-6a5f-4875-af01-08c6b92cc6fa)


I think maybe this is due to some kind of memoization.

**Comment by neil-marcellini** [comment]
Yep it was a useMemo problem. I got a PR up for review.

**Comment by neil-marcellini** [comment]
Hey @dubielzyk-expensify, while working on the [PR for this](https://github.com/Expensify/App/pull/42497) I noticed that we're missing an indication that the composer is loading after signing in. You can see it towards the end of this video.

Would you please help us come up with a design for a loader, or some other similar pattern which makes it clear to the user that they will be able to comment shortly?

Shoot, actually now that I write this, I'm thinking maybe it would be better to handle with optimistic data, so that there isn't a need to wait for loading at all. I'll see if that's feasible and un-assign you if so.

https://github.com/Expensify/App/assets/26260477/3523b8c5-1512-4071-95e8-66aa3f123013

**Comment by dubielzyk-expensify** [comment]
Great catch. Is it possible to do a disabled composer bar? Basically do a 50% opacity on it and disable interactions until it's fully loaded? I think that could be a neat way to do it instead of creating a loading indicator. We could use a skeleton, but I think I'd prefer a disabled composer like this:

![image](https://github.com/Expensify/App/assets/145416827/b4d13a67-98a2-4405-b647-9a94885b52df)

Keen to hear if @Expensify/design agrees

**Comment by dubielzyk-expensify** [comment]
We should probably remove the placeholder until it's enabled though:

![CleanShot 2024-06-04 at 12 49 35@2x](https://github.com/Expensify/App/assets/145416827/3ca7fe03-fd6e-48ee-8356-4776a55c8932)

**Comment by shawnborton** [comment]
Hmm I'm a little torn here. I see what you are thinking with the 50% opacity idea but I think I would rather just optimistically load the composer instead of using any kind of loading state.

**Comment by dubielzyk-expensify** [comment]
Yeah, optimistic loading is the better solution.

I assume this doesn't mean that if a user prematurely starts typing into the compose bar, then it fully loads, it'll delete what the user types?

**Comment by neil-marcellini** [comment]
Yeah we made it optimistically load, and it won't lose any data. You can see the end result in the [test videos here](https://github.com/Expensify/App/pull/42497#issuecomment-2148472657). I think the PR is on staging now and will go to prod today.

**Comment by rojiphil** [comment]
@sonialiap Please note that I was the C+ reviewer here as referenced [here](https://github.com/Expensify/App/pull/42497#issuecomment-2148472657)

**Comment by sonialiap** [comment]
@rojiphil thanks for the ping. I've added you as an assignee here so that it reminds me that you're to be paid for the review on the 20th

**Comment by sonialiap** [comment]
Payment summary
- @rojiphil $250 reviewer - [offer](https://www.upwork.com/nx/wm/offer/102807663) sent

**Comment by sonialiap** [comment]
@rojiphil since you're the C+ on the issue, please complete the [checklist](https://github.com/Expensify/App/issues/41955#issuecomment-2166001968)

**Comment by rojiphil** [comment]
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/40010)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/40010/files#r16492066908)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. :  Since the composer is an important component which the user interacts with, it is worth adding a test case for this.
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

Test Steps
	1	Without signing-in, launch a public room by entering the path in url: /r/868417741568295
	2	Verify that the public room opens with no composer. Instead, there is a sign-in button.
	3	Sign in with google
	4	Verify that the composer displays after a short duration.

**Comment by rojiphil** [comment]
> @rojiphil since you're the C+ on the issue, please complete the [checklist](https://github.com/Expensify/App/issues/41955#issuecomment-2166001968)

@sonialiap BZ Checklist completed and accepted offer too. Thanks

**Comment by sonialiap** [comment]
Paid and QA issue created ✔️
