### ISSUE TITLE
[payment due 8-27][Track Tax] Support tax tracking when categorizing tracked expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42114]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace has enabled taxes.

1. Go to staging.new.expensify.com
2. Go to FAB > Track expense.
3. Track a manual expense.
4. In 1:1 DM, click Categorize from the whisper.
5. Select a category.
6. On confirmation page, click Show more.

## Expected Result:
Tax rate will be populated in the Tax rate row.

## Actual Result:
Tax rate row is empty.
After the expense is submitted, the Tax rate row in transaction thread shows the selected tax rate.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/576e9914-ae3d-4f59-a932-b416f9e8e1c1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163666547be770dfa</li>
        <li>Upwork Job ID: 1793250352331440128</li>
        <li>Last Price Increase: 2024-05-22</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@sonialiap FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #vip-vsb

**Comment by aldo-expensify** [comment]
In `staging` and dev, I see that the transaction created in the conversation with ourselves has `taxAmount` and `taxCode`:

<img width="423" alt="image" src="https://github.com/Expensify/App/assets/87341702/17110ec2-30ce-40b0-bc99-042449d2f75a">

These fields get copied to the transaction draft, which I guess then it makes it show no value selected for taxes

Meanwhile, in production, I see that the transaction is missing `taxAmount` and `taxCode`

<img width="417" alt="image" src="https://github.com/Expensify/App/assets/87341702/12686503-3290-4f67-aeda-ec4a32613a83">

**Comment by aldo-expensify** [comment]
If I log out and log back in, the problem is gone, which makes me think this is an optimistic data problem

**Comment by aldo-expensify** [comment]
Deploy blocker caused by: https://github.com/Expensify/App/pull/40443/files#r1599258680

**Comment by aldo-expensify** [comment]
Created a PR: https://github.com/Expensify/App/pull/42126
I'm not 100% sure if there is something more to do or not, if the default tax is not 0%, the transaction ends up with a negative amount calculated... is that correct?

**Comment by MonilBhavsar** [comment]
Thanks for the investigation Aldo! 
I'll co assign and take a look

**Comment by MonilBhavsar** [comment]
I agree with root cause. When creating track expense, we create transaction with taxCode as `""` and taxAmount as `0`
When MoneyRequestConfirmationList is rendered, we have a useEffect to initialize taxCode and taxAmound fields with value but since taxCode and taxAmount are set, it does not update them.
We have two solutions - 

1. When categorizing expense, when user selects a policy and if it is policy expense chat, at that moment we update taxCode and taxAmount with defaults, optimistically
2. Do not create track expense with taxRate and taxAmount

Looking into 1, since it aligns with user actions and workflow

**Comment by aldo-expensify** [comment]
Hey @MonilBhavsar I think you have a better understanding of how taxes work, so feel free to proceed with the solution you find best: https://github.com/Expensify/App/pull/42151 or https://github.com/Expensify/App/pull/42126. Did you test both? is there one that works better?

**Comment by MonilBhavsar** [comment]
https://github.com/Expensify/App/pull/42126 looks good to me. Do you want to test it and push it forward for review?
We would also need Web-E and Auth updates to make this flow work completely

**Comment by MonilBhavsar** [comment]
I have added this project to wave collect and Xerocon release.

---

Communicating with Aldo, on how we're tackling this...

**Comment by aldo-expensify** [comment]
I'll have to come back to this next week, I've been focusing in higher priority issues

**Comment by aldo-expensify** [comment]
I'll try to get to this tomorrow, was OOO on Monday and I focused today on SharePolicy improvements which is higher priority.

**Comment by aldo-expensify** [comment]
I did some work on the frontend on Friday, but there is still work to do for the tax amount calculated. I haven't worked more in the backend yet,

**Comment by aldo-expensify** [comment]
Aiming to get back to this tomorrow (Friday)

**Comment by aldo-expensify** [comment]
Worked a bit on this on Friday, will try to continue tomorrow

**Comment by aldo-expensify** [comment]
Ended up re-implementing the front end PR in https://github.com/Expensify/App/pull/43519. This should avoid the bugs of the old PR and does less changes.

**Comment by aldo-expensify** [comment]
I'll work on the backend tomorrow

**Comment by aldo-expensify** [comment]
@MonilBhavsar , with the changes from this Auth PR https://github.com/Expensify/Auth/pull/10987/files, I see that the backend returns the amount and taxAmount as negative values

<img width="656" alt="image" src="https://github.com/Expensify/App/assets/87341702/cd005c76-c16a-4176-88d0-d53a153999c6">

And then in the UI they are displayed as positive values:

<img width="832" alt="image" src="https://github.com/Expensify/App/assets/87341702/fa9a50b1-7599-4060-8ac0-cc73fcd4c6db">

I think this is correct, right? Then, when I see the optimistic data in the transactionDraft in the frontend, these values are stored as positive numbers... which maybe is incorrect, is it incorrect?

<img width="1368" alt="image" src="https://github.com/Expensify/App/assets/87341702/3235520f-5695-43ce-8a20-c7d721f0dcf5">

This becomes visible if we follow the flow of categorizing while offline 


cc @eh2077, I may need to do more work in the App PR

**Comment by MonilBhavsar** [comment]
> I think this is correct, right? Then, when I see the optimistic data in the transactionDraft in the frontend, these values are stored as positive numbers... which maybe is incorrect, is it incorrect?

Ah yes, backend stores it as negative amount. We can make the amount as negative in optimistic data. We display absolute value in the UI

**Comment by MonilBhavsar** [comment]
@aldo-expensify any update here?

**Comment by aldo-expensify** [comment]
Sorry for the slowness, I'll get to this today or tomorrow. My plan is to fix the frontend so the optimistic tax is calculated using negative values, then make that App PR ready for review again, and then go to the backend.

**Comment by aldo-expensify** [comment]
Added a fix for the tax amount showing as negative: https://github.com/Expensify/App/pull/43519 and fixed the existing conflicts. I'll work on the backend tomorrow.

**Comment by aldo-expensify** [comment]
I barely worked after lunch because I'm not feeling well so I couldn't get to this today, I'll try again tomorrow (Thursday).

**Comment by aldo-expensify** [comment]
@MonilBhavsar do you mind taking over the backend changes (or find someone else to do them)? I just came back to work today and next week I'll be ooo
I think the frond end should be ready

**Comment by zsgreenwald** [comment]
@aldo-expensify can we find someone else while Monil is OOO?

**Comment by MonilBhavsar** [comment]
I'm back and can work on backend issues

**Comment by aldo-expensify** [comment]
> @aldo-expensify can we find someone else while Monil is OOO?

Ouch, I didn't notice @MonilBhavsar was OOO. I'm back too now.

**Comment by aldo-expensify** [comment]
I resumed working on this, I'll try to have the backend ready before making the App PR ready for review again to try to avoid having to resolve conflicts more times.

**Comment by aldo-expensify** [comment]
Made backend PRs ready for review:

- https://github.com/Expensify/Auth/pull/10987
- https://github.com/Expensify/Web-Expensify/pull/42115

**Comment by aldo-expensify** [comment]
[App PR](https://github.com/Expensify/App/pull/43519) was approved by @eh2077, waiting on internal engineer approval now.

**Comment by sonialiap** [comment]
@Christinadobrzyn I'm OOO Aug 19-30, adding leave buddy. 
Status: getting close to payment, waiting for reviews to be completed

**Comment by Christinadobrzyn** [comment]
awesome! moving this back to weekly to track for payment.

**Comment by Christinadobrzyn** [comment]
looks like the [PR](https://github.com/Expensify/App/pull/43519) is in staging so getting close -

**Comment by Christinadobrzyn** [comment]
The payment summary didn't trigger, I think this is due for payment today. 

Payouts due:

- [ ] Contributor+: $250 @eh2077 

@eh2077 are you paid via Upwork or NewDot? Do we need a regression test for this?

**Comment by Christinadobrzyn** [comment]
nuged @eh2077 can you confirm - https://github.com/Expensify/App/issues/42114#issuecomment-2313466286

**Comment by eh2077** [comment]
@Christinadobrzyn Thanks for the ping. I'd like to pay via upwork. Yes, I think we need to add regression test for this issue.

**Comment by eh2077** [comment]
I'm away from keyboard and I'll complete the checklist asap, thanks 🙏

**Comment by Christinadobrzyn** [comment]
Thanks @eh2077 I just send you an [Upwork offer](https://github.com/Expensify/App/issues/42114#issuecomment-2313466286) too.

**Comment by sonialiap** [comment]
Thanks @Christinadobrzyn ! I'm back from OOO and can take this back, feel free to keep on or unassign yourself

@eh2077 I've approved the payment ✔️ 
Please complete the checklist once you get a chance :D

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**I can't a PR directly caused this issue. The task ended up a larger scope than the original issue.**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. **_Yes_**

### Regression test
==== Prepare ====
1. Create a workspace
2. Set the workspace default currency to USD if it is not already that
3. Go to "More features" and enable "Distance rates" and "Taxes"
4. Go to "Taxes" and define 3 tax rates:
   - Tax USD40: 40%
   - Tax other currency10: 10%
   - Tax distance25: 25%
5. Still in "Taxes", click in "Settings" in the top and choose the following defaults:
<image width="300" src="https://github.com/user-attachments/assets/38c2f106-eafc-48d2-9ba0-2226f7871fb4">

6. Verify you end up with a configuration like this:
<image width="300" src="https://github.com/user-attachments/assets/c6306e7d-e7c1-4c1a-915e-e3ae0b2ce070">

7. Go "Distance rates" and enable "Track tax" in the top right settings
8. Create a distance rate, assign a tax rate to it and input some amount smaller than the rate in "Tax reclaimable on":
   
<image width="300" src="https://github.com/user-attachments/assets/c24d6f86-9635-4a0f-b560-bd95f8249942">

==== case 1 ====

9. In the DM chat with yourself, click "+ > Track expense" and create an expense with the same currency as the workspace currency
   
<image width="300" src="https://github.com/user-attachments/assets/dfaea596-f940-4a6f-a858-2eb56fd513f1">

10. Wait for the concierge message with actions and click "Categorize it"
    
<image width="300" src="https://github.com/user-attachments/assets/37a2b00f-2d1a-4004-830d-e465b29c0dbd">

11. The RHN should open with the workspace as the only alternative, select the workspace
12. Choose any category from the list
13. In the expense form, click "Show more"
14. Verify that the tax code is set to the default tax code for expenses with the currency of the workspace
15. Verify that the tax amount looks correct
16. Change the tax code manually
17. Verify that the tax amount is updated

==== case 2 ====

18. Dismiss the RHN clicking outside
19. In the DM chat with yourself, click "+ > Track expense" and create an expense with a different currency
20. Wait for the concierge message with actions and click "Categorize it"
21. The RHN should open with the workspace as the only alternative, select the workspace
22. Choose any category from the list
23. In the expense form, click "Show more"
24. Verify that the tax code is set to the default tax code for expenses with a different currency of the workspace

==== case 3 ====

25. Dismiss the RHN clicking outside
26. In the DM chat with yourself, click "+ > Track expense" and create a distance request
27. Wait for the concierge message with actions and click "Categorize it"
28. The RHN should open with the workspace as the only alternative, select the workspace
29. Choose any category from the list
30. Verify that the tax code is set to the default tax code for the distance rate selected
