### ISSUE TITLE
[Auth Next Steps] [Tracking] Implement report NextSteps in Auth

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42118]
Whatsnext post [here](https://expensify.slack.com/archives/CC7NECV4L/p1715644599860159).

Design doc https://docs.google.com/document/d/1gUDVqDdDj0jVOIuFBqPr0D6-vnClB-iztl38PzsiBqE/edit

GH Project https://github.com/orgs/Expensify/projects/154/views/1
CAP issue https://github.com/Expensify/Expensify/issues/406189

**Proposal**
Migrate the report next steps from PHP to Auth

**Problem**
Report next steps are currently calculated on the fly in PHP and are not stored in a database. This means that any commands using report next steps cannot be implemented following the true 1:1:1 API philosophy at the moment. We cannot queue report next steps updates in Auth because we must wait for an Auth command response to trigger the calculation of updated next steps in PHP. Only then can the update be pushed to relevant clients.

Similar to the case of [violations](https://github.com/Expensify/Expensify/issues/393838), this leads to multiple Auth calls being made during a single API request, breaking the 1:1:1 rule. Many commands are slowed down due to the report next steps computation triggering multiple Auth calls. For example, any action that changes the state or status of a report will trigger a new next step computation. These may be computed multiple times per report as each participant of the expense report might receive different next steps.

It's worth noting that in order to support optimistic and offline calculation of some report next steps, we've implemented the core collect workspace next steps logic in the front-end code of NewDot.

_While this project should only focus on migrating what we have from PHP to Auth, it is important to note that this migration is likely to be critical for ensuring that important upcoming projects are 1:1:1-compliant, such as the Search page, where we need to compute the next action for a report efficiently._

**Solution**
At a high level, the solution is to move report next steps to Auth; however, the details need to be fleshed out through predesign and a design document.

At minimum, we should discuss:

- The exact scope of this project.
- The deadline and priority of this project among others.
- How we are going to execute this migration from PHP to Auth to avoid any regressions in OldDot.
- Whether we should keep the report next steps in their own Onyx reportNextSteps key or add them as a key inside the report object.
- How we are going to coordinate with the violations migration that is related to this project (we need to be able to compute report violations to determine report next steps).
- How the timelines for the report [next steps audit](https://expensify.slack.com/archives/CC7NECV4L/p1715181813248599) and this project will align.

cc @JmillsExpensify @cead22 

---

## Tasks

- [x] Post **Proposal (full Problem/Solution statement)** in `#whatsnext`
- [x] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [x] Paste Proposal in the space above with a link to the Slack thread
- [x] Email `strategy@expensify.com` and paste in the Proposal
- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in an appropriate slack channel to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [x] Fill out the **High-level overview of the problem**, **Timeline**, **Terminology**, and **High-level of proposed solution** sections of the Design Doc
- [x] Email `strategy@expensify.com` (continue the same email chain as before - your last message should be the WN Proposal) with the link to your Design Doc containing your high-level problem and solution
- [x] Add the `DesignDocReview` label to get the **High-level overview of the problem** and **High-level of proposed solution** section reviewed
- [x] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Host another pre-design meeting in the appropriate slack channel to ask for engineering feedback on the technical solution.
- [x] Fill out the **Detailed implementation of the solution** and related sections.
- [x] Re-add the `DesignDocReview` label to this issue
- [x] Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase
- [x] Implement the changes
- [x] Add regression tests so that QA can test your feature with every deploy ([instructions](https://stackoverflowteams.com/c/expensify/questions/363))
- [ ] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by mountiny** [comment]
Shared in WN https://expensify.slack.com/archives/CC7NECV4L/p1715644599860159

**Comment by muttmuure** [comment]
Moving this to critical to include it in the daily updates

**Comment by mountiny** [comment]
The proposal got enough support so we can move ahead. I will plan to make a short predesign for this project, but my week is broken up with moving stuff from Scotland to Czechia and short planned holiday. I expect to make more progress next week, but I will attempt to have the predesign out by EOW, early next week the latest.

**Comment by mountiny** [comment]
Gonna pick this back up this week once the performance is in better place

**Comment by mountiny** [comment]
Looking into a predesign for tomorrow

**Comment by mountiny** [comment]
Deployer duties took over, still on my list

**Comment by mountiny** [comment]
The [predesign](https://expensify.slack.com/archives/C05LX9D6E07/p1716557793526289) was posted on Friday, going to sum it up to the doc this week

**Comment by mountiny** [comment]
Aiming for EOW still

**Comment by mountiny** [comment]
Violations doc is out, I havent made much progress yet on this, but will ship this on Monday

**Comment by mountiny** [comment]
Working on the high level still, aiming to have it mostly ready today

**Comment by mountiny** [comment]
Sent the design doc for high-level review

**Comment by dannymcclain** [comment]
I have read and reviewed this Design Doc!

**Comment by abekkala** [comment]
I have read and reviewed this Design Doc!

**Comment by marcaaron** [comment]
I have read and reviewed this Design Doc!

**Comment by Gonals** [comment]
I have read and reviewed this Design Doc!

**Comment by slafortune** [comment]
I have read and reviewed this Design Doc!

**Comment by danielrvidal** [comment]
I have read and reviewed this Design Doc!

**Comment by mountiny** [comment]
Reviews trickling in

**Comment by MitchExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by davidcardoza** [comment]
I have read and reviewed this Design Doc!

**Comment by mountiny** [comment]
reviews still coming in

**Comment by coleaeason** [comment]
I have read and reviewed this Design Doc!

**Comment by AndrewGable** [comment]
I have read and reviewed this Design Doc!

**Comment by puneetlath** [comment]
I have read and reviewed this Design Doc!

**Comment by twisterdotcom** [comment]
I have read and reviewed this Design Doc!

**Comment by mountiny** [comment]
Working through the comments and I will work on the detailed section

**Comment by iwiznia** [comment]
I have read and reviewed this Design Doc!

**Comment by francoisl** [comment]
I have read and reviewed this Design Doc!

**Comment by mountiny** [comment]
Nailing down the last remaining things in #fast-apis from the high level comments before heading to the detailed section.

**Comment by mountiny** [comment]
We are mostly agreeing on the threads now. We want to make sure we can send the **same** update/ text to everyone (so we can use pusher report channel), and keep the reporti the next steps inside the report object with `nextSteps`.

There is a project that should ideally come before this in implementation https://docs.google.com/document/d/1mUUQzep18IWdZpwG6Qqtw9JH0dvLMvLXh-KTn_B51I4/edit we are simplifying the next steps/ doing audit and as part of that we are focusing on updating the copy so the **same** message can be shown to every participant of the report such that is makes sense **who** needs to do **what**.

We are going to get that ready to review by Monday

**Comment by heyjennahay** [comment]
I have read and reviewed this Design Doc!

**Comment by mountiny** [comment]
Update: 
- we are going to first implement the update to the report next steps https://docs.google.com/document/d/1mUUQzep18IWdZpwG6Qqtw9JH0dvLMvLXh-KTn_B51I4/edit project, that should help us with the migration too
    - with the updated next steps, we are going to be sending the same copy to all participants, so we can use report pusher channel 
    - this will simplify the number of cases to handle making the migration itself smaller

**Comment by mountiny** [comment]
Same as above, getting through the audit

**Comment by mountiny** [comment]
Working on updating the next steps based on the audit project. Also going to loop in another engineer for help with this project

**Comment by mountiny** [comment]
Still proceeding with the next steps audit, @dangrous is going to take over this migration detailed doc and implementation

**Comment by mountiny** [comment]
@dangrous is joining the team, we are getting through the copy update for now, midway implementation there

**Comment by dangrous** [comment]
Working on the PRs! There's a bit of clarification needed but comments are left in the doc, we should be able to keep moving shortly. We may also need one additional cleanup PR at the end, both to fix some edge cases but also to DRY up and simplify the code that touches all cases, once everything's simplified!

**Comment by mountiny** [comment]
Getting through the report audit and then we can move ahead with the migration

**Comment by dangrous** [comment]
Almost done with the simplification/audit, then can move forward with this

**Comment by dangrous** [comment]
Nearly done! Should be ready to move forward with the detailed design next week

**Comment by dangrous** [comment]
I believe all PRs for the simplification are now merged! Will be able to continue work on the migration details this week in hopes of getting it ready to go for once violations are migrated. I'll have a better ETA on the details once I start working on that - right now focusing on finishing up the Copilot design doc

**Comment by dangrous** [comment]
Finishing up some minor changes to copy - https://github.com/Expensify/Web-Expensify/pull/42950

**Comment by dangrous** [comment]
Not overdue, the simplification is just waiting on new tests, and then we can start shifting attention to this. We're also still waiting for the violations migration so I may switch this to Weekly for a little bit, since the pressure is a bit off. Let me know if you disagree!

**Comment by dangrous** [comment]
Prioritizing copilot, and then will get back to this one afterwards!

**Comment by dangrous** [comment]
Still working on copilot. Expecting to be freed up by next week at the latest, to at least get a chunk of work done on this

**Comment by dangrous** [comment]
Still on track for next week

**Comment by dangrous** [comment]
Still finishing up copilot but hopefully should be able to start making headway later this week

**Comment by dangrous** [comment]
Same

**Comment by dangrous** [comment]
I... have not had time. Next week for sure! I think this will be a bit slow even once I get started since there's a lot of moving pieces

**Comment by dangrous** [comment]
okay! starting to look into this again. I need to remember how far I got before and then go from there

**Comment by dangrous** [comment]
this is proceeding, discussing what we want to do about translations (which may change our approach) in [this issue](https://github.com/Expensify/Expensify/issues/418091)

**Comment by mountiny** [comment]
@dangrous is working through the detailed section and the increased scope with translations

**Comment by mountiny** [comment]
@dangrous is working through the detailed section and the increased scope with translations

**Comment by dangrous** [comment]
still prioritizing copilot, that will be launched on mon and can focus more on this then, if not before

**Comment by dangrous** [comment]
predesign for a couple pieces of this will be going out tomorrow, then can continue work

**Comment by dangrous** [comment]
https://expensify.slack.com/archives/C05CBC62HGW/p1726247710654929

**Comment by dangrous** [comment]
WIll start updating design doc based on predesign shortly!

**Comment by dangrous** [comment]
Got some good further discussion on the predesign, I'll be restructuring the design doc and should be out by EOnextW - that's the plan anyway

**Comment by dangrous** [comment]
Okay chill melvin, will have time to start mapping this out again this afternoon!

**Comment by dangrous** [comment]
Working on this literally as we speak. Hoping to have the draft ready by EOW.

**Comment by mountiny** [comment]
Michal is going to help out on this project 🎉

**Comment by mjasikowski** [comment]
Still working on it, I'm helping with the PHP -> Auth mappings

**Comment by dangrous** [comment]
As @mjasikowski said. I was OOO at the end of last week; I'm back in and catching up now! Hoping to have this out for review by EOW

**Comment by trjExpensify** [comment]
Can we move this out of the `Done` status in the #fast-apis project to where it should be?

**Comment by dangrous** [comment]
moved to HIGH to match the issue title (which I am assuming is correct)

**Comment by dangrous** [comment]
Working on this with @mjasikowski - we're dealing with some higher priority work atm so it's a little slow but we'll get there

**Comment by dangrous** [comment]
I feel like these shouldn't go overdue on the weekend even if they're daily? Nonetheless, no update since Friday afternoon, should get some time to work on this this week!

**Comment by dangrous** [comment]
Still looking for the time here. Good news is @mountiny is working on a solution to get this to be 1:1:1 even before the migration, so the urgency in terms of making things faster is a little eased up. But still hoping to knock this out soon

**Comment by dangrous** [comment]
Falling behind due to higher pri work, hopefully after the 10/28 deadline for a lot of things we can tackle this again (at the latest)

**Comment by dangrous** [comment]
Will open up for this next week

**Comment by dangrous** [comment]
Copilot is 99% wrapped, should be good to jump back in

**Comment by dangrous** [comment]
Okay this time for sure. Next week!

**Comment by mjasikowski** [comment]
Shall we change this to weekly for now?

**Comment by dangrous** [comment]
higher priority stuff is on the table, will ideally get to this soon!

**Comment by dangrous** [comment]
We'll get there one day, hopefully as things slow down a bit in the holiday season

**Comment by dangrous** [comment]
Holiday project maybe? If not, in Jan for sure.

**Comment by dangrous** [comment]
happy new year! hopefull.y jumping back into this momentarily

**Comment by dangrous** [comment]
getting there.... I have time scheduled today to start working through this again

**Comment by dangrous** [comment]
other work taking priority, be here soon hopefully

**Comment by dangrous** [comment]
one dayyy

**Comment by dangrous** [comment]
Was OOO, will look into this again soon

**Comment by dangrous** [comment]
Ack! No time this week either

**Comment by dangrous** [comment]
Same as above.

**Comment by dangrous** [comment]
@mjasikowski how are you looking on bandwidth? I'm still slammed at the moment but would like to get this moving again soon. Would you be free to regroup sometime early next week?

**Comment by dangrous** [comment]
I'm like 95% sure I'll actually have time to jump back into this next week, for real this time. Much more optimistic than before.

**Comment by mjasikowski** [comment]
@dangrous I think I'll have some bandwidth next week, so we can catch up and give this one a go again

**Comment by dangrous** [comment]
Okay hi! I finished my read through. Here's what I think we still have left to do (cc @mountiny since you were working on this back in the day).

## Questions we need to answer
* What is the Old Dot flow that will access NextStep::get()
* How do we interface with search?
* How do we make sure formats that don't have "new" format next steps (like invoices) go through the old build process but still use the Onyx updates appropriately?
    * Note: I think we probably just copy only the necessary logic over from the old to the new style, just for invoices
* The HL mentions an incremental migration comparing PHP and Auth next steps, but says "(going to remove this bit)". Are we doing this, or no?
* How do we handle ETAs in next steps (e.g. on Sunday, end of the week, etc.)
  * I think sending a `etaKey` or similar, like `endOfWeek` or whatever, rather than a datestring as much as possible would be ideal, and calculate it from that in App. 
* What information do we need to include in the design doc for the Old Dot next step replication?
    * As little as possible would be ideal, because it's literally for now just duplicating the logic. Can we just say that and handle the rest during implementation?
* How do we make sure the approver is correct (using getNextReceiver somehow)?
* Are there any other places we need to add a call to NextStep::get(), outside of OpenReport and Search?
* What do we need to modify in PHP?

## Things we still need to detail (but we know how to do it)
* Need to create the pseudocode for the New Dot if/else block
* Need to make sure we call out which report / policy / actor / any other info we need for the New Dot if/else block
* Clarify how we add the next steps to OpenReport

It's still a lot, but it seems semi manageable. Most of the App logic is already in the doc (though not ETAs), and for the most part we've got the working plan for New Dot next steps. I'll set up some time for next Monday to discuss this, but we can chat here in the meantime, and I'll try to pick away at it over the next couple of days too.

**Comment by dangrous** [comment]
starting work on updating this, @mjasikowski is also going through it now so we should be able to make some progress soon!

**Comment by dangrous** [comment]
Nearly there! I think we should have this out by EOW!

**Comment by dangrous** [comment]
Retract report took precedence, but hoping to get to this either today, or, if not, the week after next (I'm OOO next week). But really there's not a huge amount left to do, we just need to handle it.

**Comment by dangrous** [comment]
Back from OOO - will catch up and review this week

**Comment by dangrous** [comment]
Okay for real this week! About to jump into this either today or tomorrow

**Comment by dangrous** [comment]
Okay, we're nearly there - just updating one last piece and will ship ideally today!

**Comment by mountiny** [comment]
I have read and reviewed this Design Doc!

**Comment by dangrous** [comment]
Not overdue, in review and responding to feedback

**Comment by grgia** [comment]
I have read and reviewed this Design Doc!

**Comment by JmillsExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by dangrous** [comment]
@stitesExpensify @AndrewGable @danielrvidal @coleaeason as assigned reviewers, would love your thoughts when you have time, thank you!

**Comment by danielrvidal** [comment]
I have read and reviewed this Design Doc!

**Comment by dangrous** [comment]
Dealing with final feedback in the docs, have pinged remaining reviewers. hopefully be able to get this started next week!

**Comment by dangrous** [comment]
I think by dropping down reviews to their lowest matching tier we are only waiting on one more engineering graduate review - we've got some extra higher level ones. Pinged the remaining assigned reviewers at the end of last week, too.

**Comment by coleaeason** [comment]
I have read and reviewed this Design Doc!

**Comment by stitesExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by trjExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by AndrewGable** [comment]
I have read and reviewed this Design Doc!

**Comment by dangrous** [comment]
Will create implementation issues this week and discuss with @rayane-d who's volunteered for the project!

**Comment by dangrous** [comment]
OKay @rayane-d I think I caught all the implementation issues we'll need and assigned them to you in Expensify/Expensify. Let me know if you have any questions or concerns!

**Comment by dangrous** [comment]
@rayane-d continues to work on the PRs!

**Comment by s77rt** [comment]
**Update** Working on https://github.com/Expensify/App/issues/69615. Draft [PR](https://github.com/Expensify/Auth/pull/17267).

**Comment by s77rt** [comment]
**Update:**
- https://github.com/Expensify/App/issues/69615: [PR](https://github.com/Expensify/Auth/pull/17267) is pretty much ready for merge
- https://github.com/Expensify/Expensify/issues/528712: 1st Auth [PR](https://github.com/Expensify/Auth/pull/17392) is merged. Waiting on 2nd Auth [PR](https://github.com/Expensify/Auth/pull/17408) and on a Web-E [PR](https://github.com/Expensify/Web-Expensify/pull/48800). Currently this only compares PHP results with Auth results and does not send Onyx updates to App yet. I may do that either in the existing Web-E PR or another one (should be easy work). Note: For now we will have to queue onyx updates from PHP because we want to queue them after comparison (which happens in PHP level). After removing PHP code, we should queue the updates on Auth.
- https://github.com/Expensify/Expensify/issues/528713: Starting on this one today.

**Comment by dangrous** [comment]
Work continues, and @rayane-d is back, too, so we have a bunch of hands. Hoping to get the comparison logic sorted y the end of the week and then we can refine as necessary!

**Comment by dangrous** [comment]
still in progress, shush melvin

**Comment by rayane-d** [comment]
Latest update here: https://expensify.slack.com/archives/C07NMDKEFMH/p1766514260505109?thread_ts=1766514253.120509&cid=C07NMDKEFMH

**Comment by dangrous** [comment]
Still getting there - mostly focusing on https://github.com/Expensify/Expensify/issues/582221 so we can flip the switch sometime soon!

**Comment by dangrous** [comment]
Not overdue! We are proceeding with fixing diffs.

**Comment by dangrous** [comment]
Not overdue, same as above.

**Comment by flodnv** [comment]
This is all done, right? 😃 🎉 👏

**Comment by s77rt** [comment]
Yes! It's been a year since I got assigned 😅 😁 Happy to see this one done! 🎉
