### ISSUE TITLE
[Awaiting checklist] [$250] IOU - App crashed after deleting IOU and relaunching app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42529]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in
2. Open any 1:1 chat
3. Tap + > Submit expense
4. Open the created IOU and delete it
5. Navigate back to LHN
6. Open the same chat again
7. Kill the app and open it again

## Expected Result:
The app opens and LHN is displayed

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c016f6a9-e684-41f9-b29d-e1e661f11d31

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0160e20b7c9a05d3c9</li>
        <li>Upwork Job ID: 1793688592596738048</li>
        <li>Last Price Increase: 2024-05-30</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 102740724</li>
<li>abzokhattab | Contributor | 102740725</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashed after deleting IOU and relaunching app
### What is the root cause of that problem?
 after removing the IOU, the returned report action of the deleted IOU here is `null` so the null value cannot be deconstructed here thus it the app is crashed:
 
 https://github.com/Expensify/App/blob/06f4dab76beb109fea28ac033eb8a6f0c598e67d/src/hooks/useReportIDs.tsx#L77-L96
### What changes do you think we should make in order to solve the problem?


we need to filter null report actions first


```js
const reportActionsSelector = (reportActions: OnyxEntry<OnyxTypes.ReportActions>): ReportActionsSelector =>
    (reportActions &&
        Object.values(reportActions)
            .filter(Boolean)
            .map((reportAction) => {
                const {reportActionID, actionName, errors = [], originalMessage} = reportAction;
                const decision = reportAction.message?.[0]?.moderationDecision?.decision;

                return {
                    reportActionID,
                    actionName,
                    errors,
                    message: [
                        {
                            moderationDecision: {decision},
                        },
                    ] as Message[],
                    originalMessage,
                };
            })) as ReportActionsSelector;
```

**Comment by ahmedGaber93** [comment]
Reviewing tomorrow

**Comment by ahmedGaber93** [comment]
@abzokhattab @aksh1t Thanks for the proposals.

I think we need to include the offending PR in the root cause to make sure we are doing the right solution.

**Comment by ahmedGaber93** [comment]
Waiting on proposals updates.

**Comment by ahmedGaber93** [comment]
Waiting on proposals.

**Comment by ahmedGaber93** [comment]
@tienifr can you dig into the code and find it?

**Comment by ahmedGaber93** [comment]
I do some investigation into onyx, I can't find the offending PR, but I found a few PRs talk about changing the way of removing null values. This issue https://github.com/Expensify/react-native-onyx/issues/553 is for performance purpose related to https://github.com/Expensify/App/issues/42654, but it changes the way that onyx used to remove null values, and it was merged in version `2.0.43`. I test this issue with onyx version `2.0.43` and it works fine.

So this issue is not reproduced on the last version of onyx `2.0.43`. And based on this comment https://github.com/Expensify/react-native-onyx/pull/554#pullrequestreview-2089430667 we are going to bump onyx version on next few days.

@twisterdotcom I think we can hold this for https://github.com/Expensify/App/issues/42654 which will bump onyx version to `2.0.43` that fix this issue.
Also, this issue causes a crash that prevent the user from opening the app, I am not sure if it should be a deploy blocker or not

**Comment by twisterdotcom** [comment]
Great investigation @ahmedGaber93.

**Comment by ahmedGaber93** [comment]
Bump onyx PR https://github.com/Expensify/App/pull/42772 still not merged.

**Comment by ahmedGaber93** [comment]
Bump onyx PR #42772 still not merged

**Comment by ahmedGaber93** [comment]
Bump onyx PR https://github.com/Expensify/App/pull/42772 still not merged.

**Comment by abzokhattab** [comment]
Can we push this forward, the app still crashes .. i think we should put a higher priority on this one

**Comment by abzokhattab** [comment]
yes still occuring

**Comment by ahmedGaber93** [comment]
checking

**Comment by ahmedGaber93** [comment]
The latest onyx `2.0.48` version not cause the issue is in the previous place [here](https://github.com/Expensify/App/blob/06f4dab76beb109fea28ac033eb8a6f0c598e67d/src/hooks/useReportIDs.tsx#L77-L94), but it appears a similar issue in a new place [here](https://github.com/Expensify/App/blob/15a6ef4121c12bd086441a1a8b39fb0fdf54e96e/src/libs/ReportUtils.ts#L6778) 

<details>
<summary>Screenshot</summary>

![Simulator Screenshot - iPhone 15 Pro Max - 2024-06-14 at 18 27 08](https://github.com/Expensify/App/assets/41129870/1a261be2-17d9-4146-a145-1a7f2e2cc10b)

</details>

**Comment by abzokhattab** [comment]
correct i updated my proposal to tackle this as well

**Comment by ahmedGaber93** [comment]
The RCA for this issue is onyx sent null values to the E/App while it should remove it. 
We have a [PR](https://github.com/Expensify/react-native-onyx/pull/554) in onyx that supposed to remove null values from all getter options, like `withOnyx`, `useOnyx` and `Onyx.connectand` see here https://github.com/Expensify/react-native-onyx/pull/554#issuecomment-2141356570, but it is not fixed it in all places, it fixed [here](https://github.com/Expensify/App/blob/06f4dab76beb109fea28ac033eb8a6f0c598e67d/src/hooks/useReportIDs.tsx#L77-L94) using `useOnyx`, but it appears in a new place [here](https://github.com/Expensify/App/blob/15a6ef4121c12bd086441a1a8b39fb0fdf54e96e/src/libs/ReportUtils.ts#L6778) using `Onyx.connectand`

I comment with the issue in the PR here https://github.com/Expensify/react-native-onyx/pull/554#issuecomment-2168569583

But because of **this issue causes a crash that prevent the user from opening the app** I think we can move forward with @abzokhattab's [proposal](https://github.com/Expensify/App/issues/42529#issuecomment-2127597831) which add null check in E/App using `.filter(Boolean)` same as we do in many places in the app.

🎀 👀 🎀 C+ reviewed

**Comment by abzokhattab** [comment]
Yes no problem will work on it tomorrow morning

**Comment by abzokhattab** [comment]
The PR is ready!

**Comment by ahmedGaber93** [comment]
PR has been reviewed by C+

**Comment by hayata-suenaga** [comment]
The PR was merged 🚀

**Comment by twisterdotcom** [comment]
Payment Summary:

- @ahmedGaber93 paid $250 [here](https://www.upwork.com/nx/wm/offer/102740724) (Reviewer)
- @abzokhattab paid $250 [here](https://www.upwork.com/nx/wm/offer/102740725) (Contributor)

Waiting on the checklist @ahmedGaber93

**Comment by ahmedGaber93** [comment]
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: N/A
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug. Yes
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Open any 1:1 chat
2. Tap + > Submit expense
3. Open the created IOU and delete it
4. Navigate back to LHN
5. Open the same chat again
6. Make sure the app is not crashed and the IOU report is deleted successfully.

Do we agree 👍 or 👎
