### ISSUE TITLE
[WAITING ON CHECKLIST] [$125] android-Quick action-Pay someone quick action text is truncated differently in mweb& Android

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43801]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.84-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Launch app and mweb site
2. Tap fab --- pay someone
3. Enter an amount and tap next
4.Select a user with long mail id
5.Tap pay someone
6.Navigate to LHN
7.Tap fab
8.Note Quick action text

## Expected Result:
Pay someone quick action text must appear in same way in mweb and Android.

## Actual Result:
Pay someone quick action text is truncated differently in mweb and Android.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/5003b0b0-1409-4e81-aa0d-daea1f65d748

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01de2d4ebfe6056500</li>
        <li>Upwork Job ID: 1802507450394853188</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 102856350</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by m-natarajan** [comment]
@jliexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pay someone quick action text is truncated differently in mweb& Android 

### What is the root cause of that problem?
The menuItem does not take full width since `styles.flex1` isn't applied to title for `FocusableMenuItem` here:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/PopoverMenu.tsx#L219

### What changes do you think we should make in order to solve the problem?
We will pass `styles.flex1` as the `titleStyles` [here](https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/PopoverMenu.tsx#L219):

```jsx
    titleStyle={styles.flex1}

```

**Comment by jliexpensify** [comment]
This is a quick action button issue, so should be in #collect

**Comment by Ariqkip** [comment]
**Proposal** 
Android-Quick Action-Pay Someone Quick Action Text is Truncated Differently in Mweb & Android
**Root Cause Analysis**
The issue stems from differences in text rendering and layout handling between mobile web (mweb) and Android platforms. Specific factors contributing to this issue include:

1.**_CSS and Layout Variation_**: Differences in CSS styles and layout configurations between mweb and Android components affecting text wrapping and truncation behavior.

2.**_Text Measurement and Handling_**: Variations in how text is measured, particularly concerning available width and font metrics, leading to differing truncation points.
**### Proposed Solution**
**_Unified CSS Styling_**:

Implement consistent CSS styles across mweb and Android components rendering the quick action text. Ensure uniformity in padding, margins, width constraints, and text overflow handling.
**_Font and Text Handling:_**

Ensure consistent font family, size, and weight across both platforms. Use platform-specific adjustments if necessary to maintain visual consistency.
**_Responsive Design Considerations:_**

Implement responsive design principles to handle varying screen sizes and orientations across platforms. Use media queries to adapt layouts similarly on mweb and Android.

**Comment by Ariqkip** [comment]
Contributor details
Your Expensify account email: ariqngoneshi@gmail.com
Upwork Profile Link:https://www.upwork.com/freelancers/~01e8fca580ad3567b3

**Comment by jliexpensify** [comment]
Bump @MonilBhavsar on approval for the proposal.

**Comment by MonilBhavsar** [comment]
Minor styling issue on Android, so updating the price cc @jliexpensify

**Comment by neonbhai** [comment]
While solving this issue, I was blocked by this error


https://github.com/Expensify/App/assets/64629613/f46f0e6d-1334-4e05-b2d3-e101183cd80c



### Root Cause:

I tried paying the applause user in the original issue video and it failed. But with the API fail the app crashed. This rendered the app unusable for me.

I looked into this and realised the bug happens if `quickAction` is `Send Money` but no avatar was loaded (i.e., `quickActionAvatars` is empty). This made the condition here false:
https://github.com/Expensify/App/blob/5e464eaa3e7614e6f17007e05203e184c275faf2/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L211

and this line is executed:

https://github.com/Expensify/App/blob/5e464eaa3e7614e6f17007e05203e184c275faf2/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L216

### Why does the app crash?

This is because the `quickAction.paySomeone` string takes in the `name` param inside an object. 

https://github.com/Expensify/App/blob/5e464eaa3e7614e6f17007e05203e184c275faf2/src/languages/en.ts#L622

If no second param is passed, this object destructing fails (as the app tries to read `name` property of `undefined`)

<Details><Summary>Image</Summary>
<img width="394" alt="Screenshot 2024-06-26 at 5 48 57 PM" src="https://github.com/Expensify/App/assets/64629613/a2f9ecad-6fab-40af-a95a-18d43e5176cb">


</Details>

### How to solve?
We should have the `name` param as a variable and not an object. 

Change [this line](https://github.com/Expensify/App/blob/5e464eaa3e7614e6f17007e05203e184c275faf2/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L213) to:

```jsx
return translate('quickAction.paySomeone', name);
```

and [here](https://github.com/Expensify/App/blob/5e464eaa3e7614e6f17007e05203e184c275faf2/src/languages/en.ts#L622):

```jsx
paySomeone: (name: string) => `Pay ${name ?? 'someone'}`,
```

**Comment by neonbhai** [comment]
Should we fix this?

cc: @thesahindia @MonilBhavsar 

👍 - Agree go ahead

👎 - Disagree

**Comment by MonilBhavsar** [comment]
Thanks for proposing this. Let's fix it 👍

**Comment by neonbhai** [comment]
not overdue, finalizing PR soon!

**Comment by jliexpensify** [comment]
Payment summary:

- C: @neonbhai$125
- C+: @thesahindia $125 (New.Dot payment) - waiting on checklist!

[Upwork job](https://www.upwork.com/jobs/~01de2d4ebfe6056500)

**Comment by jliexpensify** [comment]
Paid and job closed. Waiting on checklist.

**Comment by jliexpensify** [comment]
Bumping @thesahindia for a checklist, if necessary

**Comment by jliexpensify** [comment]
All good, cheers! Closing.

**Comment by JmillsExpensify** [comment]
$125 approved for @thesahindia
