### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] IOU - On entering amount with decimals, 3rd decimal 0 is added in IOU confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43945]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A ](https://expensify.testrail.io/index.php?/tests/view/4642442)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab -- submit expense
3. Select JOD currency
4. Enter an amount with 2 decimal place eg: 56788.56
5. Try to enter in 3rd decimal place, and note user not allowed to enter
6. Tap next and select a workspace
7. Note the amount in IOU confirmation page

## Expected Result:
In BNP, for 3rd decimal place user not allowed to enter similarly in iou confirmation page, zero must not be shown at 3rd decimal place when using JOD currency

## Actual Result:
In BNP, for 3rd decimal place user not allowed to enter but in iou confirmation page, zero is shown at 3rd decimal place when using JOD currency

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/276acf85-8fe5-4332-a392-b17783dc579d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed9d350ad9d63d20</li>
        <li>Upwork Job ID: 1803907448446264563</li>
        <li>Last Price Increase: 2024-06-20</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 102858807</li>
<li>Krishna2323 | Contributor | 102858808</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by greg-schroeder** [comment]
Sent through for proposal review

**Comment by thienlnam** [comment]
> @thienlnam - Please confirm whether we still limit the number of decimals to two on the backend. Thank you!

Yes this is correct - depending on the currency we format to 0 or 2 decimals

**Comment by greg-schroeder** [comment]
PR on staging, awaiting deploy to prod

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @Krishna2323 - $250 - Paid via Upwork
C+: @rayane-djouah - $250 - Paid via Upwork

**Comment by greg-schroeder** [comment]
@rayane-djouah for the checklist now!

**Comment by aldo-expensify** [comment]
I don't think it was a bug what this issue is describing. Was the backend formatting JOD with 2 decimals and the frontend with 3? if that is the case, then 👍 , if the backend is formatting JOD with 3 decimals, and now the front end will format JOD with 2 decimals, then we may be introducing a regression. The point is that they should be aligned.

**Comment by aldo-expensify** [comment]
nice, all good then, thanks for confirming.
