### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] [$250] Track expense - "Join" button appears in report details page when tracking expense in self DM

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44202]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause -Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a manual expense
4. Go to transaction thread
5. Click on the chat header

## Expected Result:
"Join" button will not appear in report details page

## Actual Result:
"Join" button appears in report details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/609b50b0-fad6-4647-af21-0734a99d7de4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a02e6fd1b333eff</li>
        <li>Upwork Job ID: 1805160854935465741</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 102853800</li>
<li>bernhardoj | Contributor | 102853801</li>
<li>c3024 | Contributor | 102854334</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Join button shows in the track expense report details page.

### What is the root cause of that problem?
We already hide the join button if it's an expense report.
https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/pages/ReportDetailsPage.tsx#L450

But the expense report only covers invoice, IOU/expense report, and IOU/expense transaction thread.
https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/pages/ReportDetailsPage.tsx#L123

### What changes do you think we should make in order to solve the problem?

Add a new condition to check if it's a track expense report.
```
const canJoin = !isExpenseReport && !ReportUtils.isTrackExpenseReport(report) && ReportUtils.canJoinChat(report, parentReportAction, policy);
```

_we can optionally move the condition to canJoinChat_

**Comment by twisterdotcom** [comment]
@arosiclair or @akinwale - can we assign @bernhardoj here?

**Comment by mountiny** [comment]
Just moving this ahead before Andrew comes online. @bernhardoj, can you please raise the PR for this quickly as it's a deploy blocker? Thanks!

**Comment by arosiclair** [comment]
Merged the PR. Asking for a CP

**Comment by arosiclair** [comment]
Fix works on staging 

![Screenshot 2024-06-24 at 2 15 02 PM](https://github.com/Expensify/App/assets/6833644/4f94e8c1-d11f-4d33-974c-4303232d116b)

**Comment by c3024** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #43251 
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/bernhardoj/Expensify/commit/9c88ab83f3a9402b28f10f716e861791f311da2d#r144232517
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No, this could not have been identified earlier.
* [x]  [@c3024] Determine if we should create a regression test for this bug. No, this was caught in staging. So, no separate test is required.
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. NA

**Comment by twisterdotcom** [comment]
Hello folks, sorry I was OOO last week. I have a bunch to do, I will get them all done today. Thanks for your patience.

**Comment by twisterdotcom** [comment]
Payment Summary:

 @bernhardoj paid $250 [here](https://www.upwork.com/nx/wm/offer/102853801) (Contributor)
- @c3024 paid $250 [here](https://www.upwork.com/nx/wm/offer/102854334) (Contributor)
