### ISSUE TITLE
[$250] Task –Several Subtasks appears in chat when assign task to you and change to user B few times

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44435]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4671285
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open chat with user B
4. Create a task without assignee in a 1:1 chat
5. Open task details and create a subtask without assignee
6. Open Subtask details and assign it to you
7. Assign to user B
8. Repeat steps 6-7
9. Navigate back to 1:1 chat

## Expected Result:
Verify 1 subtask present in the 1:1 chat

## Actual Result:
Verify 2 subtasks present in 1:1 chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6c6a1100-564c-465b-96ab-fdd11ff1877e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01215e598c7ed0eadc</li>
        <li>Upwork Job ID: 1809007855713589443</li>
        <li>Last Price Increase: 2024-08-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by RachCHopkins** [comment]
I can't replicate this - for me it assigns the task and just shows it the once. Then it later shows it as changed, but still online shows the one. 

![image](https://github.com/Expensify/App/assets/32854888/d3875d49-22ff-4094-8332-573db64e551e)

**Comment by MelvinBot** [comment]
This has been labelled "Needs Reproduction". Follow the steps here: https://stackoverflowteams.com/c/expensify/questions/16989

**Comment by kavimuru** [comment]
Tester is still able to reproduce.

https://github.com/Expensify/App/assets/43996225/77006ec7-6afb-4898-9452-a1c66844ec5d

**Comment by RachCHopkins** [comment]
Maybe I just don't understand what I am supposed to see. 

Step 1: Assign sub task back and forth a few more times than before:

![image](https://github.com/Expensify/App/assets/32854888/5638c4ba-fca5-4448-85fb-869735088352)

Step 2: Go back to chat:

![image](https://github.com/Expensify/App/assets/32854888/22e7d0e8-cb9c-479f-8c36-7e0ed1b33487)

I can now see each assignment for User 2.

**Comment by RachCHopkins** [comment]
@kavimuru What should I be seeing? The sub task listed only one time?

**Comment by mvtglobally** [comment]
Issue is reproducible during KI retests. 

https://github.com/Expensify/App/assets/43995119/321190e3-c06e-4dd0-83d7-762ebbbf9c36

**Comment by RachCHopkins** [comment]
Thank you, I think we can consider this reproduced, even if I don't entirely understand personally what it should look like.

**Comment by rushatgabhane** [comment]
waiting for proposals

**Comment by rushatgabhane** [comment]
same

**Comment by RachCHopkins** [comment]
@rushatgabhane what do you think we should do here? I'm new to the process.

**Comment by rushatgabhane** [comment]
@RachCHopkins i think you have to take it to the project room on slack and 
1. determine if its a bug. 
2. is the bug worth solving 
3. expected results 
4. then we're back to waiting for proposals from contributors

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
Each time we re-assign the task, a comment to notify the assignee will always be created.

### What changes do you think we should make in order to solve the problem?
This will also require backend change.
The following code works in offline mode.

Add new check to this line:

https://github.com/Expensify/App/blob/f7e265a65f695edd85870bd0c8048cf4578e14fb/src/libs/actions/Task.ts#L662-L664

This will check if similar comment has already been made.
```tsx
    const assigneeChatReportActions = ReportActionsUtils.getAllReportActions(assigneeChatReportID);
    const hasMatchingChildReportID = Object.values(assigneeChatReportActions).some(action => action.childReportID === report.reportID);
    if (assigneeAccountID && assigneeAccountID !== report.managerID && assigneeAccountID !== ownerAccountID && assigneeChatReport && !hasMatchingChildReportID) {
```

[Branch for this solution.](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/44435-fix-duplicate-task-comment?expand=1)
### What alternative solutions did you explore? (Optional)

**Comment by RachCHopkins** [comment]
VIP-VSB is now on hold. I don't think this is something we'll want to fix right now.
