### ISSUE TITLE
[Tracking] Offline Distance issues

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#44582]
Let's address these issues holistically with @paultsimura overseeing them and devising a plan of attack. 

- [x] https://github.com/Expensify/App/issues/44154
- [x] https://github.com/Expensify/App/issues/44163
- [x] https://github.com/Expensify/App/issues/43738
- [ ] https://github.com/Expensify/App/issues/40589
- [x] https://github.com/Expensify/App/issues/38392

Others already working on
- https://github.com/Expensify/App/issues/42784 
- https://github.com/Expensify/App/issues/34686
- https://github.com/Expensify/App/issues/37560 
- https://github.com/Expensify/App/issues/34686
- https://github.com/Expensify/App/issues/30123

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by mallenexpensify** [comment]
@paultsimura please comment so I can assign to you

**Comment by mallenexpensify** [comment]
Thanks @paultsimura .  Keep tabs on the issues for now.
