### ISSUE TITLE
[Awaiting BZ checklist][$500] LHN – Offline created chat disappears from LHN when come back online

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#44829]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4697531&group_by=cases:section_id&group_id=296759&group_order=asc
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
1. Login with gmail account

Steps:
1. Disable the internet connection in the device
2. Click on the green + button
3. Click on the "Start Chat" option
4. Search for a user with no existing conversation before> Create the chat
5. Send some messages
6. Go online

## Expected Result:
Chat should be present on LHN when user come back online

## Actual Result:
Chat disappears from LHN when user come back online

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/7e25eea4-91be-47b2-8974-1bf39d9c5014

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b675008f8cbacd91</li>
        <li>Upwork Job ID: 1810508261864647523</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>b4s36t4 | Contributor | 103408313</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by kavimuru** [comment]
@kadiealexander FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by ranit2018** [comment]
Contributor details
Your Expensify account email: developer.ranit@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/ranit

**Comment by ranit2018** [comment]
> @ranit2018 Please update your proposal as per the guidelines.

I did post the solutions, what else is needed let me know.

**Comment by ranit2018** [comment]
@parasharrajat I did post the solution as mentioned in the Upwork description. If you need anything else, let me know clearly.

**Comment by ranit2018** [comment]
@parasharrajat I did the same

**Comment by ranit2018** [comment]
@parasharrajat hope it's fine now.

**Comment by mallenexpensify** [comment]
Bumping price, this seems important.  @kadiealexander and @parasharrajat , are you able to reproduce?

**Comment by kadiealexander** [comment]
@mallenexpensify yeah kinda, it disappears if I click away:

https://github.com/user-attachments/assets/68dce2d3-6c0c-4315-a6d0-000371e252d7

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN – Offline created chat disappears from LHN when come back online
### What is the root cause of that problem?

Root cause for this issue is how we handle offline updates and how we're handling the notification prefreneces.

By default backend send `notificationPrefernece` hidden for new chat unless it contains some `reportActions`.

This works in online mode because there's queuing happens in online mode i.e each api call's onyx updates are happened as soon they're done.

Online Flow:

* Create Chat - `notificationPrefernece` as `hidden`
* Add Comment - Nothing
* GetMissingOnyxMessages - `notificationPrefernece` as `always`

Because all this flow executed as soon as they're done we don't have any problem with the online flow.

Let's understand the offline flow.

Offline Flow:

* Go Offline
* Create Chat - Queue Onyx Update
* Add Comment - Queue Onyx Update - Do Optimistic update for prop `notificationPrefernece` as `alaways` 
* Go Online
* Execute `openReport` call and save updates in queue.
* Execute `AddComment` call and save updates in queue.
* Execute `GetMissingOnyxMessages` call and apply onyx updates `notificationPrefernece` as `alaways`.
* Call `ReConnectApp` and nothing happens cause all the required updates are already happened.

Now that all queue api calls are done i.e `SequentialQueue` is emptied we call https://github.com/Expensify/App/blob/959d6d0271169536ae46e15d482049d8a2468234/src/libs/actions/QueuedOnyxUpdates.ts#L16 this function which will execute the queue updates.

`AddComment` updated `notificationPrefernece` optimisticly but the onyx updates coming from the `openReport` api does contain the onyx update for `notificationPrefernece` key with value `hidden` which is overriden when `flushQueue` function get's executed.

Basically the updates happening in offline mode are overriden by the queue we're maintaing which is defaulting the value to back it's state causing the report to be hidden as per this condition we have here https://github.com/Expensify/App/blob/31df927305511d53f4f8b5d6d4132d9293cce843/src/libs/SidebarUtils.ts#L111


### What changes do you think we should make in order to solve the problem?

Current execution doesn't have any problem other than how we're applying them. 

To solve this issue we can have a `success` update for the `AddComment` method which will append the `notificationPreference` key to the flush queue which makes sure that the value is updated accordingly.

Right now we're doing the following logic for optimistic update, we can do it for `successData` as well.

Adding the following block of code after this line https://github.com/Expensify/App/blob/7939596d77617448231356ecba23bb2537accaa6/src/libs/actions/Report.ts#L524 should fix the issue.

```jsx

 if (!isEmptyObject(report) && ReportUtils.getReportNotificationPreference(report) === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN) {
        successData.push({
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
            onyxMethod: Onyx.METHOD.MERGE,
            value: {notificationPreference: CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS, "hello":"hello" },
        });
        // optimisticReport.notificationPreference = CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS;
    }

```



### What alternative solutions did you explore? (Optional)
Or we could return the `notificationPreference` prop from `AddComment` method from backend itself if `reportActions` does have length as 1.

### Demo

https://github.com/user-attachments/assets/ed07cfc7-b9d9-4538-a007-de6e96419e95

**Comment by b4s36t4** [comment]
Gentle bump for review @parasharrajat.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

LHN – Offline created chat disappears from LHN when come back online

### What is the root cause of that problem?

When the notification preferences is hidden, [this code](https://github.com/Expensify/App/blob/38cddeeb3879a1eefd4458ba69083c84c8fd83b1/src/libs/SidebarUtils.ts#L140-L142) makes the report not included in LHN options even when LHN mode is default (not focused mode.)

### What changes do you think we should make in order to solve the problem?

According to https://github.com/Expensify/App/pull/33779
> Hide muted reports in the LHN in focus mode, even if they have unread messages

So we can add `isInFocusMode` condition to [the hidden condition](https://github.com/Expensify/App/blob/38cddeeb3879a1eefd4458ba69083c84c8fd83b1/src/libs/SidebarUtils.ts#L140-L142).

```tsx
        if (isHidden && !shouldOverrideHidden && isInFocusMode) {
            return;
        }
```

### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment]
I think [this](https://github.com/Expensify/App/issues/44829#issuecomment-2237879048) behavior is expected when `isInFocusMode` is `true`.

**Comment by b4s36t4** [comment]
@parasharrajat Gentle bump for proposal review :)

**Comment by marcochavezf** [comment]
Thanks for the review @parasharrajat, assigning @b4s36t4 🚀

**Comment by b4s36t4** [comment]
@parasharrajat maybe by the end of tomorrow I'll have the pr ready with all things. If there's any blocker will update as soon as possible.

**Comment by b4s36t4** [comment]
Hi, @parasharrajat. Sorry I tried to raise the PR soon, but wasn't able. Anyhow now I'm facing an issue with the app not able to send message for web version. I'm not sure it's for me or it's based on the code. Once that's resolved I'll just need to record the videos for chrome-mobile and ios-safari that's it. Will update here once PR is done.

**Comment by b4s36t4** [comment]
Yea, got the answer from slack and it seems working. Will share the PR soon!

**Comment by puneetlath** [comment]
I think with the changes we're making this problem would still exist, but only momentarily. Because: 

1. addComment optimistically sets the participant.me.notificationPreference as "always"
2. OpenReport returns participant.me.notificationPreference as "hidden" when back online
3. addComment returns the participant.me.notificationPreference as "always"

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $X @parasharrajat via NewDot
- [x] Contributor+: $X @b4s36t4 ([Upwork](https://www.upwork.com/nx/wm/workroom/38017911/overview?nav_dir=pop))

Upwork job is [here](https://www.upwork.com/jobs/~01b675008f8cbacd91).

**Comment by kadiealexander** [comment]
@parasharrajat please complete the checklist!

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
