### ISSUE TITLE
[HOLD for payment 2024-09-17][$250] [Tracking][Search v2.1] Follow up issues

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#45293]
A couple of clean up items as we start to roll out Search v2:

- [x] [Remove getQueryHash](https://github.com/Expensify/App/pull/45161#discussion_r1672750303)
- [x] [Add better error handling to SaerchUtils.buildJSONQuery](https://github.com/Expensify/App/pull/45161#discussion_r1672750541)
- [x] [Add comments to getFilters](https://github.com/Expensify/App/blob/58e257532290aa0228f1c668ed461a15f1b2b136/src/libs/SearchUtils.ts#L333)
- [x] [Add policyID to grammar](https://github.com/Expensify/App/blob/58e257532290aa0228f1c668ed461a15f1b2b136/src/libs/SearchParser/searchParser.peggy#L85-L104)
- [x] [Send index from the backend to simplify frontend sorting logic.](https://github.com/Expensify/App/issues/46720#issuecomment-2273377077)
- [x] [Group multi-select filters as an array](https://github.com/Expensify/App/pull/47789#issuecomment-2326266242)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833881850571575893</li>
        <li>Upwork Job ID: 1833881850571575893</li>
        <li>Last Price Increase: 2024-09-11</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
Gonna get to this soon

**Comment by luacmartins** [comment]
We'll handle these once the filter PRs are done.

**Comment by Kicu** [comment]
I will start to work on adding `policyIDs` to grammar.
This task is a bit tricky since we have a lot of special hacks for making `policyIDs` query param work with existing `.../w/<policyid>/report...` routes and with workspace switcher.

Once we move `policyIDs` into AST we need to go over all the special edge cases and refactor or remove them

**Comment by luacmartins** [comment]
Thanks for picking this one up!

**Comment by 289Adam289** [comment]
I can start to work on updating the grammar to return multi-select values in the same AST node.

**Comment by 289Adam289** [comment]
While working on issues related to grammar i came across two bugs:

1. Operators `>=` and `<=` don't work. It is directly connected to how peggy handles disjunctions and should be easily solved by changing the order of operators in grammar.

2. Words in free text that have a prefix equal to any keyword results in unexpected behavior. For example `ink` results in `{operator: 'eq', left: 'in', right: 'k'}`. It is caused by operator in filter being optional.

I can implement fixes in the pr updating the grammar

**Comment by luacmartins** [comment]
Ah nice catch @289Adam289, yea let's update those cases

**Comment by Kicu** [comment]
I wanted to suggest that we mark:
`Add better error handling to SaerchUtils.buildJSONQuery` as done.

Reason: the error that is thrown now is a bit more verboes (done by me) and @289Adam289 has updated the grammar and gave better names to parts of grammar.
https://github.com/Expensify/App/blob/main/src/libs/SearchUtils.ts#L324

Here's how an error looks now:
![Screenshot 2024-09-02 at 17 02 47](https://github.com/user-attachments/assets/b0ee90f5-ed93-4d19-b63a-bb22072e9f42)

**Comment by luacmartins** [comment]
The only thing left here is to send a sortIndex from the backend to simplify the sorting logic on the frontend. My only concern with that approach is that live updates would mess up with the sorting in the frontned. Assume the following case:

1. User opens the page and gets a list of sorted transactions
2. User opens one transaction and edits the date, which would change the sort order
3. Data now shows up out of order

So given the above, I'm inclined to just close this issue for now. We can revisit the backend sorting logic if needed.

**Comment by lschurr** [comment]
Could you clarify what you're referring to @Kicu? The PR was deployed and now we wait 7 days before closing to make sure there are no regressions.

**Comment by luacmartins** [comment]
@lschurr @Kicu was replying to my comment [here](https://github.com/Expensify/App/issues/45293#issuecomment-2343909328)

**Comment by lschurr** [comment]
Looks like the automation didn't work, so I manually sent the offer @rayane-djouah - https://www.upwork.com/nx/wm/offer/104006695
