### ISSUE TITLE
[Awaiting checklist] [$250] mWeb - Chat - Keyboard is not dismissed when pasting an image on compose box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45471]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4724379
**Email or phone of affected tester (no customers):** vdargentotest+mweb071524@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: copy an image from the phone gallery
1. Go to any chat
2. Tap on the compose box for the keyboard to be displayed
3. Paste the image you copied before

## Expected Result:
The image preview page should be completely displayed

## Actual Result:
The image preview page is partially displayed and the keyboard is not dismissed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/eff65df1-0802-4984-a19e-c8b71c4ba942

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f768185460c027a</li>
        <li>Upwork Job ID: 1813533658277249254</li>
        <li>Last Price Increase: 2024-07-17</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103215448</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone. 

[Proposal](https://github.com/Expensify/App/issues/45471#issuecomment-2230816028) from @Krishna2323 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by twisterdotcom** [comment]
Payment Summary:

- @sobitneupane paid $250 via NewDot Manual Request
- @Krishna2323 paid $250 [here](https://www.upwork.com/nx/wm/offer/103215448) (Contributor)

**Comment by twisterdotcom** [comment]
Bump on this @sobitneupane.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Go to any chat
2. Tap on the compose box.
3. Paste an image in the compose box.
4. Verify that the keyboard is closed (if open) and image is previewed in the Attachment Modal.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment]
I could not identify the exact PR which might have caused this issue. The feature was added by [this PR](https://github.com/Expensify/App/pull/685).

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane based on [this summary.](https://github.com/Expensify/App/issues/45471#issuecomment-2271312046)
