### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] Contact method - Secondary contact method can not select Set as default

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46350]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a751@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login with new gmail account
2. Go to Account settings> Profile> Contact method> New contact method> Add new email> Add
3. Click on newly added secondary contact method> Complete the verification process
4. Click on the verified secondary contact method> Set as default

## Expected Result:
There should be no error message. Since the secondary contact method becomes primary contact method - Set as default option should not be present

## Actual Result:
"This is already your primary contact" error message appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/01543e66-f0ce-494e-a88d-2bad396845dc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a16b21d55b907d8</li>
        <li>Upwork Job ID: 1818663412557629626</li>
        <li>Last Price Increase: 2024-08-07</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103456590</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't select secondary method as default on a new non-validated account.

### What is the root cause of that problem?
When we have a non-validated account, add a secondary login, and then verify the secondary login, the BE actually sets the secondary login as the primary login. It can be verified from an email received after verifying, telling that the primary login has been changed to the secondary login. So, when we try to set the secondary login as the primary login, the BE responds with a message that the secondary login is already the primary login.

### What changes do you think we should make in order to solve the problem?

If the BE behavior is expected, then we can fix this on the FE. What we want to do is, when validating a secondary login, if the primary login isn't validated yet, set the secondary login as the primary login on success verifying.

The loginList will be passed from the function params.
https://github.com/Expensify/App/blob/9901ca3a554f4c2991b56862dfb8e43d2e1aba80/src/libs/actions/User.ts#L368
```
if (!loginList[currentEmail].validatedDate) {
    successData.push(...[
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.ACCOUNT,
            value: {
                primaryLogin: contactMethod,
            },
        },
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.ACCOUNT,
            value: {
                primaryLogin: contactMethod,
            },
        },
        ...,
    ]);
}
```

The data that requires update can be seen from the [setContactMethodAsDefault](https://github.com/Expensify/App/blob/9901ca3a554f4c2991b56862dfb8e43d2e1aba80/src/libs/actions/User.ts#L768) optimistic data. (except the login list)

**Comment by ikevin127** [comment]
⚠️ @bernhardoj I was not able to successfully verify if your solution fixes the issue, this is what I did (see diff below) to test the solution and the issue is still present. Please let me know if I missed something!

<details>
<summary>Diff</summary>

```diff
diff --git a/src/libs/actions/User.ts b/src/libs/actions/User.ts
index 3019e3dfbb6..ea9fa1e6a60 100644
--- a/src/libs/actions/User.ts
+++ b/src/libs/actions/User.ts
@@ -365,7 +365,7 @@ function validateLogin(accountID: number, validateCode: string) {
 /**
  * Validates a secondary login / contact method
  */
-function validateSecondaryLogin(contactMethod: string, validateCode: string) {
+function validateSecondaryLogin(contactMethod: string, validateCode: string, loginList: Record<string, Login>) {
     const optimisticData: OnyxUpdate[] = [
         {
             onyxMethod: Onyx.METHOD.MERGE,
@@ -444,6 +444,20 @@ function validateSecondaryLogin(contactMethod: string, validateCode: string) {
         },
     ];
 
+    if (!loginList[currentEmail].validatedDate) {
+        successData.push(
+            ...[
+                {
+                    onyxMethod: Onyx.METHOD.MERGE,
+                    key: ONYXKEYS.ACCOUNT,
+                    value: {
+                        primaryLogin: contactMethod,
+                    },
+                },
+            ],
+        );
+    }
+
     const parameters: ValidateSecondaryLoginParams = {partnerUserID: contactMethod, validateCode};
 
     API.write(WRITE_COMMANDS.VALIDATE_SECONDARY_LOGIN, parameters, {optimisticData, successData, failureData});
diff --git a/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.tsx b/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.tsx
index 352260c275f..0ed81cddcfb 100644
--- a/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.tsx
+++ b/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.tsx
@@ -178,8 +178,8 @@ function BaseValidateCodeForm({account = {}, contactMethod, hasMagicCodeBeenSent
         }
 
         setFormError({});
-        User.validateSecondaryLogin(contactMethod, validateCode);
-    }, [validateCode, contactMethod]);
+        User.validateSecondaryLogin(contactMethod, validateCode, loginList);
+    }, [validateCode, contactMethod, loginList]);
 
     return (
         <>

```

</details>

**Comment by bernhardoj** [comment]
Oh my bad, the ONYXKEYS.ACCOUNT is duplicated, it should be

```
{
    onyxMethod: Onyx.METHOD.MERGE,
    key: ONYXKEYS.SESSION,
    value: {
        email: newDefaultContactMethod,
    },
},
```

This will make sure the secondary login will be the default contact method.

I have updated my proposal to fix that.

**Comment by ikevin127** [comment]
Thanks for clarifying!

@bernhardoj's [updated proposal](https://github.com/Expensify/App/issues/46350#issuecomment-2253721504) looks good to me. The RCA is on point and the updated solution fixes the issue in accordance with the **Expected result.**

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment]
We're currently awaiting **Rory**'s input on the reviewed / selected proposal.

**Comment by ikevin127** [comment]
Yes we do!

cc @roryabraham for assignment based on https://github.com/Expensify/App/issues/46350#issuecomment-2264186568.

**Comment by bernhardoj** [comment]
PR is ready

cc: @ikevin127

**Comment by ikevin127** [comment]
ℹ️ Will review on Saturday (PST) when I'll return to office.

**Comment by greg-schroeder** [comment]
PR merged. Awaiting deploy to staging -> prod

**Comment by ikevin127** [comment]
⚠️ Production deploy automation failed here -> this should be on **[HOLD for Payment 2024-08-20]** according to yesterday’s production deploy confirmed in https://github.com/Expensify/App/pull/47132#issuecomment-2289865815 and [deploy checklist](https://github.com/Expensify/App/issues/47219).

cc @greg-schroeder

**Comment by greg-schroeder** [comment]
Sure, adjusted

**Comment by ikevin127** [comment]
cc @greg-schroeder

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @bernhardoj - $250 - You can make a manual request via ND
C+: @ikevin127 - $250 - Paid via Upwork

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by ikevin127** [comment]
@greg-schroeder Thanks for the payment 💯 

##

* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/15751
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/15751/files#r1723731216
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:**N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Login as a new user with a new email address.
2. Add a secondary contact method and validate it.
3. Verify the secondary contact method is assigned as the default contact method.
4. Open the contact method page again and now verify the other contact method.
5. Set the other contact method as default.
6. Verify the other contact method is set as default.
7. Repeat step 5 and 6.
8. Verify that the contact method selected at step (5.) is set as default.

Do we agree 👍 or 👎.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by greg-schroeder** [comment]
Filed regression, payments done. closing
