### ISSUE TITLE
[Waiting on Checklist - HOLD for payment 2024-11-05] [$250] QBO - Connection options are missing in QBO connection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46445]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to the app with a new expensifail account
2. Create a new workspace
3. Go to more features > enable accounting
4. Navigate to the accountings page and connect with QBO
5. When you are navigated to the QBO page enter the credentials and finish the connection
6. After connecting with QBO, you will be navigated to the app
7. Wait for the connection to sync

## Expected Result:
QBO options (Import, Export, Card reconciliation and Advanced options) are displayed

## Actual Result:
QBO options (Import, Export, Card reconciliation, and Advanced options) are not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/68e150fa-1694-4b1f-b1b5-1345f6db5416

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841525897082466980</li>
        <li>Upwork Job ID: 1841525897082466980</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 104412598</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by tgolen** [comment]
@kosmydel @hungvu193 @arosiclair Is it possible this is related to https://github.com/Expensify/App/pull/44733 ?

**Comment by arosiclair** [comment]
I don't think so. Those changes should only affect report exports.

**Comment by chiragsalian** [comment]
Not a web-e blocker as discussed [here](https://expensify.slack.com/archives/C07J32337/p1722289686600549?thread_ts=1722289205.639069&cid=C07J32337)

**Comment by tgolen** [comment]
Sounds like @yuwenmemon might know what's happened here and he will be looking into it.

**Comment by yuwenmemon** [comment]
Weird, not able to reproduce this in Dev

**Comment by yuwenmemon** [comment]
Oh I see it now. @NikkiWines it looks like this is because we initially set the `lastSync` `isConnected` property to false:
https://github.com/Expensify/Integration-Server/commit/a4cca1bb4863dfcbe9c566cbeeaa47d5676c8c72#diff-49d9c0cf9775a8c0d9890e99f5085ddbed36dbe92d1d8ec3a3956e50d5d9a555R27

**Comment by yuwenmemon** [comment]
I think this will need to be fixed via the IS.

**Comment by yuwenmemon** [comment]
@roryabraham This should be fixed when https://github.com/Expensify/Integration-Server/pull/8025 is deployed to prod.

**Comment by roryabraham** [comment]
[tester was no longer able to reproduce](https://expensify.slack.com/archives/C9YU7BX5M/p1722385217362779?thread_ts=1722383981.691799&cid=C9YU7BX5M), so I'm going to close this and check it off

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 9.0.29-9

https://github.com/user-attachments/assets/6496f751-a381-4ee1-a15a-31b4f482bf74

**Comment by twisterdotcom** [comment]
I still cannot recreate this, I'm not clear how to follow the steps in the video without always having to configure the company you choose in QBO when you authenticate. It seems you never had to do that @lanitochka17?

Also this bug states that it occurs on MacOS: Chrome / Safari and Android: mWeb Chrome, but your video seems to show Desktop. Does this only happen for you on Desktop?


https://github.com/user-attachments/assets/5a415aef-1020-45c9-a61a-525b5b18fa4b

I'm going to downgrade this to Daily as I can't reliably reproduce and the mainline case of connecting in Chrome works fine.

**Comment by yuwenmemon** [comment]
I wasn't able to reproduce this exactly in Desktop, but I was able to see a split second here where we do see this behavior, but eventually, the menu options load.

https://github.com/user-attachments/assets/f4192109-c7e0-47e0-b25f-f67338df00ad

**Comment by yuwenmemon** [comment]
What's tipping me off is that we see `Last synced      ` in both videos where this happens, which means the `lastSync` object or something we're reading off of it is off.

**Comment by yuwenmemon** [comment]
So yeah for when we see  `Last synced       ` all I see in the connection object is this:
![Screenshot 2024-09-06 at 2 05 21 PM](https://github.com/user-attachments/assets/8eef4b01-db1a-41e3-9f92-3c04b87d3306)

However, a few seconds later an onyxUpdate is pushed updating the connection and showing the full connection:
![Screenshot 2024-09-06 at 2 04 12 PM](https://github.com/user-attachments/assets/e44f88dc-041d-4d8c-9cae-b893ff6eec84)

What looks to be happening is that the `jobDone` event is getting sent before the policy update that updates the `lastSync` value. cc @aldo-expensify

**Comment by yuwenmemon** [comment]
Yup, that's exactly it. If I play around with the debugger to delay the `jobDone` notification this is what I see:

https://github.com/user-attachments/assets/a9f93430-01c1-49b7-bc93-5fb4f21547b3

**Comment by yuwenmemon** [comment]
@francoisl @aldo-expensify Not sure what the best way to fix this is 🤔 

It's kind of a race condition and sits at the heart of how the new connection with Onyx updates works. A few ideas
1. Delay the `jobDone` notification by 1 second - kind of hacky, doesn't solve the root of the problem
2. Somehow, redundantly push the entire connectionData with the `jobDone` event. This way even if the onyx update from setting the connection data via the API doesn't come through, we send it directly from the IS.
3. Do something in the front-end where we show "Loading" state or something like that if we don't have full `connectionData` for a connection yet.

**Comment by aldo-expensify** [comment]
hmm what about passing some flag from the IS to the last `SavePolicy` so that last `SavePolicy` pushes the `jobDone` instead of the IS?

**Comment by yuwenmemon** [comment]
Oooooooh, I like that 💡

@francoisl does that sound good to you?

**Comment by yuwenmemon** [comment]
Hmmm.. yeah. In theory, you would want to do this when you [save the connection data](https://github.com/Expensify/Integration-Server/blob/70368329640d1e2b950f6137d059c26a1a383dee/src/expensify/quickbooksonline/QuickbooksOnlineFullSync.java#L56), so that there's no race condition between the connection object having a config/data and the spinner stopping (`jobDone`). However, there are other [sync tasks that could still be running after that](https://github.com/Expensify/Integration-Server/blob/70368329640d1e2b950f6137d059c26a1a383dee/src/expensify/quickbooksonline/QuickbooksOnlineFullSync.java#L64).

**Comment by aldo-expensify** [comment]
> However, there are other [sync tasks that could still be running after that](https://github.com/Expensify/Integration-Server/blob/70368329640d1e2b950f6137d059c26a1a383dee/src/expensify/quickbooksonline/QuickbooksOnlineFullSync.java#L64).

but I think the user wouldn't be able to change any setting until the `jobDone` is received, right? If the user can't touch any setting until that, then there won't be more syncs running.

**Comment by trjExpensify** [comment]
Pulled this out [here](https://expensify.slack.com/archives/C036QM0SLJK/p1726693508189779?thread_ts=1726504683.311379&cid=C036QM0SLJK) to chat about in realtime to help move this along!

**Comment by yuwenmemon** [comment]
Discussion ongoing in that thread

**Comment by yuwenmemon** [comment]
Latest is here: https://expensify.slack.com/archives/C036QM0SLJK/p1727153689087659?thread_ts=1726504683.311379&cid=C036QM0SLJK

**Comment by trjExpensify** [comment]
@yuwenmemon mentioned sending this external again. Do you have the outline of what we want to see in a proposal before we do that?

**Comment by yuwenmemon** [comment]
Yes! I will open this up to contributors to create a POC for an idea we were kicking around that is front-end only. Here's the thought:

**If we don't have full connection data for a connection yet, show a "Loading" state for it.**

Specifically for QuickBooks Online, the case would be if we see `quickbooksOnline.config.credentials` but not `quickbooksOnline.data`. Instead of showing the QBO view with no connection options (i.e., no Import/Export/Advanced), we should show the loading spinner so the customer knows things are still syncing.

Let's have the message with the spinner say "initializing" for now.

**Comment by hungvu193** [comment]
@yuwenmemon I can reproduce this issue.
As I checked the logs, Pusher events never seem to push updates after QBO was connected until the next manual sync (I tried to logout and login again but it didn't work).

<img width="609" alt="Screenshot 2024-10-03 at 14 16 42" src="https://github.com/user-attachments/assets/b01e8e86-ee71-4c01-bf55-896a05636e1a">

 If we show a loading when credentials are not empty and data is empty, it will load infinitely. So I think in this case, if we don't update the BE, we should change the FE behavior for QBO. 

If 
> Specifically for QuickBooks Online, the case would be if we see `quickbooksOnline.config.credentials` but not `quickbooksOnline.data`

We should let users know that they need to do another sync ( or we can do it inside PolicyAccount with an useEffect). 
What do you think 🤔 ?

**Comment by trjExpensify** [comment]
I don't think we want to ask them to do a manual sync just after connecting for the first time. That seems like a bad design, so can we trigger that if necessary?

**Comment by hungvu193** [comment]
Cool. Agreed.

**Comment by hungvu193** [comment]
While working on proposal, I realized this issue was fixed. Is there anyone here can reproduce it? 😂

**Comment by trjExpensify** [comment]
Don't you have to simulate a crappy network and delay the`jobDone` event as Yuwen did [here](https://github.com/Expensify/App/issues/46445#issuecomment-2334828310)?

**Comment by hungvu193** [comment]
> Don't you have to simulate a crappy network and delay the`jobDone` event as Yuwen did [here](https://github.com/Expensify/App/issues/46445#issuecomment-2334828310)?

In this comment, I'm seeing Yuwen is debugging in his local BE env, I'm not sure if I can replicate with only my local FE setup 😨

**Comment by hungvu193** [comment]
> @hungvu193 I'm happy to work with you to test any solution you drum up with my debugger setup.

Sure thing. But I wonder if anyone can still reproduce this issue? I can reproduce it easily a few days ago. However, I can't reproduce it now.

**Comment by yuwenmemon** [comment]
I can still reproduce this (notice the moment when I move the mouse a lot - you can still see a split second where we have the connection options missing but the sync has "finished"):

https://github.com/user-attachments/assets/0e4abb28-1b41-45ff-8ff2-80811b8a5ad4

**Comment by aldo-expensify** [comment]
> I can still reproduce this (notice the moment when I move the mouse a lot - you can still see a split second where we have the connection options missing but the sync has "finished"):

but... is that a bug? I would be concern if the menu options don't ever appear.. but if they have such a small delay 🤷

**Comment by aldo-expensify** [comment]
I have something kind of related here: https://github.com/Expensify/App/issues/49372, but opposite? Opposite because the menu options appear too soon.

I think the problem in my issue is that we show the options but we still load some data after... so if you are quick in changing something it may get reverted.

**Comment by yuwenmemon** [comment]
Well, if something were to happen where, for whatever reason, the Push notification came from the IS for the job to be done but the data from the sync did not, it would be more severe.

I agree, though; the small flash is not the worst bug in the world. However, it's still a bug nevertheless.

**Comment by hungvu193** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
QBO - Connection options are missing in QBO connection
### What is the root cause of that problem?
As described above, the RCA of this issue is `race condition and sits at the heart of how the new connection with Onyx updates works`. Our FE received `jobDone` event from our Pusher event, even when we didn't have `lastDate` data yet, so we will see the `Last synced` without the date:
https://github.com/Expensify/App/blob/abdfb7233e040a61d1e4433e202a8b644c7455f4/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L333-L335
### What changes do you think we should make in order to solve the problem?
This is QBO case-specific, so we can add a condition in our `isConnectionInProgress` function, if we see `qboConnection?.data` but not  `qboConnection?.config?.credentials`, we still want to display the loading indicator.

Let's update `isConnectionInProgress` function to the following:

```javascript
function isConnectionInProgress(connectionSyncProgress: OnyxEntry<PolicyConnectionSyncProgress>, policy?: OnyxEntry<Policy>): boolean {
    if (!policy) {
        return false;
    }

    const qboConnection = policy?.connections?.quickbooksOnline;

    const lastSyncProgressDate = parseISO(connectionSyncProgress?.timestamp ?? '');
    return (
        (!!connectionSyncProgress?.stageInProgress &&
            (connectionSyncProgress.stageInProgress !== CONST.POLICY.CONNECTIONS.SYNC_STAGE_NAME.JOB_DONE || !policy?.connections?.[connectionSyncProgress.connectionName]) &&
            isValid(lastSyncProgressDate) &&
            differenceInMinutes(new Date(), lastSyncProgressDate) < CONST.POLICY.CONNECTIONS.SYNC_STAGE_TIMEOUT_MINUTES) ||
// If qboConnection?.data is null and !!qboConnection?.config?.credentials is true, then it's still in progress.
        (!!qboConnection && !qboConnection?.data && !!qboConnection?.config?.credentials)
    );
}

```

### What alternative solutions did you explore? (Optional)
N/A

<details><summary>Result</summary>

https://github.com/user-attachments/assets/37cac7cb-4d29-4dfe-8623-238a5e607b55


</details>

**Comment by hungvu193** [comment]
Here's the test branch: https://github.com/hungvu193/App/tree/fix-qbo-syncing

**Comment by hungvu193** [comment]
Yeah I can still reproduce, you can try with brand new workspace.

**Comment by hungvu193** [comment]
I think I still can reproduce on latest main

<img width="1656" alt="Screenshot 2024-10-14 at 08 42 22" src="https://github.com/user-attachments/assets/b2f68f9f-0a87-410c-b587-86a10d30a664">

**Comment by hungvu193** [comment]
[PR](https://github.com/Expensify/App/pull/50766) is ready!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by twisterdotcom** [comment]
Payment Summary:

- @hungvu193 paid $250 via NewDot Manual Request
- @ishpaul777 paid $250 [here](https://www.upwork.com/nx/wm/offer/104412598) (Reviewer)

**Comment by garrettmknight** [comment]
@hungvu193 please complete the checklist

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193

**Comment by twisterdotcom** [comment]
Weird, that didn't show up in Upwork for me at all. All done now.
