### ISSUE TITLE
[Awaiting checklist] [$250] [Search v2] [POLISH] Icons Overflow from Dropdown Button on Search Results Page on Mobile

### ISSUE THREAD

**Issue by rayane-djouah** [Expensify/App#46664]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rayane-djouah
**Slack conversation:**

## Action Performed:

1. Deep-linked to `new-expensify://search/filters/` on mobile.
2. Selected multiple filters.
3. Clicked on "View Results."

## Expected Result:
The icons of the dropdown button should be contained entirely within the button.

## Actual Result:
The icons of the dropdown button overflow beyond the button's boundaries.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Simulator_Screenshot_-_iPhone_15_Pro_Max_-_2024-08-01_at_12 02 16](https://github.com/user-attachments/assets/dcf778db-96a3-468f-ae07-23f39be5169d)

<img width="325" alt="Screenshot_2024-08-01_at_12 17 19_PM" src="https://github.com/user-attachments/assets/9d7a5d9a-a9d9-4348-853a-d2fb6b2c204a">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184ce67444300c7ba</li>
        <li>Upwork Job ID: 1819040519824038842</li>
        <li>Last Price Increase: 2024-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103360495</li>
<li>nkdengineer | Contributor | 103360498</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The icons of the dropdown button overflow beyond the button's boundaries.

### What is the root cause of that problem?
We're letting the `Text` with `numberOfLines` [here](https://github.com/Expensify/App/blob/a3339efeee58cfd2b179544c01877ddf2d8de381/src/pages/Search/SearchStatusMenuNarrow.tsx#L82) alone without any wrapper `View`, so it takes the full width of the container and pushes the buttons outside

### What changes do you think we should make in order to solve the problem?

Just need to wrap the `Text` in a `View` with `flex: 1`, the `View` itself will take only the spaces left after accounting for the buttons' spaces. And then the `Text` inside the `View` will only take the full size of that `View`.
```
<View style={styles.flex1}>
```

No need to hardcode any width for the container.

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment]
[Proposal updated](https://github.com/Expensify/App/issues/46664#issuecomment-2263521125) to add screenshot to show the result after the change, and also added references to other places in the app where the same solution is used.

**Comment by shawnborton** [comment]
The screenshot looks good but I agree with @nkdengineer that we don't need to hard code a width.

**Comment by shawnborton** [comment]
I think @nkdengineer's solution is cleaner.

**Comment by nkdengineer** [comment]
Thanks for the assigment! I'm raising the PR now.

> Though why are we adding an extra View layer when we can just use flex1 on the Text itself?

@ShridharGoel It's the same solution, we can handle these small polish in PR phase.

**Comment by nkdengineer** [comment]
@rayane-djouah this [PR](https://github.com/Expensify/App/pull/46689) is ready for review

**Comment by twisterdotcom** [comment]
Payment Summary:

- @rayane-djouah paid $250 [here](https://www.upwork.com/nx/wm/offer/103360495) (Reviewer)
- @nkdengineer paid $250 [here](https://www.upwork.com/nx/wm/offer/103360498) (Contributor)
