### ISSUE TITLE
[WAITING ON CHECKLIST][$250] Workspace picker -Inconsistent Navigation After Creating Workspace on "Workspace picker"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46816]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** biruknew45+ees@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to [staging.new.expensify.com].
2. Click on the "Workspace picker"
3. Click on the plus icon to create a new workspace.
4. Click the in-app back button.
5. Observe that you are not navigated back to the previous page.
6. Navigate to the inbox.
7. Click on the "Workspace picker"
8. Click on the plus icon to create a new workspace.
9. Click the browser’s back button.

## Expected Result:
After creating a workspace from the "Workspace picker" page, the in-app back button should navigate the user back to the "Workspace picker" page, consistent with the behavior of the browser's back button.

## Actual Result:
After creating a workspace from the "Workspace picker" page using the plus icon, the in-app back button fails to navigate to the workspace picker page, while the browser’s back button correctly returns the user to the "Workspace picker" page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0c002825-6ed1-46d7-b408-65ff36640554

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d2558fbd9a9d9b23</li>
        <li>Upwork Job ID: 1820632265547564333</li>
        <li>Last Price Increase: 2024-08-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent Navigation After Creating Workspace on "Workspace picker"

### What is the root cause of that problem?
This because we are using dismiss MOdal here
https://github.com/Expensify/App/blob/0e46257f3295243e5ef306b723288cb1673ed6f1/src/pages/workspace/WorkspaceInitialPage.tsx#L396-L397
### What changes do you think we should make in order to solve the problem?

We should use the default `goBAck` so we can omit onBackPressed
### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment]
Able to repro on v9.0.16-5 (staging)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After creating a workspace from the "Workspace picker" page using the plus icon, the in-app back button fails to navigate to the workspace picker page, while the browser’s back button correctly returns the user to the "Workspace picker" page.

### What is the root cause of that problem?
When going back [here](https://github.com/Expensify/App/blob/6c3dcc298cad62f69f7440ddec77dfbd647113d8/src/pages/workspace/WorkspaceInitialPage.tsx#L396), we just `dismissModal`, so it will only dismiss the workspace profile page and will not go back to the workspace switcher as it should do.

### What changes do you think we should make in order to solve the problem?

We should use the accepted approach of using `backTo` route param to make sure the navigation is correct in these cases/

Update https://github.com/Expensify/App/blob/6c3dcc298cad62f69f7440ddec77dfbd647113d8/src/pages/workspace/WorkspaceInitialPage.tsx#L396 to go to the `backTo` route if there's `backTo` param defined.
```
onBackButtonPress={() => {
    if (route.params?.backTo) {
        Navigation.goBack(route.params.backTo, true);
    } else {
        Navigation.dismissModal();
    }
}}
```
Update the route definition [here](https://github.com/Expensify/App/blob/6c3dcc298cad62f69f7440ddec77dfbd647113d8/src/ROUTES.ts#L525) to allow a `backTo` param
```
getRoute: (policyID: string, backTo?: string) => getUrlWithBackToParam(`settings/workspaces/${policyID}`, backTo) as const,
``` 

Use the `backTo` param [here](https://github.com/Expensify/App/blob/6c3dcc298cad62f69f7440ddec77dfbd647113d8/src/libs/actions/App.ts#L364) and in `createWorkspaceWithPolicyDraftAndNavigateToIt` too

Then in [here](https://github.com/Expensify/App/blob/6c3dcc298cad62f69f7440ddec77dfbd647113d8/src/pages/WorkspaceSwitcherPage/WorkspacesSectionHeader.tsx#L35), pass the current route (or specifically `ROUTES.WORKSPACE_SWITCHER`) as `backTo` 

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
[Proposal updated](https://github.com/Expensify/App/issues/46816#issuecomment-2270498375) to add an alternation solution

**Comment by eh2077** [comment]
@nkdengineer 's [proposal](https://github.com/Expensify/App/issues/46816#issuecomment-2270498375) looks good to me. Coding details can be discussed in PR.

🎀👀🎀 C+ reviewed

**Comment by carlosmiceli** [comment]
Not sure what happened here... @jliexpensify did we end up manually hiring the contributors?

@parasharrajat sorry to bring you in here, but am I to understand that [this issue](https://github.com/Expensify/App/issues/47562) will also fix this one?

I'll move this back to weekly since something seems broken.

**Comment by jliexpensify** [comment]
Hmm looks like the automation broke, I'll manually hire.

**Comment by jliexpensify** [comment]
Hired @eh2077 and @nkdengineer

**Comment by carlosmiceli** [comment]
What's the status here @parasharrajat?

**Comment by carlosmiceli** [comment]
Gotcha! Can we close this then @jliexpensify ?

**Comment by jliexpensify** [comment]
Before I do, I just want to confirm: @parasharrajat you had a PR fixed this, so there's no need to hire and pay anyone?

I notice @nkdengineer and @eh2077 were hired, so will need to cancel these contracts if so.

**Comment by eh2077** [comment]
@jliexpensify I believe our work previously hired is legitimate for payment. And it's been overdue for quite a while

**Comment by jliexpensify** [comment]
Sorry, let's take a step back here! I want to clarify exactly what needs to be done.

Firstly, I am trying to work out what @parasharrajat means by this: https://github.com/Expensify/App/issues/46816#issuecomment-2329178918

Rajat, can you clarify this comment please? Are you implying the PR was not ended to fix this issue?

Separately, @eh2077 - you and @nkdengineer worked on https://github.com/Expensify/App/pull/46939 that resolved this issue? cc @carlosmiceli

**Comment by eh2077** [comment]
Yes, https://github.com/Expensify/App/pull/46939 is the PR we worked on to fix this issue.

**Comment by jliexpensify** [comment]
Great, so it sounds like this is the Payment Summary and job:

- C: @nkdengineer 
- C+: @eh2077 

https://www.upwork.com/jobs/~01d2558fbd9a9d9b23

So @parasharrajat - I'll wait for your explanation on this before making payment: https://github.com/Expensify/App/issues/46816#issuecomment-2329178918

**Comment by jliexpensify** [comment]
Ok, thanks for clearing this one up! @eh2077 do we need a checklist here?

**Comment by jliexpensify** [comment]
Everyone has been paid, just waiting on checklist.

**Comment by jliexpensify** [comment]
Bump @eh2077 for checklist

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**I don't there's a PR causes this bug. It's an edge case we want to polish**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. **_Yes_**


#### Regression test

1. Click on the "Workspace picker"
2. Click on the plus icon to create a new workspace.
3. Click the in-app back button.
4. Observe that you are not navigated back to the previous page.
5. Navigate to the inbox.
6. Click on the "Workspace picker"
7. Click on the plus icon to create a new workspace.
8. Click the browser’s back button.
9. Verify that: After creating a workspace from the "Workspace picker" page, the in-app back button should navigate the user back to the "Workspace picker" page

Do you agree 👍 or 👎?
