### ISSUE TITLE
[$250] [CRITICAL] [CVP] Track Expense - App crashes when tracking an expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46879]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43163
## Action Performed:
1. Sign in with a new account
2. Go to FAB > Track Expense

## Expected Result:
Track expense modal opens and user is able to track an expense

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c8879a1d-1e29-41fb-bee9-bdde3e266e5d

![Bug6563076_1722947936494!Capture22](https://github.com/user-attachments/assets/a56bc101-3131-449c-a0b5-1097f8418a1b)

[logs (2).txt](https://github.com/user-attachments/files/16510434/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f114a28e4f405b1</li>
        <li>Upwork Job ID: 1820938917945788496</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 103522001</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment]
@thienlnam here's another track expense flow bug, this time a crash and also seems to be referencing `policyID -1` in the console error like https://github.com/Expensify/App/issues/46338#issuecomment-2272071153

**Comment by jp928** [comment]
Not reproducible on latest code base.

**Comment by trjExpensify** [comment]
@danielrvidal how are you repro'ing this as soon as yesterday?

**Comment by danielrvidal** [comment]
I'm reproducing it on production still as of now. @jp928 did you try it on mobile web? 

I'm on Safari, private tab if it helps at all

**Comment by jp928** [comment]
@danielrvidal 
I tried with a new created account still fine to me.  The console log shows it is a javascript error so it doesn't matter which browser it should reproducible cross all browsers. However, in the error the doge value `policy_FAKE_` is the key of this bug.
I would assume it is a testing policy data for testing accounts. Sorry I couldn't test with your internal testing email boxes, but I would suggest to contact your backend team to investigate if you are adding special policy value to testing accounts, especially for the value of `policy_FAKE_`.

**Comment by danielrvidal** [comment]
> in the error the dodgy value policy_FAKE_

@trjExpensify any idea where this would be coming from? I would think it should be fake since I was testing in production?

**Comment by alexpensify** [comment]
Waiting for proposals here

**Comment by alexpensify** [comment]
Waiting for proposals here

**Comment by jp928** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Javascript throws fatal exception if the onyx collection key contains underscore, such as `policy__FAKE_`

### What is the root cause of that problem?

In the code
https://github.com/Expensify/react-native-onyx/blob/397c2cba8fe5c2bdd5f0e6eaa6761043f1bf51a6/lib/OnyxUtils.ts#L409C3-L409C50

The last index of underscore is using for check if the key is valid so that `policy__FAKE_` will be treated as invalid key. 
Test case is like below:
```
function splitCollectionMemberKey(key) {
  const underscoreIndex = key.indexOf('_');

  if (underscoreIndex === -1) {
      throw new Error(`Invalid ${key} key provided, only collection keys are allowed.`);
  };

  const collectionKey = key.substring(0, underscoreIndex + 1);
  const memberKey = key.substring(underscoreIndex + 1);
  return [collectionKey, memberKey];
  
}


function isCollectionMemberKey(collectionKey, key, collectionKeyLength) {
  return key.startsWith(collectionKey) && key.length > collectionKeyLength;
}

console.log(splitCollectionMemberKey('policy__FAKE_')); // ['collection', 'member']

console.log(isCollectionMemberKey('policy__FAKE_', 'policy__FAKE_',  'policy__FAKE_'.length));
```
The function isCollectionMemberKey will return false in this case.

### What changes do you think we should make in order to solve the problem?
Use `indexOf` instead of `lastIndexOf` to support the key contains multiple underscores, such as `policy__FAKE_`

### What alternative solutions did you explore? (Optional)

Change the `policy__FAKE_` from backend, such as `policy_FAKE`

**Comment by trjExpensify** [comment]
>@trjExpensify any idea where this would be coming from? I would think it should be fake since I was testing in production?

Yeah, that's used for off-workspace DMs: https://github.com/Expensify/App/blob/ff2b8887e8bf540997f3bf290ae15f2c8853eb22/src/libs/ReportUtils.ts#L1178-L1179

**Comment by trjExpensify** [comment]
Thanks, @jp928. @thesahindia can you review that proposal? Also, CC'ing @hannojg for eyes from the blame. :)

**Comment by hannojg** [comment]
@jp928 trying to understand your proposal I don't think this really returns 'collection', 'member', right? What does it actually return?

<img width="666" alt="Screenshot 2024-08-13 at 11 40 20" src="https://github.com/user-attachments/assets/e785c85f-113a-492e-bb04-0540a69d3855">

**Comment by hannojg** [comment]
Hm, we are having these test cases in onyx which expect the underscore for the collection to be at the end. These tests are failing with your proposal:

<img width="990" alt="Screenshot 2024-08-13 at 11 47 36" src="https://github.com/user-attachments/assets/c10bdf12-8217-4d22-979d-30313434f696">

**Comment by hannojg** [comment]
While it may not be perfect we maybe want to consider handling the case for double __ or for _FAKE_ explicitly

**Comment by jp928** [comment]
> While it may not be perfect we maybe want to consider handling the case for double __ or for _FAKE_ explicitly

@hannojg SRY for confusing you. The code snippet I attached is trying to reproduce the bug because I don't have a way to have that invalid onyx key.  Will update my proposal. Cheers.

**Comment by trjExpensify** [comment]
@thesahindia can you chime in on the proposal please?

**Comment by trjExpensify** [comment]
Can't reproduce on mWeb Safari anymore myself, @danielrvidal can try for good measure and then we can close. 

![IMG_0540](https://github.com/user-attachments/assets/e2db9821-22b5-4468-ba37-59a3fd1bec37)

**Comment by danielrvidal** [comment]
I can't reproduce it either.
