### ISSUE TITLE
Add SAML Setup

### ISSUE THREAD

**Issue by twisterdotcom** [Expensify/App#47068]
## Proposal

**Proposal:** Add SAML configuration to New Expensify

**Problem:** Last year we added user SAML SSO last year to newDot to allow access to Expensify for controlled users on SAML Required domains, but SAML configuration currently still lives solely in Expensify Classic **Domains > SAML** settings, meaning any #wave-control domain admin needing to setup, or make requirement and certificate changes is still required to follow the _Switch to Expensify Classic_ flow to configure SAML for their organization.

SAML is also often [the](https://www.notion.so/pricing) [major](https://github.com/pricing) [selling](https://app.slack.com/plans/TCCJQKCBW?geocode=en-gb) [point](https://stackoverflow.co/teams/pricing/) for higher subscription costs in Enterprise SaaS software for all of the benefits it brings and not supporting it's setup in New Expensify means we lose the ability to sell Expensify with those benefits for customers willing to pay top dollar:

- Enhanced Security: Centralized authentication, reduced phishing risk, and support for MFA (also good for us!)
- Improved User Experience: One login for multiple apps and faster access.
- Compliance and Auditing: Audit trails and standardized protocol for easier compliance.
- Reduced IT Support Burden: Fewer password resets and simplified integration.
- Scalability: Easier onboarding and enterprise readiness.
- Increased Adoption: Seamless login experience and enterprise appeal.

**Solution:**

Let's add SAML configuration to New Expensify and possibly [fix some long-standing bugs](https://expensify.slack.com/archives/C094TGUTZ/p1686073263296659?thread_ts=1686072995.192169&cid=C094TGUTZ) in the process. _Some fun discussions surely to be had on where/how we add this domain feature into NewDot during the predesign._

Slack: https://expensify.slack.com/archives/CC7NECV4L/p1724103770176439

## Tasks

- [x] Post **Proposal (full Problem/Solution statement)** in `#expensify-open-source`
- [x] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [x] Paste Proposal in the space above with a link to the Slack thread
- [x] Email `strategy@expensify.com` and paste in the Proposal
- [x] Fill out the **High-level overview of the problem**, **Timeline**, and **Terminology** sections of the Design Doc
- [x] Email `strategy@expensify.com` (continue the same email chain as before) with the link to your Design Doc
- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [x] Fill out the **High-level of proposed solution** section
- [ ] Email `stategy@expensify.com` again with links to the doc and pre-design conversation in Slack
- [ ] Add the `DesignDocReview` label to get the **High-level of proposed solution** section reviewed
- [ ] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [ ] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [ ] Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.
- [ ] Fill out the **Detailed implementation of the solution** and related sections.
- [ ] Re-add the `DesignDocReview` label to this issue
- [ ] Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary
- [ ] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [ ] Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase
- [ ] Implement the changes
- [ ] Add regression tests so that QA can test your feature with every deploy ([instructions](https://stackoverflowteams.com/c/expensify/questions/363))
- [ ] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

**Comment by dubielzyk-expensify** [comment]
Let's do it 💪

**Comment by dubielzyk-expensify** [comment]
Let me know if you need anything to get started with this :)

**Comment by twisterdotcom** [comment]
Throwing this here just as a note about services that basically charge more because they have this: 
<img width="1237" alt="image" src="https://github.com/user-attachments/assets/22b97a1f-39a5-492a-9b88-4f0d8eed5d53">

**Comment by twisterdotcom** [comment]
<img width="847" alt="image" src="https://github.com/user-attachments/assets/4ed0874f-5d44-4e01-88ff-9a0995f1c7b1">

**Comment by twisterdotcom** [comment]
Doc: https://docs.google.com/document/d/1JP7Tx6g0vPf4mKHzWDeHf5XoAzzw9hNhokNUIJ5Kf9M/edit?usp=sharing

**Comment by twisterdotcom** [comment]
Headed OOO for a bit. Will pick this up when I'm back.

**Comment by twisterdotcom** [comment]
Predesign here: https://expensify.slack.com/archives/C06ML6X0W9L/p1725445965797999

**Comment by twisterdotcom** [comment]
Okay @dubielzyk-expensify, I'll hopefully be looking to post some final screens next week and get the doc out. @dannymcclain has been pretty active here: https://expensify.slack.com/archives/C06ML6X0W9L/p1725446027972499, so not sure if you want to swap out, or if you're fine taking over and we can have a sync early next week? I should be around Monday now I think.

**Comment by dubielzyk-expensify** [comment]
Yep saw that @dannymcclain has done a great job so reassigning to him 😄  If you're swamped Danny, let me know and I can take it on.

**Comment by dubielzyk-expensify** [comment]
(Sorry for that. Got a bit trigger happy haha)

**Comment by dannymcclain** [comment]
Not overdue—let's leave this issue open for a bit to catch any tweaks or updates that we might need.

**Comment by jasperhuangg** [comment]
Joining the team on this one!

**Comment by jasperhuangg** [comment]
Making good progress on getting context to write the doc, working on the data storage section right now. Still wrapping my head around all the different flows in OldDot.

**Comment by jasperhuangg** [comment]
I think I'm mostly done with the data storage section. I scheduled a call with Carlos on Monday to ask him some questions and clarify a few things since he worked a lot on the OldDot implementation.

**Comment by jasperhuangg** [comment]
Gonna make this Daily since we should probably get the HL out really soon if we want to meet the deadline for this project.

**Comment by jasperhuangg** [comment]
Got some feedback from Carlos that I'm going to look into implementing today. We have some further discussions we need to have about a few of the suggestions he made as well.

**Comment by jasperhuangg** [comment]
Clarified with @twisterdotcom that we should probably aim to send the HL out for review soon.

In the meantime, I started working on a few sections of the detailed design in a separate doc that likely won't change.

**Comment by twisterdotcom** [comment]
Okay, looks like we might move this into #convert. So, will find a new priority for it and work towards that.

**Comment by twisterdotcom** [comment]
Okay, we are punting this indefinitely for now until we find a cohort who needs it.
