### ISSUE TITLE
[WAITING ON CHECKLIST] Update the workspace connected bank account page for clarity and consistency

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#47578]
Users are confused when they go to add a bank account to their workspace and cannot select their linked personal bank accounts. So let's add some explainer text that educates them on the need for a Business Bank Account. While we're at it, let's also update the page to our newest pattern for consistency.

Today
<img width="275" alt="image" src="https://github.com/user-attachments/assets/9d1f14fd-3f69-4539-a569-c592aa910bae">

Update to
<img width="608" alt="image" src="https://github.com/user-attachments/assets/c02517d0-da47-4854-bf10-0bb9a3febb43">

Final copy for the note: 
>Note: Personal bank accounts can't be used for payments on workspaces.

cc @shawnborton @maddylewis @jamesdeanexpensify 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a8923a1af5c75af2</li>
        <li>Upwork Job ID: 1824502151817768637</li>
        <li>Last Price Increase: 2024-08-23</li>
<li>Automatic offers: </li>
<ul>
<li>BhuvaneshPatil | Contributor | 103689249</li>
</ul></li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update the workspace connected bank account page for clarity and consistency [Design Update]

### What is the root cause of that problem?
New Feature

### What changes do you think we should make in order to solve the problem?
1. We should use Section component's prop to apply new design. 
https://github.com/Expensify/App/blob/c7d4c5ff253a0d05b1ca9046787064b5f8187a27/src/pages/ReimbursementAccount/BankAccountStep.tsx#L128-L131
```tsx
<Section
  title={translate("workspace.bankAccount.streamlinePayments")}
  illustration={LottieAnimations.Coin}
  isCentralPane
  subtitle={translate("bankAccount.toGetStarted")}
  subtitleMuted
></Section>;
```
2. By passing `illustration` instead of icon, we can achieve given design. With this prop, we need to add extra prop `isCentralPane` (**which is missing in both proposals**), and if it's passed the content doesn't have padding. With these props we need to pass `subtitle` prop as well, with `subtitleMuted`.
3. For showing new content (one with Bulb icon in design), we will need to add following view - Inside <Section/> component
```tsx
<View
  style={[
    styles.flexRow,
    styles.mv3,
    styles.alignItemsStart,
    styles.gap2,
    styles.mln1,
  ]}
>
  <Icon
    src={Expensicons.Lightbulb}
    height={variables.iconSizeLarge}
    width={variables.iconSizeLarge}
    fill={theme.icon}
    additionalStyles={styles.p1}
  />
  <Text style={[styles.textLabelSupporting, styles.textAlignLeft]}>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi fugiat
    facilis nisi alias
  </Text>
</View>;

```

Result - 
<img width="388" alt="Screenshot 2024-08-17 at 2 57 19 AM" src="https://github.com/user-attachments/assets/beecce5b-64b2-44d9-995f-e77b3a114612">

<details>
<summary>
Without isCentralPane
</summary>
<img width="458" alt="Screenshot 2024-08-17 at 2 58 26 AM" src="https://github.com/user-attachments/assets/ebc8289f-c08a-4162-9641-5f8b4a6d230c">

</details>

### What alternative solutions did you explore? (Optional)

**Comment by shawnborton** [comment]
Just adding a note that we do have an existing lottie animation to use in the top green area of the card, so it will match other places in our app (like in Settings) where the header area is animated.

**Comment by BhuvaneshPatil** [comment]
@Nodebrute By looking at timestamps, when I posted my proposal, your proposal didn't mention about updating /adding `illustration` prop in. `<Section/>` component

**Comment by tgolen** [comment]
Hey, I'm just seeing this issue, but whoever works on this, can you please only make the new "Note" visible when the user has a personal bank account connected? I don't think the note needs to be visible if they haven't ever added a personal bank account and it could be just as confusing.

**Comment by francoisl** [comment]
Hi @Ollyws, can confirm the chosen proposal is still valid please, especially given the last request to only make the note visible after an account is connected, and also the discussion about using `isCentralPane` above in [this comment](https://github.com/Expensify/App/issues/47578#issuecomment-2296530091)?

**Comment by trjExpensify** [comment]
Adding the `Bug` label to get a BZ assigned. Also, @BhuvaneshPatil can you provide an ETA for the PR? Thanks!

**Comment by BhuvaneshPatil** [comment]
@trjExpensify I am facing trouble testing on IOS device. I will raise PR as soon as it works

**Comment by trjExpensify** [comment]
Have you taken your questions to #expensify-open-source to get some help on what's blocking you from testing on iOS?

**Comment by maddylewis** [comment]
@BhuvaneshPatil - bump on Tom's question when you have a sec! https://github.com/Expensify/App/issues/47578#issuecomment-2325341777

**Comment by BhuvaneshPatil** [comment]
PR is in review

**Comment by BhuvaneshPatil** [comment]
@anmurali 

While working on PR I found out that this page is also using old design shall we cover this page as well.

I would love to work on that as well. Let me know what you think.

<img width="1512" alt="Screenshot 2024-09-12 at 11 53 07 PM" src="https://github.com/user-attachments/assets/7fb68de2-1c88-4548-84a8-9a32fe6459e3">

**Comment by shawnborton** [comment]
I think following up to fix that particular spot makes sense for consistency's sake. 

I also think something we missed when implementing this is that we should use our standard edge-to-edge push rows here. Right now we use the old "rounded pill" option row style which I think we should kill:

https://github.com/user-attachments/assets/5aea28cd-1693-4619-8e32-018afab7f14e



The correct style looks like this:

https://github.com/user-attachments/assets/5204a320-7faa-4b92-bae3-e3ad9eb9ed26

**Comment by trjExpensify** [comment]
@BhuvaneshPatil can you work on a PR to address Shawn's feedback please, and then tag Design for review? Thanks!

**Comment by BhuvaneshPatil** [comment]
Sure. I will raise the PR.

@trjExpensify what do you think about this [comment](https://github.com/Expensify/App/issues/47578#issuecomment-2346964573)

**Comment by BhuvaneshPatil** [comment]
raised the PR, uploaded video for macos web. will update videos on other platforms next morning

**Comment by trjExpensify** [comment]
I agree with Shawn: 

>I think following up to fix that particular spot makes sense for consistency's sake.

**Comment by BhuvaneshPatil** [comment]
@trjExpensify @shawnborton PR is now merged 🎊

**Comment by trjExpensify** [comment]
Great!

**Comment by BhuvaneshPatil** [comment]
The PR was deployed to production on Sep 27
https://github.com/Expensify/App/pull/49490#issuecomment-2379773696

**Comment by BhuvaneshPatil** [comment]
@kadiealexander Can you please take a look

**Comment by kadiealexander** [comment]
Sorry for missing this one guys!

**Comment by kadiealexander** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@Ollyws] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@Ollyws] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@Ollyws] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@Ollyws] Determine if we should create a regression test for this bug.
- [ ] [@Ollyws] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @BhuvaneshPatil ([Offer link](https://www.upwork.com/nx/wm/offer/103689249))
- [ ] Reviewer: $250 @Ollyws (via manual requests)

Upwork job is [here](https://www.upwork.com/jobs/~01a8923a1af5c75af2).

**Comment by kadiealexander** [comment]
@Ollyws bump on the checklist!

**Comment by jliexpensify** [comment]
I might get @francoisl to weigh in when he's back. I'm sorry, but I just got assigned this issue, so I don't have any context. 

I'm happy to amend the Payment Summary, but it also might be easier to have a second job for payment? (for auditing/record keeping sake)

**Comment by francoisl** [comment]
It looks to me like the changes from the second PR weren't included in the scope of the original issue, so that would mean it's also due for payment.

**Comment by jliexpensify** [comment]
@francoisl - just to check here? We are including the second payment for @Ollyws in this issue? If so, I can amend the summary to $500?

**Comment by Bhuvanesh-Fictiv** [comment]
@francoisl  will contributor also be eligible for payment here?

**Comment by BhuvaneshPatil** [comment]
@francoisl contributor will be eligible for payment here, right?

**Comment by francoisl** [comment]
> just to check here? We are including the second payment for @Ollyws in this issue? If so, I can amend the summary to $500?

Yes, that sounds right to me.

> @francoisl contributor will be eligible for payment here, right?

Yes

**Comment by jliexpensify** [comment]
Thanks @francoisl for confirming!

@Ollyws - [I've amended the original Summary for you](https://github.com/Expensify/App/issues/47578#issuecomment-2412269439).

@BhuvaneshPatil - I need to create a new Upworks job for the new $250 amount.

**Comment by jliexpensify** [comment]
@Ollyws - also, does a checklist need to be completed?

**Comment by jliexpensify** [comment]
@BhuvaneshPatil - invited you [here](https://www.upwork.com/jobs/~021853983407062225065)

**Comment by BhuvaneshPatil** [comment]
Accepted offer

**Comment by jliexpensify** [comment]
Paid and job closed. 

@Ollyws still waiting on checklist.

**Comment by jliexpensify** [comment]
Great, thanks!

**Comment by garrettmknight** [comment]
$500 approved for @Ollyws
