### ISSUE TITLE
[$250] Task – Edited subtask name not updated in chat with user B in LHN

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47655]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open group chat
4. Create a task assigned to yourself with user B
5. Open task details and create a subtask assigned to another user
6. Open subtask details and edit subtask name
7. Observe 1:1 chat with user B in LHN

## Expected Result:
Edited subtask name updated in 1:1 chat with user B in LHN

## Actual Result:
Edited subtask name not updated in 1:1 chat with user B in LHN

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/db4d3761-a989-4f55-a102-7ca20697f02c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df2aca4c9f6dbfa6</li>
        <li>Upwork Job ID: 1826727852654566628</li>
        <li>Last Price Increase: 2024-08-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@zanyrenney z FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment]
nice! looking at external label noq

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Edited subtask name not updated in 1:1 chat with user B in LHN

### What is the root cause of that problem?
When we get the `lastMessageTextFromReport` we've had the logic to get the task created message via task report

https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/libs/SidebarUtils.ts#L384

https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/libs/OptionsListUtils.ts#L661-L664

https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/libs/TaskUtils.ts#L41

https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/libs/TaskUtils.ts#L50

But the problem here is that `lastMessageTextFromReport` is calculated in `SidebarUtils`, and we call it [here](https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/components/LHNOptionsList/OptionRowLHNData.tsx#L44). The `OptionRowLHNData` of the DM report doesn't re-render when the task report is changed, which causes this bug.

After the `EditTask` API is called, only the parent report action of task report is updated then we will not see this bug for shared report.
### What changes do you think we should make in order to solve the problem?
The `getLastMessageTextForReport` function has some cases in which we will get the data from other reports. It's better if we get this in  `LHNOptionsList` here because we've had dependency for all reports. Follow the pattern we do it [here](https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/libs/SidebarUtils.ts#L371-L384)

- `visibleReportActionItems[report.reportID]` is `lastReportAction` [here](https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/components/LHNOptionsList/LHNOptionsList.tsx#L141) because we've sorted the display report action

- `report` is `itemFullReport`

- `policy` is `itemPolicy`

```
let lastActorDetails: Partial<PersonalDetails> | null = itemFullReport?.lastActorAccountID && personalDetails?.[itemFullReport.lastActorAccountID] ? personalDetails[itemFullReport.lastActorAccountID] : null;

if (!lastActorDetails && lastReportAction) {
    const lastActorDisplayName = lastReportAction?.person?.[0]?.text;
    lastActorDetails = lastActorDisplayName
        ? {
            displayName: lastActorDisplayName,
            accountID: report.lastActorAccountID,
        }
        : null;
}

const lastMessageTextFromReport = OptionsListUtils.getLastMessageTextForReport(itemFullReport, lastActorDetails, itemPolicy);
```

https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/components/LHNOptionsList/LHNOptionsList.tsx#L114

Then we can pass `lastMessageTextFromReport` from `LHNOptionsList` --> `OptionRowLHNData` --> `SidebarUtils` and we can remove the logic calculate `lastMessageTextFromReport` in `SidebarUtils` since we've passed a param to this function or we can still keep this logic and do this if `lastMessageTextFromReport` param is `undefined`.
### What alternative solutions did you explore? (Optional)
NA

**Comment by mkzie2** [comment]
@allroundexperts I don't think it's a good idea because

1. Maybe we will have many related reports when we change the assignee many times
2. Currently, we're using the task report's data to display the message in LHN and do this in `TaskPreview`. The current problem here is `OptionRowLHN` isn't re-rendered when the task report is changed. If we offline and go to the DM after editing the task title, the  `TaskPreview` doesn't have this bug because this component is re-rendered when the task report is changed.

**Comment by mkzie2** [comment]
Adding the task report as a dependency can cause many unnecessary re-renders for `OptionRownLHNData` of all parent reports that are related to the task report which is a bad performance for `OptionRownLHNData`

**Comment by allroundexperts** [comment]
@mkzie2 I think I had different results when testing this offline. When I was offline, no matter how many times I refreshed, the LHN did not update with the correct data. Can you post a video of the data updating after refreshing when offline?

**Comment by mkzie2** [comment]
@allroundexperts The video here.

https://github.com/user-attachments/assets/735ff1a9-5c8c-401b-95ae-b424c7621029

**Comment by mkzie2** [comment]
@allroundexperts The video here.

https://github.com/user-attachments/assets/a5958f36-63cb-49b2-95eb-7334ad8cc616

**Comment by allroundexperts** [comment]
> @allroundexperts The video here.
> 
>  Untitled.mp4

Hm... I see now. I was 'refreshing' the page. Instead, I just moved across the screens.

**Comment by allroundexperts** [comment]
Given above, I'd agree that @mkzie2's [proposal](https://github.com/Expensify/App/issues/47655#issuecomment-2306153283) is more accurate. Let's go with them instead.

🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment]
@zanyrenney / @cead22 For this issue, could you please unassign me from C+ and assign the @allroundexperts instead?

**Comment by mkzie2** [comment]
@zanyrenney The PR was deployed to production. Please help to process the payment here.

**Comment by JmillsExpensify** [comment]
Re-opening for payment and BZ checklist

**Comment by allroundexperts** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: N/A

I wasn't able to pinpoint a single PR that caused this issue. It seemed to me that this issue existed since the feature was implemented.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- Login to any account, and start a chat with a user (call it user B).

### Test:


1. Go to DM with user B
2. Create a task assigned to user B
3. Open task details
4. Create a subtask assigned to user B
5. Open subtask details
6. Edit subtask name

Verify DM with user B in LHN shows edited subtask name

Do we agree 👍 or 👎

**Comment by zanyrenney** [comment]
https://github.com/Expensify/Expensify/issues/458546

**Comment by zanyrenney** [comment]
@mkzie2 looks like you never applied to the job [here](https://github.com/Expensify/App/issues/47655#issuecomment-2315692557)

**Comment by zanyrenney** [comment]
job is here: https://www.upwork.com/jobs/~021877051447641705406

**Comment by zanyrenney** [comment]
invited @mkzie2

**Comment by zanyrenney** [comment]
### Payment summary

$250 owed to @allroundexperts for C+ review.  - to be paid via ND requests.
$250 owed to @mkzie2 for contribution. - to be paid via upwork.

**Comment by zanyrenney** [comment]
all done @JmillsExpensify

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by zanyrenney** [comment]
@mkzie2 can you please apply to the job? I have invited you and bumped this issue a few times now!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Fourth week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (fifth week). Can we close?

**Comment by zanyrenney** [comment]
Please ensure that payouts are accepted promptly in the future, @mkzie2. Delays create additional work for the team, as we have to manually recreate jobs.

**Comment by zanyrenney** [comment]
can't find @mkzie2 on slack.

**Comment by zanyrenney** [comment]
https://www.upwork.com/jobs/~021900574720135721285 job post is here and @mkzie2 is invited. FYI I am ooo next week so if this is not accepted in the next hour or so, will need to reapply bug label to finish payout.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (6th week)

**Comment by zanyrenney** [comment]
cool, @mkzie2 I have sent you an offer on Upwork: please accept it.

**Comment by zanyrenney** [comment]
**payment summary**

$250 to @mkzie2 via upwork.
