### ISSUE TITLE
[ready for payment] Project: Bring the Auditor role to NewDot

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#47695]
Tracking issue for the Fall '24 #wave-control project, Bring the Auditor Role to NewDot

# DESIGN DOC ➡️: [Here](https://docs.google.com/document/d/1Okva7PJJwmOEFPbsD74pWUzB2R8EzOqnz4EKjcLnTJQ/edit)

### Implementation issues
* Backend - https://github.com/Expensify/App/issues/48589
* Frontend - only one issue needed, so it's this one!

### Cleanup tasks
TBD

### Tasks

- [x] Post **Proposal (full Problem/Solution statement)** in `#whatsnext` 
- [x] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [x] Paste Proposal in the space above with a link to the Slack thread
- [x] Email `strategy@expensify.com` and paste in the Proposal
- [x] Fill out the **High-level overview of the problem**, **Timeline**, and **Terminology** sections of the Design Doc
- [x] Email `strategy@expensify.com` (continue the same email chain as before) with the link to your Design Doc
- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in an appropriate slack channel to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [x] Fill out the **High-level of proposed solution** section
- [x] Email `stategy@expensify.com` again with links to the doc and pre-design conversation in Slack
- [x] Add the `DesignDocReview` label to get the **High-level of proposed solution** section reviewed
- [x] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Host another pre-design meeting in the appropriate slack channel to ask for engineering feedback on the technical solution.
- [ ] Fill out the **Detailed implementation of the solution** and related sections.
- [ ] Re-add the `DesignDocReview` label to this issue
- [ ] Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary
- [ ] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [ ] Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase
- [ ] Implement the changes
- [ ] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by hungvu193** [comment]
Update: I'm working on detailed implementation and prepare a draft PR.

**Comment by dylanexpensify** [comment]
https://github.com/Expensify/Expensify/issues/400285

**Comment by dylanexpensify** [comment]
Ongoing! Linking E/E repo issue ^

**Comment by hungvu193** [comment]
https://github.com/Expensify/App/pull/47561 is now ready for review!

**Comment by dangrous** [comment]
and just FYI, we'll have to wait for the full design doc review process on our side before pushing the PR, so we've got some time to kill!

**Comment by dylanexpensify** [comment]
Ongoing, making good progress

**Comment by dylanexpensify** [comment]
Pushing through!

**Comment by dangrous** [comment]
@hungvu193 @ishpaul777 we're ready to move forward with this one; @hungvu193 there's [one outstanding comment thread](https://docs.google.com/document/d/1Okva7PJJwmOEFPbsD74pWUzB2R8EzOqnz4EKjcLnTJQ/edit?disco=AAABUkk_Mm8) in the doc and please double check that you updated the PR appropriately with any of the minor changes that were discussed.

I will plan to start the backend PR tomorrow, which will send the roles to New Dot where needed to make sure we know when users are auditors or not. That should unlock full testing.

**Comment by dylanexpensify** [comment]
Ongoing, but in implementation!

**Comment by dangrous** [comment]
backend PR is deployed, looking at front end for final review hopefully today! [One additional bug](https://github.com/Expensify/App/pull/47561#issuecomment-2334736285) noticed during testing, which I'm looking into.

**Comment by dylanexpensify** [comment]
Moving along great!

**Comment by dylanexpensify** [comment]
so close to wrap up!

**Comment by hungvu193** [comment]
> backend PR is deployed, looking at front end for final review hopefully today! [One additional bug](https://github.com/Expensify/App/pull/47561#issuecomment-2334736285) noticed during testing, which I'm looking into.

@dylanexpensify  I think this one is also resolved (https://github.com/Expensify/App/pull/47561#issuecomment-2369384941). So I think we're good to wrap up here?

**Comment by dangrous** [comment]
agreed! I think we're done!

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor: @ishpaul777 $1000 via Upwork
Contributor: @hungvu193 $2000 via NewDot

Please apply/request!

**Comment by dylanexpensify** [comment]
Note having issues with creating an Upwork job! Will post as soon as I can!

**Comment by dylanexpensify** [comment]
@ishpaul777 job post [here](https://www.upwork.com/jobs/~021842149663153516278)! Sent invite to apply!

**Comment by dylanexpensify** [comment]
@ishpaul777 offer sent!

**Comment by garrettmknight** [comment]
$2000 approved for @hungvu193

**Comment by dylanexpensify** [comment]
Noice!

**Comment by dylanexpensify** [comment]
Done! Only internal steps left so closing this one!
