### ISSUE TITLE
[$250] Tags - System message for disabling, adding tax code and deleting X: Y tag shows X\: Y tag

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47804]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh05081@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace is under Control plan.
1. Go to staging.new.expensify.com
2. Go to workspace settings > Tags
3. Add a tag in X: Y format
4. Disable, add tax code and delete the tag in X:Y format
5. Go to #admins

## Expected Result:
The system message for disabling, adding tax code and deleting tag in X: Y format will display the tag correctly

## Actual Result:
The system message for disabling, adding tax code and deleting tag in X: Y format displays the tag in X\: Y format

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/82c903e7-a874-4bbf-affe-946c767d4150

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7a0584538b48c5f</li>
        <li>Upwork Job ID: 1826803032920988282</li>
        <li>Last Price Increase: 2024-08-23</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by sakluger** [comment]
@CortneyOfstad could you please help manage this issue while I'm OOO through next Friday, 8/30? Thanks!

**Comment by nabeel-tariq** [comment]
**Proposal**

**Proposal: System Message for Disabling, Adding Tax Code, and Deleting Tag Shows X\: Y Tag**

**Issue:**
The system currently displays messages related to actions such as disabling, adding tax codes, and deleting tags with the X\: Y tag format.

**Proposed Solution:**
To resolve this issue, we propose implementing a getCleanedTagName() function. This function will standardize the display of tags in system messages by removing unwanted escape characters and formatting tags properly.

**Technical Explanation:**
Currently, system messages for actions such as adding, updating, enabling, and deleting tags display the tag names with the escape character (\) resulting in the format X\: Y. We will introduce a getCleanedTagName()` function that will clean and format tag names for display in system messages. This function will remove any escape characters and return the cleaned tag name in a user-friendly format. The addition of this function will require updates to the parts of the code responsible for generating system messages. Any existing code that directly displays tag names will be modified to use getCleanedTagName() to ensure consistency in tag display.

**Implementation Plan:**
*Implement the getCleanedTagName() function in the relevant utility.
*Refactor existing code that generates system messages to use getCleanedTagName() instead of directly referencing tag 
  names.
*Test the updated message formatting to ensure tags are displayed correctly.

**Conclusion:**
Implementing the getCleanedTagName() function will standardize the display of tag names in system messages, removing unnecessary escape characters and enhancing readability. This approach will address the current formatting issue and ensure that system messages are clear and user-friendly o n all the platforms like Android, IOS, MAC and Web.

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
@abzokhattab 's proposal here https://github.com/Expensify/App/issues/47804#issuecomment-2302659959 looks good and works well. Other proposal seems improvised version of core issue to fix system, so going with the original proposal.

🎀 👀 🎀
C+ Reviewed

**Comment by sakluger** [comment]
Here's the offer for @abzokhattab: https://www.upwork.com/nx/wm/offer/103753777

**Comment by abdulrahuman5196** [comment]
Hi @francoisl / @sakluger I think the automation failed here.

The change was pushed to production 2 weeks before. And should be up for payment.

**Comment by francoisl** [comment]
Changing to Daily so we can issue payments then @sakluger

**Comment by sakluger** [comment]
Sorry about that delay!

Summarizing payment on this issue:

Contributor: @abzokhattab $250, paid via Upwork
Contributor+: @abdulrahuman5196 $250, please request on Newdot

@abdulrahuman5196 please complete the BZ checklist:

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@abdulrahuman5196] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@abdulrahuman5196 ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@abdulrahuman5196 ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@abdulrahuman5196 ] Determine if we should create a regression test for this bug.
- [ ] [@abdulrahuman5196 ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@sakluger ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by sakluger** [comment]
@abdulrahuman5196 please complete the BZ checklist:

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@abdulrahuman5196] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@abdulrahuman5196 ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@abdulrahuman5196 ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@abdulrahuman5196 ] Determine if we should create a regression test for this bug.
- [ ] [@abdulrahuman5196 ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@sakluger ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by sakluger** [comment]
We can close this as soon as the BZ checklist is completed.

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Workspace is under Control plan.
2) Go to workspace settings > Tags
3) Add a tag in X: Y format
4) Disable, add tax code and delete the tag in X:Y format
5) Go to #admins
6) The system message for disabling, adding tax code and deleting tag in X: Y format will display the tag correctly

**Comment by sakluger** [comment]
Thanks!

**Comment by JmillsExpensify** [comment]
$250 approved for @abdulrahuman5196
