### ISSUE TITLE
[HOLD for payment 2024-09-18] Update the Magic code form to be easier to reuse in other flows and add it to Reveal card details flow

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#48541]
### Problem

We are adding the magic code verification to a couple of flows that are accessible in newDot as well. Internal tracking issue is [here](https://github.com/Expensify/Expensify/issues/423001). Namely, they are:
- [x] When adding a new [contact method](https://github.com/Expensify/Expensify/issues/423805) - we already implemented this in this PR https://github.com/Expensify/App/pull/48320 @getusha and @hungvu193 for payment
- [x] Adding a [copilot](https://github.com/Expensify/Expensify/issues/423806) - cc @rushatgabhane @dangrous @NikkiWines this is a new feature for NewDot @rushatgabhane are you able to work on implementing the magic code requirement to this flow?
- [ ] ~Create [new virtual card](https://github.com/Expensify/Expensify/issues/423808) - @MariaHCD @koko57 - We will need to incorporate this into the Create New virtual card flow, probably as a last step - I think we need to discuss this more in Slack still~
- [x] Require magic code when [revealing card details](https://github.com/Expensify/Expensify/issues/423809) - @marcaaron is working on the backend parts and we need to add this to Newdot as well

### Solution

Create a reusable component for the user to input the magic code and submit the form, calling an API command, including the `validateCode` param.

The page should look like this 
![image](https://github.com/user-attachments/assets/dc65b21a-ce08-4ec1-8d64-1c7b2f34040a)

We can build on top of this PR https://github.com/Expensify/App/pull/48320 to make it more reusable 

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by mountiny** [comment]
@hungvu193 is working on adding this to the Reveal card details page

**Comment by hungvu193** [comment]
Created a draft PR here https://github.com/Expensify/App/pull/48628. 
I will need to setup an physical card to test it.

**Comment by marcaaron** [comment]
This is working great. I'm not sure about this copy though? 

Should we make this "Verify it's you" and "Please enter the code we sent to your email".

![2024-09-05_14-03-09](https://github.com/user-attachments/assets/cc238a70-fbe2-4a2c-b3a9-1a298c687148)

**Comment by marcaaron** [comment]
Oh I see we have different copy in the description of this issue. So, which are we using? Maybe @dubielzyk-expensify knows.

**Comment by rushatgabhane** [comment]
> are you able to work on implementing the magic code requirement to this flow?

yep it'll be merged tomorrow

**Comment by marcaaron** [comment]
James said:

>Let's make sure it's you
>Please enter the magic code sent to [james@expensify.com](mailto:james@expensify.com).

**Comment by dubielzyk-expensify** [comment]
LGTM

**Comment by mountiny** [comment]
PR merged and in staging, currently being deployed to production

**Comment by mountiny** [comment]
I think this project is basically done for now as we are not actively adding this to the virtual cards for now.

So I think we can pay out; I am not sure how many PRs have been linked to this issue; @hungvu193 @getusha, was it 2 PRs, so $500? Can you please summarize it here? thanks!

**Comment by hungvu193** [comment]
I reviewed https://github.com/Expensify/App/pull/48320 and implemented https://github.com/Expensify/App/pull/48628 (Marc reviewed it).
@getusha implemented https://github.com/Expensify/App/pull/48320

**Comment by mountiny** [comment]
$500 to @hungvu193 and $250 to @getusha then, do you agree?

**Comment by mountiny** [comment]
@hungvu193 @getusha could you please suggest regression tests for the two new updated flows? I think we need to make changes in the testrail

**Comment by hungvu193** [comment]
**Regression test:**

**Add new contact method flow:**
1. Go to Settings
2. Go to Profile
3. Go to Contact methods
4. Click “Add new contact method”
5. Enter a new email or phone number
6. Verify that ValidateCodeModal is open.
7. Once the magic code is inserted, click Submit
8. Verify that the contact is added and you're navigated to contact list page

**Reveal detail card flow:**
*Prerequisite: You must have a virtual card setup*
1. Go to Profile => Wallet => Click the Reveal details button on your virtual card.
2. Enter the magic code input.
3. Verify that you can see your card details if you entered correct magic code.

**Comment by hungvu193** [comment]
> $500 to @hungvu193 and $250 to @getusha then, do you agree?

I think both tasks are urgent, so can it be $500 for @getusha and $750 for me 😄

**Comment by mountiny** [comment]
@hungvu193 I will propose $625 to @hungvu193 and $350 to @getusha. This was an urgent task we needed help with, and you stepped up, which we appreciate, but at the same time, I do think we need to double the price on the task. I have already granted you the follow up tasks so you will get bounties from those.

**Comment by hungvu193** [comment]
Thank you. Totally agreed! 😄

**Comment by OfstadC** [comment]
## Payment Summary
- @hungvu193 due $625 via Manual New Expensify Request
- @getusha due $350 via Manual New Expensify Request

**Comment by garrettmknight** [comment]
$325 approved for @getusha
