### ISSUE TITLE
[Tracking] Add email tracking for email deliverability and open/click rates.

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#48663]
[High level design doc](https://docs.google.com/document/d/1merEKHp29NjG2z7dKM-np8ia9Wcirx7Cl98GEgWixfo/edit)

Proposal: Add email tracking for email deliverability and open/click rates.

Problem: Recipients are not reliably clicking on IOUs from senders, and thus never coming into the product. We know a non zero percentage of users ignore the emails we send, but we don’t actually know how bad the problem is. We rely on email notifications to pull viral leads into our product. However, we’re unable to determine if our emails are making this problem bigger by not being engaging and compelling for our users, or even worse not getting delivered. This lack of insight prevents us from optimizing our email communications, resulting in decreased user engagement, decreased understanding of our value, decreased conversion rates, and ultimately hampers our ability to drive sustainable growth.

Solution: Let’s start tracking email deliverability and open/click through rates with all relevant notifications so we know how big the problem is and can a/b test email communications to increase conversion of invited users to active users.
1. Let’s start by tracking the emails we send for one invite type: IOUs for new users.
2. We already use custom subject line to trigger an immediate unread message notification to the IOU recipient (added in [this PR](https://github.com/Expensify/Web-Expensify/pull/40903)). Let’s add a tracker in this same place that identifies the type of email.
- It might look something like $this->parameters['trackingKey'] = 'IOUnewUser'
3. We’ll send this tracker as a tag to Mailgun
  - Here is an [example of where](https://github.com/Expensify/Web-Expensify/blob/main/lib/Mailgun/Utils.php#L337) we’ll put it.
4. Mailgun is already set up to measure [email deliverability](https://www.mailgun.com/products/optimize/inbox-placement/) and open/click-through rates for all emails. All we need to do now is distinguish an IOU notification vs. any other unread message notification and the tracker accomplishes that
- Note: Mailgun only covers 50% of our emails. But so long as we track the control and test versions and compare them within that 50% pool, and then wait for statistical significance, we should learn if/which notifications are effective.
5. We’ll run an inbox placement test which sends the IOU notification to various mail providers and lets us know how often the specific notification is getting caught by spam.
6. We will get a baseline on the current notification open/click rate and validate this design before we introduce any A/B testing
- A/b testing the open rate of IOUs for new users using different subject lines will likely be our first test which is why we chose that, but the a/b test will come later.

## Tasks

- [x] Post **Proposal (full Problem/Solution statement)** in `#expensify-open-source`
- [x] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [x] Paste Proposal in the space above with a link to the Slack thread
- [x] Email `strategy@expensify.com` and paste in the Proposal
- [x] Fill out the **High-level overview of the problem**, **Timeline**, and **Terminology** sections of the Design Doc
- [x] Email `strategy@expensify.com` (continue the same email chain as before) with the link to your Design Doc
- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section.
- [x] Fill out the **High-level of proposed solution** section
- [x] Email `stategy@expensify.com` again with links to the doc and pre-design conversation in Slack
- [x] Add the `DesignDocReview` label to get the **High-level of proposed solution** section reviewed
- [x] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [ ] Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.
- [x] Fill out the **Detailed implementation of the solution** and related sections.
- [x] Re-add the `DesignDocReview` label to this issue
- [x] Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase
- [x] Implement the changes
- [x] Add regression tests so that QA can test your feature with every deploy ([instructions](https://stackoverflowteams.com/c/expensify/questions/363))
- [ ] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

<details><summary>Issue Owner</summary>Current Issue Owner: @danielrvidal</details>

**Comment by danielrvidal** [comment]
Here are the next steps as of now

- [ ] @justinpersaud - Give access to Mailgun: https://github.com/Expensify/Expensify/issues/426298
- [ ] @justinpersaud - Update IOUs to have the tag: https://github.com/Expensify/Expensify/issues/426303
- [ ] @justinpersaud - Update Mailgun to store the tags for IOUs: https://github.com/Expensify/Expensify/issues/426306

From there we'll plan the next steps once those are done.

**Comment by justinpersaud** [comment]
Workong on it this week but I'm just trying to wrap up some SOX audit issues that keep coming back from EY + finishing up blocking spam with ChatGPT for #fireroom-05-23-spam

**Comment by danielrvidal** [comment]
We should have the doc out today or tomorrow!

**Comment by danielrvidal** [comment]
### **[High level design doc](https://docs.google.com/document/d/1merEKHp29NjG2z7dKM-np8ia9Wcirx7Cl98GEgWixfo/edit)** 

The HL is ready for reviews. Please give it a read and ask questions in the doc or room. Assigning the review label now!

**Comment by fukawi2** [comment]
I have read and reviewed this Design Doc!

**Comment by srikarparsi** [comment]
I have read and reviewed this Design Doc!

**Comment by garrettmknight** [comment]
I have read and reviewed this Design Doc!

**Comment by MarcFillari** [comment]
I have read and reviewed this Design Doc!

**Comment by twisterdotcom** [comment]
I have read and reviewed this Design Doc!

**Comment by twisterdotcom** [comment]
I have read and reviewed this Design Doc!

**Comment by danielrvidal** [comment]
I just bumped the remaining reviewers but hopefully we'll move to detailed in the next day or so.

**Comment by Christinadobrzyn** [comment]
I have read and reviewed this Design Doc!

**Comment by davidcardoza** [comment]
I have read and reviewed this Design Doc!

**Comment by justinpersaud** [comment]
Detailed is ready to go out I think.

**Comment by francoisl** [comment]
I have read and reviewed this Design Doc!

**Comment by techievivek** [comment]
I have read and reviewed this Design Doc!

**Comment by iwiznia** [comment]
I have read and reviewed this Design Doc!

**Comment by flodnv** [comment]
I have read and reviewed this Design Doc!

**Comment by justinpersaud** [comment]
Wrapping up some discussions in the detailed portion

**Comment by puneetlath** [comment]
I have read and reviewed this Design Doc!

**Comment by garrettmknight** [comment]
I have read and reviewed this Design Doc!

**Comment by cead22** [comment]
I have read and reviewed this Design Doc!

**Comment by CherylWalsh** [comment]
I have read and reviewed this Design Doc!

**Comment by tylerkaraszewski** [comment]
I have read and reviewed this Design Doc!

**Comment by chiragsalian** [comment]
I have read and reviewed this Design Doc!

**Comment by justinpersaud** [comment]
Implementation for this is in review

**Comment by JmillsExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by justinpersaud** [comment]
Working on some last bit of bugs with the IOU tracking

**Comment by justinpersaud** [comment]
Need to review and see if this is working this week

**Comment by justinpersaud** [comment]
Seems like this is working given we found data for the variants here

https://expensify.slack.com/archives/C07HPDRELLD/p1731372028836229?thread_ts=1730161250.824289&cid=C07HPDRELLD

**Comment by justinpersaud** [comment]
Daniel is going to review the data from the analytics before we close this off

**Comment by justinpersaud** [comment]
Latest update was here https://expensify.slack.com/archives/C07HPDRELLD/p1732551384217819?thread_ts=1730161250.824289&cid=C07HPDRELLD

**Comment by danielrvidal** [comment]
We have the data in MailGun. @anmurali and I are still working through MailGuns logs to ensure we can get click through rate as well.

**Comment by danielrvidal** [comment]
This is done, but we still haven't concluded the first test so I'm keeping it open.

**Comment by danielrvidal** [comment]
I need to follow up on this one so will this week.

**Comment by danielrvidal** [comment]
This is done! We found that we were sending way less IOUs than we anticipated to new users and ended up changing the subject line based on other updates. We have added email tracking to the awareness emails which we'll be evaluating next.
