### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] mWeb - Task - After deleting task and tapping on back button, user is not redirected to LHN

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49991]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Open any group chat.
3. Tap on the "+" button.
4. Tap on "Assign Task"
5. Write any title for the task.
6. Tap on "Next"
7. Tap on "Confirm Task"
8. Open the created task report.
9. Tap on the header.
10. Tap on "Delete"
11. Once back in the chat, tap on the arrow on the top left corner.
12. Verify you are redirected to LHN.

## Expected Result:
After deleting a task and tapping on the back button on chat, the user should be redirected to LHN.

## Actual Result:
After deleting a task, and tapping on the back button on chat, the user is redirected to the deleted task chat, and tapping on back button again, leads to the previous chat again and not to LHN.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1726cc30-4927-4459-b70d-2315e9237468

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841211663509385892</li>
        <li>Upwork Job ID: 1841211663509385892</li>
        <li>Last Price Increase: 2024-10-01</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 104308384</li>
<li>nyomanjyotisa | Contributor | 104308386</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alitoshmatov** [comment]
@nyomanjyotisa Thank you for your proposal, your RCA is correct and your solution is solving the problem

**Comment by alitoshmatov** [comment]
@mkzie2 Thank you for your proposal, I think logic used in transaction deleting is different from our use-case. For example, after transaction deletion if there is another transaction left it will navigate there.

**Comment by alitoshmatov** [comment]
I think we can go with @nyomanjyotisa 's [proposal ](https://github.com/Expensify/App/issues/49991#issuecomment-2386006862)

C+ reviewed 🎀 👀 🎀

**Comment by mkzie2** [comment]
@alitoshmatov I don't think the logic will be different because we only call this `navigateBackAfterDeleteTransaction` function if `navigateBackToAfterDelete` exists.

**Comment by greg-schroeder** [comment]
PR is merged and on staging. Awaiting deploy to prod

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @nyomanjyotisa - $250 - Paid via Upwork
C+: @alitoshmatov - $250 - Paid via Upwork

**Comment by greg-schroeder** [comment]
@alitoshmatov Can you complete the checklist so we can close this out? Thanks!

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/46950
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/46950/files#r1812284617
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. No need

**Comment by alitoshmatov** [comment]
@greg-schroeder Checklist done

**Comment by greg-schroeder** [comment]
Thanks!
