### ISSUE TITLE
[$250] [AWAITING CHECKLIST for payment 2025-01-28]  IOU - Empty suggestion pop-up appears below numeric keyboard, preventing number input

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50057]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+omqq1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user has signed in
1. Open app
2. Tap on FAB
3. Select Submit Expense
4. Try to enter value with multiple numbers e.g. "3456"

## Expected Result:
The user should be able to continuously input numbers in the Amount field without any interruptions, and all taps on the numeric keyboard should be properly registered. The "Next" button should remain fully accessible

## Actual Result:
The empty keyboard suggestion is displayed below the numeric keyboard and also overlaps the "Next" button. It prevents continuous input in the Amount field because tapping a number on the numeric keyboard only dismisses the empty suggestion pop-up without registering the number. The empty suggestion pop-up appears with each tap on the numeric keyboard. This issue also makes it difficult to proceed, as the empty suggestion pop-up covers the "Next" button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: IPAD
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/dbd0e4ef-066c-462a-8ca1-828d212a5808

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021886483321730129635</li>
        <li>Upwork Job ID: 1886483321730129635</li>
        <li>Last Price Increase: 2025-02-03</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by rezkiy37** [comment]
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by rezkiy37** [comment]
For context:

1. There was a similar issue - https://github.com/Expensify/App/issues/38349.
2. It was fixed - https://github.com/Expensify/App/pull/38728.

However, this issue describes a little bit different problem.

**Comment by rezkiy37** [comment]
Actively working on the issue.

**Comment by rezkiy37** [comment]
Discussing a proposal internally.

**Comment by garrettmknight** [comment]
@rezkiy37 is there anywhere I can follow along with the proposal in slack?

**Comment by rezkiy37** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The empty keyboard suggestion is displayed below the numeric keyboard and overlaps the "Next" button. It prevents continuous input in the **Amount** field because tapping a number on the numeric keyboard only dismisses the empty suggestion pop-up without registering the number. The empty suggestion pop-up appears with each tap on the numeric keyboard. This issue also makes proceeding difficult, as the empty suggestion pop-up covers the "Next" button.

### What is the root cause of that problem?
The empty suggestion pop-up cannot be hidden from React Native programmatically. There was a [PR](https://github.com/Expensify/App/pull/38728/files) that helped to hide the **QuickType** bar, but not this particular empty bar.

### What changes do you think we should make in order to solve the problem?
Since this text input is controlled by the custom numeric buttons, it is not actually an input on native platforms. Moreover, the app passes tons of props and does many other work such as computing, lifecycle, and hooks. However, it is just a text for the user.
So I am proposing to simplify **AmountTextInput** for native platforms. It should use the **Text** component with same styles.

```typescript
function AmountTextInput(
    {style, containerStyle, formattedAmount, placeholder}: AmountTextInputProps,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    _ref: ForwardedRef<BaseTextInputRef>,
) {
    const theme = useTheme();
    const shouldShowPlaceholder = !formattedAmount;

    return (
        <View style={containerStyle}>
            <Text style={[style, shouldShowPlaceholder && {color: theme.placeholderText}]}>{shouldShowPlaceholder ? placeholder : formattedAmount}</Text>
        </View>
    );
}
```

### What alternative solutions did you explore? (Optional)
1. Do nothing. Because it is an edge case and replicable only after some scenario. It shows the micro suggestion bar by default. It blocks the first interaction as well.

**Comment by rezkiy37** [comment]
I've posted a [proposal](https://github.com/Expensify/App/issues/50057#issuecomment-2401990631). 
cc @garrettmknight @shubham1206agra

**Comment by garrettmknight** [comment]
@shubham1206agra can you please review the proposal?

**Comment by rezkiy37** [comment]
> @rezkiy37 I believe that with your proposal, we lose access to change input via an external keyboard on native devices.

Do you mean like an iPad with a keyboard? We can implement a listener or a kind of `onKeyPress` handler. WDYT?

```typescript
useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
        if (event.key >= '0' && event.key <= '9') {
            console.log(`Number key pressed: ${event.key}`);
            // Handle the number key press here
        }
    };

    // Add event listeners for keydown
    window.addEventListener('keydown', handleKeyDown);

    // Clean up event listeners on component unmount
    return () => {
        window.removeEventListener('keydown', handleKeyDown);
    };
}, []);
```

**Comment by rezkiy37** [comment]
No overdue, we are still discussing. @shubham1206agra FYI: https://github.com/Expensify/App/issues/50057#issuecomment-2407024657.

**Comment by garrettmknight** [comment]
Not overdue - they're discussing the best solution.

**Comment by rezkiy37** [comment]
@shubham1206agra, just a friendly reminder - https://github.com/Expensify/App/issues/50057#issuecomment-2410619685.

**Comment by rezkiy37** [comment]
> I am not a fan of adding events like that here tbh. Is there any other way to do this?

There is no other way to handle an external keyboard when we don't use `TextInput`. Why do you mind this approach? It is a normal solution because we use it quite often in the project. 

<details><summary>Screenshot</summary>
<p>

<img width="1050" alt="Screenshot 2024-10-16 at 14 58 35" src="https://github.com/user-attachments/assets/bbe15a08-b967-47bc-b6d7-021153d6f73f">

</p>
</details>

**Comment by rezkiy37** [comment]
Yeah, that's true.

**Comment by rezkiy37** [comment]
I will try to find better solution.

**Comment by rezkiy37** [comment]
No overdue. I am working on the issue.

**Comment by rezkiy37** [comment]
I have one idea for disabling this suggestion pop-up. Working on it.

**Comment by rezkiy37** [comment]
Actively working on the issue. Discussing proposals internally.

**Comment by rezkiy37** [comment]
Other tasks occupied me today. Will work tomorrow.

**Comment by rezkiy37** [comment]
The [doc](https://developer.apple.com/documentation/uikit/uitextinputassistantitem) says:
> To hide shortcuts altogether, set the [leadingBarButtonGroups](https://developer.apple.com/documentation/uikit/uitextinputassistantitem/1614575-leadingbarbuttongroups) and [trailingBarButtonGroups](https://developer.apple.com/documentation/uikit/uitextinputassistantitem/1614532-trailingbarbuttongroups) properties to empty arrays. Doing so hides only the shortcuts and doesn’t hide the typing suggestions. For information on managing the typing suggestions, see [autocorrectionType](https://developer.apple.com/documentation/uikit/uitextinputtraits/1624453-autocorrectiontype).

However, React Native itself does not manage these properties.

<img width="944" alt="Screenshot 2024-10-25 at 13 10 27" src="https://github.com/user-attachments/assets/41b7119f-a6c7-434e-998c-b7e35df570c9">

We are discussing internally how to fix it.

**Comment by rezkiy37** [comment]
Working on the issue.

**Comment by rezkiy37** [comment]
Working on the issue.

**Comment by rezkiy37** [comment]
I am preparing a proposal.

**Comment by rezkiy37** [comment]
I am OOO till Tuesday and will continue to work on this issue later.

**Comment by rezkiy37** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1730400037918759

**Comment by garrettmknight** [comment]
Bumping for some input in the thread.

**Comment by rezkiy37** [comment]
Posted a RN discussion https://github.com/react-native-community/discussions-and-proposals/discussions/830.

**Comment by garrettmknight** [comment]
Looks like we got an initial response from someone there!

**Comment by rezkiy37** [comment]
I am preparing a PR to RN.

**Comment by rezkiy37** [comment]
Other tasks occupied me today. I will work on this tomorrow.

**Comment by rezkiy37** [comment]
Working on the PR.

**Comment by rezkiy37** [comment]
The draft PR link - https://github.com/facebook/react-native/pull/47630. Working on it.

**Comment by rezkiy37** [comment]
Working on the PR.

**Comment by rezkiy37** [comment]
https://github.com/facebook/react-native/pull/47671

**Comment by rezkiy37** [comment]
Working on the PR.

**Comment by rezkiy37** [comment]
The review in progress.

**Comment by rezkiy37** [comment]
The PR (https://github.com/facebook/react-native/pull/47671) has been opened for review 🙂

**Comment by rezkiy37** [comment]
Yeah, I've fixed the CI warning mentioned by a Meta Engineer. Waiting for another review round.

**Comment by rezkiy37** [comment]
Hi!
I am writing to let you know about my upcoming vacation until the 7th Tuesday of January. I will resume my work on the issue when I get back.

Wishing you a Happy New Year!

**Comment by rezkiy37** [comment]
The PR was merged. I am looking forward to the upcoming RN version to apply in the app.

**Comment by rezkiy37** [comment]
Yeah, makes sense. I'll do it.

**Comment by rezkiy37** [comment]
I've opened for review - https://github.com/Expensify/App/pull/54957.

**Comment by rezkiy37** [comment]
The last step is to bump the RN version with the newly added property. However, it can be managed with other issues.

**Comment by garrettmknight** [comment]
@shubham1206agra can you complete the checklist when you get a chance and I'll pay out the job?

**Comment by rezkiy37** [comment]
The checklist was [posted](https://github.com/Expensify/App/issues/50057#issuecomment-2619664011).

**Comment by garrettmknight** [comment]
@shubham1206agra offer out to you.
