### ISSUE TITLE
[Awaiting checklist] [$250] mWeb/Chrome - Workspace - Invite button hidden behind keypad

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50073]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch both mweb and Android
2. Go to workspace -- invite members
3. Go offline and note no internet connection above
4. Select a member and tap next

## Expected Result:
In mweb and Android, in offline inviting members, invite button should display in same way

## Actual Result:
In mweb, invite button hidden behind keypad but in Android above keypad

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/250bd971-ef81-4694-8012-d676e6cf96b1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841522414660630574</li>
        <li>Upwork Job ID: 1841522414660630574</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 104343060</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment]
Ahh @Nodebrute are you on iOS there? I didn't test that, it wasn't included in the report. Let me double check then.

**Comment by twisterdotcom** [comment]
https://github.com/user-attachments/assets/1cfab2bb-a2a8-4190-b93d-58fe3d00010a

**Comment by twisterdotcom** [comment]
Okay agreed. This has nothing to do with being offline/online either though. It just occurs regardless. Not sure what all the bottom padding is for either when you scroll with the keyboard in view. Can we fix that too @Nodebrute?

**Comment by eh2077** [comment]
@Krishna2323 Thanks for your proposal! 

> The privacy link is render as footerContent which is rendered below the submit button.

Does this cause the Invite button hidden issue? Or it's another issue found when investigating the issue?

**Comment by eh2077** [comment]
I think we should go with @Nodebrute 's [proposal](https://github.com/Expensify/App/issues/50073#issuecomment-2388981429) as they're the first to point out the root cause and suggested a fix.

Setting `shouldEnableMaxHeight` property for `ScreenWrapper` fixes the issue.

🎀👀🎀 C+ reviewed

**Comment by twisterdotcom** [comment]
Payment Summary:

- @Nodebrute paid $250 [here](https://www.upwork.com/nx/wm/offer/104343060) (Contributor)
- @eh2077 paid $250 via NewDot Manual Request

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**After searching the commit histories, I don't think this is a bug introduced by a recent PR. It's more likely an edge case that was uncovered**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. **_No, because it's a minor change of style and won't impact the main user flow._**

**Comment by eh2077** [comment]
Requested payment in NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @eh2077
