### ISSUE TITLE
[HOLD for payment 2024-11-11 - Waiting on checklist] [$250] Android – Sign in – Able to dismiss the Onboarding modal using back button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50177]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5043083
**Email or phone of affected tester (no customers):** ponikarchuks+1331024@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging app
2. Log in with a new Gmail account
3. When Onboarding modal appears tap on Something else
4. Background the app
5. Open app and tap back button some times

## Expected Result:
Onboarding modal present

## Actual Result:
Onboarding modal disappears

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/64a94e9a-9d0b-4485-a7ad-5b4028f724d8
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844399665498037051</li>
        <li>Upwork Job ID: 1844399665498037051</li>
        <li>Last Price Increase: 2024-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104560308</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is able to dismiss the onboarding flow on the personal details step.

### What is the root cause of that problem?
The onboarding has 3 steps, purpose, work information, and personal details. On the purpose page, we already override the back button to prevent the user from going back.
https://github.com/Expensify/App/blob/0ed41d77dfb67666302201ceff561f64b7b13e77/src/pages/OnboardingPurpose/index.native.tsx#L8-L18

But this isn't present in either work information or personal details. However, that's not the problem. When going back from the work information or personal details, the user should be going back to the correct step instead of preventing them from going back.

What happens in this issue is, that when we reopen the app, the app will show the last step of the onboarding step, in our case, the personal details step.
https://github.com/Expensify/App/blob/0ed41d77dfb67666302201ceff561f64b7b13e77/src/libs/actions/Welcome/OnboardingFlow.ts#L106-L113

That's possible because of `getAdaptedStateFromPath`. The result from `getAdaptedStateFromPath` looks like this (simplified):

```
{
    routes: [{name: BottomTabNavigator}, {name: OnboardingModalNavigator, state: {routes: [{name: Onboarding_Personal_Details}]}}]
}
```

So, in the nav stack, only the onboarding personal details page is present. So, when going back, instead of going back to the purpose step, the page is closed.

Why this doesn't happen when we press go back using the in-app back button? That's because we reset the root state which contains the correct state for the onboarding navigator.
https://github.com/Expensify/App/blob/0ed41d77dfb67666302201ceff561f64b7b13e77/src/libs/actions/Welcome/OnboardingFlow.ts#L140-L145
https://github.com/Expensify/App/blob/0ed41d77dfb67666302201ceff561f64b7b13e77/src/libs/actions/Welcome/OnboardingFlow.ts#L52-L101

But this solution will cause a brief LHN to be seen.

### What changes do you think we should make in order to solve the problem?

We should improve `getAdaptedStateFromPath` so that it returns the complete state for the onboarding navigator, then, we won't need `adaptOnboardingRouteState` anymore. The improvement will be inspired from `adaptOnboardingRouteState` logic to build the correct routes.

First, create a new function in a separate file called `getOnboardingAdaptedState`.

```
export default function getOnboardingAdaptedState(state: PartialState<NavigationState>): PartialState<NavigationState> {
    const onboardingRoute = state.routes[0];
    if (onboardingRoute.name === SCREENS.ONBOARDING.PURPOSE) {
        return state;
    }

    const routes = [];
    if (onboardingRoute.name === SCREENS.ONBOARDING.PERSONAL_DETAILS && selectedPurpose === CONST.ONBOARDING_CHOICES.MANAGE_TEAM) {
        routes.push({name: SCREENS.ONBOARDING.PURPOSE});
        routes.push({name: SCREENS.ONBOARDING.WORK});
        routes.push(onboardingRoute);
    } else {
        routes.push({name: SCREENS.ONBOARDING.PURPOSE});
        routes.push(onboardingRoute);
    }

    return {
        routes,
        index: routes.length - 1,
    }
}
```

Next, modify the onboarding navigator state here to use the new state from `getOnboardingAdaptedState`.
https://github.com/Expensify/App/blob/0ed41d77dfb67666302201ceff561f64b7b13e77/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L255-L257

```
if (onboardingModalNavigator && onboardingModalNavigator.state) {
    routes.push({
        ...onboardingModalNavigator,
        state: getOnboardingAdaptedState(onboardingModalNavigator.state),
    });
}
```

Last, we can remove `OnboardingFlow.goBack` and just use `Navigation.goBack`.

**Comment by twisterdotcom** [comment]
Sorry, should this be closed or are you saying it's a regression @allgandalf?

**Comment by twisterdotcom** [comment]
@allgandalf / @blazejkustra I can recreate this, so I'm going to make it external... but let me know if you think this should be handled by somebody specific.

**Comment by suneox** [comment]
@bernhardoj Your proposal is a potential solution, but could you please update it with the latest main branch and handle the duplicate OnboardingEmployees state issue as well?


https://github.com/user-attachments/assets/355d161c-7898-4dd3-833c-4e1c475b1240

**Comment by bernhardoj** [comment]
Updated my [proposal](https://github.com/Expensify/App/issues/50177#issuecomment-2392857553).

> handle the duplicate OnboardingEmployees state issue as well?

I can't repro it with my proposal.

**Comment by suneox** [comment]
> I can't repro it with my proposal.

@bernhardoj It still reproduces on my side.


https://github.com/user-attachments/assets/cdba1b38-a12c-41cc-9d44-a6e8d750d1b2

**Comment by bernhardoj** [comment]
Ah, I think it's the same issue as this [one](https://github.com/Expensify/App/issues/50064). Can you check if applying the solution there fixes the issue?

**Comment by trjExpensify** [comment]
👋 @twisterdotcom onboarding related bugs, I'd put those in #convert going forward.

**Comment by twisterdotcom** [comment]
Added to Convert.

**Comment by suneox** [comment]
> Ah, I think it's the same issue as this [one](https://github.com/Expensify/App/issues/50064). Can you check if applying the solution there fixes the issue?

@bernhardoj The selected proposal from #50064 retains the use of `adaptOnboardingRouteState`, which will conflict with your solution since it avoids using [OnboardingFlow.goBack](https://github.com/Expensify/App/blob/4bad8853733095e5a388606b2b3ef75b634ae5f6/src/libs/actions/Welcome/OnboardingFlow.ts#L145).

**Comment by bernhardoj** [comment]
I don't think they will use `adaptOnboardingRouteState` to solve https://github.com/Expensify/App/issues/50064. What I understand is that they will follow the same pattern of `adaptOnboardingRouteState` that is using the root state when resetting the root.

**Comment by twisterdotcom** [comment]
@suneox any thoughts on @bernhardoj's response, or are we waiting for more proposals?

**Comment by suneox** [comment]
> @suneox any thoughts on @bernhardoj's response, or are we waiting for more proposals?

I'll check @bernhardoj's response with issue #50064 in few hours

**Comment by suneox** [comment]
I’ve verified that [this issue](https://github.com/Expensify/App/issues/50177#issuecomment-2408415530) can be resolved in #50064, so @bernhardoj’s [proposal](https://github.com/Expensify/App/issues/50177#issuecomment-2392857553) LGTM. Based on the onboarding steps, we will push the missing onboarding route during initialization

🎀 👀 🎀 C+ reviewed

**Comment by blazejkustra** [comment]
@bernhardoj Please tag me on the PR once it's ready 🙏

**Comment by bernhardoj** [comment]
@blazejkustra sure, @danieldoglas waiting for an assignment

**Comment by danieldoglas** [comment]
Assigned.

**Comment by bernhardoj** [comment]
PR is ready

cc: @suneox @blazejkustra

**Comment by adamgrzybowski** [comment]
It looks good to me. However, I'm wondering if we want to have the swipe back action possible after freshly opening the app.

e.g. swipe back on the mobile browser ios means go back in history so that would be inconsistent. 

If yes then 🟢 

If not then I guess we could use a param for the `goBack` function instead of adding logic to `getAdaptedState`.

**Comment by suneox** [comment]
> It looks good to me. However, I'm wondering if we want to have the swipe back action possible after freshly opening the app.
> 
> e.g. swipe back on the mobile browser ios means go back in history so that would be inconsistent.

I’ve verified that it still works as expected

**Comment by suneox** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by twisterdotcom** [comment]
Payment Summary:

- @suneox paid $250 [here](https://www.upwork.com/nx/wm/offer/104560308) (Reviewer)
- @bernhardoj paid $250 via NewDot Manual Request

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by suneox** [comment]
I have completed the checklist
