### ISSUE TITLE
[$250] Onboarding - 'Submit an expense' task gets marked as complete when tracking an expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50178]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5039985
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with new Gmail account
3. Select 'Get paid back by my employer' in onboarding modal
4. Enter user name and submit modal
5. Click on FAB > Track expense > Manual and finish the flow
6. Navigate to Concierge chat

## Expected Result:
'Submit an expense' onboarding task should remain unchecked as the expense is not submitted yet

## Actual Result:
'Submit an expense' gets marked as complete when tracking an expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/471c0408-3d7e-4dc7-bd3c-5d4f0a937d70

---

Note that the same issue can be observed when 'Chat and split expenses with friends' selected in onboarding modal
In this scenario, the 'Start a chat' task gets marked as completed when tracking an expense:

https://github.com/user-attachments/assets/56bcad50-20d5-4841-9112-d76706c637e2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843765208299825426</li>
        <li>Upwork Job ID: 1843765208299825426</li>
        <li>Last Price Increase: 2024-10-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by kubabutkiewicz** [comment]
Hello, Im Jakub from Callstack and would like to help with this issue

**Comment by kubabutkiewicz** [comment]
This seems to me that its working as expected or issue on the BE, when making a `TrackExpense` command in the response we are getting onyx data which indicate that `Submit an expense` should be marked as completed 
<img width="657" alt="image" src="https://github.com/user-attachments/assets/f979277e-72bb-4ab8-874f-292f54ac6ec8">

**Comment by greg-schroeder** [comment]
@kubabutkiewicz Okay so to be clear, Onyx Data shows this is actually expected in the end, and that "Submit an expense"  is supposed to be checked there. Hmm. I wonder if it just needs to be re-named to "Create an expense" or if that is actually a bug?

**Comment by greg-schroeder** [comment]
I am asking the team

**Comment by kubabutkiewicz** [comment]
> Okay so to be clear, Onyx Data shows this is actually expected in the end, and that "Submit an expense" is supposed to be checked there.

@greg-schroeder yes

**Comment by trjExpensify** [comment]
Moving this out of wave-collect to #convert as an onboarding task related issue if we need to do something here.

**Comment by greg-schroeder** [comment]
checking with #convert team

**Comment by greg-schroeder** [comment]
Bumped thread

**Comment by greg-schroeder** [comment]
Go away melvin

**Comment by greg-schroeder** [comment]
I reproduced this on web staging again:

![image](https://github.com/user-attachments/assets/83e92653-2e94-421f-848d-dbec6dd58e8e)
![image](https://github.com/user-attachments/assets/6dfab860-d42c-4ee2-a5e1-56953d4f3b04)

**Comment by greg-schroeder** [comment]
As originally noted in the OP: the same issue can be observed when 'Chat and split expenses with friends' selected in onboarding modal. In this scenario, the 'Start a chat' task gets marked as completed when tracking an expense. 

Should we track that separately or handle it here? I'm assuming it's the same RC and they're both onboarding tasks, but are obviously separate flows.

**Comment by greg-schroeder** [comment]
Awaiting proposals

**Comment by greg-schroeder** [comment]
Same as above

**Comment by kubabutkiewicz** [comment]
@greg-schroeder did someone from BE team checked this? because I don't think we can do something on frontend to fix that

**Comment by greg-schroeder** [comment]
Awaiting an internal volunteer

**Comment by greg-schroeder** [comment]
Still waiting for a volunteer

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment]
Awaiting a volunteer

**Comment by greg-schroeder** [comment]
Same as above

**Comment by greg-schroeder** [comment]
Same as above

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by greg-schroeder** [comment]
This seems to have been fixed, so closing for now.
