### ISSUE TITLE
[Waiting on checklist] [$250] Saved search - Saved search name is blank in the list after clearing name field and saving it

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50225]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search.
3. Click 3-dot menu next to saved search.
4. Click Rename.
5. Clear the name field and save it.

## Expected Result:
The saved search in the list will have the default name instead of blank name after saving empty name.

## Actual Result:
The saved search in the list shows empty name.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a202a0e0-a7e3-41d2-8f3d-883598fea03e

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021842161451688398163</li>
        <li>Upwork Job ID: 1842161451688398163</li>
        <li>Last Price Increase: 2024-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>adeel0202 | Contributor | 104543798</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sher999** [comment]
### Proposal 
----

### Please re-state the problem that we are trying to solve in this issue.

Saved search name is blank in the list after clearing name field and saving it


### What is the root cause of that problem?

We currently don't have any implementation in our code to prevent users from saving an empty name.

 ### What changes do you think we should make in order to solve the problem?
 
<img width="608" alt="Screenshot 2024-10-04 at 8 35 24 PM" src="https://github.com/user-attachments/assets/149db2b8-38e9-4e00-a2aa-e14f89e6e408">


`isSubmitDisabled={!newName}`

to the FormProvider

POC


https://github.com/user-attachments/assets/f8c01779-8c73-4893-9469-965041fb0add

----
### What alternative solutions did you explore? (Optional)

**Comment by sher999** [comment]
<h2>Proposal updated</h2>

Added what else can we do

**Comment by AlienistSolution** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

The saved search name appears as blank in the list after the name field is cleared and saved. Instead, you wish for the default name for a saved search, i.e. the query, to be stored as new name, rather than the empty string.

## What is the root cause of that problem?

When saving an empty string, the empty string is passed on as is to the SearchActions.

## What changes do you think we should make in order to solve the problem?

It's a very easy fix. `SavedSearchRenamePage.tsx` already receives the query in the query params as `q`, regardless of what the name is. This is equal to the default name given to saved searches. All we have to do is add that value as a fallback for when `newName` turns out to be falsey, in this case an empty string.

![image](https://github.com/user-attachments/assets/d10a9335-438d-40bc-9f32-20ecca939886)

## What else can we do?

I think frontend wise this is the only solution that fits the parameters of the problem. You could also consider doing the same thing, but server side instead of client side.

**Comment by AlienistSolution** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The saved search name appears as blank in the list after the name field is cleared and saved. Instead, you wish for the default name for a saved search, i.e. the query, to be stored as new name, rather than the empty string.

### What is the root cause of that problem?

When saving an empty string, the empty string is passed on as is to the SearchActions.

### What changes do you think we should make in order to solve the problem?

It's a very easy fix. `SavedSearchRenamePage.tsx` already receives the query in the query params as `q`, regardless of what the name is. This is equal to the default name given to saved searches. All we have to do is add that value as a fallback for when `newName` turns out to be falsey, in this case an empty string.

![image](https://github.com/user-attachments/assets/d10a9335-438d-40bc-9f32-20ecca939886)

**Comment by mollfpr** [comment]
>The saved search in the list will have the default name instead of blank name after saving empty name.

@abzokhattab @Nodebrute @sher999 I don't think preventing saving the empty string is what we are looking for.

**Comment by mollfpr** [comment]
Our API seems already handled with the empty string value for `newName` and using the `q` value for the default, but this wasn't handled in our app for offline cases.

https://github.com/user-attachments/assets/ed73b0bf-d4b8-41aa-b900-98a445894878

The [proposal](https://github.com/Expensify/App/issues/50225#issuecomment-2394555550) from @AlienistSolution seems to have the correct solution. It implements the same logic as the API response and will handle the offline case on the ND side.

🎀 👀 🎀 C+ reviewed!

**Comment by AlienistSolution** [comment]
@mollfpr awesome, happy to help. It's a miniscule change and this is the first time for me doing an Expensify bug. Are you guys gonna fix it yourself since it's so small or am I still supposed to do it? I'm fine either way, but just so I know how we continue from here :)

**Comment by chiragsalian** [comment]
Proposal LGTM. Feel free to create a PR @AlienistSolution. Let us know if you have any questions along the way 🙂

**Comment by AlienistSolution** [comment]
I have applied for the job on Upwork. I expect to shoot a PR your way latest by the end of tonight (It is 12:20 PM for me now)

**Comment by AlienistSolution** [comment]
@chiragsalian I see in the PR guidelines there is an Expensify Slack. I'd like to join that if possible :smile:

**Comment by chiragsalian** [comment]
> I'd like to join that if possible 😄

Neat, yeah i would just follow the steps posted [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#slack-channels) if you haven't already i.e.,
> Before requesting an invite to Slack, please ensure your Upwork account is active, since we only pay via Upwork (see [below](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions)). To request an invite to Slack, email [contributors@expensify.com](mailto:contributors@expensify.com) with the subject Slack Channel Invites. We'll send you an invite!

**Comment by AlienistSolution** [comment]
@adeel0202 I agree with your points. Thank you for noting them.

**Comment by mollfpr** [comment]
@AlienistSolution Could you inform us when the PR ready? Thanks!

**Comment by AlienistSolution** [comment]
@mollfpr I have the change ready, since it was miniscule, but I am blocked by the huge checklist. I have requested access to the Slack channel to ask some questions on how to get certain parts set up properly for testing on all platforms and then I need to record/screenshot those processes as well. I got feedback from the team that Slack is having issues and I cannot be added yet, so I am in deadlock at the moment. Also I wasn't expecting this amount of due diligence for this one liner, so I apologize for giving a wrong time estimate initially.

**Comment by twisterdotcom** [comment]
How are you doing now @AlienistSolution?

**Comment by AlienistSolution** [comment]
@twisterdotcom Same spot, basically. I don't have access to the Slack Channel yet and I don't have the resources to test this change on every platform, let alone make screenshots and videos of it on every platform. I can't finish the checklist and I can therefore not click on "Create pull request".

I was very psyched about being awarded the bug, I could definitely use the cash for it, but I don't think this is gonna happen properly from my side. I will have to take the time to get a setup where I can actually do all of this, and given circumstances right now, I can't. It's the smallest of changes on 1 line. You guys could easily just close this issue and fix it internally, I'll take the loss.

**Comment by twisterdotcom** [comment]
@chiragsalian can we take this internally instead then?

**Comment by chiragsalian** [comment]
We could but I'm pretty sure internally most of us don't have the bandwidth.
I think we should just open it up to other contributors at this point. What do you feel @mollfpr? Alternatively you can prepare the PR too if you like. Let me know.

**Comment by mollfpr** [comment]
We can ask other contributors to help implement the solution, and to be fair, the compensation can be split with @AlienistSolution. Otherwise, I can help open the PR.

**Comment by mollfpr** [comment]
>The solution does not account for the scenario where the user enters a space in the search input, which would still result in an empty name being saved.

I agree this will happen, but I'm not sure if the changes will include @AlienistSolution solution or not. Could you elaborate?

**Comment by mollfpr** [comment]
>const saveSearchName = newName?.trim() || queryJSON?.inputQuery || '';

Is it only the above line? Or does it still use the `q` params for the fallback?

**Comment by mollfpr** [comment]
Okay, I think we can use the changes.

cc @chiragsalian

**Comment by chiragsalian** [comment]
Cool, go for it @adeel0202. Feel free to create the PR.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @adeel0202 paid $250 [here](https://www.upwork.com/nx/wm/offer/104543798) (Contributor)
- @mollfpr paid $250 via NewDot Manual Request

**Comment by mollfpr** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by garrettmknight** [comment]
@mollfpr can you fill that checklist out?

**Comment by mollfpr** [comment]
@garrettmknight Yup, sorry I forgot to update the checklist. I'm doing it now!

**Comment by mollfpr** [comment]
@garrettmknight The checklist is filled 🚀

**Comment by garrettmknight** [comment]
$250 approved for @mollfpr
