### ISSUE TITLE
[C+ Checklist Needs Completion] [$250]  Copilot - Two accounts are highlighted in account list when navigating via keyboard

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50779]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Interna Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in as a copilot.
3. Go to Account settings.
4. Click on the account switcher.
5. Navigate through the account list via keyboard.

## Expected Result:
The current account will no longer be highlighted and the selected account will be highlighted (same behavior as workspace switcher).

## Actual Result:
Both the current account and the selected account are highlighted when navigating via keyboard.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4c6c8cd2-0247-4ea5-b3ec-3b8d1dffbef1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846231572731332050</li>
        <li>Upwork Job ID: 1846231572731332050</li>
        <li>Last Price Increase: 2024-10-15</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 104458668</li>
<li>nkdengineer | Contributor | 104458669</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by mjasikowski** [comment]
Account switcher component was changed in this PR: https://github.com/Expensify/App/pull/49051 - this is most likely the offender

**Comment by nkdengineer** [comment]
@mjasikowski In this PR, we discussed this and agreed it isn't a problem.

**Comment by mjasikowski** [comment]
@Expensify/design can you weigh in here and let us know if this is OK or expected?

**Comment by nkdengineer** [comment]
Currently, this is the behavior of other `PopoverMenu` components.

https://github.com/user-attachments/assets/8d3296ed-6a69-4d01-8bfb-7250105cf000

**Comment by shawnborton** [comment]
Interesting, I think I would expect the keyboard navigation to use the same background color as hover. So this way we save the selected color for when a row is truly selected/checked, and we just reuse a background hover highlight for keyboard nav. Thoughts on something like that?

**Comment by s77rt** [comment]
We were aware of this during PR review and the bug is not new, it's an existing bug in `PopoverMenu` which we switched to. This should be fixed to match the behaviour on the `SelectionList`. This does not need to be a deploy blocker though 


https://github.com/user-attachments/assets/57bc5f1c-af58-4b68-8051-3e68a17ddbcf


https://github.com/user-attachments/assets/35cf085f-4ce3-4667-ae97-40553c88623f

**Comment by mjasikowski** [comment]
OK, removing the deployblocker tag for now and switching this to weekly

**Comment by s77rt** [comment]
Does that mean we'd have to change the behaviour on other lists i.e. the ones that use `SelelctionList`. On such lists the keyboard navigation clears the background from the checked item and moves it to the selected one. Check the example above on language selector page.

**Comment by dannymcclain** [comment]
Personally I think we should. IMO selected items should _always_ have a background and the hover color makes more sense for keyboard navigating. Just because something is focused with the keyboard doesn't mean it's selected, so I think keyboard navigating is more similar to hovering with a mouse cursor than it is having the item selected. `:my_two_cents:`

**Comment by shawnborton** [comment]
Yup, I agree with Danny here

**Comment by s77rt** [comment]
Got it 👍

**Comment by s77rt** [comment]
@greg-schroeder Let's make this `External`

**Comment by s77rt** [comment]
@jjcoffee I can take this over as C+ if you want

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Both the current account and the selected account are highlighted when navigating via keyboard.

### What is the root cause of that problem?
When an item is focused, the background color is calculated by `getButtonBackgroundColorStyle` function here

https://github.com/Expensify/App/blob/4f1224cf21f3fa0aeb816b29eeb75d0935e5f035/src/components/MenuItem.tsx#L586-L588

In `PopoverMenu` we passed the background color as the focused background color above
https://github.com/Expensify/App/blob/4f1224cf21f3fa0aeb816b29eeb75d0935e5f035/src/components/PopoverMenu.tsx#L322

So the selected item and the focused item by keyboard has the same background color
### What changes do you think we should make in order to solve the problem?
We can pass `wrapperStyle` with `backgroundColor ` color as a hover background color if the keyboard focuses on an item and it's not a selected item to override the default focused background color. We can do something like this and remove the `style` prop here

```
wrapperStyle={{backgroundColor: item.isSelected ? theme.activeComponentBG : focusedIndex === menuIndex ? theme.hoverComponentBG : undefined}}
```
https://github.com/Expensify/App/blob/4f1224cf21f3fa0aeb816b29eeb75d0935e5f035/src/components/PopoverMenu.tsx#L322

Or if we don't want to remove `style` prop we can do something like this

```
wrapperStyle={{backgroundColor: !item.isSelected && focusedIndex === menuIndex ? theme.hoverComponentBG : undefined}}
```
### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/user-attachments/assets/813a4472-d72a-4698-ac88-4417ae731dd8

**Comment by nkdengineer** [comment]
@shawnborton Is the resulting video in my proposal the expected behavior we want?

**Comment by s77rt** [comment]
@nkdengineer Let's fix the inconsistency with the other lists too e.g. `SelectionList`

**Comment by nkdengineer** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/50779#issuecomment-2414704920) to include the other places.

**Comment by dannymcclain** [comment]
>@shawnborton Is the resulting video in my proposal the expected behavior we want?

That looks correct to me.

**Comment by shawnborton** [comment]
Yup agree with Danny, that looks like what I had in mind.

**Comment by jjcoffee** [comment]
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/50779#issuecomment-2414704920) LGTM! I'm a little unsure about blanket-changing this in other areas (the `PopoverMenu` seems much more clearly an issue).

For `AutocompleteSuggestion`, for example, it feels natural that you can navigate with the keyboard arrows to change the "selected" suggestion whilst we still have the hover effect for the mouse interaction. I don't think this should change.

https://github.com/user-attachments/assets/dbc73aaa-ba8a-4fa7-aae9-4545a91716c1

I'm unsure about changing how this works in search too, as this feels pretty natural that there's a distinct hover effect from the mouse, and then the keyboard navigation is changing the "selected" item (i.e. that will be chosen on pressing enter).

https://github.com/user-attachments/assets/285e868a-c22c-4327-84da-a1f7a23128d0

I wonder if we should focus on fixing the most obvious problem with `PopoverMenu` first so we don't change too much at once?

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment]
@s77rt Sorry I have literally zero work at the moment, so I can't really pass on this one :sweat_smile:

**Comment by greg-schroeder** [comment]
Does anyone have thoughts on which project board this live under?

**Comment by dubielzyk-expensify** [comment]
> I don't really see a difference between hovering with your cursor and navigating through the choices with your keyboard

Agree. Same intent, different input device.

**Comment by jjcoffee** [comment]
Great, thanks for confirming the expected behaviour all. Just waiting for @mjasikowski to assign @nkdengineer then!

**Comment by greg-schroeder** [comment]
PR review continues

**Comment by nkdengineer** [comment]
@jjcoffee I created another PR [here](https://github.com/Expensify/App/pull/51937).

**Comment by greg-schroeder** [comment]
Payment date is 11/18 to account for deploy blocker fix

**Comment by greg-schroeder** [comment]
Timeline:

- Original [PR](https://github.com/Expensify/App/pull/51158) (Author: @nkdengineer, Reviewer: @jjcoffee) deployed to staging 2024-10-31
- Reverted 2024-11-04 after several regressions arose
- New [PR](https://github.com/Expensify/App/pull/51937) (Author: @nkdengineer, Reviewer: @jjcoffee) deployed to staging 2024-11-04, deployed to prod 2024-11-05
- Another regression occurred, prompting a [new PR](https://github.com/Expensify/App/pull/51988) (Author: @luacmartins, Reviewer: @jjcoffee) deployed to prod 2024-11-11
- More regressions leading to this [PR](https://github.com/Expensify/App/pull/52273) deployed 2024-11-11

So, it seems to me that this led to two distinct regression periods.

**Comment by greg-schroeder** [comment]
@mjasikowski @luacmartins Do you agree with the above that there were two regression periods here?

Original payment $250 -> $125 -> $62.50 per the payment guidelines (50% reduction per regression)

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @nkdengineer - $62.50 - Upwork
C+: @jjcoffee - $62.50 - Upwork

**Comment by mjasikowski** [comment]
@greg-schroeder agreed on regressions

**Comment by greg-schroeder** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by jjcoffee** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [x] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- Have an account with a copilot.

### Test:


1. Log in as a copilot.
2. Go to Account settings.
3. Click on the account switcher.
4. Navigate through the account list via keyboard arrows.
5. Verify that: The current account and the selected account are both highlighted but with different background colours.
6. Do the same with workspace switcher, emoji suggestion, emoji picker

Do we agree 👍 or 👎

**Comment by greg-schroeder** [comment]
Thanks! Filed regression test
