### ISSUE TITLE
iOS/Android - Hybrid app - "Submit it to someone" option is still shown after tracking expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50920]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50331
**Email or phone of affected tester (no customers):** iheretsutest+1610_1230@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expenisfy Hybrid app
2. Sign into a valid account and access the ND features within the app
3. Go to self DM.
4. Click + > Track expense > Distance > Complete the flow

## Expected Result:
The actionable whisper of the expense created in (2) has no `Submit it to someone` option/button (unless you enable P2P Beta)

## Actual Result:
`Submit to someone` option is still shown

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Screenshot_20241016-184557](https://github.com/user-attachments/assets/2641ff20-4128-48db-941f-cdaddf17da5b)
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment]
@IuliiaHerets I can repro this but .49-2 was deployed only 7 hrs ago:

![image](https://github.com/user-attachments/assets/cfff3fa6-c806-4aeb-a29d-2337b7b0183e)

I'm only on .48 for Hybrid, so can you retest in a few days with the new version?

**Comment by jliexpensify** [comment]
Ok I'm on v50 and can still repro.

@MariaHCD @abdulrahuman5196 adding you here as you worked on the PR.

**Comment by MariaHCD** [comment]
Hmm, weird. The HybridApp version is always be in-sync with App version so it's weird that the issue is fixed on ND but not on HybridApp.

Just to double check - @jliexpensify were you testing with an account that is not on the P2P beta?

**Comment by jliexpensify** [comment]
Hmm are our standard expensify accounts on the beta? That's what I tested on.

**Comment by jliexpensify** [comment]
So just to confirm...this is still an issue/bug right?

**Comment by MariaHCD** [comment]
It's not a bug if the account is on the P2P distance requests beta. If this is happening on accounts that are _not_ on the beta, then it would be a bug.

Can we retest on an account that is not on the beta?

**Comment by jliexpensify** [comment]
Thanks for clariofying @MariaHCD - I tested on a personal account on Hybrid and it's all good:

![Screenshot_20241021-183653](https://github.com/user-attachments/assets/fb96ddd3-2c8b-4669-968b-961294494cea)

Closing this then!
