### ISSUE TITLE
[Waiting on Checklist] [$125] [Dev] Console Warning: No native ExponentConstants module found

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51054]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** DEV
**Reproducible in production?:** DEV
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @eVoloshchak 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729174865370699

## Action Performed:
1. Launch the iOS app
2. Observe the warning

## Expected Result:
No warning is displayed

## Actual Result:
Warning is displayed

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
![Simulator Screenshot - iPhone 15 Pro - 2024-10-17 at 16 17 56](https://github.com/user-attachments/assets/2e076611-8c45-408f-ac83-fa1e228efc92)

https://github.com/user-attachments/assets/82efbce0-52e7-44dc-9c30-25a1ba3902e8

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849240595196131510</li>
        <li>Upwork Job ID: 1849240595196131510</li>
        <li>Last Price Increase: 2024-10-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by MelvinBot** [comment]
This has been labelled "Needs Reproduction". Follow the steps here: https://stackoverflowteams.com/c/expensify/questions/16989

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A "No native ExponentConstants module found" warning is shown.

### What is the root cause of that problem?
We don't link the expo-const module, so it's not found.
https://github.com/Expensify/App/blob/c3d33fcec7df3fcbb31cdfcb61951ce985da63c7/package.json#L354-L357

expo-const is being used in expo-asset module and it's found in PlatformUtils file. However, all the properties that is being used inside the file doesn't exist even if we installed the expo-const.
https://github.com/expo/expo/blob/d576550145ede25dec3f6636bf260f7b05bec7a6/packages/expo-asset/src/PlatformUtils.ts#L32-L39

So, it's no different whether we include expo-const module or not. Here is the available properites from expo-const.
```
{"addListener": [Function addListener], "debugMode": true, "deviceName": "iPhone 15 Plus", "emit": [Function emit], "executionEnvironment": "bare", "getWebViewUserAgentAsync": [Function getWebViewUserAgentAsync], "isHeadless": false, "listenerCount": [Function listenerCount], "manifest": {"description": "New Expensify is the next generation of Expensify: a reimagination of payments based atop a foundation of chat.", "name": "new.expensify", "platforms": ["ios", "android", "web"], "sdkVersion": "51.0.0", "slug": "new.expensify", "version": "9.0.50-7"}, "platform": {"ios": {"buildNumber": "9.0.50.7"}}, "removeAllListeners": [Function removeAllListeners], "removeListener": [Function removeListener], "removeSubscription": [Function removeSubscription], "sessionId": "715902EE-F726-43EA-B204-6797A7E27318", "statusBarHeight": 54, "systemFonts": [listOfFontsTooLong]}
```

### What changes do you think we should make in order to solve the problem?

We can suppress the warning. One way to do it is by suppressing it here.
https://github.com/Expensify/App/blob/c3d33fcec7df3fcbb31cdfcb61951ce985da63c7/src/App.tsx#L48-L53
```
'No native ExponentConstants module found',
```

OR

We can link the expo-const by remove it from the auto-link exclude list.
https://github.com/Expensify/App/blob/c3d33fcec7df3fcbb31cdfcb61951ce985da63c7/package.json#L354-L357

**Comment by twisterdotcom** [comment]
Seems straightforward right? I haven't recreated this, so will lean on C+ too for this dev specific issue.

**Comment by twisterdotcom** [comment]
Downgrading as this isn't customer facing.

**Comment by mollfpr** [comment]
I'm assuming we exclude the `expo-constants` to reduce the binary size. I think we can suppress the warning like it [proposed](https://github.com/Expensify/App/issues/51054#issuecomment-2421412479) from @bernhardoj.

🎀 👀 🎀 C+ reviewed!

**Comment by blimpich** [comment]
Proposal seems good, but question: why is this only getting reported and fixed now? [The PR that added that code](https://github.com/Expensify/App/pull/30905) was merged 10 months ago. Did we just live with warning until @eVoloshchak decided to report it?

**Comment by bernhardoj** [comment]
PR is ready
cc: @mollfpr 

> Did we just live with warning until @eVoloshchak decided to report it?

I think yes. There has been so much warning on the app that I think people keep ignoring them 😅

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by twisterdotcom** [comment]
It is done Melv. Just waiting on @mollfpr to do the checklist, although... looking again, I don't think we need one just for this console error. Going to close.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
Payment summary is updated and so is my approval amount.

**Comment by mollfpr** [comment]
Sorry for the delay! Yes, we don't need the checklist here.

**Comment by garrettmknight** [comment]
$125 approved for @mollfpr
