### ISSUE TITLE
[Awaiting checklist] [$250] Workspace - Invited members can open import members page by navigating to ../members/import

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51129]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User is invited to a workspace.

1. Go to staging.new.expensify.com
2. Go to workspace settings of the invited workspace.
3. Go to Members.
4. Add /import to the end of URL and navigate to it.

## Expected Result:
Not here page will show up.

## Actual Result:
Import member modal shows up.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b97cc1e6-9f45-4c78-8ec4-03abea418473

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849229257554464797</li>
        <li>Upwork Job ID: 1849229257554464797</li>
        <li>Last Price Increase: 2024-11-06</li>
<li>Automatic offers: </li>
<ul>
<li>BhuvaneshPatil | Contributor | 104773620</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by IuliiaHerets** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Invited members can open import members page by navigating to ../members/import

### What is the root cause of that problem?
We are not wrapping this component
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/pages/workspace/members/ImportMembersPage.tsx#L10-L19

with `AccessOrNotFoundWrapper` component. This allows users to view page with URL.

### What changes do you think we should make in order to solve the problem?
We shall wrap the component `ImportMembersPage` with  `AccessOrNotFoundWrapper`  Like we have done here -

https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/pages/workspace/WorkspaceInvitePage.tsx#L310-L314

This way we ensure only people who can invite can import members.

If business needs are other then we can change the `accessVariants` prop to manage role based permissions.

### What alternative solutions did you explore? (Optional)

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
invited workspace members can import members spreadsheet using url manipulation
### What is the root cause of that problem?
we did not protect this page : **ImportMembersPage**
### What changes do you think we should make in order to solve the problem?

in the ImportMembersPage page
add this: 
```
return (
        <FullPageNotFoundView shouldShow={!isPolicyAdmin}>
        <ImportSpreedsheet
            backTo={ROUTES.WORKSPACE_MEMBERS.getRoute(policyID)}
            goTo={ROUTES.WORKSPACE_MEMBERS_IMPORTED.getRoute(policyID)}
        />
        </FullPageNotFoundView>
    );
```

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invited members can open import members page using deeplink.

### What is the root cause of that problem?
Invite members page is not wrapped with `AccessOrNotFoundWrapper`.
Additionally `importedMembers` page is also accessible using deeplink ( 'settings/workspaces/:policyID/members/imported')
Similar could be observed for `ImportTagsPage`, 'ImportedTagsPage`, `ImportCategoriesPage` and `ImportedCategoriesPage`

### What changes do you think we should make in order to solve the problem?
Wrap all of the following pages with `AccessOrNotFoundWrapper`.
[ImportMembersPage](https://github.com/Expensify/App/blob/73cbbd2e259f18631e1efc5bb12f16b399b2a42f/src/pages/workspace/members/ImportMembersPage.tsx)
[ImportedMembersPage](https://github.com/Expensify/App/blob/73cbbd2e259f18631e1efc5bb12f16b399b2a42f/src/pages/workspace/members/ImportedMembersPage.tsx)
[ImportCategoriesPage](https://github.com/Expensify/App/blob/73cbbd2e259f18631e1efc5bb12f16b399b2a42f/src/pages/workspace/categories/ImportCategoriesPage.tsx)
[ImportedCategoriesPage](https://github.com/Expensify/App/blob/73cbbd2e259f18631e1efc5bb12f16b399b2a42f/src/pages/workspace/categories/ImportedCategoriesPage.tsx)
[ImportTagsPage](https://github.com/Expensify/App/blob/73cbbd2e259f18631e1efc5bb12f16b399b2a42f/src/pages/workspace/tags/ImportTagsPage.tsx)
[ImportedTagsPage](https://github.com/Expensify/App/blob/73cbbd2e259f18631e1efc5bb12f16b399b2a42f/src/pages/workspace/tags/ImportedTagsPage.tsx)

### What alternative solutions did you explore? (Optional)
Alternatively [ImportSpreadsheet](https://github.com/Expensify/App/blob/73cbbd2e259f18631e1efc5bb12f16b399b2a42f/src/components/ImportSpreadsheet.tsx) could be wrapped with `AccessOrNotFoundWrapper` along with [ImportedMembersPage](https://github.com/Expensify/App/blob/73cbbd2e259f18631e1efc5bb12f16b399b2a42f/src/pages/workspace/members/ImportedMembersPage.tsx), [ImportedCategoriesPage](https://github.com/Expensify/App/blob/73cbbd2e259f18631e1efc5bb12f16b399b2a42f/src/pages/workspace/categories/ImportedCategoriesPage.tsx) and [ImportedTagsPage](https://github.com/Expensify/App/blob/73cbbd2e259f18631e1efc5bb12f16b399b2a42f/src/pages/workspace/tags/ImportedTagsPage.tsx)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Pujan92** [comment]
@BhuvaneshPatil's [proposal](https://github.com/Expensify/App/issues/51129#issuecomment-2424103768) looks good to me which suggested wrapping `ImportMembersPage` and other required pages with `AccessOrNotFoundWrapper`.

🎀👀🎀 C+ reviewed

**Comment by BhuvaneshPatil** [comment]
@deetergp 👀

**Comment by twisterdotcom** [comment]
@deetergp we need you to review and assign please.

**Comment by deetergp** [comment]
Apologies for the late assignment, I just got back from being OOO.

**Comment by twisterdotcom** [comment]
How we doing @BhuvaneshPatil now?

**Comment by ChavdaSachin** [comment]
By any chance if current assignee is unable to complete the assignment and internals decide to reassign, I could take it over and raise a quick PR.
My [proposal](https://github.com/Expensify/App/issues/51129#issuecomment-2425269438) is essentially the mostly matching with currently selected proposal, and contains additional pages we need to cover.

**Comment by BhuvaneshPatil** [comment]
I will be raising the PR tonight. Thank you for your patience

**Comment by twisterdotcom** [comment]
Payment Summary:

- @Pujan92 paid $250 via NewDot Manual Request
- @BhuvaneshPatil paid $250 [here](https://www.upwork.com/nx/wm/offer/104773620) (Contributor)

**Comment by Pujan92** [comment]
# BugZero Checklist:

- [X] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [X] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [X] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [X] 3d. QA
  - [ ] 3z. Other:

</details>

- [X] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/48876/files#r1869197328

- [X] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [X] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal

1. Try to access link https://staging.new.expensify.com/settings/workspaces/{workspaceId}/members/import in the URL directly by replacing the workspaceId where you are a member and not an owner
2. Verify the no access page will be shown 

Do we agree 👍 or 👎

**Comment by garrettmknight** [comment]
$250 approved for @Pujan92
