### ISSUE TITLE
[HOLD for payment 2024-11-18] [$250] iOS - App crashes when opening attachments in #expensify-roadmap public room

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51181]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app and log in
2. Send the link to the #expensify-roadmap public room https://staging.new.expensify.com/r/868417741568295 in any chat
3. Open the link
4. Scroll up and open any attachment

## Expected Result:
The attachment is opened

## Actual Result:
The app crashes. Sometimes attachments open, but the app crashes when swiping to another attachment.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[Bug6641063_1729518281267!ios.txt](https://github.com/user-attachments/files/17462274/Bug6641063_1729518281267.ios.txt)

https://github.com/user-attachments/assets/d38425c0-d3d7-427d-9ebe-a737b0867499

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849220985376407970</li>
        <li>Upwork Job ID: 1849220985376407970</li>
        <li>Last Price Increase: 2024-10-23</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 104573284</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by IuliiaHerets** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by JKobrynski** [comment]
The [PR](https://github.com/Expensify/App/pull/51783) is ready for review!

**Comment by puneetlath** [comment]
@shubham1206agra friendly reminder about the checklist.

**Comment by puneetlath** [comment]
Looks like the original offer expired. @shubham1206agra please ping me here when you've accepted this one: https://www.upwork.com/nx/wm/offer/105192072

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
