### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] [Search v2.5] - Unable to perform search by hitting Enter on search bar when expense is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51427]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search
3. Click Filters
4. Apply any filter that will return results
5. Select an expense via checkbox
6. Click on the search input field
7. Type anything and hit Enter

## Expected Result:
App will perform a new search

## Actual Result:
The dropdown button is expanded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/cab1eefa-0d9f-46a0-bb50-052c2c62e1f4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854660565820716226</li>
        <li>Upwork Job ID: 1854660565820716226</li>
        <li>Last Price Increase: 2024-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104870980</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Unable to perform search by hitting Enter on search bar when expense is selected

### What is the root cause of that problem?
We have set `pressOnEnter` on the drop down button and in side the button we already have a code that disable the shortcut based on the active element role but it only disables it if the active element is presentation, which is correct
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/Button/index.tsx#L163
but we set our text inputs role as presentation
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/Search/SearchRouter/SearchRouterInput.tsx#L99
### What changes do you think we should make in order to solve the problem?

I propose two options 
1. We should give the text input a proper role like `textbox`
We need to add the role [here](https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/CONST.ts#L4216)  
```
        TEXTBOX: 'textbox',

```
2. Along with active role element management we can keep track if a text input is focused. Here
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/ActiveElementRoleProvider/index.tsx#L9-L11 
```
const [isTextInputFocused, setIsTextInputFocused] = useState<boolean | null>(null);
    const handleFocusIn = () => {
        setRole(document?.activeElement?.role ?? null);
        setIsTextInputFocused(['INPUT', 'TEXTAREA'].includes(document.activeElement?.nodeName ?? ''));
    };

....


    const value = React.useMemo(
        () => ({
            role: activeRoleRef,
            isTextInputFocused,
        }),
        [activeRoleRef, isTextInputFocused],
```
then 
```
const useIsTextInputFocused = () => {
    const {isTextInputFocused} = useContext(ActiveElementRoleContext);
    return isTextInputFocused;
};
```
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/Button/index.tsx#L163
```
const isTextInputFocused = useIsTextInputFocused();
    const shouldDisableEnterShortcut = useMemo(
        () => isTextInputFocused || (accessibilityRoles.includes(activeElementRole ?? '') && activeElementRole !== CONST.ROLE.PRESENTATION),
        [activeElementRole, isTextInputFocused],
    );
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Unable to perform search by hitting Enter on search bar when expense is selected

### What is the root cause of that problem?
We have set `pressOnEnter` on the drop down button and in side the button we already have a code that disable the shortcut based on the active element role but it only disables it if the active element is presentation, which is correct
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/Button/index.tsx#L163
but we set our text inputs role as presentation
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/Search/SearchRouter/SearchRouterInput.tsx#L99
### What changes do you think we should make in order to solve the problem?

I propose two options 
1. We can give the text input a proper role like `textbox`
We will need to add the role [here](https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/CONST.ts#L4216)  
```
        TEXTBOX: 'textbox',

```
2. Along with active role element management we can keep track of whether a text input is focused. Here
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/ActiveElementRoleProvider/index.tsx#L9-L11 
```
const [isTextInputFocused, setIsTextInputFocused] = useState<boolean | null>(null);
    const handleFocusIn = () => {
        setRole(document?.activeElement?.role ?? null);
        setIsTextInputFocused(['INPUT', 'TEXTAREA'].includes(document.activeElement?.nodeName ?? ''));
    };

....


    const value = React.useMemo(
        () => ({
            role: activeRoleRef,
            isTextInputFocused,
        }),
        [activeRoleRef, isTextInputFocused],
```
then 
```
const useIsTextInputFocused = () => {
    const {isTextInputFocused} = useContext(ActiveElementRoleContext);
    return isTextInputFocused;
};
```
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/Button/index.tsx#L163
```
const isTextInputFocused = useIsTextInputFocused();
    const shouldDisableEnterShortcut = useMemo(
        () => isTextInputFocused || (accessibilityRoles.includes(activeElementRole ?? '') && activeElementRole !== CONST.ROLE.PRESENTATION),
        [activeElementRole, isTextInputFocused],
    );
```
### What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment]
I don't think it's very clear how this should behave. You are changing the filter criteria, but there is a selected expense. Should the filter results update? What if the selected expense no longer matches the criteria? cc @luacmartins @trjExpensify @JmillsExpensify

**Comment by luacmartins** [comment]
I imagine we'd just clear the selection and perform the new Search. cc @JmillsExpensify for your input as well.

**Comment by eh2077** [comment]
Reviewing proposals

**Comment by eh2077** [comment]
> We can remove the pressOnEnter prop.

@Krishna2323 Thanks for your proposal. Is there any drawback if just remove `pressOnEnter`?

**Comment by anmurali** [comment]
Rotating to get another BZ assigned while OOO

**Comment by eh2077** [comment]
Thanks for your proposals!

I think we can go with @Krishna2323 's [proposal](https://github.com/Expensify/App/issues/51427#issuecomment-2436009378) - just remove the `pressOnEnter` prop to fix the issue.

🎀👀🎀 C+ reviewed

**Comment by greg-schroeder** [comment]
This one is kind of weird ... I _think_ it falls under #expense? But I'm not sure about the platform 😅

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @Krishna2323 - $250 - Upwork
C+: @eh2077 - $250 - Paid via NewDot manual request

---

Next up @eh2077 can you complete [the checklist](https://github.com/Expensify/App/issues/51427#issuecomment-2478998183)? Thank you!

**Comment by eh2077** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by eh2077** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by luacmartins** [comment]
We're adding tests as part of the project wrap up, so no need to do that now,

**Comment by greg-schroeder** [comment]
Okay, thanks @luacmartins

**Comment by eh2077** [comment]
Requested payment in NewDot
