### ISSUE TITLE
[Tracking] Add a private domain email check to the new user onboarding flow 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#51496]
## [DESIGN DOC](https://docs.google.com/document/d/1JlM9G3jZpaHDlcILWL9170ancMLtOnI2a73dQgX6ENo/edit?tab=t.0)

___

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @MitchExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C07HPDRELLD/p1729809438307289
**Figma file:** https://www.figma.com/design/ir27daDKHaB1g4iZCT22K5/Onboarding-v2?node-id=7690-61846&t=VUO5F3YHDzF2O7Sw-1
**Pre-design 1:** https://expensify.slack.com/archives/C07HPDRELLD/p1730909567485999
**Pre-design 1 summary:** https://expensify.slack.com/archives/C07HPDRELLD/p1731000105159589
**Design Doc:** https://docs.google.com/document/d/1JlM9G3jZpaHDlcILWL9170ancMLtOnI2a73dQgX6ENo/edit?tab=t.0

##  Problem

Our product works a bit better when a user signs up with a private email address because we can more reliably get their First/Last name, better name auto created workspaces, etc. Further, our sales processes are enhanced when we know the domain of a user so we can target high-profile leads. Yet, the majority of our users sign up with public emails and/or phone numbers making it harder to catch edge cases where they accidentally create a new account when they should have added a secondary login to an existing account.

## Solution

1. Users sign in to New Expensify for the first time using a phone or public domain email address

2. We will add a step immediately after signing in to the onboarding flow asking if they have a work email address.
- This email field will only accept private domain entries, otherwise, it will throw an error: "Please use a valid work email from a private domain"

3. If they enter a work email and choose to "Log in with my work email" we merge the accounts, making the work email their primary login
- If the work email is tied to an existing account, we send a magic code and add a  step to verify it so that we know they own it before merging.

4. Once merged, users continue on their onboarding path or get redirected to Classic
- If the work email is on any policy that is not `isPolicyExpenseChatEnabled=true`, or is `tryNewDot.classicRedirect.dismissed=true`, or has no `tryNewDot` NVP they are routed to Classic. Everyone else goes to the next NewDot onboarding step (Intent) 

**Work email check step**:
![image](https://github.com/user-attachments/assets/dac0ddd1-c3d7-4cae-adb7-4d83442ac8e3)

**Magic code step for existing accounts**:
![image](https://github.com/user-attachments/assets/5c3c7316-3d2f-44e6-8638-b01e1022e972)

## Tasks

- [x] Post **Proposal (full Problem/Solution statement)** in ~~`#expensify-open-source`~~ '#convert`: https://expensify.slack.com/archives/C07HPDRELLD/p1730909567485999
- [x] Wait at least one full business day, and until the post has a majority (2/3) of positive reactions (👍)
- [x] Paste Proposal in the space above with a link to the Slack thread
- [ ] ~~Email `strategy@expensify.com` and paste in the Proposal~~ This is not a What's Next proposal but we're using the Design Doc template to make sure its done right
- [ ] Fill out the **High-level overview of the problem**, **Timeline**, and **Terminology** sections of the Design Doc
- [ ] ~~Email `strategy@expensify.com` (continue the same email chain as before) with the link to your Design Doc~~ This is not a What's Next proposal but we're using the Design Doc template to make sure its done right
- [x] Host a **pre-design** meeting ([example](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794669539419)) in `#expensify-open-source` to discuss any necessary details in public before filling out the **High-level of proposed solution** section: https://expensify.slack.com/archives/C07HPDRELLD/p1730909567485999
- [x] Fill out the **High-level of proposed solution** section
- [ ] ~~Email `stategy@expensify.com` again with links to the doc and pre-design conversation in Slack~~ This is not a What's Next proposal but we're using the Design Doc template to make sure its done right
- [x] Add the `DesignDocReview` label to get the **High-level of proposed solution** section reviewed
- [x] Respond to any questions or concerns and bring up blockers in Slack to get a consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Host another pre-design meeting in `#expensify-open-source` to ask for engineering feedback on the technical solution.
- [x] Fill out the **Detailed implementation of the solution** and related sections.
- [x] Re-add the `DesignDocReview` label to this issue
- [x] Respond to any questions or concerns and bring up blockers in Slack to get consensus if necessary
- [x] Confirm that the doc has the minimum necessary number of reviews before proceeding
- [x] Email `strategy@expensify.com` one last time to let them know the Design Doc is moving into the implementation phase
- [ ] Implement the changes
- [ ] Add regression tests so that QA can test your feature with every deploy ([instructions](https://stackoverflowteams.com/c/expensify/questions/363))
- [ ] Send out a follow up email to `strategy@expensify.com` once everything has been implemented and do a **Project Wrap-Up** retrospective that provides:
    - Summary of what we accomplished with this project
    - What went well?
    - What could we have done better?
    - What did we learn?

**Comment by anmurali** [comment]
Do we want to add this in the Stage 1 flow? @MitchExpensify

**Comment by MitchExpensify** [comment]
That's the idea @anmurali, do you think it makes sense to add for everyone signing up before the "what would you like to do today?" options or after a choice on that screen and only for certain options? 

<img width="606" alt="image" src="https://github.com/user-attachments/assets/03ffe783-1ab7-4624-b07b-4fe9d9621d7a">

I think track, manage, and get paid back all indicate a higher chance the user should have logged in using their work email so I'd lean to the latter (Adding the check after the welcome message only for certain choices)

**Comment by anmurali** [comment]
So long as it is optional, I would try it across the board and if conversion through the stage 1 funnel falls, we can do something else.

**Comment by shawnborton** [comment]
Posted some ideas to Slack [here](https://expensify.slack.com/archives/C07HPDRELLD/p1730279381387299?thread_ts=1730161354.770299&cid=C07HPDRELLD), working from this Figma file [here](https://www.figma.com/design/ir27daDKHaB1g4iZCT22K5/Onboarding-v2?node-id=7690-61846&t=VUO5F3YHDzF2O7Sw-1)

**Comment by MitchExpensify** [comment]
Pre-design here https://expensify.slack.com/archives/C07HPDRELLD/p1730909567485999

**Comment by MitchExpensify** [comment]
Pre-Design summarized - https://expensify.slack.com/archives/C07HPDRELLD/p1731000105159589

Will update this issue as a next step

**Comment by shawnborton** [comment]
Not overdue, I think we're all good from a mockup standpoint at least.

**Comment by MitchExpensify** [comment]
I'm gonna get this into a Design Doc as a next step to make sure we don't miss anything and get good visibility on the plan

**Comment by MitchExpensify** [comment]
Design doc is coming along here: https://docs.google.com/document/d/1JlM9G3jZpaHDlcILWL9170ancMLtOnI2a73dQgX6ENo/edit?tab=t.0

I need to confirm:

1. What the plan for secondary logins in NewDot is for the resource management section
2. Get @blimpich 's help completing the data storage section

Then send it out for review

**Comment by blimpich** [comment]
Raised some questions about edge cases and starting a conversation with what to do about them [here](https://expensify.slack.com/archives/C07HPDRELLD/p1731456900542699).

**Comment by MitchExpensify** [comment]
I might need a little help from you here, @shawnborton. What do you think the generic merging error screen should look like? https://www.figma.com/design/ir27daDKHaB1g4iZCT22K5/Onboarding-v2?node-id=8053-5297&node-type=frame&t=Rio4Ccv3iyJ9Izr9-0

![image](https://github.com/user-attachments/assets/ccb2f541-6459-4b93-af49-6055ebc661d5)

**Comment by shawnborton** [comment]
Why does that error happen? To confirm, it would happen after the user enters their magic code?

One idea is to just add the error right on that screen, which feels more in line with the rest of the app:
![image](https://github.com/user-attachments/assets/69ee9084-3c1a-4a3f-8fee-6ca523d15a1b)


The other idea is something like you have, just a different illustration and a line break:
![image](https://github.com/user-attachments/assets/73487dc4-91f1-436a-b52e-9d8c12b04080)

**Comment by shawnborton** [comment]
cc @Expensify/design for thoughts on this one too.

**Comment by shawnborton** [comment]
Cool cool, I can get down with that!

**Comment by blimpich** [comment]
Finished writing the [Data Storage and API Changes section](https://docs.google.com/document/d/1JlM9G3jZpaHDlcILWL9170ancMLtOnI2a73dQgX6ENo/edit?tab=t.0#heading=h.o0ogvdg2aixu) of the high-level. Spent a lot of time today thinking about the implementation and how it could exactly work. Need to confirm a few assumptions but I think we can start getting reviews on the HL next week.

**Comment by dubielzyk-expensify** [comment]
I like what you've done here Shawn. Initially I was thinknig we should have a try again, but I think it's better to just keep going and tell them where to retry like you've done

**Comment by MitchExpensify** [comment]
Updated to the new illustration, thank you both for the input!

**Comment by MitchExpensify** [comment]
Doc here ready for review https://docs.google.com/document/d/1JlM9G3jZpaHDlcILWL9170ancMLtOnI2a73dQgX6ENo/edit?tab=t.0

**Comment by blimpich** [comment]
@allgandalf Thank you! We're still working through the high-level, and I've mostly been focusing on what backend changes will be needed for this, but I think hiring a C+ for the frontend design/implementation would be a good idea. Need to do a few things first though, I'll get back to you about what we might need 🙂👍

**Comment by trentpetty** [comment]
I have read and reviewed this Design Doc!

**Comment by jamesdeanexpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by greg-schroeder** [comment]
I have read and reviewed this Design Doc!

**Comment by alexpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by thienlnam** [comment]
I have read and reviewed this Design Doc!

**Comment by davidcardoza** [comment]
I have read and reviewed this Design Doc!

**Comment by danielrvidal** [comment]
I have read and reviewed this Design Doc!

**Comment by pecanoro** [comment]
I have read and reviewed this Design Doc!

**Comment by MitchExpensify** [comment]
Comment resolution and slack discussion happening https://expensify.slack.com/archives/C07HPDRELLD/p1732315417627669?thread_ts=1732140230.737009&cid=C07HPDRELLD

**Comment by quinthar** [comment]
I have read and reviewed this Design Doc!

**Comment by blimpich** [comment]
Not overdue, resolving last few discussions on high-level, hired C+ for the frontend detailed portion, and getting ready to write detailed design once last few discussions are resolved.

**Comment by nkuoch** [comment]
I have read and reviewed this Design Doc!

**Comment by MitchExpensify** [comment]
Detailed is being written, aiming to get it out next week

**Comment by blimpich** [comment]
Detailed is done. Lets get this reviewed!

**Comment by trentpetty** [comment]
I have read and reviewed this Design Doc!

**Comment by blimpich** [comment]
Discussing some implementation details around logging into the work account on [this Slack thread](https://expensify.slack.com/archives/C03TQ48KC/p1733348605460889).

**Comment by nkuoch** [comment]
I have read and reviewed this Design Doc!

**Comment by danielrvidal** [comment]
I have read and reviewed this Design Doc!

**Comment by pecanoro** [comment]
I have read and reviewed this Design Doc!

**Comment by thienlnam** [comment]
I have read and reviewed this Design Doc!

**Comment by MitchExpensify** [comment]
Latest: [Almost ready to start implementing](https://expensify.slack.com/archives/C07HPDRELLD/p1733789956398259)

**Comment by JmillsExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by blimpich** [comment]
We have the necessary reviews to move to the implementation phase. Created a [project board here](https://github.com/orgs/Expensify/projects/161/views/5?filterQuery=title%3A%22*%5BPrivate+Domain+Onboarding+Check%5D*%22+). Have to head out but will create all the GH issues tomorrow morning.

**Comment by blimpich** [comment]
Not overdue, marking as weekly because now we're in implementation phase and updates aren't as juicy, mostly just incremental progress on PRs. Work is being done!

**Comment by MitchExpensify** [comment]
In implementation, check out the project board for an overview on progress https://github.com/orgs/Expensify/projects/161/views/5?filterQuery=title%3A%22*%5BPrivate+Domain+Onboarding+Check%5D*%22+

**Comment by blimpich** [comment]
Implementation is coming along well. All backend PRs are merged and in the process of being deployed. Should be on staging/prod soon. Frontend is under development and will be connected to the backend api once its deployed. [Steady as she goes](https://www.youtube.com/watch?v=DXAidGQUuns).

**Comment by blimpich** [comment]
Not overdue, we are making progress. C+ is working on frontend and communicating with me when they are encountering issues with the backend. Work is coming along.

**Comment by blimpich** [comment]
Same as last update, waiting on [frontend PR](https://github.com/Expensify/App/issues/54075). I think we're getting close.

**Comment by blimpich** [comment]
Latest update [here](https://github.com/Expensify/App/issues/54075#issuecomment-2635544922). Frontend PR is in the review process.

**Comment by blimpich** [comment]
### Update

Frontend is coming along, but [a few bugs that require a backend fix have cropped up](https://github.com/Expensify/App/issues/54075#issuecomment-2647690198). I have a [draft PR up](https://github.com/Expensify/Auth/pull/14150) to fix the issues but it isn't ready for review yet. I hope to have that in review and merged sometime next week, which means we're looking at probably late February for a deploy of this since we still need to finish the frontend review after fixing the backend, QA it in an Ad-hoc build, and then merged and deployed.

**Comment by blimpich** [comment]
### Update

Frontend is coming along, [backend PR is in review](https://github.com/Expensify/Auth/pull/14150). Backend took longer than expected so that pushes deploy date to probably the first week of February.

**Comment by blimpich** [comment]
### Update

Backend PR is merged and deployed! Took awhile because we didn't deploy Auth Thursday or Friday last week. @allgandalf is actively testing and finishing off the frontend, getting it ready for review. We're so close!!

**Comment by blimpich** [comment]
### Update

@allgandalf is working on completing the frontend PR [here](https://github.com/Expensify/App/issues/54075#issuecomment-2697105821). There seems to be one last thing to figure out, making sure that we don't get signed out after merging the accounts.

**Comment by blimpich** [comment]
Not overdue, we're working through this. Seems like we need one more backend update to make the frontend able to do what it's trying to do.

**Comment by blimpich** [comment]
Not overdue, we're close, frontend is moving along and is actively being reviewed [here](https://github.com/Expensify/App/pull/54186/files).

**Comment by blimpich** [comment]
### Update

We found another bug that requires a backend fix. I'm working on it. That will delay releasing this till next week though. Lots of edge cases with this feature since we're doing two tricky things at once: merging two accounts and then actively logging out of the old account and logging into the new account seamlessly without any visual hiccups or actions needed by the user.

**Comment by blimpich** [comment]
Waiting on backend fix to be deployed so that the frontend can use it. We don't deploy on Fridays so this has to wait till Monday.

**Comment by blimpich** [comment]
FE has been merged! Woot! Now we move on to QA, and if that goes well, deployment. There will probably be some follow up to fix some edge cases / bugs, but this is good news!

**Comment by blimpich** [comment]
### Update: 

Things are going well. FE was merged and deployed to staging. We hit [some deploy blockers](https://expensify.slack.com/archives/C01GTK53T8Q/p1744885869057899), but all have either been demoted or fixed. Things are looking good!

I've got a follow up [BE issue here](https://github.com/Expensify/App/issues/60303) that I have a PR up for. But after that is done we are just waiting to see the FE PR hit production on Monday, and fixing any issues that arise there. Very happy here! 😄

**Comment by blimpich** [comment]
[FE was deployed to production](https://github.com/Expensify/App/pull/54186#issuecomment-2816149860)! We also have a PR merged in for a [backend fix for one of the last remaining bugs/edge-cases we know about for this.](https://github.com/Expensify/App/issues/60303). That should get deployed to prod on Monday. We may get a few more bugs that crop up over the next few weeks, but the hard part is done! 🥳

**Comment by blimpich** [comment]
We're deployed to production! We're still waiting on this [backend edge case fix](https://github.com/Expensify/App/issues/60303) to get deployed to Auth.

**Comment by MitchExpensify** [comment]
Yes, I can, @allgandalf. Have we already agreed on an amount? Remind me please 😎

**Comment by blimpich** [comment]
Added some cleanup items and assigned them to myself.

**Comment by MitchExpensify** [comment]
Offer sent here, @allgandalf : https://www.upwork.com/nx/wm/offer/107026391

**Comment by MitchExpensify** [comment]
Paid! Thanks, @allgandalf

**Comment by blimpich** [comment]
We technically still have this last little follow up PR [here](https://github.com/Expensify/App/pull/60632). Once that is done I think we can close.

**Comment by blimpich** [comment]
Closing as we just merged our last follow up PR.  I have some cleanup issues that I'll handle separately, but I consider this done.
