### ISSUE TITLE
[C+ Checklist Needs Completion] [$125] mWeb - Chat - Part of the #Admins welcome message is still in english when changing language

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51577]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5131860&group_by=cases:section_id&group_order=asc&group_id=229070
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website
2. Tap on "Settings" on the bottom of the screen
3. Tap on "Preferences"
4. Tap on "Language" and select "Spanish"
5. Tap on the arrow on the top left corner
6. Tap on "Inbox" and enter the "#Admins" chat
7. Verify that the welcome message is fully displayed in spanish now

## Expected Result:
The welcome message in "#Admins" chat should be displayed completely in spanish when changing language

## Actual Result:
"Use it to chat about workspace setup and more" in the "#Admins" chat welcome message, is still displayed in english when changing language

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/fa6c2a32-400d-4e02-abb3-3f3c8e8ba0e9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851377431726711266</li>
        <li>Upwork Job ID: 1851377431726711266</li>
        <li>Last Price Increase: 2024-10-29</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104762311</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by greg-schroeder** [comment]
Awaiting proposal review

**Comment by greg-schroeder** [comment]
Gentle bump @rushatgabhane

**Comment by greg-schroeder** [comment]
Review is ongoing in linked PR

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @Krishna2323 - $125 - Paid via Upwork
C+: @rushatgabhane - $125 - NewDot manual request

**Comment by greg-schroeder** [comment]
All that's left is the C+ checklist @rushatgabhane

**Comment by greg-schroeder** [comment]
Bump @rushatgabhane <3
