### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] Track distance - Distance and Rate show “Pending” when tracking via Just track it route

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51679]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account has no expense
1. Go to staging.new.expensify.com
2. Go to Search
3. Click Create expense
4. Go to Distance
5. Enter waypoints > Next
6. Click Just track it

## Expected Result:
Distance and Rate will show the correct distance and rate when tracking via Just track it route

## Actual Result:
Distance and Rate show “Pending” when tracking via Just track it route

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/f4863806-3bb4-4f3f-873f-fba14a49508c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851378732093417344</li>
        <li>Upwork Job ID: 1851378732093417344</li>
        <li>Last Price Increase: 2024-10-29</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104720899</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance and Rate show “Pending” when tracking via Just track it route

### What is the root cause of that problem?
When we click on `Just track it`, we don't set the `customUnitRateID` as we do [here](https://github.com/Expensify/App/blob/9f92c5e7850301b3b04efe80814a4790188fdde5/src/pages/iou/request/step/IOURequestStepParticipants.tsx#L106)

https://github.com/Expensify/App/blob/9f92c5e7850301b3b04efe80814a4790188fdde5/src/pages/iou/request/step/IOURequestStepParticipants.tsx#L164


Then the `mileageRate` in the confirmation page [here](https://github.com/Expensify/App/blob/9f92c5e7850301b3b04efe80814a4790188fdde5/src/components/MoneyRequestConfirmationList.tsx#L245) is `undefined` based on [this](https://github.com/Expensify/App/blob/9f92c5e7850301b3b04efe80814a4790188fdde5/src/libs/DistanceRequestUtils.ts#L343) logic


Which causes `isDistanceRequestWithPendingRoute` is `true`

https://github.com/Expensify/App/blob/9f92c5e7850301b3b04efe80814a4790188fdde5/src/components/MoneyRequestConfirmationList.tsx#L290

and `waypoints` pendingField is added as `add` which makes `Pending...` is displayed for distance and rate field
https://github.com/Expensify/App/blob/9f92c5e7850301b3b04efe80814a4790188fdde5/src/components/MoneyRequestConfirmationList.tsx#L664-L678
### What changes do you think we should make in order to solve the problem?
We should update the `customUnitRateID` when we click on `Just track it` button here

```
const rateID = DistanceRequestUtils.getCustomUnitRateID(selfDMReportID, !canUseP2PDistanceRequests);
IOU.setCustomUnitRateID(transactionID, rateID);
```

https://github.com/Expensify/App/blob/9f92c5e7850301b3b04efe80814a4790188fdde5/src/pages/iou/request/step/IOURequestStepParticipants.tsx#L164

OPTIONAL: We can also update the `reportID` of the draft transaction to `selfDMReportID`
### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment]
@nkdengineer Thanks for the proposal. Your RCA makes sense. Do you know at what stage we set the `comment.customUnit.customUnitRateID` when using the FAB Track Expense option?

**Comment by nkdengineer** [comment]
@s77rt  When using FAB Track expense the `customUnitRateID` is updated here.

https://github.com/Expensify/App/blob/a4c8de60b4cdcd99aad0089ce73c339afa5d94f9/src/libs/actions/IOU.ts#L352-L354

**Comment by s77rt** [comment]
@nkdengineer Got it! Thanks! The proposed solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/51679#issuecomment-2445086970)

**Comment by nkdengineer** [comment]
@robertjchen Please take a look when you have a chance.

**Comment by robertjchen** [comment]
👍 to proposal!

**Comment by s77rt** [comment]
# BugZero Checklist:

- [X] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [X] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [X] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [X] 3d. QA
  - [ ] 3z. Other:

</details>

- [X] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/49007#discussion_r1835666613

- [X] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: n/a

- [X] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- Account has no expenses

### Test:


1. Go to Search > Expenses
2. Click Create expense
3. Choose Distance and select waypoints then click on Next
4. Click Just track it
5. Verify that all the fields display the correct values and none is "Pending"

Do we agree 👍 or 👎

**Comment by s77rt** [comment]
@greg-schroeder I think you still need to create a GH issue for the testrail test

**Comment by greg-schroeder** [comment]
Yeah of course. I'll file it after I pay this on 11/14

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @nkdengineer - $250 - Upwork
C+: @s77rt - $250 - NewDot manual request
