### ISSUE TITLE
[AWAITING CHECKLIST] [HOLD for payment 2024-12-12] [$250] Search-Order of the words is reversed when the query is submitted

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52170]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.58-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to the Search page.
2. Click on the search bar icon to open the search field.
3. Enter any search query and press the Enter key to submit the query.

## Expected Result:
The order of the words remains without changes when the query is submitted.

## Actual Result:
The order of the words is reversed when the query is submitted.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6656086_1730861572949!51314-Web](https://github.com/user-attachments/assets/01d02002-5f03-4a4d-9e2f-77dcb832afac)

https://github.com/user-attachments/assets/cf3f7dec-bac0-4361-9b9e-3d1b5483d97c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854577953623256419</li>
        <li>Upwork Job ID: 1854577953623256419</li>
        <li>Last Price Increase: 2024-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>Tony-MK | Contributor | 105099831</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search-Order of the words is reversed when the query is submitted
### What is the root cause of that problem?
 [Here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L273C49-L273C71) we pass the `result`  to `getQueryHashes` which iterates on filters and sorts them see [here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L238C1-L240C8). 
### What changes do you think we should make in order to solve the problem?
[Here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L273C64-L273C70) we have to pass a clone of the `Result` object instead of the original.

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search-Order of the words is reversed when the query is submitted
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L273C49-L273C71) we pass the `result`  to `getQueryHashes` function which iterates on `filters` and sorts them. [See here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L238C1-L240C8) 
### What changes do you think we should make in order to solve the problem?
[Here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L273C64-L273C70) we have to pass a clone of the `result` object instead of the original.

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search-Order of the words is reversed when the query is submitted
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L273C49-L273C71) we pass the `result`  to `getQueryHashes` function which iterates on `filters` and sorts them. [See here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L238C1-L240C8) 
### What changes do you think we should make in order to solve the problem?
[Here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L273C64-L273C70) we have to pass a clone of the `result` object instead of the original.
```
getQueryHashes(lodashDeepClone(result))
```


### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search-Order of the words is reversed when the query is submitted
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L273C49-L273C71) we pass the `result` object as a param  to `getQueryHashes` function. And the `getQueryHashes` function sorts filters [here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L238C1-L240C8) which leads the `filters` to be sorted in original object
### What changes do you think we should make in order to solve the problem?
[Here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L273C64-L273C70) we have to pass a clone of the `result` object as a param instead of the original .
```
getQueryHashes(lodashDeepClone(result))
```


### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search-Order of the words is reversed when the query is submitted

### What is the root cause of that problem?

The `SearchPage` uses the `SearchQueryUtils.buildSearchQueryJSON` function to build a query.
https://github.com/Expensify/App/blob/b5c2c73e9abea84866f85e83eb6c8b77c9458152/src/pages/Search/SearchPage.tsx#L21-L23

However, we end up sorting the `query.flatFilters` which are the keywords by alphabetical order when calling the [`getQueryHashes`](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L273-L273) function.

https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L272-L274

### What changes do you think we should make in order to solve the problem?


Remove the lines from the [`getQueryHashes`](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L238-L240) function which sorts the `query.flatFilters` such as the one below so that the order of the keywords from `result.hash` is correct.

https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L238-L240

**Comment by Jaeta01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search-Order of the words is reversed when the query is submitted
### What is the root cause of that problem?
In [this](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L273C49-L273C71) code, we pass the `result` object as a parameter to the `getQueryHashes` function. Within this function, filters are sorted [here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L238C1-L240C8), which inadvertently causes the filters to be sorted in the original object as well.
### What changes do you think we should make in order to solve the problem?
[Here](https://github.com/Expensify/App/blob/494211d9fbbaddb6290a97db38206b0bd113e1ca/src/libs/SearchQueryUtils.ts#L273C64-L273C70) we can to pass a clone of the result object as a param instead of the original .
```
getQueryHashes(lodashDeepClone(result))
```
### What alternative solutions did you explore? (Optional)

**Comment by Jaeta01** [comment]
Hi @rushatgabhane. There is no comment explaining the meaning of the sorting. So I came up with a solution that doesn't change the logic and doesn't require removing existing code.

**Comment by Tony-MK** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/52170#issuecomment-2462915922)

##

> hmm could someone please explain why is it being sorted in the first place?

@rushatgabhane, It is sorted because a consistent hash function is needed to produce constant hashes when the function is been passed the same keywords but in a different order.

> and what could be a problem if we removed the sorting?

We might get into collisions and inefficiency when searching the user's search history.

**Comment by garrettmknight** [comment]
@rushatgabhane can you give these two proposals a look?

**Comment by garrettmknight** [comment]
@rushatgabhane can you give these proposals a look?

**Comment by garrettmknight** [comment]
**Payment Summary**
- Contributor: @Tony-MK $250 paid via Upwork
- Reviewer: @rushatgabhane $250 via NewDot once he finishes the checklist.

**Comment by garrettmknight** [comment]
@rushatgabhane can you complete the checklist when you get a chance?

**Comment by garrettmknight** [comment]
Still awaiting the checklist

**Comment by JmillsExpensify** [comment]
Confirming the payment summary:

 - Contributor: @Tony-MK $250 via Upwork
 - Reviewer: @rushatgabhane $250 via New Expensify

**Comment by rushatgabhane** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/50883/files#r1908818356

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not critical but we can add test for it.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.



<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1. Go to the search page.
2. Click on the search bar.
3. Type in random letters or words preferably in reverse alphabetical order. E.g.: dog cat bird apple.
4. Press enter to search the keywords.
5. Check if the order of the keywords in the search bar is unchanged and exactly as you typed in Step 3.

Do we agree 👍 or 👎


</details>
