### ISSUE TITLE
[HOLD for payment 2024-12-30] [$250] Room - Page does not scroll to bottom when send message in #expensify-roadmap public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52208]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to staging.new.expensify.com
2. Open #expensify-roadmap public room ( https://staging.new.expensify.com/r/868417741568295
)
3. Scroll to the top of the page
4. Send a message

## Expected Result:
Page should scroll to the bottom when send new message

## Actual Result:
Page does not scroll to bottom of the conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/56c39d92-e9cf-488f-9754-74aaab345276

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021855979378378206243</li>
        <li>Upwork Job ID: 1855979378378206243</li>
        <li>Last Price Increase: 2024-11-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale / @sonialiap</details>

**Comment by jestinjoshi** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Page does not scroll to bottom of the conversation in #expensify-roadmap public room

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/b2d6a0eace9d22bb93b5e37aa83dda3bbe7eec1b/src/pages/home/report/ReportActionsList.tsx#L427

### What changes do you think we should make in order to solve the problem?
The `return` statement can be removed here, as it was added simply to follow a similar logic in `scrollToBottomAndMarkReportAsRead`, as noted in https://github.com/Expensify/App/pull/46724#discussion_r1702085773. Removing it won't affect functionality in this context.

### What alternative solutions did you explore? (Optional)
NA

**Comment by Anaslancer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room - Page does not scroll to bottom when send message in #expensify-roadmap public room

### What is the root cause of that problem?
We are calling the `scrollToBottomForCurrentUserAction` callback function before changing the `hasNewestReportActionRef.current`. we should wait until changing `hasNewestReportActionRef.current`.

### What changes do you think we should make in order to solve the problem?
We need to wrap this block into the `InteractionManager.runAfterInteractions`.
https://github.com/Expensify/App/blob/b2d6a0eace9d22bb93b5e37aa83dda3bbe7eec1b/src/pages/home/report/ReportActionsList.tsx#L417-L429
So this below is the working block;
```
            InteractionManager.runAfterInteractions(() => {
                // If a new comment is added and it's from the current user scroll to the bottom otherwise leave the user positioned where
                // they are now in the list.
                if (!isFromCurrentUser) {
                    return;
                }
                if (!hasNewestReportActionRef.current) {
                    if (isInNarrowPaneModal) {
                        return;
                    }
                    Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.reportID));
                    return;
                }
                reportScrollManager.scrollToBottom();
            });
```

### What alternative solutions did you explore? (Optional)
N/A

### Contributor details
Your Expensify account email: anasup1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by akinwale** [comment]
@Anaslancer Could you post a video demo of your proposed solution?

**Comment by Anaslancer** [comment]
@akinwale Here is the before video

https://github.com/user-attachments/assets/2f3abe99-ccd0-4986-9d39-4ecd2e4bd117

**Comment by Anaslancer** [comment]
@akinwale Here is the after video

https://github.com/user-attachments/assets/162ba043-9a48-42a8-bb62-41d66ed71dc7

**Comment by sonialiap** [comment]
@akinwale what do you think of the videos showing the proposal?

**Comment by akinwale** [comment]
I will review and test this today.

**Comment by akinwale** [comment]
We can move forward with @Anaslancer's [proposal](https://github.com/Expensify/App/issues/52208#issuecomment-2470540762) here.

🎀👀🎀 C+ reviewed.

**Comment by Anaslancer** [comment]
Applied on Upwork. Thank you!!!

**Comment by Anaslancer** [comment]
May I create a PR now?

**Comment by akinwale** [comment]
> May I create a PR now?

Yes, you have been assigned to the issue, so you can go ahead.

**Comment by aldo-expensify** [comment]
Waiting on: https://github.com/Expensify/App/pull/52955#pullrequestreview-2463987825

**Comment by sonialiap** [comment]
I'm OOO Dec 16-20, adding a leave buddy

next steps:
- might need payment while I'm out

**Comment by garrettmknight** [comment]
👋 it looks like [this issue](https://github.com/Expensify/App/issues/54307) might be a regression from the PR for this fix. @aldo-expensify / @akinwale can you have a look?

**Comment by sonialiap** [comment]
Not regression https://github.com/Expensify/App/issues/54307#issuecomment-2552145375

**Comment by sonialiap** [comment]
Payment summary:
- @akinwale $250 via ND - please complete the [checklist](https://github.com/Expensify/App/issues/52208#issuecomment-2560293385)

**Comment by akinwale** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: N/A

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Test:
1. Launch Expensify
2. Log in with an account
3. Navigate to a chat room that has a long chat history that can be scrolled, with the latest message being a message from a user different from the currently logged in account
4. Scroll up through the chat history to the top
5. Send a message to the chat room
6. Verify that the chat area automatically scrolls to the bottom after the message has been sent to the room.

Do we agree 👍 or 👎?

**Comment by sonialiap** [comment]
Thanks @akinwale! If you haven't yet, please request payment in ND

**Comment by Anaslancer** [comment]
@sonialiap Can I get the payment?

**Comment by aldo-expensify** [comment]
S

**Comment by sonialiap** [comment]
@Anaslancer $250 for fix, offer sent!

**Comment by Anaslancer** [comment]
Thank you!!!

**Comment by sonialiap** [comment]
Payment completed 😊

**Comment by JmillsExpensify** [comment]
$250 approved for @akinwale
