### ISSUE TITLE
[Awaiting checklist] [HOLD for payment 2024-12-25] [$250] Search -"Join" button displayed for some seconds when opening expenses in search after login

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52589]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5227066&group_by=cases:section_id&group_order=asc&group_id=296775
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the Expensify app
2. Log in with any account that contains several expenses on it
3. Tap on "Search" on the bottom of the screen
4. Open any expense on the list
5. Verify that the report and information load correctly

## Expected Result:
When user opens any expense on search section, all the information available on the report, should load automatically

## Actual Result:
A "Join" green button, can be seen on top of reports when opening expenses on search after logging in, and the report title only displays "Expense" instead of the expense details for some seconds

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/768654a3-740c-4579-8e04-a6b43c5000df

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858438366366454101</li>
        <li>Upwork Job ID: 1858438366366454101</li>
        <li>Last Price Increase: 2024-11-18</li>
<li>Automatic offers: </li>
<ul>
<li>daledah | Contributor | 105062627</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by twisterdotcom** [comment]
@getusha and @daledah I would love to sign in and pay this on Christmas day, but my family will not. As a heads up, this may be delayed until the new year.

**Comment by puneetlath** [comment]
@getusha friendly bump.

**Comment by twisterdotcom** [comment]
@getusha there can't be a payment for you until the checklist is done please.

**Comment by getusha** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: N/a

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/a

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

Seems like we already have a testrail for this: https://expensify.testrail.io/index.php?/tests/view/5227066&group_by=cases:section_id&group_order=asc&group_id=296775

**Comment by twisterdotcom** [comment]
Nice, you did it!

**Comment by twisterdotcom** [comment]
Payment Summary:

- @getusha paid $250 via NewDot Manual Request
- @daledah paid $250 [here](https://www.upwork.com/nx/wm/offer/105062627) (Contributor)

**Comment by garrettmknight** [comment]
$250 approved for @getusha
