### ISSUE TITLE
Full Setup Checklist Not Sending 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#53224]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.66-8
**Reproducible in staging?:**  
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** See internal issue below for details 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/448100
**Issue reported by:** @MitchExpensify 
**Slack conversation** (hyperlinked to channel name): NA

## Action Performed:
1. Sign into New.Expensify via a new account
2. Select 1-10 employees 
3. Select QBO 

## Expected Result:
See a full setup checklist in Concierge or #admins like this:

<img width="1572" alt="image" src="https://github.com/user-attachments/assets/90edde3a-4272-46dc-b073-165c83b65a5b">

## Actual Result:
Land on a long loading skeleton view with only one task showing:

<img width="997" alt="image" src="https://github.com/user-attachments/assets/72e9075b-a8c6-423f-8d58-570743f85683">

## Workaround:

Explore the app despite this janky-ness but smooth onboarding is compromised at this point 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari (Chrome, OS X)
- [ ] MacOS: Desktop

## Screenshots/Videos

Added above, full story here: https://app.fullstory.com/ui/o-1WN56P-na1/session/6735773232164417224:6735773232164417224!6172688171892001743

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by VictoriaExpensify** [comment]
I haven't been able to reproduce this as the flow to select how I will be using Expensify is not coming up. I've posted in #quality to find out if that's an expected change or a bug

https://expensify.slack.com/archives/C05LX9D6E07/p1733121675571129

**Comment by VictoriaExpensify** [comment]
I wasn't able to reproduce this:

![image](https://github.com/user-attachments/assets/e11de37a-f136-4d3a-ae7b-370c6276d3a2)

I'm wondering if the issue was resolved with this -  https://github.com/Expensify/App/issues/53284

@MitchExpensify are you able to reproduce this now?

**Comment by MitchExpensify** [comment]
I cannot reproduce @VictoriaExpensify

**Comment by VictoriaExpensify** [comment]
Excellent! I think we can close this then. If you disagree, feel free to reopen
