### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] Unable to delete workspace/Workspace shown with Strikethrough font

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53413]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @VictoriaExpensify 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1733133960497129)

## Action Performed:

1. Log into [New.Expensify.com](http://new.expensify.com/) with a new email address
2. Create a new Workspace to start a subscription
3. Go to "subscriptions" and make sure it shows "Annual"
4. Go to Workspaces and delete the newly created Workspace
5. This will give an error Looks like you're on an annual subscription. Please downgrade your account from your account settings before trying again. and the Workspace will be crossed out (strikethrough)
6. Go back to Subscriptions and change from Annual to Pay Per Use
7. Go back to Workspaces and attempt to delete - the three dots will be greyed out and it will still be crossed out

## Expected Result:
Error message dismissed and user able to delete the workspace

## Actual Result:
Error message not dismissed, unable to delete the workspace as its greyed out
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![2024-12-02_16-51-05 (1)](https://github.com/user-attachments/assets/52973987-634d-465f-a9ed-4c5e5b4c71fc)

https://github.com/user-attachments/assets/42b17986-89c5-4ce0-ba46-11bbc76377b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021865088803803540719</li>
        <li>Upwork Job ID: 1865088803803540719</li>
        <li>Last Price Increase: 2024-12-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unable to delete workspace/Workspace shown with Strikethrough font

### What is the root cause of that problem?

The current behavior requires dismissing the error message if we want to continue deleting the workspace after it appears. Once the error is dismissed, the action to delete the workspace can proceed as normal.

https://github.com/user-attachments/assets/de493db3-9b76-4f07-af46-173eb9437146

Because calling `dismissError` will clear the delete workspace error.

https://github.com/Expensify/App/blob/a3fe37d9497119084f18a09b02d1eae9d9dba977/src/pages/workspace/WorkspacesListPage.tsx#L88

https://github.com/Expensify/App/blob/a3fe37d9497119084f18a09b02d1eae9d9dba977/src/pages/workspace/WorkspacesListPage.tsx#L209

After clearing the workspace error, the `disable` flag will be set to `false`, and the action to delete the workspace can proceed as normal.

https://github.com/Expensify/App/blob/a3fe37d9497119084f18a09b02d1eae9d9dba977/src/pages/workspace/WorkspacesListPage.tsx#L356

### What changes do you think we should make in order to solve the problem?

To resolve this issue, I suggest we should automatically call `dismissError` when we go back to the workspace list page. Something like that:

```diff
    useEffect(() => {
        if (!policies || isAnnual) {
            return;
        }

        const processPolicies = () => {
            const policiesList = Object.values(policies)
                .filter((policy): policy is PolicyType => PolicyUtils.shouldShowPolicy(policy, isOffline, session?.email))
                .map((item) => ({id: item.id, pendingAction: item.pendingAction}));

            policiesList.forEach((item) => {
                dismissWorkspaceError(item.id, item.pendingAction);
            });
        };

        processPolicies();
        // tThis code only executes when going back to the workspace, and to avoid the case where we change `yearly` -> `monthly` -> `yearly`.
    }, []);
```

<details>
<summary>POC</summary>



</details>

**Comment by jacobkim9881** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When after changing from Annual to Pay Per Use, error message on workspace settings isn't deleted.

### What is the root cause of that problem?
When entering workspace settings, no function activates to dismiss the error message thought we have `dismissWorkspaceError` function.

https://github.com/Expensify/App/blob/583f777ec579da26bc2e78ca8213df8fcd97f7e4/src/pages/workspace/WorkspacesListPage.tsx#L88-L92

And this part renders error message for delete whenever rendering workspace list and here isn't any function for the issue:

https://github.com/Expensify/App/blob/583f777ec579da26bc2e78ca8213df8fcd97f7e4/src/pages/workspace/WorkspacesListPage.tsx#L320-L356

### What changes do you think we should make in order to solve the problem?
We can add a condition to dismiss error message. When the user changed from Annual to Pay Per Use, private subscription is changed. We can add `dismissWorkspaceError`:

```js
//// add this
const subscription = useOnyx(ONYXKEYS.NVP_PRIVATE_SUBSCRIPTION);
//// add this
...
                        action: () => null,
                        dismissError: () => null,
                        isJoinRequestPending: true,
                    };
                }

//// add these
if(policy.errors && policy.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE && subscription.at(0).type === CONST.SUBSCRIPTION.TYPE.PAYPERUSE)  {
  dismissWorkspaceError(policy.id, policy.pendingAction)

}
//// add these

                return {
                    title: policy.name,
                    icon: policy.avatarURL ? policy.avatarURL : ReportUtils.getDefaultWorkspaceAvatar(policy.name),
                    action: () => Navigation.navigate(ROUTES.WORKSPACE_INITIAL.getRoute(policy.id)),
...
```

Then when there is error for deleting a workspace and when subscription is Pay Per Use, workspace error will be dismissed.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users are unable to delete a workspace when:

1. They are on an annual subscription
2. They attempt to delete their first workspace
3. Even after changing the subscription type from Annual to Pay Per Use

### What is the root cause of that problem?
Currently we don't clear the deletion error when the subscription type changes. Specifically:

- When on an annual subscription, attempting to delete a workspace triggers an error
- The error message is stored in the errors field of the policy
- Changing the subscription to Pay Per Use does NOT automatically remove this error
- The error can only be manually dismissed by clicking the 'X' symbol, by triggering this part of the code.

https://github.com/Expensify/App/blob/b80c68ea76cdf825d9331bbf298cc41b40716037/src/pages/workspace/WorkspacesListPage.tsx#L89-L91

### What changes do you think we should make in order to solve the problem?
We can add this check to automatically clear the workspace deletion error when the subscription type is no longer annual.here: https://github.com/Expensify/App/blob/b80c68ea76cdf825d9331bbf298cc41b40716037/src/pages/workspace/WorkspacesListPage.tsx#L321-L322

```diff
            .map((policy): WorkspaceItem => {
+                if(!isAnnual){
+                  Policy.clearDeleteWorkspaceError(policy.id);
+                }
```

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users are unable to delete a workspace when:

1. They are on an annual subscription
2. They attempt to delete their first workspace
3. Even after changing the subscription type from Annual to Pay Per Use

### What is the root cause of that problem?
Currently we don't clear the deletion error when the subscription type changes. Specifically:

- When on an annual subscription, attempting to delete a workspace triggers an error
- The error message is stored in the errors field of the policy
- Changing the subscription to Pay Per Use does NOT automatically remove this error
- The error can only be manually dismissed by clicking the 'X' symbol, by triggering this part of the code.

https://github.com/Expensify/App/blob/b80c68ea76cdf825d9331bbf298cc41b40716037/src/pages/workspace/WorkspacesListPage.tsx#L89-L91

### What changes do you think we should make in order to solve the problem?
We can add this check to automatically clear the workspace deletion error when the subscription type is no longer annual.here: https://github.com/Expensify/App/blob/b80c68ea76cdf825d9331bbf298cc41b40716037/src/pages/workspace/WorkspacesListPage.tsx#L321-L322

```diff
            .map((policy): WorkspaceItem => {
+                if(!isAnnual){
+                  Policy.clearDeleteWorkspaceError(policy.id);
+                }
```


https://github.com/user-attachments/assets/ce4aade6-890e-4b72-b2eb-4c84fc2a87c9

**Comment by FitseTLT** [comment]
This is expected we need to first dismiss the error.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If the workspace deletion failed, the workspace list row stays disabled until we clear the error.

### What is the root cause of that problem?
When we delete the workspace, we set the pending action to DELETE. This disables the workspace item.
https://github.com/Expensify/App/blob/b9107bf59cbb3982d958abbae357e3b903ed4c63/src/pages/workspace/WorkspacesListPage.tsx#L379

It makes sense to disable it because we already archived all its report, so it doesn't make sense if the user can open the 3-dot menu again to delete it again. The problem here is that, after it fails, the pending action isn't cleared.

### What changes do you think we should make in order to solve the problem?

Clears the pending action in `failureData`.
https://github.com/Expensify/App/blob/b9107bf59cbb3982d958abbae357e3b903ed4c63/src/libs/actions/Policy/Policy.ts#L365-L380

(or `finallyData` also works)

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

We can create a test in PolicyTests following the existing test there. The thing that we need to test is that after the request is failed, the policy onyx data `pendingAction` should be empty.

**Comment by greg-schroeder** [comment]
Set `External`, next up is proposal review

**Comment by greg-schroeder** [comment]
@alitoshmatov will review soon!

**Comment by alitoshmatov** [comment]
I am easily able to delete workspace even if subscription is annual. Can we anyone make sure it is still reproducible, if yes I will reassign this issue

**Comment by greg-schroeder** [comment]
I also was able to do it as well just now testing. Huh.

**Comment by greg-schroeder** [comment]
Let's close as not reproducible for now, but please comment/reopen if you disagree

**Comment by bernhardoj** [comment]
I can still reproduce this. You need to make sure you are deleting the last workspace from the account.
https://github.com/user-attachments/assets/df06c79a-0029-4630-88ae-3d58e558b803

**Comment by VictoriaExpensify** [comment]
Reopening based on @bernhardoj's last comment

**Comment by greg-schroeder** [comment]
Ah, that makes sense why I couldn't do it. Got it.

**Comment by alitoshmatov** [comment]
Thanks @bernhardoj, I also was able to reproduce it now.

**Comment by alitoshmatov** [comment]
Thank you all for proposals, I think most of the proposals are missing a point that workspace shouldn't be strikethrough, or having `delete` state in their pending actions. And not dismissing error shouldn't prevent you from interacting with workspace

**Comment by alitoshmatov** [comment]
I think @bernhardoj is the only proposal with correct RCA and provides correct solution. We can go with @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/53413#issuecomment-2523278930)

C+ reviewed 🎀 👀 🎀

**Comment by greg-schroeder** [comment]
Bump @srikarparsi on contributor assignment :)

**Comment by srikarparsi** [comment]
Sorry for the delay here, assigning @bernhardoj

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment]
@alitoshmatov is still on the review ... looks like he asked @srikarparsi for help. Do you mind taking a look at the PR and weighing in?

**Comment by greg-schroeder** [comment]
@alitoshmatov I think you're next up on the linked PR as I see you requested for review

**Comment by greg-schroeder** [comment]
Bump @alitoshmatov on the checklist! Then we can close.

**Comment by alitoshmatov** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by greg-schroeder** [comment]
Thanks @alitoshmatov!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
$250 approved for @alitoshmatov
