### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] IOS - Avatar doesn't get back to its original center position after zooming in and out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53471]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.70-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5291133
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2272@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open hybrid app
2. Upload a custom avatar for your profile
3. Open your self DM
4. Open the avatar to show in full screen
5. Pinch out to zoom and without releasing our finger pinch in to zoom out and position your fingers to the corner while zooming out and release your fingers

## Expected Result:
The position of the avatar gets back to its original center position

## Actual Result:
The avatar stays at the position it was released on and doesn't get back to the center

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a8d89fe4-1531-4e6a-8db5-7ce3d3f2931a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863989062279850488</li>
        <li>Upwork Job ID: 1863989062279850488</li>
        <li>Last Price Increase: 2025-02-03</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 106011607</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedkhan28** [comment]
Hi! I came across your job posting on Upwork regarding the avatar centering issue in your iOS app. After analyzing the problem where the avatar doesn't return to center after zoom gestures, I believe this can be fixed effectively through iterative solutions. I am a full time full stack iOS developer, designer and game developer at MagicHabits. This can be fixed in max 1-2 days.

Based on my experience with iOS gesture handling and UI animations, I've identified 5 potential approaches that could solve this:

**Spring Animation Reset**

swiftCopyUIView.animate(withSpringDamping: 0.8) {
    avatarImageView.center = view.center
}

**Velocity-Based Repositioning**

swiftCopylet velocity = gesture.velocity(in: view)
let newCenter = calculatePosition(from: velocity)
animateToPosition(newCenter)


**Smart Edge Detection**

swiftCopyif !safeBounds.contains(avatar.frame) {
    returnToCenter(animated: true)
}

**Progressive Center Force**

swiftCopylet centerForce = 1 - currentScale
let newCenter = interpolate(current: position, 
                          target: center,
                          force: centerForce)

**Physics-Based Boundaries**

swiftCopylet behavior = UIAttachmentBehavior(item: avatarImageView)
animator.addBehavior(behavior)
Most natural but complex implementation
Recommended Approach:

I suggest implementing Solution #1 (Spring Animation Reset) first, then enhancing it with elements of Solution #4 (Progressive Center Force). This combination would:

Provide immediate improvement in UX
Feel natural and iOS-native
Be quick to implement and test
Allow for easy tuning of behavior

Let me know if you like it so I can submit a proposal on upwork!

**Comment by ahmedkhan28** [comment]
Contributor details
Your Expensify account email: ahmedkhan850@gmail.com
Upwork Profile Link: www.upwork.com/agencies/1838604427293852717

**Comment by JoshIri360** [comment]
I'll help you write a proposal for this issue. Based on the code and issue description, here's a clear proposal:

**Problem Statement:**
When a user zooms out on an avatar image and releases their fingers while the image is positioned away from the center, the image stays in that off-center position instead of returning to the center of the screen.

**Root Cause:**
The pinch gesture handler only resets the position to center when zooming below the minimum zoom level, but doesn't handle the case where the image is off-center when returning to the default zoom level.

**Proposed Solution:**
We should modify the `onEnd` handler in `usePinchGesture.ts` to reset the position to center whenever the zoom scale returns to its minimum value, regardless of the current position. Here's the specific code change needed:


```typescript:src/components/MultiGestureCanvas/usePinchGesture.ts
.onEnd(() => {
    // ... existing code ...

    if (zoomScale.get() <= zoomRange.min) {
        // When at minimum zoom or below, always reset position to center
        pinchScale.set(zoomRange.min);
        zoomScale.set(withSpring(zoomRange.min, SPRING_CONFIG, triggerScaleChangedEvent));

        // Animate back to center position
        offsetX.set(withSpring(0, SPRING_CONFIG));
        offsetY.set(withSpring(0, SPRING_CONFIG));
    } else if (zoomScale.get() > zoomRange.max) {
     // ... existing code ...
});
```

**Test Scenarios:**
1. Zoom out to minimum scale while centered - verify image stays centered
2. Zoom out to minimum scale while off-center - verify image returns to center
3. Zoom out below minimum scale while off-center - verify image returns to center

**Alternative Solutions Considered:**
1. Always center the image on gesture end, but this would limit user control when zoomed in

**Comment by JoshIri360** [comment]
Contributor details
Your Expensify account email: aidelojejoshua@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018bc4a19179469daa

**Comment by ahmedkhan28** [comment]
Submitted the proposal just now, thank you!

**Comment by greg-schroeder** [comment]
Next up is proposal review

**Comment by ahmedkhan28** [comment]
We had to have a contract before me solving it, right?

**Comment by abdulrahuman5196** [comment]
Hi, will review today

**Comment by greg-schroeder** [comment]
Thanks @abdulrahuman5196

**Comment by abdulrahuman5196** [comment]
@ahmedkhan28 / @JoshIri360 Kindly follow the proposal template for suggesting solutions as mentioned here https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job

And on another not @JoshIri360 I tried your solution and its not fixing the issue. I am still able to repro the issue with your solution.

**Comment by abdulrahuman5196** [comment]
No pending proposal to review or approve yet

**Comment by JoshIri360** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/53471#issuecomment-2516037552)

**Comment by abdulrahuman5196** [comment]
> ## Proposal
> 
> [Updated](https://github.com/Expensify/App/issues/53471#issuecomment-2516037552)

The only change is that the code changed from the if check to else check. Why do think the new change would work? Not sure on how the new change in the proposal is expected to work.

**Comment by JoshIri360** [comment]
@abdulrahuman5196 

Currently, recentering only happens in extreme cases:

```typescript:src/components/MultiGestureCanvas/usePinchGesture.ts
.onEnd(() => {
    // Extreme case 1: Zoomed too far out
    if (zoomScale.get() < zoomRange.min) {
        pinchScale.set(zoomRange.min);
        zoomScale.set(withSpring(zoomRange.min, SPRING_CONFIG));
        // Image recenters here
    } 
    // Extreme case 2: Zoomed too far in
    else if (zoomScale.get() > zoomRange.max) {
        pinchScale.set(zoomRange.max);
        zoomScale.set(withSpring(zoomRange.max, SPRING_CONFIG));
        // Image recenters here
    } 
    // Normal case: No recentering happens
    else {
        pinchScale.set(zoomScale.get());
    }
});
```

The proposed change ensures recentering happens in all cases:

```typescript:src/components/MultiGestureCanvas/usePinchGesture.ts
.onEnd(() => {
    // Extreme case 1: Zoomed too far out
    if (zoomScale.get() < zoomRange.min) {
        pinchScale.set(zoomRange.min);
        zoomScale.set(withSpring(zoomRange.min, SPRING_CONFIG));
    } 
    // Extreme case 2: Zoomed too far in
    else if (zoomScale.get() > zoomRange.max) {
        pinchScale.set(zoomRange.max);
        zoomScale.set(withSpring(zoomRange.max, SPRING_CONFIG));
    } 
    // Normal case: Now we also recenter here
    else {
        // Always recenter after any pinch gesture
        offsetX.set(withSpring(0, SPRING_CONFIG));
        offsetY.set(withSpring(0, SPRING_CONFIG));
        pinchScale.set(zoomScale.get());
    }
});
```

As shown in the video, this creates a more consistent experience because the avatar always returns to center after the user finishes their pinch gesture, regardless of whether they were doing an extreme zoom or just a normal interaction. I'll update the proposal to include these explanations to better illustrate the technical difference.

**Comment by abdulrahuman5196** [comment]
@JoshIri360 
>However, it doesn't handle the case where the image is at a normal zoom level but offset from center. Here's the relevant code showing this limitation:

I am not sure this is correct RCA. I am even reproducing this issue in zoomed out state.

>The proposed change ensures recentering happens in all cases:

I don't think we should blindly recentering without knowing what is the exact root cause.


I would need to know a strong RCA since the issue is happening at rare cases and its easy to mistake any change we make as a potential fix. Kindly provide information on RCA with some proof information.

**Comment by greg-schroeder** [comment]
Proposals still coming through

**Comment by abdulrahuman5196** [comment]
Will check the updated in my morning

**Comment by abdulrahuman5196** [comment]
> ## Proposal
> 
> [Updated](https://github.com/Expensify/App/issues/53471#issuecomment-2516037552)

@JoshIri360 I still don't agree on the rootcause

>The root cause of this problem is that recentering the avatar is only done if the zoom scale is less than the minimum zoom scale or more than the maximum zoom scale.

I am seeing this issue even on other normal zoom cases occasionally as well

**Comment by greg-schroeder** [comment]
Still awaiting viable proposals per the above

**Comment by greg-schroeder** [comment]
What do you think @abdulrahuman5196 - raise bounty here?

**Comment by greg-schroeder** [comment]
Updated bounty to generate more interest

**Comment by anboia** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The avatar image does not get back to original position after composition of pinch and pan gestures, when leaving one of the fingers out of the canvas area.

### What is the root cause of that problem?

Inadequate handling when a touch pointer leaves the screen. The pinch gesture is being interrupedt by the `pinchEnabled` state, when there is no more two fingers and the punch gesture is on course.

#### Explanation:

The pinch gesture is defined as follow, in `usePinchGesture.ts`:
```javascript
const pinchGesture = Gesture.Pinch()
    .enabled(pinchEnabled)
    /// .......
```
The following part of the code disable the pinch gesture:
```javascript
.onChange((evt) => {
    // Disable the pinch gesture if one finger is released,
    // to prevent the content from shaking/jumping
    if (evt.numberOfPointers !== 2) {
        runOnJS(setPinchEnabled)(false);
        return;
    }

```

When a touch pointer leaves the screen, the pinch gesture does not end properly, and the accumulated transformations are not finalized. Specifically on iOS, when a touch leaves the screen, the gesture may not trigger `onEnd` handlers, leading to incomplete gesture resolution.



### What changes do you think we should make in order to solve the problem?

The simplest solution would be wrap the `onEnd` calback in a function `handleGestureEnd`, and call this function instead of `runOnJS(setPinchEnabled)(false);`. That would be enough to propper finish the pinch gesture. Also, remove the usage of `.enabled(pinchEnabled)` since it would not be needed.

#### Additional fixes:
1. This error is raised everytime the gesture canvas is displayed. By adding a `'worklet';` statement on each gesture callback. After fixing this, the error stops.

> Some of the callbacks in the gesture are worklets and some are not. Either make sure that all calbacks are marked as 'worklet' if you wish to run them on the UI thread or use '.runOnJS(true)' modifier on the gesture explicitly to run all callbacks on the JS thread.


2. An error is preventing the correct update of the zoom: After zooming in beyond the limit, it does not zoom back:

https://github.com/Expensify/App/blob/44d3a4f1ff33c0ff47f1c98e659b916c7c550209/src/components/MultiGestureCanvas/usePinchGesture.ts#L132

A fix would be just replace `zoomScale.get()` with `newZoomScale` in the condition, what actually needs to compare if should update or not the `zoomScale` value.

#### Result

https://github.com/user-attachments/assets/970e0df0-61d2-48ab-89e3-8bab7efc06e9

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
NA

**Comment by greg-schroeder** [comment]
Proposal review is next up cc @abdulrahuman5196

**Comment by anboia** [comment]
I am not sure if it would be a good moment to add a related fix in this proposal, but there is also an issue with the update of the pinch gesture translation. the issue is in this line:

https://github.com/Expensify/App/blob/44d3a4f1ff33c0ff47f1c98e659b916c7c550209/src/components/MultiGestureCanvas/usePinchGesture.ts#L147

the fix is to subtract `pinchBounceTranslateX.get()` the same way as it is used in the `else` condition. Fixed:
```javascript
pinchTranslateX.set(newPinchTranslateX - pinchBounceTranslateX.get());
```

here is a video that show the current app with this flickering issue:

With Error| With Fix
--|--
<video src="https://github.com/user-attachments/assets/b68c41d6-4d7f-4b14-9f8e-40e9bd5b4e9a" width="600" />|<video src="https://github.com/user-attachments/assets/58bed3ba-f2c3-480a-ae58-8a1098bbbdd9" width="600" />

**Comment by abdulrahuman5196** [comment]
Hi @anboia , I am not sure of the RCA mentioned here - https://github.com/Expensify/App/issues/53471#issuecomment-2599005567. I would like to know more information on the RCA.

>Inadequate handling when a touch pointer leaves the screen. The pinch gesture is being interrupedt by the pinchEnabled state, when there is no more two fingers and the punch gesture is on course.
1) How did we arrive at this RCA.?
2) Is there any reliable way to reproduce the issue consistently?
3) >Specifically on iOS, when a touch leaves the screen, the gesture may not trigger onEnd handlers, leading to incomplete gesture resolution.
Does this mean when we lift one finger alone?

**Comment by anboia** [comment]
@abdulrahuman5196 Sorry I skiped the explanation on getting into this conclusion:

1. The pinchEnabled is being set to false (a lot of times) when the onChange calback is triggered. The pinchEnabled is configured to automatically get back to true, when it is changed to false:
```javascript
useEffect(() => {
    if (pinchEnabled) {
        return;
    }
    setPinchEnabled(true);
}, [pinchEnabled]);
```

what is happening is that once the pinch gesture is disabled and finalized, it does not get back to active state anymore. I have logged this failure event:

Interruped| Normal
--|--
<img width="550" alt="Image" src="https://github.com/user-attachments/assets/66014848-ce72-47ad-b25d-78bc5f233aee" />|<img width="329" alt="Image" src="https://github.com/user-attachments/assets/df9a5d22-b5e6-4086-b1ba-d23414e77992" />

This is an unexpected behaivior due to having the pinchEnabled state on a different thread (JS Thread), while the gesture is being handled in the UI Thread. Is like the pinchEnabled state is not getting back to true again, or if it does, this id not being reflected on the pinch gesture.

2. To reproduce the issue: start the pinch gesture, in a fast movement, let one of the fingers leave the canvas area, while the other keeps touching the screen.

3. Yes, when leaving the finger out of the canvas, this behaivior might be different from android devices.

I have added new Alternative solutions on proposal, please let me know if you have any question.

**Comment by anboia** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/53471#issuecomment-2599005567)

**Comment by anboia** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/53471#issuecomment-2599005567)

**Comment by anboia** [comment]
@abdulrahuman5196 @greg-schroeder, is there any issue with my proposal template? I'm not sure why github-actions is adding this comment. 

Please let me know if it still unclear the [RCA](https://github.com/Expensify/App/issues/53471#issuecomment-2605597169) explanation, or should we proceed with the PR?

**Comment by greg-schroeder** [comment]
bump @abdulrahuman5196 on proposal review!

**Comment by anboia** [comment]
## Proposal
[Updated](link to proposal)

**Comment by anboia** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/53471#issuecomment-2603006937)

**Comment by anboia** [comment]
>     2. Is there any reliable way to reproduce the issue consistently?
To reproduce the issue:
1. Zoom in the avatar picture.
2. Move the image to a different position from the center.
3. Zoom out, to the min zoom. 
4. move to another position.
5. release.

the image will move back to the same position when the image transition from original scale, to a small scale ("underzoom")

does not need to " position your fingers to the corner" as described in the [action performed](https://github.com/Expensify/App/issues/53471#issue-2715157508).

@abdulrahuman5196 please let me know if you still need more detail on the RCA.

**Comment by anboia** [comment]
@greg-schroeder my proposal covers 4 additional fixes on the `MultiGestureCanvas`. Would't be a reason to raise the bounty on this?

**Comment by greg-schroeder** [comment]
What do you think of the proposal @abdulrahuman5196?

**Comment by abdulrahuman5196** [comment]
Hi, @greg-schroeder  I would be unavailable for couple of days. Could you kindly add the appropriate labels for another random C+ to take over? Unassigning myself to avoid delays.

**Comment by greg-schroeder** [comment]
Nice, thanks @dominictb

**Comment by anboia** [comment]
@greg-schroeder @dominictb how about my proposal? Wasn't that supposed to get a review?

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatar doesn't snap back to the edge of the screen after zoom in and out.

### What is the root cause of that problem?
When we zoom out, there are 2 callbacks called. First is the pinch gesture `onEnd` callback (this is to add the pinch gesture translate to the offset, offset is the total accumulated translate of all gestures),
https://github.com/Expensify/App/blob/d687284e2c10ee2bc8f49e7e5ea71c2e265d42d1/src/components/MultiGestureCanvas/usePinchGesture.ts#L156-L163

and the second one is the pan gesture `onEnd` callback (this also adds the pan gesture translate to the offset, but also does the snapping logic).
https://github.com/Expensify/App/blob/d687284e2c10ee2bc8f49e7e5ea71c2e265d42d1/src/components/MultiGestureCanvas/usePanGesture.ts#L237-L254

Pinch gesture end callback is always called first before the pan gesture. The one that is responsible for snapping the image back to the edge of the screen (boundary) is the pan gesture end callback, specifically the `finishPanGesture` function.
https://github.com/Expensify/App/blob/d687284e2c10ee2bc8f49e7e5ea71c2e265d42d1/src/components/MultiGestureCanvas/usePanGesture.ts#L134-L137

However, the problem we currently face is that even though the pinch gesture end callback is called first, the offset shared value is updated first from the pan gesture end callback.

order of calls:
1. pinch gesture end callback
2. pan gesture end callback

order of shared value updates:
1. pan gesture end callback
2. pinch gesture end callback

If we log the offset value (specifically `offsetX`) inside `finishPanGesture`, we can see that the value is not updated yet. It's as if the `offsetX` update from the pinch gesture end callback is not immediately synchronized even though all the callbacks are supposed to run on the same thread, that is the UI thread.

And that's true, somehow the pinch gesture end callback runs on the JS thread. We can prove this by printing the _WORKLET value inside the `onEnd` callback.

```
console.log(_WORKLET)
```

This all happens after https://github.com/Expensify/App/pull/52825 where we migrate the way we access and update the shared value to satisfy the react-compiler. Now the hook is successfully optimized by react-compiler, it broke the automatic workletized by the reanimated. We can prove this by disabling react-compiler for `usePinchGesture` by adding `'use no memo'` directive inside the hook.

### What changes do you think we should make in order to solve the problem?

We can either disable the react-compiler for `usePinchGesture` by adding `'use no memo'`

OR

we can manually add `'worklet'` directive inside the `onTouchesDown` callback and somehow the rest of the functions are workletized again.
https://github.com/Expensify/App/blob/33a03bf7658e0d75743f11196c8c4d0825668417/src/components/MultiGestureCanvas/usePinchGesture.ts#L106-L108

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

N/A

**Comment by greg-schroeder** [comment]
Friendly bump @dominictb

**Comment by bernhardoj** [comment]
PR is ready

cc: @dominictb

**Comment by anboia** [comment]
> @dominictb all the gestures callbacks should actually be using the 'worklet' directive. there is a big red warning that shows up in the log when opening the avatar, and gestures callback functions are all inddeed supposed to be running on UI Thread, as I mentioned in my proposal. Adding 'worklet' just to one function is more like a work-around on the problem, to forces the priority of which function should run first. And if you add 'worklet' to all callback that are suposed to be runing on UI, as it should, will not fix the problem.

**Comment by anboia** [comment]
> Thanks for all your proposals. I think [@bernhardoj](https://github.com/bernhardoj)'s [solution](https://github.com/Expensify/App/issues/53471#issuecomment-2642255684) makes more sense, I only can understand the RCA after reading his proposal. I think we can use `worklet`, but I need more time to verify the solution. I'll give the final update in 1 hour

@dominictb all the gestures callbacks should actually be using the 'worklet' directive. there is a big red warning that shows up in the log when opening the avatar, and gestures callback functions are all inddeed supposed to be running on UI Thread, as I mentioned in my proposal. Adding 'worklet' just to one function is more like a work-around on the problem, to forces the priority of which function should run first. And if you add 'worklet' to all callback that are suposed to be runing on UI, as it should, will not fix the problem.

**Comment by greg-schroeder** [comment]
Deployed to prod 2025-02-17

**Comment by greg-schroeder** [comment]
Will process today

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @bernhardoj - $250 - ND
C+: @dominictb - $250 - Upwork

**Comment by greg-schroeder** [comment]
Can you take care of the C+ checklist @dominictb? Thanks

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by greg-schroeder** [comment]
filed

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
