### ISSUE TITLE
[Awaiting checklist] [$250] mWeb - Chat - Chat not autoscrolled when categorized expense is sent to chat with content.

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/52221
**Email or phone of affected tester (no customers):** ibellicotest+91@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Motorola MotoG60 - Android 12
**App Component:** Money Requests

## Action Performed:
Precondition: Workspace to submit categorized expense, must have an expense on it.
1. Open the staging.new.expensify.com
2. Open self DM and tap on the "+" button
3. Select "Track Expense" and complete the creation flow.
4. Once naviagted to chat again, tap on "Categorize it"
5. Select any category.
6. Add a merchant.
7. Submit the expense to a workspace that already has an expense or content on it.

## Expected Result:
When categorizing an expense and submitting it to a workspace that already has content in it, the chat should be autoscrolled.

## Actual Result:
Chat is not autoscrolled after categorizing an expense and submitting it to a workspace chat that already has an expense or content in it.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/76691193-1a5d-4240-9293-29b5983b4087

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021867328605330762929</li>
        <li>Upwork Job ID: 1867328605330762929</li>
        <li>Last Price Increase: 2025-01-02</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 105580363</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The categorized track expense isn't shown fully because the chat isn't auto scrolled to the bottom.

### What is the root cause of that problem?
This only happens with WS track expense. This issue happens when the report last action `created` value doesn't match the report `lastVisibleActionCreated`.
https://github.com/Expensify/App/blob/50c1db81004285968c6388bc941860f554d411e6/src/pages/home/report/ReportActionsView.tsx#L301-L302
https://github.com/Expensify/App/blob/50c1db81004285968c6388bc941860f554d411e6/src/pages/home/report/ReportActionsView.tsx#L485

When we create a track expense, including categorizing it, we don't update the `lastVisibleActionCreated` at all.
https://github.com/Expensify/App/blob/50c1db81004285968c6388bc941860f554d411e6/src/libs/actions/IOU.ts#L1507-L1514

This doesn't happen to, money requests, for example. If we see here, we don't set the `lastVisibleActionCreated` too for the money request.
https://github.com/Expensify/App/blob/50c1db81004285968c6388bc941860f554d411e6/src/libs/actions/IOU.ts#L696-L702

But we actually mutate the chat report `lastVisibleActionCreated` here when a new report preview is created.
https://github.com/Expensify/App/blob/50c1db81004285968c6388bc941860f554d411e6/src/libs/actions/IOU.ts#L2339-L2343

Also, if we do a track expense directly on the WS (without going through Categorize flow), then it works fine even though we don't update the `lastVisibleActionCreated`. That's because we trigger `notifyNewAction` which will scroll the chat to the bottom.
https://github.com/Expensify/App/blob/50c1db81004285968c6388bc941860f554d411e6/src/libs/actions/IOU.ts#L4119

### What changes do you think we should make in order to solve the problem?

I don't like mutating the object and instead of using `notifyNewAction`, it's better to fix the root cause of the `lastVisibleActionCreated` optimistic data. So, to fix this, we can update the `lastVisibleActionCreated` to the report preview action if we are creating a new report preview.
https://github.com/Expensify/App/blob/8ed48d2a620db9de962ce0d8b534b512d648cf07/src/libs/actions/IOU.ts#L1515-L1523

```
...(shouldCreateNewMoneyRequestReport && {lastVisibleActionCreated: reportPreviewAction?.created}),
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

We can create a test for `buildOnyxDataForTrackExpense` and test the optimistic data of the chat report when `shouldCreateNewMoneyRequestReport` is true and false.

**Comment by twisterdotcom** [comment]
Still `Help Wanted`

**Comment by twisterdotcom** [comment]
Same. Making weekly over the holidays.

**Comment by bernhardoj** [comment]
I already have a proposal in case you missed it

**Comment by twisterdotcom** [comment]
Ah, @shubham1206agra let's get it reviewed!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by twisterdotcom** [comment]
Ah this is waiting on you @srikarparsi.

**Comment by sonialiap** [comment]
@srikarparsi @shubham1206agra what do you guys think about folding this https://github.com/Expensify/App/issues/54766 into your issue? Looks like they're related

**Comment by srikarparsi** [comment]
Sorry for the delay, @bernhardoj's proposal looks good to me as well, assigning

**Comment by srikarparsi** [comment]
> @srikarparsi @shubham1206agra what do you guys think about folding this https://github.com/Expensify/App/issues/54766 into your issue? Looks like they're related

I agree, they do seem to be related with `lastVisibleActionCreated`. @bernhardoj can we please fix both in the PR if possible?

**Comment by bernhardoj** [comment]
PR is ready

`lastVisibleActionCreated` is still not updated when doing the categorize, but the chat is scrolled to the bottom, so I only handle the split bill case.

cc: @shubham1206agra

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by twisterdotcom** [comment]
Payment Summary:

- @bernhardoj paid $250 via NewDot Manual Request
- @shubham1206agra paid $250 [here](https://www.upwork.com/nx/wm/offer/105580363) (Reviewer)

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by twisterdotcom** [comment]
Please accept the Upwork offer now @shubham1206agra.
