### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] The focused background isn't updated when the selected option is updated from BE side

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#54089]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation** (hyperlinked to channel name): [expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1733996157829999)

## Action Performed:
1. In the device 1, go to Settings> Preferences > Priority mode
2. In the device 2, go to Settings> Preferences > Priority mode
3. In the device 2, click on another option
## Expected Result:
The selected option is updated in the device 1 but the focus background isn't updated
## Actual Result:
The focused background isn't updated in the device 1
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/3b95637e-3636-49f1-b479-b3311cf15678

https://github.com/user-attachments/assets/1c8f1735-d5af-4ae8-9304-0fefc8bfc01d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021867633562881780913</li>
        <li>Upwork Job ID: 1867633562881780913</li>
        <li>Last Price Increase: 2024-12-13</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 105417829</li>
<li>daledah | Contributor | 105417830</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @michaelkwardrop</details>

**Comment by linhvovan29546** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The focused background isn't updated when the selected option is updated from BE side
### What is the root cause of that problem?
In BaseSelectionList, the `getItemBackgroundColorStyle` function is used to get the background color for an item. This function only applies a background color if `isFocused` is true. When updates are received from the backend, only the `isSelected` state of `priorityModes` is updated, but `isFocused` is not. As a result, the focused background does not change.
https://github.com/Expensify/App/blob/10bfe9ab2895923c3f985d6529f6ff25809053e4/src/components/SelectionList/BaseListItem.tsx#L113

### What changes do you think we should make in order to solve the problem?
In [PreferencesPage](https://github.com/Expensify/App/blob/10bfe9ab2895923c3f985d6529f6ff25809053e4/src/pages/settings/Preferences/PreferencesPage.tsx), we should use a `useEffect` with `priorityModes` as a dependency to determine the `focusedIndex` and then call `ref.current.setFocusedIndex(focusedIndex`).
```
useEffect(() => {
        const handleFocus = () => {
            const focusedIndex = priorityModes.findIndex((mode) => mode.isSelected)
            refSelectionList.current?.setFocusedIndex(focusedIndex)
        }
        handleFocus()
    }, [priorityModes])
```
We also need to export the `setFocusedIndex` method from `BaseSelectionList` using `useImperativeHandle` to enable this functionality.
https://github.com/Expensify/App/blob/10bfe9ab2895923c3f985d6529f6ff25809053e4/src/components/SelectionList/BaseSelectionList.tsx#L735-L741

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

N/A
### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment]
hey contributors, please make sure that your proposal also fix [this problem](https://github.com/Expensify/App/pull/52575#issuecomment-2501780310)

**Comment by DylanDylann** [comment]
@mountiny Let me take over this bug because it came from https://expensify.slack.com/archives/C05LX9D6E07/p1733996291225739?thread_ts=1730403194.757359&cid=C05LX9D6E07

**Comment by linhvovan29546** [comment]
Updated proposal to fix [this problem](https://github.com/Expensify/App/pull/52575#issuecomment-2501780310) 

https://github.com/Expensify/App/issues/54089#issuecomment-2540415139

**Comment by mountiny** [comment]
> What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

Make sure to add tests too

**Comment by linhvovan29546** [comment]
Updated proposal to add automated tests 

https://github.com/Expensify/App/issues/54089#issuecomment-2540415139

**Comment by DylanDylann** [comment]
@daledah Could you suggest an automated test for this one?

@linhvovan29546 It seems your test doesn't match this issue

**Comment by linhvovan29546** [comment]
@DylanDylann  The root issue lies in the `BaseSelectionList` component. In the `PriorityModePage` (and several other places), the `SelectionList` component is used, which is a wrapper around `BaseSelectionList`. Therefore, I  write automated tests for the `BaseSelectionList` component covering three basic scenarios: rendering initial sections, handling item selection via press, and updating sections outside the component (simulating updates from the backend)

**Comment by DylanDylann** [comment]
@linhvovan29546 Could you please detail your point maybe with some pseudo code?

**Comment by linhvovan29546** [comment]
@DylanDylann Here are some details:
- Mock Setup:
  - Mock the useIsFocused and useFocusEffect hooks from @react-navigation/native to simulate navigation-related behaviors during testing and .
  - Mocked data sections base on PriorityModePage, named MOCK_SECTIONS
  - Add `testID` and `accessibilityState` properties to the `BaseListItem` component
  - https://github.com/Expensify/App/blob/653af04f8bf51661eb18f1c48a56c1362e5c61b2/src/components/SelectionList/BaseListItem.tsx#L110-L114
 - Implement test
   - Test Case: Render BaseSelectionList Correctly
      - Render BaseListItem with MOCK_SECTIONS
      - Verify that the component is rendered as expected.
    - Test Case: Handle Item Press Correctly
      -  Render BaseListItem with MOCK_SECTIONS
      -  Simulate a press event on the item with test ID
      -  Verify that the onSelectRow handler is called with the correct data.
    - Test Case: Update Focused Item When Sections Change
      - Render the component with MOCK_SECTIONS.
      - Rerender the component with MOCK_UPDATED_SECTION
      - Verify that the accessibilityState updates correctly to reflect the changes.

<details>
<summary>Demo code</summary>
 
```js

const ALTERNATE_TEXT = "Only show unread sorted alphabetically"
const MOCK_SECTIONS = [
  {
    "value": "gsd",
    "text": "#focus",
    "alternateText": ALTERNATE_TEXT,
    "keyForList": "gsd",
    "isSelected": true
  },
  {
    "value": "default",
    "text": "Most recent",
    "alternateText": "Show all chats sorted by most recent",
    "keyForList": "default",
    "isSelected": false
  }
]

jest.mock('@react-navigation/native', () => {
  const actualNav = jest.requireActual<typeof Navigation>('@react-navigation/native');
  return {
    ...actualNav,
    useIsFocused: jest.fn(),
    useFocusEffect: jest.fn()
  };
});

describe('BaseSelectionList Component', () => {
  const mockOnSelectRow = jest.fn();

  const RenderBaseSelectionList = (props: BaseSelectionListProps = {}) => (
    <BaseSelectionList
      sections={[{ data: props.sections }]}
      ListItem={RadioListItem}
      onSelectRow={mockOnSelectRow}
      shouldSingleExecuteRowSelect
      initiallyFocusedOptionKey={props.sections.find((mode) => mode.isSelected)?.keyForList}
    />
  )

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('renders BaseSelectionList correctly', () => {
    // Given the component is rendered
    render(<RenderBaseSelectionList sections={MOCK_SECTIONS} />);

    // Then the label is displayed
    expect(screen.getByText(ALTERNATE_TEXT)).toBeOnTheScreen();
  });

  it('handles item press correctly', async () => {
    // Given the component is rendered
    render(<RenderBaseSelectionList sections={MOCK_SECTIONS} />);
    fireEvent.press(screen.getByTestId('BaseListItem-default'));
    expect(mockOnSelectRow).toHaveBeenCalledWith({
      ...MOCK_SECTIONS[1],
      shouldAnimateInHighlight: false
    })
  });

  it('updates focused Item when sections are updated from the background', async () => {
    // Given the component is rendered
    const updatedSections = MOCK_SECTIONS.map((section) => ({
      ...section,
      isSelected: section.keyForList === 'default' ? true : false
    }))
    const { rerender, getByTestId } = render(<RenderBaseSelectionList sections={MOCK_SECTIONS} />);
    expect(screen.getByTestId('BaseListItem-gsd')).toHaveAccessibilityState({
      selected: true
    })

    fireEvent.press(getByTestId('BaseListItem-gsd'));
    rerender(<RenderBaseSelectionList sections={updatedSections} />)
    await waitFor(() => expect(screen.getByTestId('BaseListItem-default')).toHaveAccessibilityState({
      selected: true,
    }));

  });
});

```
</details>

**Comment by DylanDylann** [comment]
@daledah Any update from you?

**Comment by DylanDylann** [comment]
Let's go with @daledah's [proposal](https://github.com/Expensify/App/issues/54089#issuecomment-2540464135) because they come first with the correct RCA and solution. For the test section, I will review it thoroughly with the code change in the PR phase

🎀 👀 🎀 C+ Reviewed

**Comment by michaelkwardrop** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by michaelkwardrop** [comment]
@daledah can you advise me on the `Contributor` sections of the checklist above? thanks!

**Comment by srikarparsi** [comment]
Hi @daledah and @DylanDylann, do you think you could take a look at this [regression](https://github.com/Expensify/App/issues/54932#issuecomment-2579948600) please which seems to come from this PR?

**Comment by michaelkwardrop** [comment]
Payment summary: 

Contributor: @daledah $125 - paying via UpWork
C+: @DylanDylann $125 - paying via UpWork (once [checklist](https://github.com/Expensify/App/issues/54089#issuecomment-2581677156) is completed)

50% regression penalty https://github.com/Expensify/App/issues/54931

**Comment by michaelkwardrop** [comment]
https://github.com/Expensify/Expensify/issues/463844

**Comment by michaelkwardrop** [comment]
### UPDATE

Payment summary:

Contributor: @daledah $125 - paid via UpWork ✅
C+: @DylanDylann $125 - paid via UpWork ✅ 

50% regression penalty https://github.com/Expensify/App/issues/54931
