### ISSUE TITLE
[BZ Checklist][$250] Rules - "days" is not displayed In Max expense age page

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#54363]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v 9.77-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** htad26+2@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** iPhone 13/iOS 18.0
**App Component:** Workspace Settings

## Action Performed:
Prerequisite
A workspace with rules enabled
1. Navigate to workspace settings
2. Navigate to rules > Max expense age 
3. Observe the end of the input field in "Max expense age"

## Expected Result:
"days" is displayed at the end of the input field.

## Actual Result:
"days" is not displayed at the end of the input field, which is not consistent with the behavior on other platforms

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6698973_1734615244485!img_0116](https://github.com/user-attachments/assets/f9df0271-c778-47b4-971e-3a02d8037060)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021871267339195943980</li>
        <li>Upwork Job ID: 1871267339195943980</li>
        <li>Last Price Increase: 2024-12-23</li>
<li>Automatic offers: </li>
<ul>
<li>linhvovan29546 | Contributor | 105454335</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by linhvovan29546** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Rules - "days" is not displayed In Max expense age page

### What is the root cause of that problem?
The BaseTextInput component is split into [index.native.ts](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput/index.native.tsx) and [index.ts](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput/index.tsx) files. However, the suffix handling logic is implemented only for non-native platforms, leaving native platforms without proper support.
That is missing from migrate here https://github.com/Expensify/App/pull/47409 

https://github.com/Expensify/App/blob/e42622c7936353724b99c546d9e272f25a177ee3/src/components/TextInput/BaseTextInput/index.tsx#L414-L423

### What changes do you think we should make in order to solve the problem?

Copy the suffix handling logic from index.ts to index.native.ts to 
<details>
 <summary>POC

</summary>

https://github.com/user-attachments/assets/225aa14d-4d0d-4f76-8cc1-acf0eba608fd
</details>

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
N/A

### What alternative solutions did you explore? (Optional)
N/A

**Comment by linhvovan29546** [comment]
This issue also appears on the Rules - "Random report audit" page

<details>
 <summary>Detail</summary>
<table align="center">
  <tr>
    <td align="center"><strong>Before</strong></td>
    <td align="center"><strong>After</strong></td>
  </tr>
  <tr>
    <td>
      <kbd>
        <img
          src="https://github.com/user-attachments/assets/9ec5917a-f37b-4f2a-a475-c049867cd97d"
          width="100%" 
        >
      </kbd>
    </td>
    <td>
      <kbd>
        <img
          src="https://github.com/user-attachments/assets/1e9b8cef-458b-4ceb-bc85-07085c350042"
            width="100%" 
        >
      </kbd>
    </td>
  </tr>
</table>


</details>

**Comment by mallenexpensify** [comment]
@Ollyws 👀 plz on @linhvovan29546 's proposal above.  

> This issue also appears on the Rules - "Random report audit" page

Thanks @linhvovan29546 , bumped the price back to the standard amount so we can fix multiple instances.  Please fix any others you're able to find.

**Comment by newangry** [comment]
![{ECA9B8F5-B1E2-4EC4-B084-FE312E7B5F29}](https://github.com/user-attachments/assets/9ae06340-4e6f-4407-b1aa-8428b99da81f)

How can I fix 403 Forbidden Error?

**Comment by linhvovan29546** [comment]
PR is ready!

**Comment by linhvovan29546** [comment]
Hi @mallenexpensify it looks like the PR has been deployed to production without any regressions after 7 days. Could you please assist with the payment?

**Comment by mallenexpensify** [comment]
Contributor: @linhvovan29546  paid $250 via Upwork
Contributor+: @Ollyws due $250 

@Ollyws it looks like the BZ checklist didn't populate, can you fill it out plz?

# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by mallenexpensify** [comment]
Thanks @Ollyws. Test case created
- https://github.com/Expensify/Expensify/issues/462302

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws
