### ISSUE TITLE
[HOLD for payment 2025-01-13] Deleting a custom card feed while offline behaves unexpectedly

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#54379]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1734560637707449)

## Action Performed:
Prerequisite: User added a company card and assigned

1. Navigate to company cards
2. Go offline
3. Click settings > Delete card feed
4. Observe the card unassigned in company cards page
5. Navigate to wallet
## Expected Result:
No card displayed in Assigned cards or deleted cards displayed with a strikethrough
## Actual Result:
Cards are displayed in Wallet
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/5b27c949-41d2-422d-bd98-bf76da7dba8a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by DylanDylann** [comment]
I'm working on Workspace Feed project so I would love to take this issue as C+

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
**Updates:**
- Opened [Draft PR](https://github.com/Expensify/App/pull/54425)

**TODOs:**
- Polish the code, 
- Update [getCompanyFeeds](https://github.com/Expensify/App/blob/927729c3ef12fb3a9a0878f5e712f2167d11f03a/src/libs/CardUtils.ts#L254-L256) function to take into consideration that direct feed data is stored in both `companyCards` and `oAuthAccountDetails` .
- Test the PR and prepare it for the review.

Most likely the PR will be ready for the review on Monday - Tuesday.

**Comment by mountiny** [comment]
in progress

**Comment by VickyStash** [comment]
**Uodates:**

- Updated [getCompanyFeeds](https://github.com/Expensify/App/blob/927729c3ef12fb3a9a0878f5e712f2167d11f03a/src/libs/CardUtils.ts#L254-L256) function to take data from `companyCards` field and removed `removeExpensifyCardFromCompanyCards` function as it's not necessary anymore. Updated tests.
- **Opened the [PR](https://github.com/Expensify/App/pull/54425) for the review!**

**Comment by VickyStash** [comment]
I'm going to be OOO Dec 25 - Dec 29 🎄

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by bfitzexpensify** [comment]
Offer sent @DylanDylann

**Comment by DylanDylann** [comment]
@bfitzexpensify No need payment. let's close this one
