### ISSUE TITLE
[Tracking] Deprecate jCenter in build.gradle

### ISSUE THREAD

**Issue by Jag96** [Expensify/App#7190]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from [this discussion](https://github.com/Expensify/App/pull/6914#discussion_r778447537), jcenter will no longer be updated. As a result, mavenCentral will be used instead for all react-native-community packages. More conversation in [this internal thread](https://expensify.slack.com/archives/C03V9A4TB/p1642017266194600) where we discussed migrating over to mavenCentral.

Creating this tracking issue for discussion and updates related to updating 3rd party packages to use mavenCentral.

cc @Expensify/mobile-deployers

**Comment by roryabraham** [comment]
Two known packages that have ditched `jcenter` but not yet included that change in a release:

- `react-native-clipboard/clipboard` (previously `react-native-community/clipboard`): https://github.com/react-native-clipboard/clipboard/commit/103b43392986ad786f44c1f06db19b1dd70443a7
- `wonday/react-native-pdf`: https://github.com/wonday/react-native-pdf/pull/606

We'll want to upgrade those by either pointing our dependency directly at a git commit or by waiting for them to release new versions of their packages. There might be other dependencies that need upgrading as well.

**Comment by Julesssss** [comment]
[Here's a PR](https://github.com/Expensify/App/pull/6773) I opened previously for removing NewDot Onfido BinTray dependency. Please feel free to review!

> We'll want to upgrade those by either pointing our dependency directly at a git commit or by waiting for them to release new versions of their packages.

I don't think we need to do this. `BinTray` is the troublesome repo, because it has completely shut down and we should replace these depenencies (we have done this already ✅ ). `JCenter` will continue to host indefinitely, so we simply need to migrate away as and when we bump lib versions. As @roryabraham has already added the `mavenCentral` repo to NewDot, I suggest that we do nothing -- in the unlikely event that a library is not hosted on` mavenCentral`, it will almost certainly be mentioned in the release notes for that library and can be dealt with manually then.

**Comment by Julesssss** [comment]
I should have created this issue when raising the PRs, so thanks for doing that @Jag96!  I suggest we do the following before marking this as resolved: 
- [x] Add `mavenCentral` to the list of repositories in NewDot `build.gradle`
- [ ] Add `mavenCentral` to the list of repositories in OldDot `build.gradle`
- [x] Merge the broken `BinTray` dependency fix in OldDot: ['BumpUA Firebase lib...'](https://github.com/Expensify/Mobile-Expensify/pull/12224)
- [ ]  Merge the broken `BinTray` dependency fix in NewDot:  ['Resolve missing Onfido dependency'](https://github.com/Expensify/App/pull/6773)
