### ISSUE TITLE
[Tracking] Active navigational issues

### ISSUE THREAD

**Issue by parasharrajat** [Expensify/App#7363]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
I have started to notice a couple of navigation issues. Creating this issue to help us better manage those and track their solutions. 

## List of issues
- [x] https://github.com/Expensify/App/issues/7010
- [x] https://github.com/Expensify/App/issues/6720
- [x] https://github.com/Expensify/App/issues/7091
- [x] https://github.com/Expensify/App/issues/6908 :hourglass: 
- [ ] https://github.com/Expensify/App/issues/7618
- [ ] https://github.com/Expensify/App/issues/4612
- [ ] https://github.com/Expensify/App/issues/6912 :hourglass: 
- [ ] https://github.com/Expensify/App/issues/5897
- [ ] https://github.com/Expensify/App/issues/7010

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MelvinBot** [comment]
Triggered auto assignment to @MitchExpensify (`AutoAssignerTriage`), see https://stackoverflow.com/c/expensify/questions/4749 for more details.

**Comment by MitchExpensify** [comment]
Thanks @parasharrajat, tracking issue looks good. I don't think any further triage action is required of me but let me know if you think otherwise

**Comment by parasharrajat** [comment]
made progress on the list.

**Comment by MelvinBot** [comment]
This issue has not been updated in over ***14*** days.  eroding to ***Weekly*** issue.

**Comment by MelvinBot** [comment]
This issue has not been updated in over ***14*** days.  eroding to ***Weekly*** issue.

**Comment by MelvinBot** [comment]
This issue has not been updated in over ***14*** days.  eroding to ***Weekly*** issue.

**Comment by MelvinBot** [comment]
This issue has not been updated in over ***14*** days.  eroding to ***Weekly*** issue.

**Comment by MelvinBot** [comment]
This issue has not been updated in over ***14*** days.  eroding to ***Weekly*** issue.

**Comment by MelvinBot** [comment]
This issue has not been updated in over ***14*** days.  eroding to ***Weekly*** issue.

**Comment by MelvinBot** [comment]
This issue has not been updated in over ***14*** days.  eroding to ***Weekly*** issue.

**Comment by parasharrajat** [comment]
Steadily making progress on issues one by one....

**Comment by mountiny** [comment]
Assigned Rajat

**Comment by parasharrajat** [comment]
Moving up...

**Comment by parasharrajat** [comment]
Shhhh.....Melvin

**Comment by mountiny** [comment]
Do you want to make this Monthly since it is a tracking issue?

**Comment by parasharrajat** [comment]
Yeah that would be great. Thanks @mountiny

**Comment by marcaaron** [comment]
Just curious, how many of these fixes have happened in the `react-navigation` repo? How many would we say are "workarounds"? And if we worked around something was there some justification as to why documented somewhere?

**Comment by marcaaron** [comment]
@parasharrajat I'm going to close this and move all related issues into a GitHub project for now if you see any issues related to navigation please grab me.

**Comment by parasharrajat** [comment]
Thank you for collaborating on these. This was much needed.
