### ISSUE TITLE
[Tracking] New Expensify: Unread Indicator Improvements

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#8230]
# Proposal 

Let’s improve the “unread” flow in New Expensify

# Problem

Our “unread” indicator feature in New Expensify has been buggy since forever. Messages don’t get marked as read when they should, they do get marked read when they shouldn’t, and numbers of unreads can appear off the charts for no explainable reason.

# Solution

Let’s get this under control as this is a core flow of New Expensify. As a chat-based platform, our chat features need to be accessible (for ourselves and contributors), maintainable and world class quality. 

# Plan of Action

- [x] Put a temporary hold on changes to the Report page
- [x] Do an audit of the code so we have a better understanding of where the potential issues are ([Audit](https://github.com/Expensify/App/issues/8230#issuecomment-1116855823))
- [x] Do a pre-design to hone in on what if anything we want to change about the “unread” feature itself ([pre-design](https://expensify.slack.com/archives/C03U7DCU4/p1651710102301769))
- [x] Figure out if we need a design doc - I think we'll need one, but it will be super short.
- [x] Write Design Doc
- [ ] Detailed pre-design
- [ ] Write Detailed Portion of Design Doc

**Comment by marcaaron** [comment]
Not overdue. Competing priorities with Offline First conversations, but will be able to move onto this soon.

**Comment by marcaaron** [comment]
I've been diving deep on some of our existing logic and wanted to drop an update here about my current understanding of how things are working and some ideas for how to improve. Will come back and update it with permalinks later, but wanted to do a quick brain dump for now.

----

# Report Unread Indicators

Generally speaking, our report unread indicators use some combination of these computed values in storage...

- `lastReadSequenceNumber` 
- `maxSequenceNumber` 
- `unreadActionCount`

### `lastReadSequenceNumber`

These are stored in the server, but not yet stored to the report object itself.

We save them locally in a map of `reportID: int` and save them when:

- We call `getUnreadCount()` (which gets called via `getSimplifiedReportObject` which is less of a getter and more of a data massager or "formatter" that prepares data to be saved into Onyx)
- We call `setLocalLastRead()` (which is called by other things - more on this below)

### `maxSequenceNumber`

- Updated optimistically - current max in memory + 1
- Updated on report fetch - `reportActionCount`
- Updated when a new report action appears - set to that action's `sequenceNumber`

### `unreadActionCount`

- Updated when a new report action appears - set to the `maxSequenceNumber` - `lastReadSequenceNumber` - number of deleted comments in between the "last read" and the "max"
- Set on report fetch - `reportActionCount` if there is no `lastReadSequenceNumber` otherwise the formula is 
>`reportActionCount` - `lastReadSequenceNumber` - number of deleted comments in between the "last read" and the "max"
- We call `setLocalLastRead()` (which is called by other things) and it computes the `unreadActionCount` the same way as before, however, this time it relies on getting the max number from a separate map containing the `maxSequenceNumbers` called `reportMaxSequenceNumbers`
	- The map of `maxSequenceNumbers` is updated whenever `handleReportChanged` is called

Even though we are storing the `unreadActionCount` so far... it seems like it could be determined by looking at the `lastReadSequenceNumber` and `maxSequenceNumber` for a report (as well as any deleted comments *if* we know about those).

**Problem:** It seems like a big problem with this design is that we don't always have an accurate picture of recent report actions or whether they are deleted? The `unreadActionCount` can't entirely be trusted unless we are in possession of all of the report actions from the `lastReadSequenceNumber` up to the `maxSequenceNumber`. If a report is in view we can trust that we have the most recent actions that we possibly can, but it feels like this should come from `Auth` and not require that we have locally downloaded "all report actions" we can possibly access that haven't yet been read.

### `setLocalLastRead()`

As mentioned previously, `setLocalLastRead()` is responsible for setting both `lastReadSequenceNumber` into a local map and also for setting the `unreadActionCount` (we hope with access to the most up to date `reportActions`). This method is called in 5 different places:

- **When a report action is deleted:** via `updateReportActionMessage()` - this method is called when we handle a Pusher event for a comment being edited after we merge a new report action we look to see if we have deleted it and then call `setLocalLastRead()`
- **When a new report action is handled by any possible source** (API, Pusher, Urban Airship) and it is from the currently logged in user - we call `setLocalLastRead()` with the new sequence number and assume it's the largest one
- **When we delete a report action optimistically:** via `Report.deleteReportComment()` we first call `setLocalLastRead()` after we merge in an optimistic object with a "deleted comment" and then call `setLocalLastRead()` in the `.then()` presumably because it would have updated the `reportActions` in memory that we are relying on to count the "deleted actions"
- **When we have to rollback a failed attempt to delete a report action:** Works similar to the last one. Also waits for the `reportActions` in the local map to update again by using a `.then()`.
- **When we explicitly call `updateLastReadActionID()` (this happens in many places)** - this is the action that actually calls the API to set our `lastReadActionID` in the server - and uses `setLocalLastRead()` to do it's "optimistic update".

### `Report.updateLastReadActionID()`

It's important to note that there are currently a few cases where this method will noop that both seem a bit like anti-patterns because we should perform the checks before ever calling this method...

1. When `isReportDataLoading = true` we won't allow this to be called
2. If we call the method with an undefined `sequenceNumber` AND we have an `undefined` `reportMaxSequenceNumber` in our `reportMaxSequenceNumbers` map

That second point is important because we can call `updateLastReadActionID()` without any specific `sequenceNumber` and it will fallback to whatever we have saved in `reportMaxSequenceNumbers`

#### Where is `Report.updateLastReadActionID()` called...

There are 6 distinct places where this is called but all originate in the `ReportActionsView`. In our current design, the "view" layer is responsible for watching various states and then marking the active report as read or unread.

- **When the `AppState` class triggers a `'change'` event** - the app itself must be visible + the drawer (sidebar) must be closed (when the drawer is open the sidebar is covering the report and we don't consider it "visible") and then we will call `updateLastReadActionID()`.

- When the `ReportActionsView` component updates because a "new action appeared" and the report is fully in view it will mark the report as read.

- **In componentDidUpdate we deduced that the report was previously not visible but is now visible because one of two things happened:**
	- The sidebar closed
	- The screen size increased from "small view" to "large view" (which would always reveal the full chat window)

- We tap the "floating green message counter" and it scrolls us to the bottom of the report + marks it as read.

- When we call `updateNewMarkerAndMarkRead()`
	- This is an interesting one because we will only actually call `updateLastReadActionID()` if the drawer is not open (similar to the logic in the `AppState` `'change'` event) 
	- Additionally, this call is only made ONCE and can be triggered from `componentDidMount()` or `componentDidUpdate()`. This is because we are "waiting" for our main list of reports to fetch. This combined with the suspicious early return in `updateLastReadActionID()` itself seem like a sign that we are holding something wrong.

- Finally, we will call `updateLastReadActionID()` when we explicitly mark a report action as "unread" via the `ContextMenuActions` [here](https://github.com/Expensify/App/blob/3faa6a77b076f6e6547340b93a2298042cf36266/src/pages/home/report/ContextMenu/ContextMenuActions.js#L125).

### Conclusions so far...

I think if we were to split this up into two sets of problems we'd have something like:

**Problems related to updating `lastReadSequenceNumber`, `maxSequenceNumber`, and `unreadActionCount`**

Ultimately, it just seems like there are a lot of ways to determine the same things. `lastReadSequenceNumber` and `unreadActionCount` seem kind of redundant since we can always figure out the "count" from `maxSequenceNumber` and `lastReadSequenceNumber` as long as we also know how many "deleted actions" we have for a given report.

Not being able to reliably determine how many deleted actions we have seems like a bug we haven't discovered yet and we'll need a solution for that.

**Problems related to triggering `updateLastReadActionID()`**

`componentDidUpdate()` is kind of being exploited a bit here to do different things that I'm not sure it should be responsible for:

These sort of make sense because the user is taking specific actions - but it's not clear from the code:

- Determining whether the sidebar is open or closed
- Determining whether we have increased our screen size

These are totally passive:
 
- Identifying when a new report action has "appeared" (we know this already in `Report.js` - but we don't know which report is in view which is why this logic ended up here)
- Detecting that the app has become active

Tapping the floating green counter button and marking a report as unread are definite "actions" a user can take here and the rest feel a bit like side effects or "events".

**Problems related to the new marker and green floating counter**

I won't go into detail here, but the logic surrounding this stuff seems flawed. For the new marker we store another data point which is the `newMarkerSequenceNumber` and I think we can just get rid of that and encapsulate this idea of a "new marker" into an HOC that:

- on init sets the `newMarkerSequenceNumber` based on the `lastReadSequenceNumber`
- passes a `hideNewMarker()` method down as a prop

For the green floating action counter, we are storing a "localUnreadCount" in `ReportActionsView` `state` and we do it for a similar reason to why the `newMarkerSequenceNumber` is tracked indepdently. When the report mounts we init that number but later calls to `updateLastReadActionID()` would modify the `report.unreadActionCount` and mess up the counter.

I think we might be able to also solve that with the same HOC that is passing down a "computed" `newMarkerSequenceNumber` instead of one in Onyx that is indepedently set.

# Conclusion

Tackling all of this right now seems like it will be a lot, but a rough plan of action might look like:

1. Solve the problem where we are depending on a local `reportActions` map that may have partial data. It just seems like there is no way [this logic](https://github.com/Expensify/App/blob/3faa6a77b076f6e6547340b93a2298042cf36266/src/libs/actions/ReportActions.js#L83-L98) can be correct because it depends on reading values of `reportActions` that we might not have downloaded yet. I could be wrong about that though.
1. Fix up how we are storing the data related to unreads - maybe we can kill `unreadActionCount` entirely. It seems like we are calculating it wrong. Alternatively, we could have a single method be responsible for updating all of these values at once instead of it being spread out in `Report.js`. Another thought could be to separate this from `Report.js` and create a `ReportUnreads.js` actions file to specifically handle this stuff and document how it all works it a bit better.

2. Fix up the `ReportActionsView` so that some of the responsibility of "watching" different state changes is clearer. Maybe we can make those "events" that we are triggering from a standalone lib instead of inside `componentDidUpdate()`.

3. Fix up the new marker and green floating counter logic. At a minimum, I can't see a clear reason for storing the new marker in Onyx and it's another data point to get confused about when we already have things like `lastReadActionID` and `unreadActionCount`.

**Comment by marcaaron** [comment]
**Moving some context out of the description to document a few other issues...**

#### Other issues

- [ ] We are setting props to state here. That is usually a sign of an anti-pattern and also looks unnecessary. Perhaps we can move this into the logic for the marker badge.
https://github.com/Expensify/App/blob/c87891b1363b5bf0a767d866023a3e327ede143a/src/pages/home/report/ReportActionsView.js#L117-L118

    - It's not clear why this would ever need to be different from the true `unreadActionCount` and probably would behave similar to the "new marker" in that when the component mounts we'll use whatever the initial `unreadActionCount` is and then not update it until you navigate away from the chat.

- [ ] The logic for tracking the "scroll" and display of marker feels like it should be separated from the logic tracking the unreads. This would be better organized if separated...
https://github.com/Expensify/App/blob/c87891b1363b5bf0a767d866023a3e327ede143a/src/pages/home/report/ReportActionsView.js#L421-L434

    - Not sure how easy this would be since the "scroll" part happens in the ReportActionsView. But we could move the listener to the `ReportScrollManager` instead and allow the message counter to use the event there.

- [ ] shouldComponentUpdate() is looking crazy with a zillion checks for various things. Can we think of another way to prevent unnecessary updates?
https://github.com/Expensify/App/blob/c87891b1363b5bf0a767d866023a3e327ede143a/src/pages/home/report/ReportActionsView.js#L161-L172

- [ ] There are a ton of side effects being performed in `componentDidUpdate()` maybe we can unnest some of it
https://github.com/Expensify/App/blob/c87891b1363b5bf0a767d866023a3e327ede143a/src/pages/home/report/ReportActionsView.js#L219-L249

    - These side effects are mostly for detecting:
        -  Whether a new action appears on a report (which does not seem like it should be the responsibility of the view)
        - Resizing of the window
        - Revealing report when sidebar was previously open
    - All of these seem like they would read cleaner as "event listeners" instead of heavy logic `componentDidUpdate()`
    - e.g. we could have `onResizeWindow()` `onDrawerClosed()` `onNewActionForReport()`
    - No need to necessarily stop using the "props" to determine this, but maybe there is an opportunity to abstract this stuff a bit and make the side effects more clear.

### Solved

- [x] Logic related to the InvertedFlatList can probably be separated from the other logic e.g. renderItem() etc
- [x] It is very hard to tell the difference between the "MarkerBadge" and the "New Marker" indicator. There are zillions of comments everywhere that mention "marker" making it hard to tell which is which. TODO: rename the `MarkerBadge` to something else.
- [x] Method declared incorrectly https://github.com/Expensify/App/blob/c87891b1363b5bf0a767d866023a3e327ede143a/src/pages/home/report/ReportActionsView.js#L279-L280

**Comment by marcaaron** [comment]
Based on the predesign I decided to move this into a design doc that is live [here](https://docs.google.com/document/d/1gvPDhGTxdcu-0lQxvruQnQJfJBrAmSjHieKciucV8eo/edit).

Once it gets enough reviews I'll do a detailed predesign to get more feedback on the above issues I've run into. I have some ideas on how to solve and clean things up - but want to make sure the design is locked down first.

**Comment by marcaaron** [comment]
Still slowly working on the detailed implementation here, but slowed down a bit by the API Refactor conversations. Planning on picking this back up once the Report API PRs are merged.

**Comment by marcaaron** [comment]
And looks like I will need to move it to Expensify/Expensify to do that 😄

**Comment by marcaaron** [comment]
Closing this in favor of https://github.com/Expensify/Expensify/issues/219592
