### ISSUE TITLE
Deploy Checklist: New Expensify 2022-04-08

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#8566]
**Release Version:** `1.1.54-1`
**Compare Changes:** https://github.com/Expensify/App/compare/production...staging

**This release contains changes from the following pull requests:**

- https://github.com/Expensify/App/pull/7807
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/8438
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8496
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8510
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8518
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8539
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8542
  - [x] QA
  - [ ] Accessibility

**Deploy Blockers:**
- [x] https://github.com/Expensify/App/issues/8570

**Deployer verifications:**
- [ ] I checked the [App Timing Dashboard](https://graphs.expensify.com/grafana/d/yj2EobAGz/app-timing?orgId=1) and verified this release does not cause a noticeable performance regression.
- [ ] I checked [Firebase Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&tag=all) and verified that this release does not introduce any new crashes.

cc @Expensify/applauseleads

**Comment by mvtglobally** [comment]
Regression completed  
Blocker - https://github.com/Expensify/App/issues/8570 

Issues logged 
https://github.com/Expensify/App/issues/8497
https://github.com/Expensify/App/issues/8501
https://github.com/Expensify/App/issues/8519
https://github.com/Expensify/App/issues/8520
https://github.com/Expensify/App/issues/8534
https://github.com/Expensify/App/issues/8545
https://github.com/Expensify/App/issues/8572
https://github.com/Expensify/App/issues/8507
 https://github.com/Expensify/App/issues/8537
 https://github.com/Expensify/App/issues/8541
 https://github.com/Expensify/App/issues/8573
 https://github.com/Expensify/App/issues/8574

**Comment by Julesssss** [comment]
The single deploy blocker is being discussed [here](https://github.com/Expensify/App/pull/7807#issuecomment-1093783008).

**Comment by Julesssss** [comment]
Marking the [deploy-blocker](https://github.com/Expensify/App/pull/8596) as resolved, now that the fix is merged (and imminently going to be cherry-picked)

**Comment by mvtglobally** [comment]
@Julesssss It doesn't look like the fix has been deployed yet on all platforms, can you confirm we are good to check or wait? https://github.com/Expensify/App/pull/8599

**Comment by Julesssss** [comment]
Hey @mvtglobally, I believe this is now [deployed to staging](https://github.com/Expensify/App/pull/8599#issuecomment-1096596163) on all platforms.

**Comment by Stutikuls** [comment]
Checked all PRs and creating accessibility issues for all PRs where accessibility issue was found.
The non-applicable PRs are - #7807, #8518, #8542 
Logged bugs - #8478 , #8479, #8480 , #8430, #8463

**Comment by Julesssss** [comment]
:shipit:

**Comment by Julesssss** [comment]
Ah, new checks.

So unfortunately it looks like we're seeing a new exception with [Android version `1.1.54`](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues/1d5ba5634a645471c9e97af9db8ab349?time=last-ninety-days&sessionEventKey=62543D65016900013D26C40D73FED202_1663806642541488455). It's non-fatal, so the user shouldn't notice this. But just to be safe I'm going to bring this up on the PR which I believe introduced the issue.

**Comment by Julesssss** [comment]
Confusingly, none of the above PRs seem related to the new issue 😕 

My best guess is [this PR](https://github.com/Expensify/App/pull/8312) from a couple of versions ago, which refactored the function which is listed as the origin of this new exception. It looks like we're attempting to call [these functions](https://github.com/Expensify/App/blob/main/src/libs/NetworkConnection.js#L123-L124) before they are defined, but I can't point to a specific recent change.

**Comment by Julesssss** [comment]
:shipit:
