### ISSUE TITLE
Deploy Checklist: New Expensify 2022-04-13

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#8631]
**Release Version:** `1.1.55-2`
**Compare Changes:** https://github.com/Expensify/App/compare/production...staging

**This release contains changes from the following pull requests:**

- https://github.com/Expensify/App/pull/8437
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8446
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8449
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8472
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8474
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8500
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8508
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8512
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8583
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8596
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8695
  - [x] QA
  - [x] Accessibility

**Deploy Blockers:**
- [x] https://github.com/Expensify/App/issues/8687

**Deployer verifications:**
- [x] I checked the [App Timing Dashboard](https://graphs.expensify.com/grafana/d/yj2EobAGz/app-timing?orgId=1) and verified this release does not cause a noticeable performance regression.
- [x] I checked [Firebase Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&tag=all) and verified that this release does not introduce any new crashes.

cc @Expensify/applauseleads

**Comment by mvtglobally** [comment]
@Julesssss Cna you pls check if IOS deployed successfully? We still dont have the build

**Comment by Stutikuls** [comment]
Checked all PRs and created accessibility issues for all PRs where accessibility issue were found.
The non-applicable PRs are - #8446, #8472 
logged Issues - #8437, #8449, #8474, #8500, #8508, #8512, #8583

**Comment by mvtglobally** [comment]
@yuwenmemon happy Monday. Let us know if you have any update on the IOS build readiness so we can resume the testing

**Comment by yuwenmemon** [comment]
@mvtglobally See https://expensify.slack.com/archives/C9YU7BX5M/p1650314731202989 I think we should be good to resume?

**Comment by mvtglobally** [comment]
thanks @yuwenmemon We are working on it. Will update all results in the morning

**Comment by Julesssss** [comment]
> @Julesssss Cna you pls check if IOS deployed successfully? We still dont have the build

Sorry @mvtglobally I was in hospital overnight and didn't see this.

**Comment by yuwenmemon** [comment]
@mvtglobally how's everything going? I see that no QA items have been checked off just yet...

**Comment by mvtglobally** [comment]
@yuwenmemon ,
Regression is completed. We are validating last 2 CPs right now

**Comment by yuwenmemon** [comment]
Awesome, thanks!

**Comment by mvtglobally** [comment]
@yuwenmemon  
https://github.com/Expensify/App/pull/8512 is blocked due to https://github.com/Expensify/App/issues/8534 Its repro in PROD, not sure if we can check it off as this is BETA feature. 

Issues logged 
https://github.com/Expensify/App/issues/8643
https://github.com/Expensify/App/issues/8640
https://github.com/Expensify/App/issues/8641
https://github.com/Expensify/App/issues/8644
https://github.com/Expensify/App/issues/8646
https://github.com/Expensify/App/issues/8648
https://github.com/Expensify/App/issues/8660
https://github.com/Expensify/App/issues/8661
https://github.com/Expensify/App/issues/8690

**Comment by yuwenmemon** [comment]
@mvtglobally I think it's fine to check off, since yeah, it is a beta feature. I'll give a heads up about the blocker though.

**Comment by mvtglobally** [comment]
@yuwenmemon CPs are pass. Checking off. Looks like we are good to 🚀

**Comment by yuwenmemon** [comment]
:shipit:
