### ISSUE TITLE
Deploy Checklist: New Expensify 2022-04-20

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#8707]
**Release Version:** `1.1.56-0`
**Compare Changes:** https://github.com/Expensify/App/compare/production...staging

**This release contains changes from the following pull requests:**

- https://github.com/Expensify/App/pull/7362
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8256
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8341
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8375
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8386
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8397
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8476
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8499
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8584
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8585
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8603
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8604
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8626
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8639
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8647
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8649
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8650
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8672
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8677
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8684
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8686
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8688
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8693
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8694
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/8695
  - [x] QA
  - [x] Accessibility

**Deploy Blockers:**
- [x] https://github.com/Expensify/App/issues/8709
- [x] https://github.com/Expensify/App/issues/8729

**Deployer verifications:**
- [x] I checked the [App Timing Dashboard](https://graphs.expensify.com/grafana/d/yj2EobAGz/app-timing?orgId=1) and verified this release does not cause a noticeable performance regression.
- [x] I checked [Firebase Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&tag=all) and verified that this release does not introduce any new crashes.

cc @Expensify/applauseleads

**Comment by mvtglobally** [comment]
@yuwenmemon Release Version: `` looks blank. 
![Screen Shot 2022-04-20 at 2 59 25 PM](https://user-images.githubusercontent.com/43995119/164303317-20ccafcb-e73a-40d3-9572-75a91bb3921b.png)

**Comment by yuwenmemon** [comment]
Updated! Should have been `1.1.55-2`

**Comment by mvtglobally** [comment]
My bad, I was adding label on another ticket https://github.com/Expensify/App/issues/8709. Its repro in Prod, but wasn't repro in the previous build

**Comment by mvtglobally** [comment]
@yuwenmemon just FYI. IOS did not deploy yet. We are working on other platforms right now, but maybe you can re-push the IOS build like yesterday if its stuck again?

**Comment by yuwenmemon** [comment]
Ah yes, it is stuck 😭

**Comment by yuwenmemon** [comment]
Trying it again.

**Comment by yuwenmemon** [comment]
Should be all good now!

**Comment by mvtglobally** [comment]
@yuwenmemon Regression is completed. Only 1 blocker maybe we can push for another deploy tomorrow? 
Deploy Blocker https://github.com/Expensify/App/issues/8729 

PR #8256 is not working https://github.com/Expensify/App/pull/8256#issuecomment-1104587697 Since it same in PROD are we good to check off? 
PR #8576 is failing for public account. Not sure if this is expected and we can check if off https://github.com/Expensify/App/issues/8728 
PR #8647 is not working https://github.com/Expensify/App/pull/8256#issuecomment-1105490722 Since it same in PROD are we good to check off? 
PR #8650 is failing https://github.com/Expensify/App/issues/8724. Since it same in PROD are we good to check off? 

Issues logged 
https://github.com/Expensify/App/issues/8690
https://github.com/Expensify/App/issues/8711
https://github.com/Expensify/App/issues/8724
https://github.com/Expensify/App/issues/8728
https://github.com/Expensify/App/issues/8729
https://github.com/Expensify/App/issues/8731
https://github.com/Expensify/App/issues/8734
https://github.com/Expensify/App/issues/8740
https://github.com/Expensify/App/issues/8744

**Comment by mvtglobally** [comment]
https://github.com/Expensify/App/issues/8709 is fixed. Checking off

**Comment by yuwenmemon** [comment]
@mvtglobally looks like there are still some items to check off like https://github.com/Expensify/App/pull/8684, right?

**Comment by mvtglobally** [comment]
@yuwenmemon i think I missed to update it in the list. 
https://github.com/Expensify/App/pull/8684 is failing due to https://github.com/Expensify/App/issues/8734 Its repro in prod. So probably not a blocker

**Comment by mvtglobally** [comment]
@francoisl checklist is all ready for you 😜

**Comment by francoisl** [comment]
> https://github.com/Expensify/App/pull/8684 is failing due to https://github.com/Expensify/App/issues/8734 Its repro in prod. So probably not a blocker

Could you test that one again please? It depended on https://github.com/Expensify/Web-Expensify/pull/33568, which has been deployed to production, so I expect it should work now as Luke pointed out [here](https://github.com/Expensify/App/issues/8734#issuecomment-1106851635) too.


I'm looking at the other unchecked PRs in the meantime.
----


For the record, there's also 1 new, non-fatal crash report for 1.1.56-0 specifically on Firebase ([here](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues/c729f526bacfb873abe223ac530d4ed3?time=last-seven-days&sessionEventKey=62655EFD018300010BD38BFBE43E9BD2_1668624815823390883)). The function causing the warning doesn't seem to have changed for this release and it's just one non-fatal occurrence, so I think it's safe to proceed.

**Comment by francoisl** [comment]
> PR https://github.com/Expensify/App/pull/8256
> PR https://github.com/Expensify/App/pull/8647

Looks like it's also happening on production for both, we can check them off.

> PR https://github.com/Expensify/App/pull/8576

This PR is still open, did you mean https://github.com/Expensify/App/pull/8476 instead?

> PR https://github.com/Expensify/App/pull/8650

We can check this one off given the explanation in the PR that the issue you noticed is somewhat expected and not a blocker.

**Comment by mvtglobally** [comment]
@francoisl  
Checking https://github.com/Expensify/App/pull/8684 again. Will update shortly. 
Checking off https://github.com/Expensify/App/pull/8650, https://github.com/Expensify/App/pull/8256, https://github.com/Expensify/App/pull/8647

and yes, Typo, I meant #8476

**Comment by mvtglobally** [comment]
@francoisl are we ok to check off https://github.com/Expensify/App/pull/8476? 

We re-tested https://github.com/Expensify/App/pull/8684#issuecomment-1109018449. Not sure if this is acceptable or will block deploy?

**Comment by francoisl** [comment]
I'm checking off https://github.com/Expensify/App/pull/8476 as per the QA instructions and tagged the author.
For #8684, it seems like applause.expensifail.com is not on the required beta, so I don't think you'd be able to test now. I'm also not sure if we'd want to add the whole domain to that beta right now. Since the feature is only available behind a beta, I'm also leaning on checking this one off. I also tagged the PR's author to double check if it's working as intended.

So with that said, looks like we're good to go with the deploy!

**Comment by francoisl** [comment]
:shipit:

**Comment by SumitDiyora** [comment]
Checked all PRs on Production / Staging and created accessibility issues for all PRs where accessibility issues were found.
The non-applicable PRs are - #8341, #8386, #8397, #8603, #8626, #8639, #8647, #8649, #8650, #8677, #8684, #8686, #8688, #8693
Logged Issues - #7362, #8256, #8375, #8476, #8499, #8584, #8585, #8604, #8672, #8694, #8695
