### ISSUE TITLE
Deploy Checklist: New Expensify 2022-07-07

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#9781]
**Release Version:** `1.1.82-5`
**Compare Changes:** https://github.com/Expensify/App/compare/production...staging

**This release contains changes from the following pull requests:**

- https://github.com/Expensify/App/pull/9062
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9350
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9385
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9476
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9501
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9519
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9567
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9573
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9599
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9601
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9602 - @Beamanator @Julesssss
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9610
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9611
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9612
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9618
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9619
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9621
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9626
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9627
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9629
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9632
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9639
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9643
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9649 - @arosiclair @Justicea83
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9650
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9651
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9654
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9665
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9672
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9674
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9682
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9689
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9690
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9694
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9711
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9714
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9715
  - [x] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9721
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9722
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9729
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9732
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9738 - @parasharrajat @MonilBhavsar
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9748
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9750
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9757
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9760
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9763
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9771
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9775
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9776
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9783
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9784
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9785
  - [x] QA
  - [x] Accessibility

**Internal QA:**
- [x] https://github.com/Expensify/App/pull/9738 - @parasharrajat @MonilBhavsar
- [x] https://github.com/Expensify/App/pull/9649 - @arosiclair @Justicea83
- [x] https://github.com/Expensify/App/pull/9602 - @Beamanator

**Deploy Blockers:**
- [x] https://github.com/Expensify/App/issues/9786
- [x] https://github.com/Expensify/App/issues/9838

**Deployer verifications:**
- [x] I checked the [App Timing Dashboard](https://graphs.expensify.com/grafana/d/yj2EobAGz/app-timing?orgId=1) and verified this release does not cause a noticeable performance regression.
- [x] I checked [Firebase Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&tag=all) and verified that this release does not introduce any new crashes.

cc @Expensify/applauseleads

**Comment by roryabraham** [comment]
Please keep this unlocked for a bit

**Comment by mvtglobally** [comment]
@roryabraham tag us when it's good to lock it. It's already late, we will start regression in the morning

**Comment by roryabraham** [comment]
@Expensify/applauseleads You can lock this whenever you're ready 🙇

**Comment by roryabraham** [comment]
Verified that https://github.com/Expensify/App/issues/9786 was resolved by https://github.com/Expensify/App/pull/9785

**Comment by roryabraham** [comment]
Checked off https://github.com/Expensify/App/pull/9732 because it's not a blocker, but it appears electron-log maybe hasn't been working since March? That's the most recent log I'm seeing in `~/Library/Logs/new.expensify/main.log`

**Comment by roryabraham** [comment]
Also there's a bunch of PRs that were already deployed to production included in this checklist. Going to check them off and hope that it's a one-off error resulting from the deploy woes earlier today / me having to manually create this checklist.

**Comment by roryabraham** [comment]
Checking off https://github.com/Expensify/App/pull/9750 because it was fixed by https://github.com/Expensify/App/pull/9783. You can verify that it's working on staging by going to https://staging.new.expensify.com/docs/index.html

**Comment by mvtglobally** [comment]
@AndrewGable  

PR #9385 one tester was able to repro https://github.com/Expensify/App/issues/8641#issuecomment-1179566811. Since its existing issue, checking off. 
PR https://github.com/Expensify/App/pull/9501 is failing https://github.com/Expensify/App/issues/9805. Repro in PROD checking off
PR #9627 & #9650 is failing https://github.com/Expensify/App/issues/9802. Potential blocker. Pls double check 
PR https://github.com/Expensify/App/pull/9649 - @arosiclair @Justicea83 Can you check this off? 
PR #9665 is pending clarification https://github.com/Expensify/App/pull/9665#issuecomment-1179141605 

Issues logged 
https://github.com/Expensify/App/issues/9742
https://github.com/Expensify/App/issues/9741
https://github.com/Expensify/App/issues/9747
https://github.com/Expensify/App/issues/9766
https://github.com/Expensify/App/issues/9802
https://github.com/Expensify/App/issues/9805
https://github.com/Expensify/App/issues/9807
https://github.com/Expensify/App/issues/9808
https://github.com/Expensify/App/issues/9809
https://github.com/Expensify/App/issues/9816
https://github.com/Expensify/App/issues/9817
https://github.com/Expensify/App/issues/9827

**Comment by AndrewGable** [comment]
No, I am working on getting all the internal QA items checked off

**Comment by mvtglobally** [comment]
checking off https://github.com/Expensify/App/pull/9665 https://expensify.slack.com/archives/C9YU7BX5M/p1657649041410549

**Comment by mvtglobally** [comment]
@AndrewGable Yes, The only issue is https://github.com/Expensify/App/issues/9802. I think we can check it off as thats expected

**Comment by AndrewGable** [comment]
Deploy did not work, we are looking into it

**Comment by roryabraham** [comment]
Closing this again

**Comment by roryabraham** [comment]
New checklist is [here](https://github.com/Expensify/App/issues/9847)
